Repository dfinity/ic, pull requests merged in 2024-10, with the labels that each got.

#1752 chore(nervous-system): update mainnet-canisters.bzl
  mainnet-canisters.bzl
Labels: chore, @idx, @nns-team

#1760 chore(dependency-mgmt): Add `linux-modules-6.8.0` to failover data store
  ci/src/dependencies/data_source/slack_findings_failover_data_store.py
Labels: chore, @product-security

#1697 refactor: [MR-603] Typed canister queues and references
  rs/messaging/tests/queue_tests.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/input_schedule/tests.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/message_pool/tests.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
Labels: refactor, @execution, @ic-message-routing-owners

#1763 chore: upgrade clap
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ic_os/build_tools/dflate/Cargo.toml
  rs/ic_os/build_tools/diroid/Cargo.toml
  rs/ic_os/build_tools/inject_files/Cargo.toml
Labels: chore, @idx

#1764 chore(ledgers): update mainnet-canisters.bzl
  mainnet-canisters.bzl
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
Labels: chore, @nns-team

#1738 chore: upgrade prost and tonic crates
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/bitcoin/service/build.rs
  rs/https_outcalls/service/build.rs
  rs/monitoring/adapter_metrics/service/build.rs
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/sns-wasm/src/gen/ic_sns_wasm.pb.v1.rs
  rs/protobuf/src/gen/bitcoin/bitcoin.v1.rs
  rs/protobuf/src/gen/bitcoin/types.v1.rs
  rs/protobuf/src/gen/crypto/registry.crypto.v1.rs
  rs/protobuf/src/gen/crypto/types.v1.rs
  rs/protobuf/src/gen/determinism_test/determinism_test.v1.rs
  rs/protobuf/src/gen/log/log.malicious_behaviour_log_entry.v1.rs
  rs/protobuf/src/gen/messaging/types.v1.rs
  rs/protobuf/src/gen/registry/registry.crypto.v1.rs
  rs/protobuf/src/gen/registry/registry.firewall.v1.rs
  rs/protobuf/src/gen/registry/registry.node_rewards.v1.rs
  rs/protobuf/src/gen/registry/registry.provisional_whitelist.v1.rs
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/registry/types.v1.rs
  rs/protobuf/src/gen/state/bitcoin.v1.rs
  rs/protobuf/src/gen/state/registry.crypto.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/protobuf/src/gen/state/state.ingress.v1.rs
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/state/types.v1.rs
  rs/protobuf/src/gen/transport/transport.v1.rs
  rs/protobuf/src/gen/types/bitcoin.v1.rs
  rs/protobuf/src/gen/types/registry.crypto.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/state.ingress.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/protobuf/src/gen/types/types.v1.rs
  rs/registry/canister/src/gen/ic_registry_canister.pb.v1.rs
  rs/registry/proto/src/gen/ic_registry_common.pb.local_store.v1.rs
  rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/root/src/gen/ic_sns_root.pb.v1.rs
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/tests/Cargo.toml
  rs/tests/common.bzl
Labels: chore, @idx, @networking, @nns-team, @ic-interface-owners

#1767 fix(dependency-mgmt): Apply ic-private patch to a leftover test
  ci/src/dependencies/scanner/manager/npm_dependency_manager_test.py
Labels: fix, @product-security

#1703 refactor(IDX): update CI env vars
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/system-tests-k8s.yml
  bazel/workspace_status.sh
  ci/bazel-scripts/main.sh
  ci/scripts/run-build-ic.sh
Labels: refactor, @idx, CI_ALL_BAZEL_TARGETS

#1465 refactor: improve docs and methods names in the p2p interface
  rs/artifact_pool/src/canister_http_pool.rs
  rs/artifact_pool/src/certification_pool.rs
  rs/artifact_pool/src/consensus_pool.rs
  rs/artifact_pool/src/dkg_pool.rs
  rs/artifact_pool/src/idkg_pool.rs
  rs/artifact_pool/src/ingress_pool.rs
  rs/interfaces/src/p2p/consensus.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/assembler.rs
  rs/p2p/artifact_manager/src/lib.rs
  rs/p2p/test_utils/src/consensus.rs
  rs/p2p/test_utils/src/mocks.rs
Labels: refactor, @consensus, @networking

#1769 chore(IDX): update intel job logic
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#1774 test: Fix TLA instrumentation for empty functions
  rs/tla_instrumentation/tla/Counter.tla
  rs/tla_instrumentation/tla/Counter_Apalache.tla
  rs/tla_instrumentation/tla_instrumentation/src/tla_value.rs
  rs/tla_instrumentation/tla_instrumentation/tests/structs.rs
Labels: test, @research, @formal-models

#1776 chore(ICP_ledger): FI-1513: Move notified test canister to its own subdirectory
  rs/rosetta-api/icp_ledger/BUILD.bazel
  rs/rosetta-api/icp_ledger/Cargo.toml
  rs/rosetta-api/icp_ledger/tests/notified/notified.did
  rs/rosetta-api/icp_ledger/tests/notified/notified.rs
Labels: chore, @finint

#1779 feat: List all PageMaps function in CheckpointLayout
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
Labels: feat

#1783 chore: Update Base Image Refs [2024-10-01-1619]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#1761 refactor: EXC-1735: Move `ongoing_long_install_code` into `drain_subnet_queues`
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
Labels: refactor, @idx, @consensus, @product-security, @boundary-node, @networking, @pocket-ic, @nns-team, @ic-message-routing-owners, @node, @ic-interface-owners, @cross-chain-team, @finint, @ic-owners-owners, @platform-operations, @research, @formal-models

#1785 chore(ICP_ledger): FI-1514: Adjust bazel target for FI nightly
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: chore, @idx

#1688 chore(ckbtc): Proposals to upgrade ckBTC ledger suite
  rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2024_09_27.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2024_09_27.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2024_09_27.md
Labels: chore

#1770 fix(IDX): only run ci/bazel-scripts/diff.sh on PRs to fix CI on pushes to dev-gh-* branches
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#1550 test(ICP_ledger): FI-1491: Add tests for existing ledger behavior regarding the anonymous principal
  Cargo.lock
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#1653 chore: Improve the error message when merging conflicting TLA locals
  rs/tla_instrumentation/tla_instrumentation/src/tla_state.rs
Labels: chore

#1726 chore(consensus): avoid recomputing the block hash when notarizing a block
  rs/consensus/src/consensus/malicious_consensus.rs
  rs/consensus/src/consensus/notary.rs
Labels: chore, @consensus

#1780 chore: update testnet execution dashboards
  rs/tests/dashboards/IC/execution-metrics.json
Labels: chore, @idx

#1762 chore: move the xnet endpoint under rs/http_endpoints and share ownership with the NET team
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  rs/http_endpoints/xnet/BUILD.bazel
  rs/http_endpoints/xnet/Cargo.toml
  rs/http_endpoints/xnet/src/lib.rs
  rs/http_endpoints/xnet/src/tests.rs
  rs/replica/BUILD.bazel
  rs/replica/Cargo.toml
  rs/replica/src/setup_ic_stack.rs
Labels: chore, @networking, @ic-message-routing-owners, @ic-owners-owners

#1733 chore: [MR-569] Drop old canister queue implementations
  rs/protobuf/def/state/queues/v1/queues.proto
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/protobuf/src/state/tests.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
Labels: chore, @execution, @ic-interface-owners

#1796 feat(BOUN-1250): BN Ubuntu upgrade to 24.04
  ic-os/boundary-guestos/context/Dockerfile
  ic-os/boundary-guestos/context/Dockerfile.base
  ic-os/boundary-guestos/defs.bzl
  ic-os/boundary-guestos/docs/Components.adoc
  ic-os/boundary-guestos/scripts/build-bootstrap-config-image.sh
  ic-os/boundary-guestos/scripts/build-deployment.sh
  ic-os/components/boundary-guestos.bzl
  ic-os/components/boundary-guestos/etc/nftables.conf
  ic-os/components/boundary-guestos/etc/prober-wallets-exporter/wallets.json
  ic-os/components/boundary-guestos/etc/prober/ic_public_key.pem
  ic-os/components/boundary-guestos/etc/prober/wallets.json
  ic-os/components/boundary-guestos/etc/systemd/system/prober-wallets-exporter.service
  ic-os/components/boundary-guestos/etc/systemd/system/prober.service
  ic-os/components/boundary-guestos/etc/systemd/system/setup-prober.service
  ic-os/components/boundary-guestos/opt/ic/bin/bootstrap-ic-node.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-prober.sh
  publish/binaries/BUILD.bazel
Labels: feat, @idx, @boundary-node, @node

#1804 fix(IDX): fix run-build-ic
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/scripts/run-build-ic.sh
Labels: fix, @idx

#1663 feat: [NODE-1355] Create 24.04 test containers
  WORKSPACE.bazel
  bazel/noble.lock.json
  bazel/noble.yaml
  rs/tests/BUILD.bazel
Labels: feat

#1808 fix(BOUN-1250): ubuntu: add systemd-resolved
  ic-os/boundary-guestos/context/Dockerfile
  ic-os/boundary-guestos/context/Dockerfile.base
Labels: fix

#1812 feat(BOUN-1250): ubuntu fix once again
  ic-os/boundary-guestos/context/Dockerfile
Labels: feat

#1233 chore(crypto): Clean up BIP340 signature processing
  rs/crypto/secp256k1/src/lib.rs
  rs/crypto/secp256k1/tests/tests.rs
Labels: chore

#1777 fix: Cap ingress induction debit for cleanup callback
  rs/execution_environment/src/execution/response.rs
  rs/execution_environment/src/execution/response/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
Labels: fix

#1806 feat: EXC-1751: Charge idle canisters for full execution
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/round_schedule.rs
  rs/execution_environment/src/scheduler/tests.rs
Labels: feat

#1797 chore: [MR-616] Drop `CanisterQueue::QueueItem` proto, part 1
  rs/protobuf/def/state/queues/v1/queues.proto
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
Labels: chore

#1816 fix(IDX): fix the "Tag Team Reviewers" workflow when run in the private repo
  .github/workflows/ci-pr-only-team-tags.yml
Labels: fix, @idx

#1799 test(consensus): add more test cases to `get_ingress_payload` benchmark and create `validate_ingress_payload` benchmarks
  rs/ingress_manager/benches/build_payload.rs
Labels: test, @consensus

#1809 refactor(ICRC_ledger): FI-1455: Refactor ICRC ledger golden state test
  Cargo.lock
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/Cargo.toml
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: refactor, @finint

#1818 fix(IDX): add BUILDEVENT_APIKEY back
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  bazel/exporter/main.go
Labels: fix, @idx

#1821 fix(IDX): add branch head sha
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/bazel-scripts/diff.sh
Labels: fix, @idx

#1810 chore: Update Base Image Refs [2024-10-02-1854]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/components/boundary-guestos.bzl
  ic-os/components/boundary-guestos/etc/systemd/system/relabel-machine-id.service
  ic-os/components/boundary-guestos/opt/ic/bin/relabel-machine-id.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-hostname.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-lvs.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-ssh-account-keys.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-ssh-keys.sh
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore, @node

#1819 fix: Tweak instruction overhead per canister
  rs/config/src/subnet_config.rs
Labels: fix

#1823 chore: Update Base Image Refs [2024-10-03-1220]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#1826 fix(IDX): remove continue-on-error
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: fix, @idx

#1794 test(ICP_ledger): FI-1428: Add ledger, archive, and index block parity checks for ICP golden state test
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/index/tests/tests.rs
  rs/ledger_suite/icp/test_utils/src/state_machine_helpers/index.rs
  rs/ledger_suite/icp/tests/golden_nns_state.rs
Labels: test, @finint

#1667 refactor(NODE-1474): Config types refactor
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/types.rs
Labels: refactor, @node

#1824 fix: Small change in how we enable systemd services
  ic-os/boundary-guestos/context/Dockerfile
  ic-os/guestos/context/Dockerfile
  ic-os/hostos/context/Dockerfile
  ic-os/setupos/context/Dockerfile
Labels: fix

#1834 chore: [MR-610] Revert custom `impl ExhaustiveSet for RejectCode`
  rs/types/types/src/exhaustive.rs
Labels: chore

#1833 chore(IDX): update rules haskell
  WORKSPACE.bazel
Labels: chore, @idx

#1660 chore(ICP-Rosetta): add neuron management test
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/icp/tests/system_tests/common/utils.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/mod.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/rosetta-api/tests/system_tests/test_cases/neuron_management.rs
Labels: chore, @finint

#1813 fix: ensure that StateMachine registry contains no special ipv6 addresses
  rs/state_machine_tests/src/lib.rs
Labels: fix, @pocket-ic, @ic-message-routing-owners

#1839 fix(Ledger-Suite): changed IC version
  rs/ledger_suite/icrc1/ledger/README.adoc
Labels: fix

#1827 chore: update execution metrics dashboards for testnets
  rs/tests/dashboards/IC/execution-metrics.json
Labels: chore, @idx

#1784 feat: RUN-1038: Propagate execution mode (wasm64/32) to replica
  rs/canister_sandbox/bin/test_sandbox.rs
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/canonical_state/src/traversal.rs
  rs/embedders/src/serialized_module.rs
  rs/embedders/src/wasm_executor.rs
  rs/embedders/src/wasm_utils.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/execution_environment/src/hypervisor/tests.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/state_layout/src/state_layout.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/src/tree_hash.rs
  rs/test_utilities/state/src/lib.rs
Labels: feat, @execution, @ic-message-routing-owners, @ic-interface-owners

#1020 feat(ICP-Ledger): FI-1433: Implement V1 for ICP ledger - add ability to read from memory manager in post_upgrade
  Cargo.lock
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/src/lib.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: feat, @finint

#1844 fix(ckETH): update readme
  rs/ethereum/cketh/playground/README.adoc
Labels: fix

#1820 chore: migrate drun to clap 4
  Cargo.lock
  rs/drun/BUILD.bazel
  rs/drun/Cargo.toml
  rs/drun/src/main.rs
Labels: chore, @languages

#1670 feat(ckbtc): Add a dashboard to the new KYT canister
  Cargo.lock
  rs/bitcoin/kyt/BUILD.bazel
  rs/bitcoin/kyt/Cargo.toml
  rs/bitcoin/kyt/src/dashboard.rs
  rs/bitcoin/kyt/src/dashboard/tests.rs
  rs/bitcoin/kyt/src/lib.rs
  rs/bitcoin/kyt/src/main.rs
  rs/bitcoin/kyt/src/state.rs
  rs/bitcoin/kyt/templates/dashboard.html
Labels: feat, @cross-chain-team

#1720 fix(IDX): simplify depending on bazel's volatile-status.txt file
  bazel/BUILD.bazel
  bazel/status.bzl
  bazel/workspace_status.sh
  rs/tests/driver/src/driver/farm.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/system_tests.bzl
Labels: fix, @idx

#1751 chore(ic): Update python formatting rules for the monorepo
  .github/scripts/determine-initial-guest-os-versions.py
  .github/scripts/generate-ci.py
  bazel/candid_integration_tests/candid_integration_tests.py
  bazel/inject_version_into_wasm_tests/inspect_stamped_trivial_wasm.py
  ci/src/git_changes/git_changes.py
  ci/src/git_changes/git_changes_test.py
  ic-os/components/conformance_tests/check_file_references.py
  ic-os/components/upgrade/shared-resources/monitor-expand-shared-data/monitor-expand-shared-data.py
  ic-os/dev-tools/bare_metal_deployment/deploy.py
  ic-os/dev-tools/power-metric-verification/parse_voltage_readings.py
  pre-commit/ruff-format.sh
  pre-commit/ruff-lint.sh
  rs/boundary_node/certificate_issuance/certificate_orchestrator/public_suffix_list_shrink.py
  rs/coverage.py
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/scripts/cost_estimator.py
  rs/ethereum/cketh/minter/scripts/ofaq_blocklist.py
  rs/tests/proptests/proptest-regression-parser.py
  rs/workload_generator/plot.py
  testnet/ansible/inventory/inventory.py
  testnet/host_inventory.py
  testnet/tools/icos_collect_debug_info.py
  toolchains/sysimage/build_container_base_image.py
  toolchains/sysimage/build_container_filesystem_tar.py
  toolchains/sysimage/build_ext4_image.py
  toolchains/sysimage/build_fat32_image.py
  toolchains/sysimage/build_lvm_image.py
  toolchains/sysimage/build_vfat_image.py
  toolchains/sysimage/container_utils.py
Labels: chore, @idx, @dre, @execution, @boundary-node, @crypto-team, @node, @ic-interface-owners, @cross-chain-team, @platform-operations

#1756 refactor(sns): Use ic-nervous-system-agent in sns-audit
  Cargo.lock
  rs/nervous_system/agent/BUILD.bazel
  rs/nervous_system/agent/Cargo.toml
  rs/nervous_system/agent/src/agent_impl.rs
  rs/nervous_system/agent/src/lib.rs
  rs/nervous_system/agent/src/nns/governance.rs
  rs/nervous_system/agent/src/nns/mod.rs
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/agent/src/sns/governance.rs
  rs/nervous_system/agent/src/sns/index.rs
  rs/nervous_system/agent/src/sns/ledger.rs
  rs/nervous_system/agent/src/sns/root.rs
  rs/nervous_system/agent/src/sns/swap.rs
  rs/nns/governance/api/src/lib.rs
  rs/nns/governance/api/src/pb.rs
  rs/nns/governance/api/src/request_impls.rs
  rs/sns/audit/BUILD.bazel
  rs/sns/audit/Cargo.toml
  rs/sns/audit/src/lib.rs
  rs/sns/audit/src/main.rs
  rs/sns/swap/src/lib.rs
  rs/sns/swap/src/request_impls.rs
Labels: refactor, @nns-team

#1699 feat: [MR-552] Implement callback expiration
  rs/protobuf/def/state/queues/v1/queues.proto
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/message_pool/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/system_state.rs
Labels: feat, @execution, @ic-interface-owners

#1815 chore: EXC-1749: Consolidate scheduling logic
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/lib.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/round_schedule.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/replicated_state/src/canister_state.rs
Labels: chore, @execution, @ic-message-routing-owners

#1851 fix: [MR-523] Prevent duplicates of aborted or paused responses
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/canister_state/tests.rs
Labels: fix, @execution

#1832 feat: [MR-552] Trigger callback expiration in `StateMachine`
  rs/messaging/src/message_routing.rs
  rs/messaging/src/state_machine.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/system_state.rs
Labels: feat, @execution, @ic-interface-owners

#1857 chore: assorted ic-os bash script clean-ups and tweaks
  ic-os/components/boundary-guestos/opt/ic/bin/firewall-counter-check.sh
  ic-os/components/early-boot/setup-hostname/hostos/setup-hostname.sh
  ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
  ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
  ic-os/components/hostos-scripts/guestos/start-guestos.sh
  ic-os/components/hostos-scripts/guestos/stop-guestos.sh
  ic-os/components/hostos-scripts/misc/detect-first-boot.sh
  ic-os/components/hostos-scripts/misc/fetch-mgmt-mac.sh
  ic-os/components/hostos-scripts/monitoring/monitor-guestos.sh
  ic-os/components/init/bootstrap-ic-node/guestos/bootstrap-ic-node.sh
  ic-os/components/monitoring/ipv4-connectivity-check/ipv4-connectivity-check.sh
  ic-os/components/setupos-scripts/check-hardware.sh
  ic-os/components/setupos-scripts/check-network.sh
  ic-os/components/setupos-scripts/check-setupos-age.sh
  ic-os/components/setupos-scripts/config.sh
  ic-os/components/setupos-scripts/functions.sh
  ic-os/components/setupos-scripts/install-guestos.sh
  ic-os/components/setupos-scripts/install-hostos.sh
  ic-os/components/setupos-scripts/setup-disk.sh
  ic-os/components/setupos-scripts/setup-hostos-config.sh
  ic-os/components/setupos-scripts/setupos.sh
  ic-os/components/upgrade/manageboot/manageboot.sh
Labels: chore, @boundary-node, @node

#1858 fix: verbose logging service file failure
  ic-os/components/hostos-scripts/verbose-logging/verbose-logging.service
Labels: fix, @node

#1490 refactor: [EXC-1724] Refactor task_queue
  Cargo.lock
  rs/canister_sandbox/src/sandbox_server.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/replicated_state/tests/system_state.rs
  rs/state_manager/src/tip.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/test_utilities/state/src/lib.rs
Labels: refactor, @execution, @ic-message-routing-owners, @ic-interface-owners

#1498 refactor: Encapsulate the CallContextManager within SystemState
  Cargo.lock
  rs/canister_sandbox/BUILD.bazel
  rs/canister_sandbox/Cargo.toml
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution/nonreplicated_query.rs
  rs/execution_environment/src/execution/response.rs
  rs/execution_environment/src/execution/update.rs
  rs/execution_environment/src/execution/update/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
  rs/execution_environment/src/hypervisor/tests.rs
  rs/execution_environment/src/query_handler/query_context.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/messaging/src/routing/stream_handler/tests.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager/tests.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/replicated_state/tests/system_state.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/tip.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/common/mod.rs
  rs/system_api/tests/system_api.rs
  rs/test_utilities/state/src/lib.rs
Labels: refactor, @execution, @ic-message-routing-owners, @ic-interface-owners

#1853 feat: Enable pprof-based flamegraphs in ingress manager benchmarks
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ingress_manager/BUILD.bazel
  rs/ingress_manager/Cargo.toml
  rs/ingress_manager/benches/build_payload.rs
  rs/ingress_manager/benches/handle_ingress.rs
Labels: feat, @idx, @consensus

#1863 fix(consensus): Use correct malicious flags in equivocation integration test
  rs/consensus/tests/integration.rs
Labels: fix, @consensus

#1866 fix: cargo build
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  Cargo.lock
  packages/icrc-ledger-types/BUILD.bazel
  packages/icrc-ledger-types/Cargo.toml
  packages/icrc-ledger-types/src/icrc21/lib.rs
  rs/types/types/src/lib.rs
  rs/types/types/src/state_sync.rs
Labels: fix, @idx, @ic-interface-owners, @finint

#1414 feat(ICRC-ledger): FI-1435: Implement V2 for ICRC ledger - use memory manager during upgrade
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/Cargo.toml
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: feat, @idx, @nns-team, @finint

#1869 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#1788 feat(sns): Add periodic task for caching the upgrade steps
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/advance_target_version.rs
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/request_impls.rs
  rs/sns/governance/src/sns_upgrade.rs
  rs/sns/governance/tests/fixtures/environment_fixture.rs
  rs/sns/governance/tests/fixtures/mod.rs
  rs/sns/governance/tests/governance.rs
Labels: feat, @nns-team

#1840 test(ICRC_ledger): FI-1455: Fix ICRC SNS golden state test
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint

#1847 chore: upgrade wasmtime to v.25
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
Labels: chore, @execution

#1881 fix(IDX): work around GHC install timeouts
  WORKSPACE.bazel
  bazel/rules_haskell.patch
Labels: fix, @idx

#1879 test: Log GuestOS and HostOS IP address in nested tests
  rs/tests/driver/src/driver/nested.rs
Labels: test

#1848 chore: upgrade wasmtime v25 dependencies
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore

#1814 refactor(nervous-system): make the ic-nervous-system-integration-tests tests async
  Cargo.lock
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/Cargo.toml
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/advance_target_version.rs
  rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/registry/admin/tests/integration_tests.rs
Labels: refactor, @nns-team

#1887 chore: rename call_v3 to sync_call for logging
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/snapshot.rs
Labels: chore

#1888 fix: [NODE-1490] Fix handling of microcode for 24.04
  ic-os/components/early-boot/initramfs-tools/hostos/amd64-microcode
  ic-os/components/early-boot/initramfs-tools/hostos/initramfs.conf
  ic-os/components/early-boot/initramfs-tools/hostos/intel-microcode
  ic-os/components/early-boot/initramfs-tools/setupos/amd64-microcode
  ic-os/components/early-boot/initramfs-tools/setupos/initramfs.conf
  ic-os/components/early-boot/initramfs-tools/setupos/intel-microcode
  ic-os/components/hostos.bzl
  ic-os/components/setupos.bzl
Labels: fix

#1894 fix(IDX): repository name
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#1895 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @dre, @consensus

#1896 chore: bump ic-gateway version to v0.1.56
  ic-os/boundary-guestos/context/Dockerfile
Labels: chore, @boundary-node, @node

#1724 feat(IDX): use json for mainnet-canisters
  .github/CODEOWNERS
  BUILD.bazel
  Cargo.lock
  WORKSPACE.bazel
  bazel/mainnet-canisters.bzl
  mainnet-canisters.json
  rs/nervous_system/tools/sync-with-released-nevous-system-wasms/BUILD.bazel
  rs/nervous_system/tools/sync-with-released-nevous-system-wasms/Cargo.toml
  rs/nervous_system/tools/sync-with-released-nevous-system-wasms/src/main.rs
Labels: feat, @idx, @nns-team, @ic-owners-owners

#1898 test(IDX): reduce nightly system-test load
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/subnet_recovery/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/nested/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/testing_verification/BUILD.bazel
Labels: test, @idx, @consensus, @boundary-node, @networking, @ic-message-routing-owners, @finint

#1878 chore: correct tabbing on repro-check.sh error log
  ci/tools/repro-check.sh
Labels: chore, @idx

#1891 fix: Disable stress test for nightly benchmarking
  ic-os/dev-tools/bare_metal_deployment/benchmark_runner.sh
Labels: fix, @idx, @node

#1908 fix(IDX): system-tests-k8s.yml: HONEYCOMB_API_TOKEN -> BUILDEVENT_APIKEY
  .github/workflows/system-tests-k8s.yml
Labels: fix, @idx

#1880 chore(consensus): add metrics for how long it takes to compute a bouncer function
  rs/consensus/src/bouncer_metrics.rs
  rs/consensus/src/certification/certifier.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/idkg.rs
  rs/consensus/src/lib.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/payload.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: chore, @consensus, @networking

#1842 test(ICRC_ledger): FI-1455: Upgrade index canisters in ICRC golden state tests
  Cargo.lock
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/Cargo.toml
  rs/ledger_suite/icrc1/tests/common.rs
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/icrc1/tests/upgrade_downgrade.rs
Labels: test, @finint

#1868 chore: update `ic-cdk` to 0.16.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/nonblocking.rs
  rs/bitcoin/ckbtc/kyt/src/main.rs
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/ledger-suite-orchestrator/ledger_suite_orchestrator.did
  rs/ethereum/ledger-suite-orchestrator/src/main.rs
  rs/execution_environment/benches/management_canister/test_canister/src/main.rs
  rs/execution_environment/tests/backtraces.rs
  rs/ledger_suite/icp/index/src/main.rs
  rs/ledger_suite/icrc1/archive/src/main.rs
  rs/ledger_suite/icrc1/benchmark/generator/src/lib.rs
  rs/ledger_suite/icrc1/index-ng/src/main.rs
  rs/ledger_suite/icrc1/index/src/lib.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/nns/sns-wasm/src/canister_stable_memory.rs
  rs/nns/sns-wasm/src/stable_memory.rs
  rs/rosetta-api/tvl/src/metrics.rs
  rs/rust_canisters/stable_memory_integrity/bin/main.rs
  rs/rust_canisters/stable_memory_integrity/src/lib.rs
  rs/rust_canisters/stable_memory_integrity/tests/stable_memory_integrity.rs
  rs/tests/networking/canisters/src/cloner_canister.rs
  rs/tests/src/execution/canister_lifecycle.rs
Labels: chore, @idx, @execution, @networking, @pocket-ic, @nns-team, @cross-chain-team, @finint

#1856 fix(NODE-1474): config_tool hostos config generation
  rs/ic_os/config/src/main.rs
Labels: fix, @node

#1855 feat(release-scripts): Output all commits to be released with colors
  testnet/tools/lib.sh
  testnet/tools/nns-tools/list-new-commits.sh
  testnet/tools/nns-tools/submit-mainnet-nns-upgrade-proposal.sh
Labels: feat, @dre, @nns-team, @node

#1883 feat(NODE-1491): replace fetch-mgmt-mac.sh with hostos_tool command
  ic-os/components/early-boot/setup-hostname/hostos/setup-hostname.sh
  ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
  ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
  ic-os/components/hostos-scripts/misc/fetch-mgmt-mac.sh
  ic-os/components/hostos.bzl
  rs/ic_os/os_tools/hostos_tool/src/main.rs
Labels: feat, @node

#1875 feat(nervous-system-tools): Reintroduce verification instructions.
  testnet/tools/nns-tools/lib/proposals.sh
Labels: feat

#1911 chore(sns): Remove accidentally-committed logs
  rs/sns/governance/src/governance.rs
Labels: chore

#1899 chore: drop run_until_completion from canister tests
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/flow.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/ledger_suite/tests/sm-tests/src/metrics.rs
  rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
  rs/rosetta-api/tvl/sm-tests/src/lib.rs
  rs/rosetta-api/tvl/tests/tests.rs
Labels: chore, @nns-team, @cross-chain-team, @finint

#1910 chore: remove prober and ic-balance-exporter
  .gitignore
  Cargo.lock
  Cargo.toml
  ic-os/boundary-guestos/docs/ProberFunding.adoc
  rs/boundary_node/ic_balance_exporter/BUILD.bazel
  rs/boundary_node/ic_balance_exporter/Cargo.toml
  rs/boundary_node/ic_balance_exporter/README.md
  rs/boundary_node/ic_balance_exporter/src/main.rs
  rs/boundary_node/ic_balance_exporter/src/metrics.rs
  rs/boundary_node/prober/BUILD.bazel
  rs/boundary_node/prober/Cargo.toml
  rs/boundary_node/prober/README.md
  rs/boundary_node/prober/src/canister.wat
  rs/boundary_node/prober/src/main.rs
  rs/boundary_node/prober/src/metrics.rs
  rs/boundary_node/prober/src/retry.rs
Labels: chore

#1912 chore: upgrade rustls
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#1884 feat(PocketIC): topology endpoint at /_/topology
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat

#1914 refactor(sns): Migrate swap canister from dfn_core to ic_cdk
  Cargo.lock
  rs/nervous_system/clients/src/management_canister_client.rs
  rs/nervous_system/initial_supply/src/tests.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/runtime/src/lib.rs
  rs/sns/governance/token_valuation/src/tests.rs
  rs/sns/swap/BUILD.bazel
  rs/sns/swap/Cargo.toml
  rs/sns/swap/canister/canister.rs
  rs/sns/swap/src/clients.rs
  rs/sns/swap/src/swap.rs
Labels: refactor, @nns-team

#1916 refactor(IDX): remove BAZEL_EXTRA_ARGS_RULES
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
Labels: refactor, @idx

#1922 chore(IDX): tag backup_manager_test with system_test_hourly
  rs/tests/consensus/BUILD.bazel
Labels: chore, @idx, @consensus

#1925 chore(IDX): no hourly at night
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: chore, @idx

#1929 fix(IDX): release is published with tag
  .github/workflows/slack-workflow-run.yml
Labels: fix, @idx

#1926 chore: bump ic-gateway to v0.1.57
  ic-os/boundary-guestos/context/Dockerfile
Labels: chore, @boundary-node, @node

#913 feat(IC-1579): TLA-code link for split_neuron
  Cargo.lock
  publish/canisters/BUILD.bazel
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/canister/tla_ledger.rs
  rs/nns/governance/feature_flags.bzl
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tla/common.rs
  rs/nns/governance/src/governance/tla/mod.rs
  rs/nns/governance/src/governance/tla/split_neuron.rs
  rs/nns/governance/src/governance/tla/store.rs
  rs/nns/governance/src/governance/tla_macros.rs
  rs/nns/governance/src/storage/neuron_indexes.rs
  rs/nns/governance/src/subaccount_index.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tla/Split_Neuron.tla
  rs/nns/governance/tla/Split_Neuron_Apalache.tla
  rs/nns/governance/tla/Variants.tla
  rs/tla_instrumentation/BUILD.bazel
  rs/tla_instrumentation/tla_instrumentation/Cargo.toml
  rs/tla_instrumentation/tla_instrumentation/src/checker.rs
Labels: feat, @idx, @nns-team, @research, @formal-models

#1793 fix(k8s-testnets): allow ssh access to bn nodes in k8s
  ic-os/components/ic/ic.json5.template
Labels: fix

#1938 chore: enable sync v3 calls on all subnets except NNS subnet
  rs/replica/src/setup_ic_stack.rs
Labels: chore, @networking

#1936 chore: Revert risky changes for load issues
  rs/config/src/subnet_config.rs
  rs/execution_environment/benches/scheduler.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/lib.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/round_schedule.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/replicated_state/src/canister_state.rs
Labels: chore

#1939 fix(IDX): open port 8100 on k8s-based UVMs to fix all the rosetta systests
  rs/tests/driver/src/k8s/virtualmachine.rs
Labels: fix, @idx

#1937 refactor: miscellaneous icos refactoring and clean-up
  ic-os/components/early-boot/setup-hostname/hostos/setup-hostname.sh
  ic-os/docs/Configuration.adoc
  ic-os/docs/README.adoc
  rs/ic_os/network/src/interfaces.rs
  rs/ic_os/network/src/mac_address.rs
Labels: refactor, @node

#1930 feat: EXC-1659: Enable storage reservation mechanism on verified application subnets
  rs/config/src/subnet_config.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/execution_environment/src/hypervisor/tests.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @execution

#1831 feat(cketh): Use EVM-RPC canister 2.0.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  WORKSPACE.bazel
  bazel/external_crates.bzl
  rs/ethereum/cketh/minter/src/checked_amount.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/test_utils/BUILD.bazel
  rs/ethereum/cketh/test_utils/Cargo.toml
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/ethereum/evm-rpc-client/BUILD.bazel
  rs/ethereum/evm-rpc-client/Cargo.toml
  rs/ethereum/evm-rpc-client/src/lib.rs
  rs/ethereum/evm-rpc-client/src/tests.rs
  rs/ethereum/evm-rpc-client/src/types.rs
Labels: feat, @idx, @cross-chain-team

#1943 refactor: remove dead code in generate-replica-config.sh
  ic-os/components/ic/generate-replica-config.sh
Labels: refactor, @node

#1932 feat(sns): Port Swap's periodic tasks from heartbeats to timers
  Cargo.lock
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/sns/integration_tests/src/initialization_flow.rs
  rs/sns/integration_tests/src/payment_flow.rs
  rs/sns/integration_tests/src/sns_treasury.rs
  rs/sns/swap/BUILD.bazel
  rs/sns/swap/Cargo.toml
  rs/sns/swap/canister/canister.rs
  rs/sns/swap/src/swap.rs
Labels: feat, @nns-team

#1892 chore: StateMachine tests only bump time if strictly necessary
  rs/execution_environment/tests/canister_history.rs
  rs/ledger_suite/icp/index/tests/tests.rs
  rs/nervous_system/integration_tests/tests/advance_target_version.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/state_machine_tests/src/lib.rs
Labels: chore, @execution, @pocket-ic, @nns-team, @ic-message-routing-owners, @finint

#1951 fix(IDX): open up more rosetta ports in the k8s-based UVM to fix the rosetta systests
  rs/tests/driver/src/k8s/virtualmachine.rs
Labels: fix, @idx

#1950 chore: Stop using NeuronId for proposal IDs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
Labels: chore, @nns-team

#1954 fix(IDX): typo in bazel flag
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: fix, @idx

#1825 feat: Add log for node_provider_rewards computation
  rs/registry/node_provider_rewards/src/lib.rs
  rs/registry/node_provider_rewards/src/logs.rs
Labels: feat, @nns-team

#1934 feat(ICP-Ledger): FI-1508 add test icp allowance getter endpoint
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/src/lib.rs
Labels: feat, @finint

#1935 chore: Remove unnecessary dependencies
  Cargo.lock
  Cargo.toml
  rs/tests/Cargo.toml
  rs/tests/node/BUILD.bazel
  rs/tests/node/Cargo.toml
Labels: chore

#1876 chore: Change how the build time is calculated
  bazel/BUILD.bazel
  bazel/conf/.bazelrc.build
  ci/bazel-scripts/main.sh
  ci/container/build-ic.sh
  ic-os/components/BUILD.bazel
  ic-os/components/setupos-scripts/check-setupos-age.sh
  ic-os/components/setupos.bzl
  ic-os/setupos/context/Dockerfile
  ic-os/setupos/context/Dockerfile.base
Labels: chore

#1958 chore(IDX): update concurrency logic
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/container-base-images.yml
  .github/workflows/release-testing.yml
Labels: chore, @idx

#1347 feat(tests): add test target generation to rust_canbench rule
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/canbench.bzl
  bazel/canbench.sh
  bazel/external_crates.bzl
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/Cargo.toml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/nns/governance/Cargo.toml
Labels: feat, @idx, @finint

#1933 chore: add bazel profile.json to .gitignore
  .gitignore
Labels: chore

#1956 test(IDX-3182): inline the nns_dapp system-test & dynamic testnets
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  rs/tests/Cargo.toml
  rs/tests/gix/BUILD.bazel
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/Cargo.toml
  rs/tests/nns/nns_dapp/BUILD.bazel
  rs/tests/nns/nns_dapp/Cargo.toml
  rs/tests/nns/nns_dapp/nns_dapp.rs
  rs/tests/nns/nns_dapp_test.rs
  rs/tests/sdk/BUILD.bazel
  rs/tests/sdk/Cargo.toml
  rs/tests/sdk/dfx_smoke_test.rs
  rs/tests/src/lib.rs
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/testnets/Cargo.toml
  rs/tests/testing_verification/testnets/large.rs
  rs/tests/testing_verification/testnets/small_nns.rs
  rs/tests/testing_verification/testnets/sns_testing.rs
  rs/tests/testing_verification/testnets/src_testing.rs
Labels: test, @idx, @nns-team, @sdk, @ic-owners-owners

#1949 chore: Update Base Image Refs [2024-10-10-0808]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#1955 chore(tests): Enable threshold signatures during backup manager test setup
  Cargo.lock
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/Cargo.toml
  rs/tests/consensus/backup_manager_test.rs
Labels: chore, @idx, @consensus

#1901 test(ICP_ledger): FI-1387: Add transaction generation to ICP ledger suite golden state test
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/tests/golden_nns_state.rs
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#1965 revert(IDX): "chore(IDX): update concurrency logic (#1958)"
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/container-base-images.yml
  .github/workflows/release-testing.yml
Labels: revert, @idx

#1931 feat(nns): Heap neuron count metric.
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron_store.rs
Labels: feat, @nns-team

#1959 feat(IDX): enable bzlmod
  .github/workflows/bazel-lockfile.yml
  BUILD.bazel
  MODULE.bazel
  MODULE.bazel.lock
  WORKSPACE.bazel
  bazel/conf/.bazelrc.build
  bazel/exporter/BUILD.bazel
  bazel/prost.bzl
  bazel/proto/BUILD.bazel
  bazel/tools/cmpbuildlogs/BUILD.bazel
  go_deps.bzl
  requirements.txt
  rs/nns/governance/src/governance/tla/mod.rs
  rs/tests/ict/BUILD.bazel
  rs/tests/ict/cmd/BUILD.bazel
  rs/tests/kubeconfig_extension.bzl
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/tla_instrumentation/tla_instrumentation/tests/structs.rs
Labels: feat, @idx, @nns-team, @ic-message-routing-owners, @ic-owners-owners, @research, @formal-models

#1962 fix(boundary): cargo build of multiple targets problem
  rs/boundary_node/discower_bowndary/Cargo.toml
  rs/boundary_node/discower_bowndary/examples/api_bn_dynamic_routing.rs
  rs/boundary_node/discower_bowndary/examples/basic_library_usage.rs
  rs/boundary_node/discower_bowndary/examples/fetch_api_bns.rs
Labels: fix, @boundary-node

#1781 chore: bump hyper-util to 0.1.9
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/canister_client/tests/tls.rs
  rs/crypto/Cargo.toml
  rs/tests/src/boundary_nodes/boundary_nodes_integration.rs
Labels: chore, @idx, @boundary-node, @networking

#1941 refactor(sns): migrate sns governance to use ic_cdk
  Cargo.lock
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/src/canister_control.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/token_valuation/src/lib.rs
  rs/sns/integration_tests/src/proposals.rs
Labels: refactor, @nns-team

#1980 fix: comment out broken launch bare metal target
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  ic-os/setupos/envs/dev/BUILD.bazel
  ic-os/setupos/envs/local-base-dev/BUILD.bazel
  ic-os/setupos/envs/local-base-prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
Labels: fix, @idx, @node

#1671 refactor(ckbtc): Do not store full transaction data in state
  rs/bitcoin/kyt/btc_kyt_canister.did
  rs/bitcoin/kyt/src/dashboard/tests.rs
  rs/bitcoin/kyt/src/fetch.rs
  rs/bitcoin/kyt/src/fetch/tests.rs
  rs/bitcoin/kyt/src/lib.rs
  rs/bitcoin/kyt/src/main.rs
  rs/bitcoin/kyt/src/state.rs
  rs/bitcoin/kyt/src/state/tests.rs
  rs/bitcoin/kyt/src/types.rs
  rs/bitcoin/kyt/tests/tests.rs
Labels: refactor, @cross-chain-team, CI_OVERRIDE_DIDC_CHECK

#1977 test(IDX): enable IPv4 and A records for PrometheusVms
  rs/tests/driver/src/driver/prometheus_vm.rs
Labels: test, @idx, CI_ALL_BAZEL_TARGETS

#1990 chore(IDX): remove bazel lockfile
  .github/workflows/bazel-lockfile.yml
  MODULE.bazel.lock
  bazel/conf/.bazelrc.build
Labels: chore

#1974 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @consensus

#1942 chore: use fixed seed for threshold keys in SM tests
  rs/state_machine_tests/src/lib.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#1957 test(ckerc20): inline setup
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
  rs/tests/src/cross_chain/mod.rs
  rs/tests/src/lib.rs
Labels: test, @idx, @cross-chain-team

#1988 fix(IDX): remove old mainnet canisters defs
  mainnet-canisters.bzl
Labels: fix, @ic-owners-owners

#1996 fix(IDX): disable lockfile for all bazel commands
  bazel/conf/.bazelrc.build
Labels: fix

#1999 feat(IDX): show buildbuddy link as step summary
  ci/bazel-scripts/main.sh
Labels: feat

#1992 fix: fix the regression in XNET
  rs/http_endpoints/xnet/src/lib.rs
Labels: fix, @networking, @ic-message-routing-owners

#2001 fix(NODE-1500): disable unstable //rs/tests/nested/... tests
  rs/tests/nested/BUILD.bazel
Labels: fix, @idx
