Repository dfinity/ic, pull requests merged in 2024-07, with the labels that each got.

#290 fix(IDX): align rosetta deps
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  Cargo.lock
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/ledger_canister_blocks_synchronizer/BUILD.bazel
  rs/rosetta-api/ledger_canister_blocks_synchronizer/Cargo.toml
Labels: fix

#301 chore(CON-1302): Make consensus framework tests more precise
  rs/consensus/tests/framework/mod.rs
  rs/consensus/tests/integration.rs
Labels: chore

#333 fix(IDX): /cache for benchmarks
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: fix

#334 fix(IDX): use the correct capitalized InfraSec team name in slack-workflow-run
  .github/workflows/team-channels.json
Labels: fix

#345 fix(IDX): update finint team name
  .github/workflows/team-channels.json
Labels: fix

#341 fix(ICRC-Index): FI-1382: remove comment on removing 0 balance accounts
  rs/rosetta-api/icrc1/index-ng/src/main.rs
Labels: fix

#350 fix(IDX): add token to lock-generate
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: fix

#332 chore(dependency-mgmt): Migrate dependency management jobs to Github
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  gitlab-ci/src/dependencies/integration/github/github_api.py
  gitlab-ci/src/dependencies/integration/github/github_trivy_finding_notification_handler.py
  gitlab-ci/src/dependencies/integration/github/github_trivy_finding_notification_handler_test.py
  gitlab-ci/src/dependencies/integration/github/github_workflow_config.py
  gitlab-ci/src/dependencies/integration/slack/slack_trivy_finding_notification_handler.py
  gitlab-ci/src/dependencies/integration/slack/slack_trivy_finding_notification_handler_test.py
  gitlab-ci/src/dependencies/job/bazel_rust_ic_scanner_periodic_job.py
  gitlab-ci/src/dependencies/job/bazel_trivy_container_ic_scanner_periodic_job.py
  gitlab-ci/src/dependencies/notification/notification_config.py
  gitlab-ci/src/dependencies/requirements.txt
  gitlab-ci/src/dependencies/scanner/dependency_scanner.py
  gitlab-ci/src/dependencies/scanner/dependency_scanner_test.py
  requirements.in
  requirements.txt
Labels: chore

#355 chore(IDX): add eng-cross-chain team
  .github/workflows/team-channels.json
Labels: chore

#351 chore(ckerc20): fix dfx.json
  rs/bitcoin/ckbtc/testnet/dfx.json
  rs/ethereum/cketh/testnet/dfx.json
Labels: chore

#346 chore(consensus): Deduplicate code in {consensus,tecdsa}_performance_test
  Cargo.lock
  rs/tests/Cargo.toml
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/consensus_performance.rs
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/tecdsa/tecdsa_performance_test.rs
  rs/tests/consensus/utils/BUILD.bazel
  rs/tests/consensus/utils/Cargo.toml
  rs/tests/consensus/utils/src/lib.rs
Labels: chore

#358 docs: rust external dep policy
  README.adoc
Labels: docs

#354 fix: RUN-1014: Free SandboxedExecutionController threads
  rs/canister_sandbox/src/replica_controller/launch_as_process.rs
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
Labels: fix

#364 feat(ckerc20): add ckWBTC (XC-146)
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_07_12.md
Labels: feat

#370 fix(IDX): update pre-commit logic for ic-private
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
  pre-commit/check-incompatibilities.sh
Labels: fix

#372 fix(dependency-mgmt): Set `fetch-depth` to 256 for `dependencies-check`
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: fix

#347 refactor(crypto): CRP-2536 replace ed25519-consensus with ic-crypto-ed25519 in prod
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/crypto/ed25519/BUILD.bazel
  rs/crypto/ed25519/Cargo.toml
  rs/crypto/ed25519/src/lib.rs
  rs/crypto/internal/crypto_lib/basic_sig/ed25519/BUILD.bazel
  rs/crypto/internal/crypto_lib/basic_sig/ed25519/Cargo.toml
  rs/crypto/internal/crypto_lib/basic_sig/ed25519/src/api.rs
  rs/rosetta-api/icrc1/rosetta/client/BUILD.bazel
  rs/rosetta-api/icrc1/rosetta/client/Cargo.toml
  rs/rosetta-api/icrc1/rosetta/client/src/lib.rs
Labels: refactor

#377 test: EXC-1653 make system api test to be state machine test
  rs/execution_environment/tests/execution_test.rs
  rs/tests/src/execution/system_api_security_test.rs
Labels: test

#386 chore(IDX): introduce the pocket-ic team and let it own the pocket-ic code
  .github/CODEOWNERS
  .github/workflows/team-channels.json
  .gitlab/CODEOWNERS
Labels: chore

#374 chore: RUN-1015: Derive ParitalEq for all sandbox IPC types
  rs/canister_sandbox/src/protocol/sbxsvc.rs
  rs/canister_sandbox/src/protocol/structs.rs
  rs/cycles_account_manager/src/lib.rs
  rs/embedders/src/lib.rs
  rs/embedders/src/serialized_module.rs
  rs/embedders/src/wasm_executor.rs
  rs/interfaces/src/execution_environment.rs
  rs/replicated_state/src/page_map.rs
  rs/replicated_state/src/page_map/checkpoint.rs
  rs/replicated_state/src/page_map/page_allocator.rs
  rs/replicated_state/src/page_map/storage.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/types/types/src/methods.rs
Labels: chore

#383 fix: RUN-1001: Follow up on the reserved cycles limit fix
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/hypervisor/tests.rs
Labels: fix

#389 chore(IDX): make nns_dapp tests bazel-agnostic
  rs/tests/crypto/BUILD.bazel
  rs/tests/gix/BUILD.bazel
  rs/tests/nns/sns/BUILD.bazel
  rs/tests/src/nns_dapp.rs
  rs/tests/system_tests.bzl
  rs/tests/testing_verification/BUILD.bazel
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/testnets/src_testing.rs
Labels: chore

#375 chore(nervous_system): Principals proto typo fix: 7 -> 1
  buf.yaml
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
Labels: chore

#366 chore(IDX): updating base images workflow
  .github/workflows/container-base-images.yml
  .github/workflows/slack-workflow-run.yml
Labels: chore

#369 fix(node): fix testonly in icos_deploy bazel rules
  testnet/tools/BUILD.bazel
Labels: fix

#376 chore(idx): Restore buf.yaml
  buf.yaml
Labels: chore

#361 fix(custom domains): ignore leading and trailing whitespaces when checking domain names
  rs/boundary_node/certificate_issuance/certificate_issuer/src/check.rs
Labels: fix

#394 feat(nns): Create a new proposal action install_code and support non-root canisters
  Cargo.lock
  rs/nervous_system/root/src/change_canister.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/api/BUILD.bazel
  rs/nns/governance/api/Cargo.toml
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/protobuf_generator/src/lib.rs
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/proposals/call_canister.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/mod.rs
  rs/nns/integration_tests/src/canister_upgrade.rs
  rs/nns/integration_tests/src/copy_inactive_neurons_to_stable_memory.rs
  rs/nns/integration_tests/src/governance_mem_test.rs
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: feat

#391 test(sns): SNS upgrade-related tests were flaking out.
  rs/nervous_system/integration_tests/BUILD.bazel
Labels: test

#343 chore: firewall counter exporter
  Cargo.lock
  Cargo.toml
  ic-os/components/guestos.bzl
  ic-os/components/ic/ic.json5.template
  ic-os/components/monitoring/nft-exporter/nft-exporter.service
  ic-os/components/monitoring/nft-exporter/nft-exporter.timer
  ic-os/guestos/defs.bzl
  publish/binaries/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/ic_os/nft_exporter/BUILD.bazel
  rs/ic_os/nft_exporter/Cargo.toml
  rs/ic_os/nft_exporter/src/main.rs
  rs/orchestrator/testdata/nftables_assigned_replica.conf.golden
  rs/orchestrator/testdata/nftables_boundary_node.conf.golden
Labels: chore

#398 test(icp_ledger): FI-1301, FI-1359: Get and query all blocks from ledger and archives and fix test_archive_indexing
  rs/rosetta-api/icp_ledger/BUILD.bazel
  rs/rosetta-api/icp_ledger/index/tests/tests.rs
Labels: test

#401 fix(IDX): use correct team names in .github/workflows/team-channels.json
  .github/workflows/team-channels.json
Labels: fix

#344 perf: CON-1360 Reduce cost of cloning tSchnorr inputs
  rs/consensus/src/ecdsa/signer.rs
  rs/consensus/src/ecdsa/test_utils.rs
  rs/consensus/utils/src/lib.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/scheduler/threshold_signatures.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/types/types/src/consensus/idkg/schnorr.rs
Labels: perf

#406 fix(dependency-mgmt): Export `GITHUB_TOKEN` for `dependency-scan-release-cut`
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
  gitlab-ci/src/dependencies/data_source/jira_finding_data_source.py
Labels: fix

#365 feat(ckerc20): Simplify adding new ckERC20 token (II)
  rs/ethereum/cketh/minter/tests/ckerc20.rs
  rs/ethereum/cketh/test_utils/src/ckerc20.rs
  rs/ethereum/ledger-suite-orchestrator/README.adoc
  rs/ethereum/ledger-suite-orchestrator/ledger_suite_orchestrator.did
  rs/ethereum/ledger-suite-orchestrator/src/candid/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/tests.rs
  rs/ethereum/ledger-suite-orchestrator/src/state/test_fixtures.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/arbitrary.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/flow.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
  rs/ethereum/ledger-suite-orchestrator/tests/tests.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
Labels: feat

#352 chore: collection of preparatory steps for canister HTTP outcalls in PocketIC and unrelated fixes
  hs/spec_compliance/src/IC/Test/Spec/HTTP.hs
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/tests/test_canister.did
  packages/pocket-ic/tests/test_canister.rs
  packages/pocket-ic/tests/tests.rs
  rs/https_outcalls/adapter/BUILD.bazel
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/tests/spec_test.rs
  rs/state_machine_tests/src/lib.rs
Labels: chore

#367 chore: CON-1257 Rename `ecdsa` modules, `EcdsaClient`, `EcdsaGossip` and `EcdsaImpl`
  rs/artifact_pool/src/idkg_pool.rs
  rs/artifact_pool/src/lmdb_pool.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/block_maker.rs
  rs/consensus/src/consensus/catchup_package_maker.rs
  rs/consensus/src/consensus/metrics.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/idkg.rs
  rs/consensus/src/idkg/complaints.rs
  rs/consensus/src/idkg/malicious_pre_signer.rs
  rs/consensus/src/idkg/metrics.rs
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/payload_builder/errors.rs
  rs/consensus/src/idkg/payload_builder/key_transcript.rs
  rs/consensus/src/idkg/payload_builder/pre_signatures.rs
  rs/consensus/src/idkg/payload_builder/resharing.rs
  rs/consensus/src/idkg/payload_builder/signatures.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/pre_signer.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/spec.md
  rs/consensus/src/idkg/stats.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/consensus/src/lib.rs
  rs/consensus/tests/framework/driver.rs
  rs/consensus/tests/framework/execution.rs
  rs/consensus/tests/framework/malicious.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/framework/types.rs
  rs/consensus/tests/payload.rs
  rs/interfaces/src/idkg.rs
  rs/interfaces/src/lib.rs
  rs/replica/setup_ic_network/src/lib.rs
  rs/tests/dashboards/IC/threshold-signatures.json
Labels: chore

#409 feat(IDX): wait queue notifications
  .github/workflows/slack-workflow-queue.yml
Labels: feat

#353 chore(PocketIC): refactor progress threads in PocketIC
  rs/pocket_ic_server/src/state_api/state.rs
Labels: chore

#368 chore(crypto): CRP-2393 Remove support for masked kappa in threshold ECDSA
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/signer.rs
  rs/crypto/benches/idkg.rs
  rs/crypto/benches/tecdsa.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/src/signing/ecdsa.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/test_utils/src/lib.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/tests/key_derivation.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/tests/protocol.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/tests/serialization.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tecdsa/tests.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/crypto/tests/canister_threshold_ecdsa.rs
  rs/crypto/tests/canister_threshold_idkg.rs
  rs/crypto/tests/canister_threshold_idkg_transcript_size.rs
Labels: chore

#413 perf(crypto): CRP-2542 Reduce the size of randomizers during Ed25519 batch verification
  rs/crypto/ed25519/src/lib.rs
Labels: perf

#420 fix(IDX): reflect the changed dept-crypto-library team name to crypto-team
  .github/CODEOWNERS
  .github/workflows/team-channels.json
  gitlab-ci/src/ci-scripts/sync-codeowners.sh
Labels: fix

#404 chore(ic-boundary): removing deprecated CLI option
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/tls.rs
Labels: chore

#393 chore(nns): Add api <--> internal type conversions
  Cargo.lock
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/api/BUILD.bazel
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/pb/mod.rs
Labels: chore

#396 feat(nns): Support upgrading root canister through install_code
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/integration_tests/src/canister_upgrade.rs
Labels: feat

#425 chore(IDX): exclude workflows with long wait times
  .github/workflows/slack-workflow-queue.yml
Labels: chore

#430 fix(IDX): fixing URL syntax
  .github/workflows/slack-workflow-queue.yml
Labels: fix

#359 feat(farm): extending from config testnet
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/prep/src/node.rs
  rs/prep/src/subnet_configuration.rs
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/driver/boundary_node.rs
  rs/tests/driver/src/driver/ic.rs
  rs/tests/driver/src/driver/node_software_version.rs
  rs/tests/driver/src/driver/resource.rs
  rs/tests/ict/cmd/testnetCreateCmd.go
  rs/tests/testing_verification/testnets/Cargo.toml
  rs/tests/testing_verification/testnets/from_config.rs
Labels: feat

#340 fix(ICRC-21): FI-1386: add e 8 s to icrc 21
  packages/icrc-ledger-types/src/icrc21/lib.rs
  rs/rosetta-api/icp_ledger/ledger/src/main.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
  rs/rosetta-api/icrc1/ledger/src/main.rs
Labels: fix

#434 chore(IDX): update release-alerts channel
  .github/workflows/slack-workflow-run.yml
Labels: chore

#356 feat(PocketIC): store registry file in state_dir
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat

#439 chore: optimize starting PocketIC server in PocketIC library
  packages/pocket-ic/src/lib.rs
Labels: chore

#437 feat(k8s-testnets): playnet certificates
  rs/tests/driver/src/driver/boundary_node.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/k8s/config.rs
  rs/tests/driver/src/k8s/tnet.rs
Labels: feat

#443 chore(IDX): update codeowners
  .github/CODEOWNERS
Labels: chore

#400 feat(ckerc20): Use EVM-RPC canister to call `eth_getLogs`
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
  rs/ethereum/cketh/minter/src/lib.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/state.rs
  rs/ethereum/cketh/minter/tests/ckerc20.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/ethereum/cketh/test_utils/src/ckerc20.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/ethereum/cketh/test_utils/src/mock.rs
  rs/ethereum/cketh/test_utils/src/response.rs
  rs/ethereum/evm-rpc-client/src/lib.rs
  rs/ethereum/evm-rpc-client/src/tests.rs
  rs/ethereum/evm-rpc-client/src/types.rs
Labels: feat

#446 fix(RUN-1019): Cap Wasm64 heap memory size
  rs/embedders/src/wasm_utils/instrumentation.rs
  rs/embedders/tests/wasmtime_embedder.rs
Labels: fix

#397 chore: Update Base Image Refs [2024-07-17-0147]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#417 chore: upgrade url and uuid and use workspace versions
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/backup/Cargo.toml
  rs/boundary_node/discower_bowndary/Cargo.toml
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/icx_proxy/Cargo.toml
  rs/boundary_node/systemd_journal_gatewayd_shim/Cargo.toml
  rs/canister_client/Cargo.toml
  rs/https_outcalls/adapter/Cargo.toml
  rs/ic_os/launch-single-vm/Cargo.toml
  rs/ic_os/setupos-inject-configuration/Cargo.toml
  rs/ic_os/utils/Cargo.toml
  rs/nns/init/Cargo.toml
  rs/orchestrator/Cargo.toml
  rs/orchestrator/registry_replicator/Cargo.toml
  rs/prep/Cargo.toml
  rs/recovery/Cargo.toml
  rs/recovery/subnet_splitting/Cargo.toml
  rs/registry/admin/Cargo.toml
  rs/registry/canister/Cargo.toml
  rs/registry/local_registry/Cargo.toml
  rs/registry/nns_data_provider/Cargo.toml
  rs/registry/nns_data_provider_wrappers/Cargo.toml
  rs/registry/regedit/Cargo.toml
  rs/replay/Cargo.toml
  rs/replicated_state/Cargo.toml
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/hardware_wallet_tests/Cargo.toml
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/Cargo.toml
  rs/rosetta-api/icrc1/rosetta/Cargo.toml
  rs/rosetta-api/icrc1/rosetta/client/Cargo.toml
  rs/rosetta-api/ledger_canister_blocks_synchronizer/Cargo.toml
  rs/rosetta-api/test_utils/Cargo.toml
  rs/scenario_tests/Cargo.toml
  rs/state_manager/Cargo.toml
  rs/tests/Cargo.toml
  rs/tests/consensus/orchestrator/Cargo.toml
  rs/tests/driver/Cargo.toml
  rs/tests/nns/ic_mainnet_nns_recovery/Cargo.toml
  rs/workload_generator/Cargo.toml
  rs/xnet/endpoint/Cargo.toml
  rs/xnet/payload_builder/Cargo.toml
Labels: chore

#436 fix(k8s-testnets): adapt firewall rules for k8s testnets
  ic-os/components/ic/ic.json5.template
  rs/tests/driver/src/driver/bootstrap.rs
Labels: fix

#449 chore(IDX-3144): inline the basic_health_test
  Cargo.lock
  rs/tests/Cargo.toml
  rs/tests/src/basic_health_test.rs
  rs/tests/src/lib.rs
  rs/tests/testing_verification/BUILD.bazel
  rs/tests/testing_verification/Cargo.toml
  rs/tests/testing_verification/basic_health_test.rs
Labels: chore

#445 chore(IDX): rm unneeded workflows
  .github/workflows/gitlab-push.yml
  .github/workflows/gitlab-sync-branches.yml
Labels: chore

#456 chore(IDX): changing schedule
  .github/workflows/slack-workflow-queue.yml
Labels: chore

#410 docs: why GuestOS deps are required
  ic-os/guestos/defs.bzl
Labels: docs

#447 refactor(nervous_system): Move `Principals` message definition to nervous_system/proto
  buf.yaml
  rs/nervous_system/proto/proto/ic_nervous_system/pb/v1/nervous_system.proto
  rs/nervous_system/proto/src/gen/ic_nervous_system.pb.v1.rs
  rs/nervous_system/proto/src/lib.rs
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/sns/swap/src/types.rs
Labels: refactor

#450 chore(idx): Restore buf.yaml
  buf.yaml
Labels: chore

#399 test(icrc_ledger): FI-1368: Upgrade test for ICRC-1 ledgers using golden state
  Cargo.lock
  rs/nns/test_utils/golden_nns_state/src/lib.rs
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/Cargo.toml
  rs/rosetta-api/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test

#424 feat: Add bitcoin and cycles ledger canisters to protocol canisters
  rs/nns/constants/src/lib.rs
  rs/nns/governance/src/proposals/install_code.rs
Labels: feat

#382 chore(ICP/ICRC-Ledger): FI-1373: refactor approvals library to allow using regular and stable allowance storage
  rs/rosetta-api/icp_ledger/ledger/src/lib.rs
  rs/rosetta-api/icp_ledger/ledger/src/main.rs
  rs/rosetta-api/icp_ledger/ledger/src/tests.rs
  rs/rosetta-api/icp_ledger/ledger/tests/tests.rs
  rs/rosetta-api/icp_ledger/src/lib.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
  rs/rosetta-api/icrc1/ledger/src/lib.rs
  rs/rosetta-api/icrc1/ledger/src/main.rs
  rs/rosetta-api/icrc1/ledger/src/tests.rs
  rs/rosetta-api/icrc1/ledger/tests/tests.rs
  rs/rosetta-api/icrc1/src/lib.rs
  rs/rosetta-api/ledger_canister_blocks_synchronizer/tests/store_tests.rs
  rs/rosetta-api/ledger_canister_core/src/ledger.rs
  rs/rosetta-api/ledger_core/src/approvals.rs
  rs/rosetta-api/ledger_core/src/approvals/tests.rs
Labels: chore

#460 fix(IDX): handle name
  .github/workflows/slack-workflow-queue.yml
Labels: fix

#463 fix(IDX): codeowners and notifications
  .github/workflows/ci-notify-slack.yml
  .github/workflows/team-channels.json
Labels: fix

#405 fix(ICP-Rosetta): FI-1390 rosetta block performance issue
  rs/rosetta-api/ledger_canister_blocks_synchronizer/src/blocks.rs
Labels: fix

#378 chore(consensus): [CON-1341] move `rw_message.rs` out of `/rs/tests/src` into `/rs/tests/consensus/utils`
  Cargo.lock
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup_manager_test.rs
  rs/tests/consensus/consensus_performance.rs
  rs/tests/consensus/orchestrator/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/tecdsa/tecdsa_performance_test.rs
  rs/tests/consensus/utils/BUILD.bazel
  rs/tests/consensus/utils/Cargo.toml
  rs/tests/consensus/utils/src/lib.rs
  rs/tests/consensus/utils/src/rw_message.rs
  rs/tests/gix/nns_dapp_test.rs
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/Cargo.toml
  rs/tests/nested/src/lib.rs
  rs/tests/nns/ic_mainnet_nns_recovery/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/Cargo.toml
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/sdk/BUILD.bazel
  rs/tests/sdk/Cargo.toml
  rs/tests/sdk/dfx_smoke_test.rs
  rs/tests/src/consensus/adding_nodes_to_subnet_test.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
  rs/tests/src/message_routing/compatibility.rs
  rs/tests/src/nns_tests/sns_deployment.rs
  rs/tests/src/orchestrator/node_assign_test.rs
  rs/tests/src/orchestrator/node_reassignment_test.rs
  rs/tests/src/orchestrator/rotate_ecdsa_idkg_key.rs
  rs/tests/src/orchestrator/subnet_recovery_app_subnet.rs
  rs/tests/src/orchestrator/subnet_recovery_nns_subnet.rs
  rs/tests/src/orchestrator/subnet_splitting.rs
  rs/tests/src/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/src/orchestrator/unstuck_subnet_test.rs
  rs/tests/src/orchestrator/upgrade_downgrade.rs
  rs/tests/src/orchestrator/upgrade_with_alternative_urls.rs
  rs/tests/src/orchestrator/utils.rs
  rs/tests/src/orchestrator/utils/subnet_recovery.rs
  rs/tests/src/tecdsa/tecdsa_add_nodes_test.rs
  rs/tests/src/tecdsa/tecdsa_two_signing_subnets_test.rs
  rs/tests/testing_verification/testnets/Cargo.toml
  rs/tests/testing_verification/testnets/from_config.rs
  rs/tests/testing_verification/testnets/large.rs
  rs/tests/testing_verification/testnets/medium.rs
  rs/tests/testing_verification/testnets/single_app_large_node_with_nns.rs
  rs/tests/testing_verification/testnets/small.rs
  rs/tests/testing_verification/testnets/small_nns.rs
  rs/tests/testing_verification/testnets/small_with_query_stats.rs
  rs/tests/testing_verification/testnets/sns_testing.rs
  rs/tests/testing_verification/testnets/src_testing.rs
Labels: chore

#459 chore(IDX): split .bazelrc
  .bazelrc
  bazel/conf/.bazelrc.build
  bazel/conf/.bazelrc.internal
  bazel/conf/README.md
Labels: chore

#414 fix(NET-1732): use idna for parsing domain names
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/certificate_issuance/certificate_issuer/Cargo.toml
  rs/orchestrator/BUILD.bazel
  rs/orchestrator/Cargo.toml
  rs/orchestrator/src/registration.rs
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/Cargo.toml
  rs/registry/canister/src/mutations/common.rs
  rs/registry/canister/src/mutations/node_management/do_add_node.rs
  rs/registry/canister/src/mutations/node_management/do_update_node_domain_directly.rs
Labels: fix

#360 fix: Maintain snapshot_ids correctly
  rs/replicated_state/src/canister_snapshots.rs
Labels: fix

#421 feat(PocketIC): canister HTTP outcalls
  Cargo.lock
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/spec_test.rs
Labels: feat

#465 chore(ICP-Rosetta): FI-1381: enable feature flag rosetta blocks
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/BUILD.bazel
  rs/rosetta-api/src/main.rs
Labels: chore

#444 chore(consensus): Compute subnet members from membership directly
  rs/consensus/src/consensus/validator.rs
Labels: chore

#473 fix(IDX): set channel correctly
  .github/workflows/slack-workflow-run.yml
Labels: fix

#474 chore(IDX): update the node PR notification channel
  .github/workflows/team-channels.json
Labels: chore

#471 chore(consensus): [CON-1341] move `ssh_access` to `consensus_system_test_utils` crate
  Cargo.lock
  rs/tests/consensus/backup_manager_test.rs
  rs/tests/consensus/utils/BUILD.bazel
  rs/tests/consensus/utils/Cargo.toml
  rs/tests/consensus/utils/src/lib.rs
  rs/tests/consensus/utils/src/ssh_access.rs
  rs/tests/src/orchestrator/node_registration_test.rs
  rs/tests/src/orchestrator/ssh_access_to_nodes.rs
  rs/tests/src/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/src/orchestrator/unstuck_subnet_test.rs
  rs/tests/src/orchestrator/utils.rs
  rs/tests/src/orchestrator/utils/subnet_recovery.rs
Labels: chore

#472 chore(consensus): [CON-1341] move `set_sandbox_env_vars` function to `consensus_system_test_utils`
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/orchestrator/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/utils/src/lib.rs
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/src/orchestrator/subnet_recovery_app_subnet.rs
  rs/tests/src/orchestrator/subnet_recovery_nns_subnet.rs
  rs/tests/src/orchestrator/subnet_splitting.rs
  rs/tests/src/orchestrator/utils/subnet_recovery.rs
Labels: chore

#476 chore(IDX): drop the --github suffix for rc branches
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: chore

#379 feat: Add new type of task OnLowWasmMemory
  rs/execution_environment/src/execution/update.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/scheduler.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/system_api/src/lib.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/types/types/src/messages.rs
  rs/types/types/src/methods.rs
Labels: feat

#388 test(ICRC-Ledger): FI-1377: Add tests for upgrading ICRC ledger with WASMs with different token types
  Cargo.lock
  WORKSPACE.bazel
  mainnet-canisters.bzl
  rs/rosetta-api/icrc1/ledger/BUILD.bazel
  rs/rosetta-api/icrc1/ledger/Cargo.toml
  rs/rosetta-api/icrc1/ledger/tests/tests.rs
Labels: test

#482 fix(IDX): move build filters
  bazel/conf/.bazelrc.build
  bazel/conf/.bazelrc.internal
Labels: fix

#348 feat(pocket-ic): [NET-1725] Support synchronous call endpoint in pocket-ic.
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/src/call.rs
  rs/http_endpoints/public/src/call/ingress_watcher.rs
  rs/http_endpoints/public/src/lib.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
  rs/state_machine_tests/BUILD.bazel
  rs/state_machine_tests/Cargo.toml
  rs/state_machine_tests/src/lib.rs
Labels: feat

#464 chore(IDX): release testing update
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
Labels: chore

#487 fix(IDX): make lock-generate.sh work on GitHub
  gitlab-ci/src/ci-scripts/lock-generate.sh
Labels: fix

#457 refactor(nns): Use governance_api instead of governance types in entrypoint in governance
  rs/nns/governance/api/src/pb.rs
  rs/nns/governance/canister/canister.rs
Labels: refactor

#492 chore: Update Base Image Refs [2024-07-20-0145]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#432 chore: Remove deprecated controller field in update settings requests
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/execution/install_code.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/tests/canister_logging.rs
  rs/nns/cmc/cmc.did
  rs/tests/execution/general_execution_test.rs
  rs/tests/src/execution/canister_lifecycle.rs
  rs/types/management_canister_types/src/lib.rs
Labels: chore

#495 fix(IDX): remove undefined CI_COMMIT_REF_NAME in lock-generate.sh
  gitlab-ci/src/ci-scripts/lock-generate.sh
Labels: fix

#486 fix(IDX): disable unused aarch64-darwin code
  rs/execution_environment/src/hypervisor/tests.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
Labels: fix

#483 chore(IDX): set wasm paths via env
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/ckbtc/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/canister_http/canister_http.rs
  rs/tests/networking/canister_http_fault_tolerance_test.rs
  rs/tests/src/boundary_nodes/boundary_nodes_integration.rs
  rs/tests/src/certificate_orchestrator.rs
  rs/tests/src/ckbtc/lib.rs
  rs/tests/src/custom_domains_integration/setup.rs
  rs/tests/src/icrc1_agent_test/mod.rs
  rs/tests/src/message_routing/global_reboot_test.rs
  rs/tests/src/message_routing/mod.rs
  rs/tests/src/nns_dapp.rs
  rs/tests/testing_verification/testnets/src_testing.rs
Labels: chore

#481 chore(consensus): [CON-1341] inline `node_registration_test` and `ssh_access_to_nodes_test` system tests
  Cargo.lock
  rs/tests/Cargo.toml
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/orchestrator/Cargo.toml
  rs/tests/consensus/orchestrator/node_registration_test.rs
  rs/tests/consensus/orchestrator/ssh_access_to_nodes_test.rs
  rs/tests/src/orchestrator/mod.rs
  rs/tests/src/orchestrator/node_registration_test.rs
  rs/tests/src/orchestrator/ssh_access_to_nodes.rs
Labels: chore

#499 chore: cleanup Bazel files
  rs/universal_canister/impl/BUILD.bazel
  scalability/BUILD.bazel
Labels: chore

#478 perf: Speed up parsing of optional blob in CanisterHttpRequestArgs
  Cargo.lock
  rs/types/management_canister_types/BUILD.bazel
  rs/types/management_canister_types/Cargo.toml
  rs/types/management_canister_types/src/http.rs
Labels: perf

#416 chore: CON-1257 Rename `ecdsa` block payload field and fix comments
  rs/artifact_pool/benches/load_blocks.rs
  rs/artifact_pool/src/idkg_pool.rs
  rs/artifact_pool/src/lmdb_pool.rs
  rs/artifact_pool/src/rocksdb_pool.rs
  rs/config/src/config_sample.rs
  rs/consensus/benches/validate_payload.rs
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/block_maker.rs
  rs/consensus/src/consensus/catchup_package_maker.rs
  rs/consensus/src/consensus/metrics.rs
  rs/consensus/src/consensus/proptests.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/dkg/payload_validator.rs
  rs/consensus/src/idkg.rs
  rs/consensus/src/idkg/complaints.rs
  rs/consensus/src/idkg/malicious_pre_signer.rs
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/payload_builder/key_transcript.rs
  rs/consensus/src/idkg/payload_builder/pre_signatures.rs
  rs/consensus/src/idkg/payload_builder/signatures.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/pre_signer.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/stats.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/consensus/tests/framework/malicious.rs
  rs/consensus/tests/integration.rs
  rs/consensus/utils/src/lib.rs
  rs/orchestrator/src/upgrade.rs
  rs/replica/setup_ic_network/src/lib.rs
  rs/test_utilities/consensus/src/fake.rs
  rs/test_utilities/consensus/src/lib.rs
  rs/test_utilities/types/src/batch/payload.rs
  rs/tests/src/tecdsa/tecdsa_complaint_test.rs
  rs/types/types/src/consensus.rs
  rs/types/types/src/consensus/idkg.rs
  rs/types/types/src/consensus/idkg/common.rs
  rs/types/types/src/consensus/payload.rs
  rs/types/types/src/malicious_behaviour.rs
  rs/types/types/src/malicious_flags.rs
Labels: chore

#480 fix(IDX): fix the did_git_test on GitHub
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  bazel/candid.bzl
Labels: fix

#440 chore(IDX): remove targets from rust_canister
  bazel/canisters.bzl
  bazel/inject_version_into_wasm_tests/BUILD.bazel
  bazel/inject_version_into_wasm_tests/service.did
Labels: chore

#321 refactor(crypto): CRP-2453 unify threshold sign method names
  rs/consensus/src/idkg/signer.rs
  rs/crypto/benches/tecdsa.rs
  rs/crypto/internal/crypto_service_provider/src/vault/api.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tecdsa/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tecdsa/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/codec.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_client.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
  rs/crypto/src/sign/canister_threshold_sig/ecdsa.rs
  rs/crypto/src/sign/mod.rs
  rs/crypto/temp_crypto/src/lib.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/crypto/test_utils/local_csp_vault/src/lib.rs
  rs/crypto/tests/canister_threshold_ecdsa.rs
  rs/crypto/tests/canister_threshold_idkg.rs
  rs/interfaces/src/crypto/sign/canister_threshold_sig.rs
  rs/test_utilities/src/crypto.rs
  rs/types/types/src/crypto/canister_threshold_sig/error.rs
Labels: refactor

#507 fix(IDX): remove unused aarch64 import
  rs/execution_environment/src/hypervisor/tests.rs
Labels: fix

#451 feat(nns): Added visibility field to neurons.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/storage/neurons/neurons_tests.rs
  rs/nns/integration_tests/test_canisters/governance_mem_test_canister.rs
Labels: feat

#349 chore(http-endpoint): Increase `SETTINGS_MAX_CONCURRENT_STREAMS` to 1000
  rs/config/src/http_handler.rs
  rs/http_endpoints/public/src/lib.rs
Labels: chore

#493 fix(PocketIC): make CallRequest of type V3 deterministic
  Cargo.toml
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
Labels: fix

#488 feat(nns): Known neurons are always public.
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_store.rs
Labels: feat

#515 feat(RUN-1021): Revert to the memory allocator
  rs/config/src/state_manager.rs
Labels: feat

#521 chore: /rs/state_machine_tests/ owned by pocket-ic
  .github/CODEOWNERS
  .gitlab/CODEOWNERS
Labels: chore

#468 fix: add missing large testnet runtime dependency
  rs/tests/testing_verification/testnets/BUILD.bazel
Labels: fix

#522 chore: Code owners for state manager config
  .github/CODEOWNERS
  .gitlab/CODEOWNERS
Labels: chore

#479 fix: Add total_size to CanisterSnapshotBits
  rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
  rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
Labels: fix

#523 chore: CON-1350 Update documentation to include tSchnorr
  rs/consensus/src/idkg.rs
  rs/interfaces/src/canister_http.rs
  rs/types/types/src/consensus/idkg/schnorr.rs
Labels: chore

#512 feat(IDX): Add Apple Silicon builds
  .github/workflows/test-namespace-darwin.yml
  gitlab-ci/src/artifacts/upload.bash.template
Labels: feat

#373 refactor(nervous_system): Add `controller` and `hotkeys` fields to CfParticipant, CfNeuron, and CfInvestment
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/sns-wasm/canister/sns-wasm.did
  rs/sns/audit/src/lib.rs
  rs/sns/init/src/lib.rs
  rs/sns/integration_tests/src/initialization_flow.rs
  rs/sns/swap/canister/swap.did
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/sns/swap/src/swap.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/common/mod.rs
  rs/sns/swap/tests/swap.rs
Labels: refactor

#514 refactor(IDX): simplify hotfix branch matching logic
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  gitlab-ci/src/bazel-ci/main.sh
  gitlab-ci/src/ci-scripts/build-ic.sh
Labels: refactor

#435 test: RUN-1016: Add unit tests for sandbox to replica IPC messages
  rs/canister_sandbox/src/protocol/ctlsvc.rs
  rs/canister_sandbox/src/protocol/logging.rs
  rs/canister_sandbox/src/protocol/structs.rs
  rs/embedders/src/wasm_executor.rs
Labels: test

#423 chore: [NODE-1382] Miscellaneous updates in prep for upgrade
  gitlab-ci/config/dependencies.yml
  gitlab-ci/config/main.yml
  gitlab-ci/config/rosetta.yml
  gitlab-ci/config/zz-generated-gitlab-ci.yaml
  gitlab-ci/src/ci-scripts/pre-commit.sh
  ic-os/defs.bzl
  scalability/templates/cd_job.yml.hb
Labels: chore

#458 feat(nns): Support StopOrStartCanister proposal action
  rs/nervous_system/root/src/change_canister.rs
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/mod.rs
  rs/nns/governance/src/proposals/stop_or_start_canister.rs
  rs/nns/integration_tests/src/lib.rs
  rs/nns/integration_tests/src/root.rs
  rs/nns/integration_tests/src/stop_or_start_canister.rs
Labels: feat

#531 test: don't upload test canister artifacts
  publish/canisters/BUILD.bazel
Labels: test

#532 fix(IDX): update release testing channel
  .github/workflows/slack-workflow-run.yml
Labels: fix

#536 feat(IDX): limit namespace runs to 1
  .github/workflows/test-namespace-darwin.yml
Labels: feat

#502 chore: remove obsolete cost scaling feature flag
  rs/cycles_account_manager/src/lib.rs
  rs/execution_environment/tests/subnet_size_test.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/rosetta-api/icrc1/index-ng/tests/retrieve_blocks_from_ledger_interval.rs
  rs/state_machine_tests/src/lib.rs
  rs/tests/src/nns_tests/cycles_minting.rs
  rs/tests/src/tecdsa/mod.rs
Labels: chore

#538 test: don't upload malicious_replica
  publish/malicious/BUILD.bazel
Labels: test

#520 refactor(IDX): remove gitlab reference from tests
  gitlab-ci/src/git_changes/git_changes.py
  gitlab-ci/src/git_changes/git_changes_test.py
Labels: refactor

#528 refactor: introduce a system-tests-pkg group and add all system tests under that package group
  rs/BUILD.bazel
  rs/tests/BUILD.bazel
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/utils/BUILD.bazel
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/crypto/BUILD.bazel
  rs/tests/driver/BUILD.bazel
  rs/tests/execution/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/ckbtc/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/gix/BUILD.bazel
  rs/tests/httpbin-rs/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/nested/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/canister_http/BUILD.bazel
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/BUILD.bazel
  rs/tests/nns/sns/BUILD.bazel
  rs/tests/node/BUILD.bazel
  rs/tests/query_stats/BUILD.bazel
  rs/tests/query_stats/lib/BUILD.bazel
  rs/tests/sdk/BUILD.bazel
  rs/tests/test_canisters/http_counter/BUILD.bazel
  rs/tests/test_canisters/kv_store/BUILD.bazel
  rs/tests/test_canisters/message/BUILD.bazel
  rs/tests/testing_verification/BUILD.bazel
  rs/tests/testing_verification/spec_compliance/BUILD.bazel
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/wabt-tests/BUILD.bazel
Labels: refactor

#539 chore(test-dashboard): Update message routing dashboards to mirror productions
  rs/tests/dashboards/IC/checkpoint-durations.json
  rs/tests/dashboards/IC/state-manager-api-calls.json
  rs/tests/dashboards/IC/state-manager-tip-duration.json
  rs/tests/dashboards/IC/tip-handler-durations.json
Labels: chore

#485 chore(PocketIC): release server v5.0.0 and library v4.0.0
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/HOWTO.md
  packages/pocket-ic/README.md
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/main.rs
Labels: chore

#525 chore(consensus): Move get_block_maker_by_rank into test utilities
  rs/consensus/src/consensus/validator.rs
  rs/test_utilities/artifact_pool/src/consensus_pool.rs
Labels: chore

#537 chore(management-canister): Remove unimplemented delete_chunks API
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/scheduler.rs
  rs/system_api/src/routing.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: chore

#546 chore: change file extension for system test logs
  rs/tests/ict/cmd/testnetCreateCmd.go
Labels: chore

#544 chore: [EXC-1633] unify ECDSA and tSchnorr signing requests
  rs/execution_environment/src/execution_environment.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
Labels: chore

#555 fix(IDX): inline namespace profile
  .github/workflows/test-namespace-darwin.yml
Labels: fix

#552 fix(drun): Make drun deterministic again
  rs/drun/src/lib.rs
Labels: bug, fix

#542 chore(execution): Remove wasm_chunk_store flag
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution/install_code/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: chore

#547 chore(IDX): update dependencies of //hs/spec_compliance:ic-ref-test
  WORKSPACE.bazel
  hs/spec_compliance/BUILD.bazel
  stackage_snapshot.json
Labels: chore

#517 feat(nns): Added setting neuron visibility.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/pb/convert_struct_to_enum.rs
  rs/nns/governance/src/pb/convert_struct_to_enum/manage_neuron.rs
  rs/nns/governance/src/pb/convert_struct_to_enum/manage_neuron/configure.rs
  rs/nns/governance/src/pb/mod.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#533 test: stop uploading test canister artifacts
  publish/canisters/BUILD.bazel
  rs/nervous_system/compressed_wasm_size_limits.bzl
Labels: test

#554 feat(sns): Include hash of upgrade args in UpgradeSnsControlledCanister payload text rendering
  rs/sns/governance/src/proposal.rs
Labels: feat

#498 chore(IDX): k8s system tests workflow
  .github/workflows/system-tests-k8s.yml
Labels: chore

#422 chore: [NODE-1384] Update ansible for upcoming lints [S3_UPLOAD]
  .pre-commit-config.yaml
  testnet/ansible/.ansible-lint-ignore
  testnet/ansible/config/common.yml
  testnet/ansible/debug_vars_dump.yml
  testnet/ansible/ic_p8s_service_discovery_destroy.yml
  testnet/ansible/ic_p8s_service_discovery_install.yml
  testnet/ansible/icos_network_redeploy.yml
  testnet/ansible/roles/ic_guest/defaults/main.yml
  testnet/ansible/roles/ic_guest/tasks/aux_disk_push.yml
  testnet/ansible/roles/ic_guest/tasks/create.yml
  testnet/ansible/roles/ic_guest/tasks/destroy.yml
  testnet/ansible/roles/ic_guest/tasks/disk_pull.yml
  testnet/ansible/roles/ic_guest/tasks/disk_push.yml
  testnet/ansible/roles/ic_guest/tasks/install.yml
  testnet/ansible/roles/ic_guest/tasks/main.yml
  testnet/ansible/roles/ic_guest/tasks/media_pull.yml
  testnet/ansible/roles/ic_guest/tasks/media_push.yml
  testnet/ansible/roles/ic_guest/tasks/prepare.yml
  testnet/ansible/roles/ic_guest/tasks/shutdown.yml
  testnet/ansible/roles/ic_guest/tasks/start.yml
  testnet/ansible/roles/ic_guest/tasks/stop.yml
  testnet/ansible/roles/ic_guest/tasks/url_waitfor_connect.yml
  testnet/ansible/roles/ic_guest_prod/defaults/main.yml
  testnet/ansible/roles/ic_guest_prod/tasks/disk_pull.yml
  testnet/ansible/roles/ic_guest_prod/tasks/main.yml
  testnet/ansible/roles/ic_guest_prod/tasks/ssh_keys.yml
  testnet/icos_test.yml
  testnet/icos_test_bnvm.yml
Labels: chore

#556 fix(registry): Optimize get_key_family
  rs/registry/canister/src/mutations/node_management/common.rs
Labels: fix

#448 fix(testnet): succeed if certs can be fetched from at least one machine
  testnet/tools/icos_deploy.sh
Labels: fix

#441 chore: Remove unused instruction limits from subnet record
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/crypto/temp_crypto/src/lib.rs
  rs/nns/integration_tests/src/subnet_handler.rs
  rs/prep/src/subnet_configuration.rs
  rs/protobuf/def/registry/subnet/v1/subnet.proto
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
  rs/registry/admin/src/create_subnet.rs
  rs/registry/admin/src/types.rs
  rs/registry/admin/src/update_subnet.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_create_subnet.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/test_utilities/registry/src/lib.rs
  rs/tests/consensus/utils/src/ssh_access.rs
  rs/tests/driver/src/nns.rs
  rs/tests/src/ckbtc/lib.rs
  rs/tests/src/tecdsa/mod.rs
Labels: chore

#553 chore: introduce release-pkg and ic-os-pkg package groups
  ic-os/bootloader/BUILD.bazel
  ic-os/boundary-guestos/envs/dev/BUILD.bazel
  ic-os/dev-tools/bare_metal_deployment/BUILD.bazel
  ic-os/guestos/envs/dev-malicious/BUILD.bazel
  ic-os/guestos/envs/dev/BUILD.bazel
  ic-os/guestos/envs/local-base-dev/BUILD.bazel
  ic-os/guestos/envs/local-base-prod/BUILD.bazel
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/dev/BUILD.bazel
  ic-os/hostos/envs/local-base-dev/BUILD.bazel
  ic-os/hostos/envs/local-base-prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/dev/BUILD.bazel
  ic-os/setupos/envs/local-base-dev/BUILD.bazel
  publish/canisters/BUILD.bazel
  rs/BUILD.bazel
  rs/bitcoin/adapter/BUILD.bazel
  rs/https_outcalls/adapter/BUILD.bazel
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/deterministic_ips/BUILD.bazel
  rs/ic_os/dflate/BUILD.bazel
  rs/ic_os/diroid/BUILD.bazel
  rs/ic_os/fstrim_tool/BUILD.bazel
  rs/ic_os/guestos_tool/BUILD.bazel
  rs/ic_os/hostos_tool/BUILD.bazel
  rs/ic_os/inject_files/BUILD.bazel
  rs/ic_os/launch-single-vm/BUILD.bazel
  rs/ic_os/network/BUILD.bazel
  rs/ic_os/nft_exporter/BUILD.bazel
  rs/ic_os/nss_icos/BUILD.bazel
  rs/ic_os/partition_tools/BUILD.bazel
  rs/ic_os/setupos-disable-checks/BUILD.bazel
  rs/ic_os/setupos-inject-configuration/BUILD.bazel
  rs/ic_os/setupos_tool/BUILD.bazel
  rs/ic_os/utils/BUILD.bazel
  rs/ic_os/vsock/guest/BUILD.bazel
  rs/ic_os/vsock/host/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
Labels: chore

#524 feat(ICP-Rosetta): FI-1378: add rosetta blocks to block/transaction endpoint
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/tests/tests.rs
  rs/rosetta-api/src/request_handler.rs
Labels: feat

#565 chore: Move drun ownership to the languages team
  .github/CODEOWNERS
Labels: chore

#534 fix(IDX): exclude certain tests from the merge train
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  gitlab-ci/src/git_changes/git_changes_test.py
Labels: fix

#568 fix(IDX): syntax error
  .github/workflows/slack-workflow-run.yml
Labels: fix

#566 chore(crypto): CRP-2551 adapt ic-signature-verification changelog
  packages/ic-signature-verification/CHANGELOG.md
Labels: chore
