Repository dfinity/ic, pull requests merged in 2024-12, with the labels that each got.

#2899 chore: split out parsing the read state response into a separate create
  Cargo.lock
  Cargo.toml
  rs/canister_client/BUILD.bazel
  rs/canister_client/Cargo.toml
  rs/canister_client/read_state_response_parser/BUILD.bazel
  rs/canister_client/read_state_response_parser/Cargo.toml
  rs/canister_client/read_state_response_parser/src/lib.rs
  rs/canister_client/src/agent.rs
  rs/canister_client/src/cbor.rs
  rs/canister_client/src/lib.rs
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/tests/test.rs
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/Cargo.toml
  rs/rosetta-api/icp/src/ledger_client.rs
Labels: chore, @networking, @finint

#2900 fix(IDX): don't depend on BUILD_TIMESTAMP in systests
  rs/tests/driver/src/driver/farm.rs
  rs/tests/system_tests.bzl
Labels: fix, @idx

#2913 revert: "revert: 'chore(IDX): replace PAT with GH App'"
  .github/workflows/sync-public-with-private.yml
Labels: revert, @idx

#2877 fix(sns): Avoid producing overly large errors upon `UpgradeSnsControlledCanister` proposal invalidation
  rs/sns/governance/src/lib.rs
  rs/sns/governance/src/proposal.rs
Labels: fix, @nns-team

#2914 test(IDX): lower parallelism and reserve more CPUs for the //rs/rosetta-api/icp:icp_rosetta_system_tests_tests
  rs/rosetta-api/icp/BUILD.bazel
Labels: test, @finint

#2910 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @dre

#2916 test: CON-1440 Assert that a subnet state exists on the node before it is deleted
  rs/tests/consensus/orchestrator/node_reassignment_test.rs
  rs/tests/consensus/utils/src/node.rs
Labels: test, @idx, @consensus

#2843 feat(nns): Improve listing neuron ids performance by reading the main section only
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_store.rs
Labels: feat, @nns-team

#2920 fix(IDX): use correct Range header when fetching logs from gatewayd from UVMs
  rs/tests/driver/src/driver/group.rs
Labels: fix, @idx

#2918 fix(nervous-system): Ensure clamp_string works on arbitrary unicode inputs
  rs/nervous_system/string/src/lib.rs
  rs/nervous_system/string/src/tests.rs
Labels: fix, @nns-team

#2924 fix(BOUN-1302): authorize to avoid cycle exhausion
  rs/boundary_node/anonymization/backend/src/lib.rs
Labels: fix

#2471 feat(nns): Added prune_some_following.
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Labels: feat

#2523 feat(crypto): CRP-2630 Add support for BIP341 Taproot signatures
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/consensus/utils/src/lib.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/execution_environment/src/scheduler/threshold_signatures.rs
  rs/execution_environment/tests/threshold_signatures.rs
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/system_api/src/routing.rs
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/consensus/idkg/schnorr.rs
Labels: feat, @idx, @consensus, @execution, @ic-message-routing-owners, @ic-interface-owners

#2929 chore(nervous-system): library to help break up messages
  rs/nervous_system/long_message/BUILD.bazel
  rs/nervous_system/long_message/Cargo.toml
  rs/nervous_system/long_message/src/lib.rs
  rs/nervous_system/long_message/tests/test_canisters/empty.did
  rs/nervous_system/long_message/tests/test_canisters/long_message_canister.rs
  rs/nervous_system/long_message/tests/test_message_breaks.rs
Labels: chore, @nns-team

#2930 refactor(nns): move cast_vote_and_cascade_following tests to voting.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/voting.rs
Labels: refactor, @nns-team

#2846 chore(ckbtc): add metrics and logging to the KYT canister
  Cargo.lock
  rs/bitcoin/kyt/BUILD.bazel
  rs/bitcoin/kyt/Cargo.toml
  rs/bitcoin/kyt/src/fetch.rs
  rs/bitcoin/kyt/src/logs.rs
  rs/bitcoin/kyt/src/main.rs
  rs/bitcoin/kyt/src/providers.rs
  rs/bitcoin/kyt/tests/tests.rs
Labels: chore, @cross-chain-team

#2935 chore(dependency-mgmt): bump cargo-audit to v0.21.0
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  ci/container/Dockerfile
  ci/container/TAG
Labels: chore, @idx, @finint

#2871 test: deriving reject code from error code
  rs/types/error_types/src/lib.rs
Labels: test

#2937 fix(IDX): Add default directory for lint script
  ci/scripts/rust-lint.sh
Labels: fix

#2392 feat(nns): Prune following when a neuron has not refreshed in 7 months.
  Cargo.lock
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/Cargo.toml
  rs/nns/integration_tests/src/neuron_following.rs
Labels: feat

#2878 refactor: small improvement on error handling in transport
  rs/p2p/quic_transport/src/connection_manager.rs
  rs/p2p/quic_transport/src/lib.rs
  rs/p2p/quic_transport/src/metrics.rs
Labels: refactor, @networking

#2938 chore: Update blocklist of Bitcoin addresses
  rs/bitcoin/kyt/src/blocklist.rs
Labels: chore, CI_ALL_BAZEL_TARGETS

#2911 docs: add initial README for the abortable broadcast
  rs/p2p/consensus_manager/README.adoc
  rs/p2p/quic_transport/README.adoc
Labels: docs, @networking

#2893 fix(ICRC_Rosetta): Align ICRC Rosetta release tag
  .github/workflows/rosetta-release.yml
Labels: fix, @idx, @finint

#2943 fix: revive the nns recovery script
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
Labels: fix

#2946 refactor(IDX): remove CI_PIPELINE_SOURCE
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  ci/bazel-scripts/main.sh
  ci/scripts/lock-generate.sh
Labels: refactor, @idx

#2950 chore: remove old P2P test dashboard
  rs/tests/dashboards/IC/ic-p2p.json
Labels: chore

#2925 chore(BOUN-1301): add more metrics to canister
  rs/boundary_node/anonymization/backend/src/lib.rs
Labels: chore, @boundary-node

#2665 fix(BOUN): integrate log anonymization into ic-boundary
  Cargo.lock
  ic-os/components/ic/share/ic-boundary.env
  rs/boundary_node/anonymization/backend/Cargo.toml
  rs/boundary_node/anonymization/backend/src/main.rs
  rs/boundary_node/anonymization/client/BUILD.bazel
  rs/boundary_node/anonymization/client/src/lib.rs
  rs/boundary_node/anonymization/interface/BUILD.bazel
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/canister_client/BUILD.bazel
  rs/crypto/internal/logmon/BUILD.bazel
  rs/orchestrator/BUILD.bazel
  rs/orchestrator/Cargo.toml
  rs/orchestrator/src/boundary_node.rs
  rs/orchestrator/src/error.rs
  rs/orchestrator/src/orchestrator.rs
Labels: fix, @boundary-node, @networking, @crypto-team, @node

#2954 chore(IDX): in system-tests, show error when uploading the image fails & retry up to 3 times
  bazel/upload_systest_dep.sh
Labels: chore, @idx

#2928 feat(BOUN-1295): periodically rotate anonymization salt
  rs/boundary_node/anonymization/backend/src/main.rs
Labels: feat, @boundary-node

#2933 fix: [NODE-1519] Fixup colliding permission services
  ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.service
  ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.sh
Labels: fix, @node

#2845 refactor(node): follow-ups to deterministic_ips/ consolidation
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
  ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
  ic-os/components/setupos-scripts/check-network.sh
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/src/generate_testnet_config.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config_types/BUILD.bazel
  rs/ic_os/config_types/Cargo.toml
  rs/ic_os/config_types/src/lib.rs
  rs/ic_os/deterministic_ips/BUILD.bazel
  rs/ic_os/deterministic_ips/Cargo.toml
  rs/ic_os/deterministic_ips/src/lib.rs
  rs/ic_os/deterministic_ips/src/main.rs
  rs/ic_os/deterministic_ips/src/node_type.rs
  rs/ic_os/network/BUILD.bazel
  rs/ic_os/network/Cargo.toml
  rs/ic_os/network/src/lib.rs
  rs/ic_os/network/src/systemd.rs
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/os_tools/hostos_tool/Cargo.toml
  rs/ic_os/os_tools/hostos_tool/src/main.rs
  rs/ic_os/os_tools/setupos_tool/BUILD.bazel
  rs/ic_os/os_tools/setupos_tool/Cargo.toml
  rs/ic_os/os_tools/setupos_tool/src/main.rs
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/driver/nested.rs
Labels: refactor, @idx, @node

#806 refactor: Move xnet_test canister to use public CDK
  Cargo.lock
  rs/messaging/tests/queue_tests.rs
  rs/rust_canisters/xnet_test/BUILD.bazel
  rs/rust_canisters/xnet_test/Cargo.toml
  rs/rust_canisters/xnet_test/src/lib.rs
  rs/rust_canisters/xnet_test/src/main.rs
  rs/rust_canisters/xnet_test/xnet_test.did
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/Cargo.toml
  rs/tests/message_routing/common/BUILD.bazel
  rs/tests/message_routing/common/Cargo.toml
  rs/tests/message_routing/common/common.rs
  rs/tests/message_routing/global_reboot_test.rs
  rs/tests/message_routing/xnet/slo_test_lib/xnet_slo_test_lib.rs
Labels: refactor, @idx, @ic-message-routing-owners, @ic-interface-owners, CI_OVERRIDE_DIDC_CHECK

#2958 test(ICRC_Ledger): FI-1531: Also check expiration time when comparing allowances in InMemoryLedger
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
Labels: test, @finint

#2963 perf: Copy outside write lock
  rs/state_manager/src/lib.rs
Labels: perf

#2961 chore: Add best practices on use of panics in the DSM
  rs/execution_environment/best-practices-panics.md
  rs/messaging/best-practices-panics.md
  rs/replicated_state/best-practices-panics.md
  rs/replicated_state/best-practices-replicated-state.md
Labels: chore, @execution

#2953 feat(NODE-1534): discard for data partition
  ic-os/components/monitoring/fstrim/fstrim_tool.service
  rs/ic_os/fstrim_tool/src/lib.rs
  rs/ic_os/fstrim_tool/src/main.rs
  rs/ic_os/fstrim_tool/src/tests.rs
  rs/ic_os/fstrim_tool/tests/integration_tests.rs
Labels: feat, @crypto-team, @node

#2949 refactor(IDX): move CI_JOB_URL
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/system-tests-k8s.yml
Labels: refactor, @idx

#2970 fix: Update argument to start function of xnet canister in global reboot test
  rs/tests/message_routing/global_reboot_test.rs
Labels: fix

#2934 feat(nns): Move spawn_neurons to a one-minute timer
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#2973 perf(nns): Add a benchmark for drawing neurons fund maturity
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_store/benches.rs
Labels: perf, @nns-team

#2975 feat(nns): Improve drawing/refunding neurons fund maturity when neurons in stable memory feature is enabled
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neurons_fund.rs
  rs/nns/governance/src/storage/neurons.rs
Labels: feat

#2974 chore: Bump canbench and pocket ic mainnet version
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  MODULE.bazel
  bazel/external_crates.bzl
Labels: chore

#2969 feat: Add various subnet info metrics
  rs/messaging/src/message_routing.rs
Labels: feat

#2977 refactor(nns): Move recompute_tally to inside of cast_vote_and_cascade_follow
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/voting.rs
Labels: refactor, @nns-team

#2393 feat(node): update-config.service
  ic-os/components/guestos.bzl
  ic-os/components/hostos.bzl
  ic-os/components/misc/update-config/update-guestos-config.service
  ic-os/components/misc/update-config/update-hostos-config.service
  ic-os/guestos/defs.bzl
  ic-os/hostos/defs.bzl
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/update_config.rs
  rs/ic_os/config_types/src/lib.rs
Labels: feat, @node

#2965 chore: enable `best_effort_responses` in `drun`
  rs/drun/src/main.rs
Labels: chore, @languages

#2964 chore: merge infallible errors, improve expect statements and use {:#?} for anyhow error formatting
  rs/p2p/quic_transport/src/connection_manager.rs
  rs/p2p/quic_transport/src/lib.rs
  rs/p2p/quic_transport/src/request_handler.rs
Labels: chore, @networking

#2984 test(IDX): improve error message in xnet_slo_test
  rs/tests/message_routing/common/common.rs
Labels: test, @idx, @ic-message-routing-owners

#2951 fix: Revert from 24.04 build container
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-mirror-images.json
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .pre-commit-config.yaml
  MODULE.bazel
  bazel/focal.lock.json
  bazel/focal.yaml
  ci/container/Dockerfile
  ci/container/TAG
  ci/container/build-image.sh
  ci/container/container-run.sh
  ci/container/files/packages.common
  ci/src/dependencies/scanner/manager/bazel_rust_dependency_manager.py
  requirements.txt
  rs/tests/BUILD.bazel
  testnet/ansible/debug_vars_dump.yml
  testnet/ansible/ic_p8s_service_discovery_destroy.yml
  testnet/ansible/ic_p8s_service_discovery_install.yml
  testnet/ansible/roles/ic_guest/tasks/aux_disk_push.yml
  testnet/ansible/roles/ic_guest/tasks/create.yml
  testnet/ansible/roles/ic_guest/tasks/destroy.yml
  testnet/ansible/roles/ic_guest/tasks/disk_pull.yml
  testnet/ansible/roles/ic_guest/tasks/disk_push.yml
  testnet/ansible/roles/ic_guest/tasks/install.yml
  testnet/ansible/roles/ic_guest/tasks/main.yml
  testnet/ansible/roles/ic_guest/tasks/media_pull.yml
  testnet/ansible/roles/ic_guest/tasks/media_push.yml
  testnet/ansible/roles/ic_guest/tasks/prepare.yml
  testnet/ansible/roles/ic_guest/tasks/shutdown.yml
  testnet/ansible/roles/ic_guest/tasks/start.yml
  testnet/ansible/roles/ic_guest/tasks/stop.yml
  testnet/ansible/roles/ic_guest/tasks/url_waitfor_connect.yml
  testnet/ansible/roles/ic_guest_prod/tasks/disk_pull.yml
  testnet/ansible/roles/ic_guest_prod/tasks/main.yml
Labels: fix, @idx, @product-security, @finint, @ic-owners-owners, @platform-operations

#2985 fix: Fix XNet end-to-end tests
  rs/tests/message_routing/common/common.rs
Labels: fix

#2741 chore: CRP-2614 Rename IDKG test functions and struct fields in Network and SubnetTopology
  packages/pocket-ic/tests/tests.rs
  rs/canonical_state/src/traversal.rs
  rs/execution_environment/benches/management_canister/ecdsa.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/execution_environment/tests/execution_test.rs
  rs/execution_environment/tests/subnet_size_test.rs
  rs/execution_environment/tests/threshold_signatures.rs
  rs/http_endpoints/public/tests/common/mod.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/message_routing/tests.rs
  rs/messaging/src/state_machine/tests.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_manager/tests/state_manager.rs
  rs/system_api/src/routing.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/test_utilities/state/src/lib.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
Labels: chore, @idx, @consensus, @execution, @networking, @pocket-ic, @ic-message-routing-owners, @ic-interface-owners, CI_OVERRIDE_BUF_BREAKING

#2986 feat(IDX): add bot approved file list
  .github/CI_README.md
  .github/repo_policies/BOT_APPROVED_FILES
Labels: feat, @idx

#2580 feat(nns): Add voting_power_economics to NetworkEconomics.
  Cargo.lock
  rs/nns/governance/api/BUILD.bazel
  rs/nns/governance/api/Cargo.toml
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/api/src/pb.rs
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/data_migration.rs
  rs/nns/governance/src/data_migration_tests.rs
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/voting.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/merge_neurons.rs
  rs/nns/integration_tests/src/network_economics.rs
Labels: feat, @nns-team

#2840 test: CON-1433 Enable `cup_compatibility_test` for new `NiDkgTag::HighThresholdForKey`
  rs/types/types/src/consensus/idkg.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg.rs
  rs/types/types/src/exhaustive.rs
Labels: test, @consensus, @crypto-team

#2966 chore(ckbtc): Rename btc kyt canister to btc checker canister
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  publish/canisters/BUILD.bazel
  rs/bitcoin/checker/BUILD.bazel
  rs/bitcoin/checker/Cargo.toml
  rs/bitcoin/checker/btc_checker_canister.did
  rs/bitcoin/checker/src/blocklist.rs
  rs/bitcoin/checker/src/dashboard.rs
  rs/bitcoin/checker/src/dashboard/tests.rs
  rs/bitcoin/checker/src/fetch.rs
  rs/bitcoin/checker/src/fetch/tests.rs
  rs/bitcoin/checker/src/lib.rs
  rs/bitcoin/checker/src/logs.rs
  rs/bitcoin/checker/src/main.rs
  rs/bitcoin/checker/src/providers.rs
  rs/bitcoin/checker/src/providers/tests.rs
  rs/bitcoin/checker/src/state.rs
  rs/bitcoin/checker/src/state/tests.rs
  rs/bitcoin/checker/src/types.rs
  rs/bitcoin/checker/templates/dashboard.html
  rs/bitcoin/checker/tests/tests.rs
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/Cargo.toml
  rs/bitcoin/ckbtc/minter/README.adoc
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/address.rs
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/guard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/lifecycle/init.rs
  rs/bitcoin/ckbtc/minter/src/lifecycle/upgrade.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/memo.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/state/audit.rs
  rs/bitcoin/ckbtc/minter/src/state/eventlog.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/src/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
  rs/bitcoin/ckbtc/minter/src/updates/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
  rs/tests/ckbtc/BUILD.bazel
  rs/tests/ckbtc/Cargo.toml
  rs/tests/ckbtc/ckbtc_minter_basics_test.rs
  rs/tests/ckbtc/ckbtc_minter_batching.rs
  rs/tests/ckbtc/ckbtc_minter_checker.rs
  rs/tests/ckbtc/ckbtc_minter_deposit_and_withdrawal.rs
  rs/tests/ckbtc/ckbtc_minter_retrieve_btc.rs
  rs/tests/ckbtc/ckbtc_minter_update_balance.rs
  rs/tests/ckbtc/src/lib.rs
Labels: chore, @idx, @ic-interface-owners, @cross-chain-team, @ic-owners-owners, CI_ALL_BAZEL_TARGETS, CI_OVERRIDE_DIDC_CHECK

#2987 chore(fuzzing): merge stable structures fuzzer(s) into a single binary
  rs/fuzzers/stable_structures/BUILD.bazel
  rs/fuzzers/stable_structures/fuzz_targets/data.rs
  rs/fuzzers/stable_structures/fuzz_targets/stable_btreemap_multiple_ops_persistent.rs
  rs/fuzzers/stable_structures/fuzz_targets/stable_minheap_multiple_ops_persistent.rs
  rs/fuzzers/stable_structures/fuzz_targets/stable_structures_multiple_ops_persistent.rs
Labels: chore, @product-security

#2980 feat: [NODE-1499] Create and use a faster alternative to `prestorecon`
  ic-os/components/guestos.bzl
  ic-os/components/ic/setup-permissions/erestorecon.sh
  ic-os/components/ic/setup-permissions/setup-permissions.sh
  ic-os/guestos/defs.bzl
Labels: feat, @node

#2939 feat(ckbtc): add timestamps to suspended UTXOs
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/state/audit.rs
  rs/bitcoin/ckbtc/minter/src/state/eventlog.rs
  rs/bitcoin/ckbtc/minter/src/state/tests.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/src/updates/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
Labels: feat, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#2999 chore: Remove prestorecon
  .gitignore
  cpp/BUILD.bazel
  cpp/Makefile
  cpp/prestorecon-cpp/prestorecon.cc
Labels: chore

#2909 chore(cketh/ckerc20): proposal to upgrade ledger suite orchestrator and managed canisters
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_12_02.md
Labels: chore, @cross-chain-team

#2993 chore(ICP_Ledger): Fix ICP ledger heap memory bytes metric comment
  rs/ledger_suite/icp/ledger/src/main.rs
Labels: chore, @finint

#3000 fix(ckbtc): compute min_withdrawal_amount using check_fee from state
  rs/bitcoin/ckbtc/minter/src/lib.rs
Labels: fix, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#2960 test(ICRC_Ledger): FI-1595: Check ledger metrics in ICRC golden state test
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/metrics.rs
Labels: test, @finint

#2997 feat(nns): Propose voting power economics.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#2994 chore: upgrade crates
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#2972 fix(nns): Change the default voting power refreshed timestamp from Nov 15 to Sep 1.
  Cargo.lock
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/Cargo.toml
  rs/nns/integration_tests/src/neuron_following.rs
Labels: fix, @nns-team

#3008 fix: Await all calls at once in xnet_test_canister's fanout()
  rs/rust_canisters/xnet_test/src/main.rs
Labels: fix, @ic-message-routing-owners

#3004 chore: Align test canister naming
  .github/CODEOWNERS
  rs/rust_canisters/statesync_test/BUILD.bazel
  rs/tests/common.bzl
  rs/tests/message_routing/BUILD.bazel
Labels: chore, @nns-team, @ic-owners-owners

#2921 refactor(ckbtc): use IC CDK to interact with Bitcoin canister
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/mock/src/main.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3002 chore(ckbtc): add Bitcoin Checker canister
  rs/bitcoin/ckbtc/mainnet/canister_ids.json
  rs/bitcoin/ckbtc/mainnet/dfx.json
  rs/bitcoin/ckbtc/testnet/canister_ids.json
  rs/bitcoin/ckbtc/testnet/dfx.json
  rs/cross-chain/proposal-cli/BUILD.bazel
  rs/cross-chain/proposal-cli/src/candid/tests.rs
  rs/cross-chain/proposal-cli/src/canister/mod.rs
Labels: chore, @cross-chain-team

#2978 chore(nns): Disable canbench test for NNS Governance
  rs/nns/governance/BUILD.bazel
Labels: chore

#3018 test(NNS): isolate upgrade_everything_test to its own bazel target
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
  rs/nervous_system/integration_tests/tests/upgrade_everything_test.rs
Labels: test, @nns-team

#3021 fix(nns): Copied RefreshVotingPower to ManageNeuronCommandRequest.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/api/src/proposal_submission_helpers.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/src/pb/conversions.rs
Labels: fix, @nns-team

#2976 perf(sns): Set up canbench
  Cargo.lock
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/canbench/canbench_results.yml
  rs/sns/governance/canbench/main.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/benches.rs
Labels: perf, @idx, @nns-team

#2955 feat: Add reboot toy
  Cargo.lock
  rs/tests/consensus/orchestrator/Cargo.toml
  rs/tests/node/BUILD.bazel
  rs/tests/node/Cargo.toml
  rs/tests/node/reboot_toy.rs
Labels: feat, @idx, @node

#2926 chore(node): networking touch-ups
  ic-os/docs/Network-Configuration.adoc
  rs/ic_os/deterministic_ips/README.md
  rs/ic_os/deterministic_ips/src/lib.rs
  rs/ic_os/network/src/info.rs
  rs/ic_os/network/src/interfaces.rs
  rs/ic_os/network/src/lib.rs
  rs/ic_os/network/src/systemd.rs
  rs/ic_os/os_tools/guestos_tool/src/generate_network_config.rs
  rs/ic_os/utils/src/lib.rs
Labels: chore, @node

#2740 chore(node): Remove legacy mercury.dfinity.systems logging targets
  ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
  ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
  ic-os/setupos/data/deployment.json.template
  rs/ic_os/config/src/deployment_json.rs
  rs/ic_os/config/src/generate_testnet_config.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/update_config.rs
  rs/ic_os/config_types/src/lib.rs
Labels: chore, @node

#2932 feat(nns): Highly scalable voting
  Cargo.lock
  rs/nervous_system/long_message/src/lib.rs
  rs/nervous_system/long_message/tests/test_canisters/long_message_canister.rs
  rs/nervous_system/long_message/tests/test_message_breaks.rs
  rs/nns/common/src/lib.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/storage.rs
  rs/nns/governance/src/test_utils.rs
  rs/nns/governance/src/voting.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/integration_tests/src/neuron_voting.rs
  rs/nns/integration_tests/src/voting_rewards.rs
Labels: feat

#3034 chore(IDX): update slack alerts
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/slack-workflow-run.yml
Labels: chore, @idx

#3036 test(IDX): isolate the advance_target_version_upgrades_all_canisters_test
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
  rs/nervous_system/integration_tests/tests/advance_target_version_upgrades_all_canisters_test.rs
Labels: test, @nns-team

#3010 fix: Use futures::Stream and remove redundant functions in rs/async_utils
  rs/async_utils/src/lib.rs
  rs/async_utils/src/unix.rs
  rs/bitcoin/adapter/src/rpc_server.rs
  rs/https_outcalls/adapter/src/lib.rs
Labels: fix, @networking

#3040 test(IDX): isolate the upgrade_existing_sns_test
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
Labels: test, @nns-team

#3041 chore(IDX): IDX no longer co-owns system-tests
  .github/CODEOWNERS
Labels: chore, @ic-owners-owners

#3042 test(IDX): do not capture logs in //rs/nervous_system/integration_tests:... tests
  rs/nervous_system/integration_tests/BUILD.bazel
Labels: test, @nns-team

#3048 test(IDX): tag tecdsa_key_rotation_test as a long_test
  rs/tests/consensus/tecdsa/BUILD.bazel
Labels: test, @consensus

#2768 test(ICP_Ledger): FI-1531: Use InMemoryLedger in ICP golden state test
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/index/tests/tests.rs
  rs/ledger_suite/icp/test_utils/src/state_machine_helpers/ledger.rs
  rs/ledger_suite/icp/tests/golden_nns_state.rs
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#3030 chore: increase PocketIC test size and cpu
  packages/pocket-ic/BUILD.bazel
Labels: chore

#3029 fix: retry bad gateway errors in spec compliance tests
  hs/spec_compliance/src/IC/Test/Agent.hs
Labels: fix

#3044 fix(registry): Ensure subnet features can be changed for subnets without any features
  rs/registry/canister/src/mutations/do_update_subnet.rs
Labels: fix, @nns-team

#3062 chore(nervous-system): Update mainnet-canisters.json
  mainnet-canisters.json
Labels: chore

#3064 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @consensus

#3013 chore(ckbtc): proposals to install Bitcoin Checker and to use it in ckBTC minter
  rs/bitcoin/ckbtc/mainnet/btc_checker_install_2024_12_06.md
  rs/bitcoin/ckbtc/mainnet/minter_upgrade_2024_12_06.md
Labels: chore, @cross-chain-team

#3061 refactor(nns): pass begin: Bound<NeuronId> to schedule_prune_some_following.
  rs/nns/governance/canister/canister.rs
Labels: refactor, @nns-team

#3065 test(sns): Make ensure_archive_canister_is_spawned_or_panic faster
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
Labels: test, @nns-team

#3069 chore(IDX): disable system tests k8s
  .github/workflows/system-tests-k8s.yml
Labels: chore, @idx

#3005 feat(BOUN-1255): Add rate-limiting canister client to `ic-boundary`
  Cargo.lock
  Cargo.toml
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/rate_limiting.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/fetcher.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/rate_limits/api/BUILD.bazel
  rs/boundary_node/rate_limits/api/Cargo.toml
  rs/boundary_node/rate_limits/api/src/schema_versions/v1.rs
  rs/boundary_node/rate_limits/canister_client/Cargo.toml
  rs/boundary_node/rate_limits/canister_client/src/main.rs
  rs/tests/boundary_nodes/rate_limit_canister_test.rs
Labels: feat, @idx, @boundary-node

#3025 fix(node): add node-reward-type default to setupos-inject-config
  rs/tests/driver/src/driver/bootstrap.rs
Labels: fix, @idx

#3068 chore(nns): Add TODO back to proposal texts to add human-readable summary before submitting
  testnet/tools/nns-tools/lib/proposals.sh
Labels: chore, @nns-team

#2991 fix(EXC-1811): Disable `anyhow` backtraces in sandbox
  rs/canister_sandbox/src/launcher.rs
  rs/canister_sandbox/src/process.rs
  rs/canister_sandbox/src/replica_controller/launch_as_process.rs
Labels: fix

#3073 test(nns): Add recent_ballots_next_entry_index to NeuronBuilder and let it be So…
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/tests/governance.rs
Labels: test

#3059 test(IDX): allow more time for //rs/nervous_system/integration_tests:...
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/tests/deploy_fresh_sns_test.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
Labels: test, @nns-team

#3078 fix(BOUN-1255): fix canister queries, add cli interval
  ic-os/components/boundary-guestos/opt/ic/bin/setup-ic-boundary.sh
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/fetcher.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
Labels: fix

#3071 fix(ckbtc): state schema upgrade
  Cargo.lock
  rs/bitcoin/checker/BUILD.bazel
  rs/bitcoin/checker/Cargo.toml
  rs/bitcoin/checker/src/main.rs
  rs/bitcoin/checker/src/state.rs
  rs/bitcoin/checker/src/state/tests.rs
Labels: fix, @cross-chain-team

#3047 fix: Use default rust edition instead of specifying it in the BUILD rules
  rs/crypto/for_verification_only/BUILD.bazel
  rs/crypto/internal/crypto_service_provider/csp_proptest_utils/BUILD.bazel
  rs/crypto/internal/logmon/BUILD.bazel
  rs/crypto/node_key_generation/BUILD.bazel
  rs/crypto/standalone-sig-verifier/BUILD.bazel
  rs/crypto/temp_crypto/BUILD.bazel
  rs/crypto/temp_crypto/temp_vault/BUILD.bazel
  rs/crypto/test_utils/csp/BUILD.bazel
  rs/crypto/test_utils/keys/BUILD.bazel
  rs/crypto/test_utils/local_csp_vault/BUILD.bazel
  rs/crypto/test_utils/metrics/BUILD.bazel
  rs/crypto/test_utils/ni-dkg/BUILD.bazel
  rs/crypto/test_utils/root_of_trust/BUILD.bazel
  rs/crypto/test_utils/tls/BUILD.bazel
  rs/crypto/tree_hash/BUILD.bazel
  rs/crypto/tree_hash/test_utils/BUILD.bazel
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config_types/BUILD.bazel
  rs/ic_os/dev_test_tools/launch-single-vm/BUILD.bazel
  rs/ic_os/network/BUILD.bazel
  rs/ic_os/os_tools/guestos_tool/BUILD.bazel
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/os_tools/setupos_tool/BUILD.bazel
  rs/ic_os/utils/BUILD.bazel
  rs/ic_os/vsock/guest/BUILD.bazel
  rs/ic_os/vsock/host/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icrc1/benchmark/generator/BUILD.bazel
  rs/ledger_suite/icrc1/benchmark/worker/BUILD.bazel
  rs/ledger_suite/icrc1/index-ng/BUILD.bazel
  rs/ledger_suite/icrc1/index/BUILD.bazel
  rs/replica_tests/BUILD.bazel
  rs/rosetta-api/tvl/BUILD.bazel
  rs/rosetta-api/tvl/xrc_mock/BUILD.bazel
  rs/test_utilities/in_memory_logger/BUILD.bazel
  rs/validator/http_request_arbitrary/BUILD.bazel
  rs/validator/http_request_test_utils/BUILD.bazel
  rs/validator/ingress_message/BUILD.bazel
Labels: fix, @execution, @crypto-team, @ic-message-routing-owners, @node, @finint

#3081 fix(IDX): override mainnet_revisions.json
  testnet/mainnet_revisions.json
Labels: fix, @dre, @consensus

#3053 feat(BOUN-1300): Add metrics to anonymization client
  Cargo.lock
  rs/boundary_node/anonymization/client/BUILD.bazel
  rs/boundary_node/anonymization/client/Cargo.toml
  rs/boundary_node/anonymization/client/src/lib.rs
  rs/boundary_node/ic_boundary/src/core.rs
Labels: feat, @boundary-node

#3001 feat(fuzzing): Duplicate STDERR to a separate file in AFL
  bin/afl_wrapper.sh
  rs/fuzzers/stable_structures/fuzz_targets/stable_structures_multiple_ops_persistent.rs
Labels: feat, @product-security

#3033 test(ICP_Ledger): FI-1506: Increase CPU reservation for flaky ICP ledger and index tests
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icp/ledger/BUILD.bazel
Labels: test, @finint

#2962 test: Port the random traffic canister to CDK.
  Cargo.lock
  rs/messaging/tests/memory_tests.rs
  rs/rust_canisters/downstream_calls_test/src/main.rs
  rs/rust_canisters/random_traffic_test/BUILD.bazel
  rs/rust_canisters/random_traffic_test/Cargo.toml
  rs/rust_canisters/random_traffic_test/src/lib.rs
  rs/rust_canisters/random_traffic_test/src/main.rs
Labels: test, @ic-message-routing-owners

#3066 chore(ckbtc): NNS proposal to update Bitcoin Checker
  rs/bitcoin/ckbtc/mainnet/btc_checker_upgrade_2024_12_09.md
Labels: chore

#3088 test(IDX-3144): inline some more fin-int system-tests
  rs/tests/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_test.rs
  rs/tests/financial_integrations/transaction_ledger_correctness.mo
  rs/tests/financial_integrations/transaction_ledger_correctness.wasm
  rs/tests/financial_integrations/transaction_ledger_correctness_test.rs
  rs/tests/src/api_test.rs
  rs/tests/src/ledger_tests/mod.rs
  rs/tests/src/ledger_tests/transaction_ledger_correctness.rs
  rs/tests/src/lib.rs
  rs/tests/src/rosetta_test.rs
Labels: test, @idx, @finint

#3019 perf(nns): Add benchmark for listing neurons fund neurons
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store/benches.rs
Labels: perf

#2959 refactor: Move statesync_test canister to Rust CDK
  Cargo.lock
  rs/rust_canisters/statesync_test/BUILD.bazel
  rs/rust_canisters/statesync_test/Cargo.toml
  rs/rust_canisters/statesync_test/src/main.rs
  rs/rust_canisters/statesync_test/test/test.rs
  rs/tests/message_routing/rejoin_test_lib/BUILD.bazel
  rs/tests/message_routing/rejoin_test_lib/Cargo.toml
  rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
Labels: refactor, @idx, @nns-team, @ic-message-routing-owners

#3060 test: Adjust cycles in cloner canister test
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/networking/canisters/src/cloner_canister.rs
  rs/tests/networking/cloner_canister_workload.rs
Labels: test, @idx

#2942 chore(IDX): bazel-test-all update
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#3091 feat(sns): Recover SNS from not knowing its deployed version
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/canbench/canbench_results.yml
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/tests/fixtures/mod.rs
  rs/sns/governance/tests/governance.rs
Labels: feat, @nns-team

#3022 chore(nns): Clarify the purpose of loading the known neuron section when calculating metrics
  rs/nns/governance/src/neuron_store/metrics.rs
Labels: chore, @nns-team

#3070 feat(nns): Periodic confirmation metrics.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/metrics/tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/tests.rs
  rs/nns/governance/tests/governance.rs
Labels: feat, @nns-team

#3097 refactor(sns): Move human-readable timestamp formatter into its own crate
  Cargo.lock
  rs/nervous_system/timestamp/BUILD.bazel
  rs/nervous_system/timestamp/Cargo.toml
  rs/nervous_system/timestamp/src/lib.rs
  rs/nervous_system/timestamp/src/tests.rs
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/proposal/advance_sns_target_version.rs
Labels: refactor, @nns-team

#3099 feat(sns): Print human-readable timestamps when printing timestamps for humans
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
Labels: feat, @nns-team

#3090 feat(nns): Count stale and expired voting power neurons.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/metrics/tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#3096 refactor(tests): `await_with_timeout` should take a range, not just a timeout
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
  rs/nervous_system/integration_tests/tests/advance_target_version_upgrades_all_canisters_test.rs
Labels: refactor, @nns-team

#2981 test(sns): Migrate upgrade qualification tests to AdvanceSnsTargetVersion
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/deploy_fresh_sns_test.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification_legacy.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs
Labels: test, @nns-team

#3100 chore: use mozilla root ca store in PocketIC tests on macOS
  MODULE.bazel
  packages/pocket-ic/BUILD.bazel
  rs/pocket_ic_server/BUILD.bazel
Labels: chore, @pocket-ic

#3107 fix: adjust timeouts and add static asserts
  Cargo.lock
  rs/p2p/quic_transport/BUILD.bazel
  rs/p2p/quic_transport/Cargo.toml
  rs/p2p/quic_transport/src/connection_manager.rs
Labels: fix, @networking

#3085 feat: adding updating of `mainnet_revisions.json` to the repo
  .github/workflows/update-mainnet-revisions.yaml
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: feat

#3112 test(IDX): increase timeout to 15m for the ic_icp_index_test
  rs/ledger_suite/icp/index/BUILD.bazel
Labels: test, @finint

#3113 test(IDX): increase timeout to 15m for the ledger_canister_test
  rs/ledger_suite/icp/ledger/BUILD.bazel
Labels: test, @finint

#3114 test(IDX): increae timeout of the NNS integration_tests_test
  rs/nns/integration_tests/BUILD.bazel
Labels: test, @nns-team

#3109 chore: reduce parallelism in PocketIC tests
  packages/pocket-ic/BUILD.bazel
Labels: chore

#2818 feat(ICP-ledger): FI-1438: Implement V3 for ICP ledger - migrate allowances to stable structures
  Cargo.lock
  rs/ledger_suite/common/ledger_canister_core/src/ledger.rs
  rs/ledger_suite/common/ledger_core/src/approvals.rs
  rs/ledger_suite/common/ledger_core/src/approvals/tests.rs
  rs/ledger_suite/common/ledger_core/src/tokens.rs
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/Cargo.toml
  rs/ledger_suite/icp/ledger.did
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/lib.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/src/tests.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/src/account_identifier.rs
  rs/ledger_suite/icp/src/lib.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/nns/inspector/BUILD.bazel
  rs/nns/inspector/Cargo.toml
  rs/nns/inspector/src/main.rs
Labels: feat, @nns-team, @finint

#2589 feat: [EXC-1753] Add mint_cycles128 API
  rs/cycles_account_manager/src/lib.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/execution_environment/benches/system_api/diff-old-vs-new.sh
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/tests/execution/general_execution_test.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
Labels: feat, @idx, @execution

#3095 chore(system-tests-k8s): kubevirt api changes
  .github/workflows/system-tests-k8s.yml
  rs/tests/driver/src/k8s/virtualmachine.rs
Labels: chore, @idx

#2936 feat: CON-1418 CON-1421 Implement a stubbed VetKd client as part of the IDKG signer
  rs/artifact_pool/src/idkg_pool.rs
  rs/artifact_pool/src/lmdb_pool.rs
  rs/consensus/src/idkg.rs
  rs/consensus/src/idkg/payload_builder/signatures.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/interfaces/src/crypto/errors.rs
  rs/interfaces/src/crypto/vetkd.rs
  rs/interfaces/src/idkg.rs
  rs/protobuf/def/types/v1/idkg.proto
  rs/protobuf/src/gen/types/types.v1.rs
  rs/test_utilities/src/crypto.rs
  rs/types/types/src/consensus/idkg.rs
  rs/types/types/src/consensus/idkg/common.rs
  rs/types/types/src/crypto/hash.rs
  rs/types/types/src/crypto/hash/domain_separator.rs
  rs/types/types/src/crypto/vetkd.rs
Labels: feat, @consensus, @crypto-team, @ic-interface-owners

#3106 feat(BOUN-1308): build and publish anonymization canister
  .github/workflows/anonymization-backend-release.yml
  rs/boundary_node/anonymization/backend/BUILD.bazel
  rs/boundary_node/anonymization/backend/build.sh
  rs/boundary_node/anonymization/backend/dfx.json
Labels: feat, @boundary-node

#3115 fix(ckbtc): Drop Host header from https outcall request
  rs/bitcoin/checker/src/providers.rs
Labels: fix, @cross-chain-team

#3007 test(ICP_Ledger): FI-1589: Adapt ICP golden state test to ledger migration v3
  rs/ledger_suite/icp/tests/golden_nns_state.rs
Labels: test, @nns-team

#3122 feat(BOUN-1308): use local bazel config for reproduction instuctions
  .github/workflows/anonymization-backend-release.yml
Labels: feat, @idx

#3128 test(sns): Do release-qualification for swap upgrades
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification_legacy.rs
Labels: test, @nns-team

#3125 revert: "feat: [EXC-1753] Add mint_cycles128 API"
  rs/cycles_account_manager/src/lib.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/execution_environment/benches/system_api/diff-old-vs-new.sh
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/tests/execution/general_execution_test.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
Labels: revert, @execution, CI_ALL_BAZEL_TARGETS

#3101 chore: Fix typo in the name of an internal bazel target
  Cargo.lock
  Cargo.toml
  rs/nervous_system/tools/sync-with-released-nervous-system-wasms/BUILD.bazel
  rs/nervous_system/tools/sync-with-released-nervous-system-wasms/Cargo.toml
  rs/nervous_system/tools/sync-with-released-nervous-system-wasms/src/main.rs
Labels: chore, @idx, @nns-team

#3076 test(nns): Add a benchmark for list neurons
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/neuron_store.rs
Labels: test, @nns-team

#3102 perf(nns): Add benchmarks for neuron data validator
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_store/benches.rs
Labels: perf, @nns-team

#3103 perf(nns): Read heap neurons for cardinalities
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store.rs
Labels: perf

#3093 feat(cmc): Increase cycles_limit by 3x.
  rs/nns/cmc/src/main.rs
  rs/nns/integration_tests/src/cycles_minting_canister.rs
Labels: feat, @nns-team

#3038 perf: EXC-1818: Fix embedder benches
  rs/embedders/BUILD.bazel
  rs/embedders/benches/compilation.rs
  rs/embedders/benches/embedders_bench/src/lib.rs
Labels: perf, @execution

#3127 fix(BOUN-1308): set bash shell on all steps
  .github/workflows/anonymization-backend-release.yml
  .github/workflows/rate-limits-backend-release.yml
Labels: fix

#3063 feat(ICP-Rosetta): FI-1603: implement refresh voting power endpoint
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/src/convert.rs
  rs/rosetta-api/icp/src/convert/state.rs
  rs/rosetta-api/icp/src/ledger_client.rs
  rs/rosetta-api/icp/src/ledger_client/handle_refresh_voting_power.rs
  rs/rosetta-api/icp/src/models/operation.rs
  rs/rosetta-api/icp/src/request.rs
  rs/rosetta-api/icp/src/request_handler/construction_parse.rs
  rs/rosetta-api/icp/src/request_handler/construction_payloads.rs
  rs/rosetta-api/icp/src/request_handler/construction_preprocess.rs
  rs/rosetta-api/icp/src/request_types.rs
  rs/rosetta-api/icp/src/transaction_id.rs
  rs/rosetta-api/icp/test_utils/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/src/rosetta_tests/lib.rs
Labels: feat, @finint
