Repository dfinity/ic, pull requests merged in 2024-11, with the labels that each got.

#2301 chore: EXC-1758: Fix doc comment
  rs/canister_sandbox/src/replica_controller/sandbox_process_eviction.rs
Labels: chore, @execution

#1725 chore: RUN-1037: Adjust Wasm64 dirty page overhead
  rs/config/src/embedders.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/tests/instrumentation.rs
Labels: chore, @execution

#2344 chore(consensus): avoid block hash computation in several places
  Cargo.lock
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/block_maker.rs
  rs/consensus/src/consensus/metrics.rs
  rs/consensus/utils/BUILD.bazel
  rs/consensus/utils/Cargo.toml
  rs/consensus/utils/src/lib.rs
  rs/types/types/src/consensus.rs
Labels: chore, @consensus

#1755 feat(sns-cli): Rename `Distribution.InitialBalances.governance` as `Distribution.InitialBalances.treasury`.
  rs/sns/cli/src/init_config_file/friendly.rs
  rs/sns/cli/src/init_config_file/friendly/friendly_tests.rs
  rs/sns/cli/test_sns_init_v2.yaml
  testnet/tools/nns-tools/sns_default_test_init_params_v2.yml
Labels: feat, @nns-team

#2319 fix: always enable canister sandboxing in SM tests
  packages/pocket-ic/tests/slow.rs
  rs/state_machine_tests/src/lib.rs
Labels: fix, @pocket-ic, @ic-message-routing-owners

#2259 fix(PocketIC): doc tests
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/lib.rs
Labels: fix, @pocket-ic

#2349 chore: reshare status handle from ic-boundary
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: chore

#2350 chore: drop unused operation in PocketIC server
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: chore

#2351 chore: drop dependency on ic-agent in PocketIC library
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/nonblocking.rs
Labels: chore

#2352 feat: allow specifying multiple bitcoin nodes in PocketIC instance configuration
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat

#2383 chore: Remove obsolete publish target sns-test-feature
  publish/binaries/BUILD.bazel
Labels: chore

#2324 feat(cketh/ckerc20): Deposit with subaccounts
  rs/ethereum/cketh/minter/DepositHelperWithSubaccount.sol
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/eth_logs/mod.rs
  rs/ethereum/cketh/minter/src/eth_logs/parser.rs
  rs/ethereum/cketh/minter/src/eth_logs/scraping.rs
  rs/ethereum/cketh/minter/src/eth_logs/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/guard/tests.rs
  rs/ethereum/cketh/minter/src/lifecycle/init.rs
  rs/ethereum/cketh/minter/src/lifecycle/tests.rs
  rs/ethereum/cketh/minter/src/lifecycle/upgrade.rs
  rs/ethereum/cketh/minter/src/state.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
Labels: feat, @cross-chain-team

#2371 chore: remove unused clippy allows
  rs/crypto/internal/crypto_lib/types/src/sign/threshold_sig/ni_dkg.rs
  rs/crypto/tree_hash/tests/proto.rs
  rs/http_endpoints/public/src/call/ingress_watcher.rs
  rs/p2p/artifact_downloader/src/fetch_artifact/download.rs
  rs/p2p/consensus_manager/src/receiver.rs
  rs/p2p/test_utils/src/consensus.rs
  rs/types/types/src/xnet/proto/tests.rs
  rs/xnet/payload_builder/src/impl_tests.rs
Labels: chore, @networking, @crypto-team, @ic-message-routing-owners, @ic-interface-owners

#2335 chore: Initial guestos vulnerability ignore list
  .github/CODEOWNERS
  ci/src/dependencies/resources/container_scanner_finding_failover_ignore_list_guestos.txt
Labels: chore, @product-security, @ic-owners-owners

#2387 fix(sns): Remove accidentally-included timer type definitions
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
Labels: fix

#2380 fix: typo in `generate_swap_canister_upgrade_proposal_text`
  testnet/tools/nns-tools/lib/proposals.sh
Labels: fix, @nns-team

#2382 chore: Remove legacy file test_sns_init_v1.yaml
  rs/sns/cli/BUILD.bazel
  rs/sns/cli/test_sns_init_v1.yaml
Labels: chore, @nns-team

#2384 fix: Make NNS init .csv parser recognize `dissolve_delay_s` and `maturity_e8s_equivalent` values again
  rs/nns/governance/init/src/lib.rs
  rs/nns/governance/tests/neurons.csv
  rs/nns/integration_tests/src/neurons.csv
Labels: fix, @nns-team

#2222 fix(nns): validate dissolve state and age before saving neuron
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/dissolve_state_and_age.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
Labels: fix, @nns-team

#2364 refactor(ckbtc): refactor the ic-btc-kyt crate
  rs/bitcoin/kyt/BUILD.bazel
  rs/bitcoin/kyt/src/dashboard/tests.rs
  rs/bitcoin/kyt/src/fetch.rs
  rs/bitcoin/kyt/src/fetch/tests.rs
  rs/bitcoin/kyt/src/lib.rs
  rs/bitcoin/kyt/src/main.rs
  rs/bitcoin/kyt/src/state.rs
Labels: refactor, @cross-chain-team

#2372 refactor(cross-chain): rename metrics related to memory
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/ledger-suite-orchestrator/src/main.rs
Labels: refactor, @cross-chain-team

#1920 test(ICRC_ledger): FI-1460: Parity check for ledger+archives vs index in ICRC golden state tests
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint

#2395 fix: EXC-1775: Replace `delete_snapshots` functionality with `remove`
  rs/execution_environment/tests/execution_test.rs
  rs/replicated_state/src/canister_snapshots.rs
Labels: fix, @execution, @ic-message-routing-owners

#2402 chore(IDX): move bazel-test-coverage to pr workflow
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
Labels: chore, @idx

#2405 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#2397 chore: increase read state retry delay in spec compliance tests
  hs/spec_compliance/src/IC/Test/Agent.hs
Labels: chore, @research

#2357 chore: refactor canister http in PocketIC
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_machine_tests/tests/multi_subnet.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#2407 refactor(IDX): move node-name to step summary
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
Labels: refactor, @idx

#2411 chore: hide canister http internals not used by PocketIC anymore
  rs/https_outcalls/adapter/src/lib.rs
  rs/https_outcalls/client/src/lib.rs
Labels: chore

#1803 feat(crypto): CRP-2589 Add support for Taproot input to Schnorr signatures
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/signer.rs
  rs/crypto/benches/tschnorr.rs
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/src/lib.rs
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/src/signing/bip340.rs
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/test_utils/BUILD.bazel
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/test_utils/Cargo.toml
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/test_utils/src/lib.rs
  rs/crypto/internal/crypto_lib/threshold_sig/canister_threshold_sig/tests/protocol.rs
  rs/crypto/internal/crypto_service_provider/src/types/external_conversion_utilities/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/api.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tschnorr/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tschnorr/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_client.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
  rs/crypto/src/sign/canister_threshold_sig/schnorr.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/crypto/test_utils/local_csp_vault/src/lib.rs
  rs/crypto/tests/canister_threshold_idkg.rs
  rs/crypto/tests/canister_threshold_schnorr_verify_combined_sig.rs
  rs/crypto/tests/canister_threshold_schnorr_verify_sig_share.rs
  rs/types/types/src/consensus/idkg/schnorr.rs
  rs/types/types/src/crypto/canister_threshold_sig.rs
  rs/types/types/src/crypto/canister_threshold_sig/error.rs
  rs/types/types/src/crypto/canister_threshold_sig/tests.rs
Labels: feat

#2410 chore(api-boundary-node): close port 80 on the API BNs
  ic-os/components/ic/ic.json5.template
  rs/orchestrator/testdata/nftables_boundary_node.conf.golden
Labels: chore, @consensus, @node

#2394 chore(nns): remove governance api--test-feature bazel target
  rs/nns/governance/api/BUILD.bazel
Labels: chore, @nns-team

#2418 fix(crypto): Fix a flaky test introduced by PR 1803
  rs/crypto/tests/canister_threshold_schnorr_verify_combined_sig.rs
Labels: fix

#2396 fix: typo in generate_swap_canister_upgrade_proposal_text (attempt 2)
  testnet/tools/nns-tools/lib/proposals.sh
Labels: fix, @nns-team

#2409 chore: increase CPUs for pocket-ic slow test
  packages/pocket-ic/BUILD.bazel
Labels: chore

#2420 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#2422 chore(k8s-system-tests): overcommit memory
  rs/tests/driver/src/k8s/tnet.rs
  rs/tests/driver/src/k8s/virtualmachine.rs
Labels: chore, @idx

#2423 chore: Bump mainnet canister versions
  mainnet-canisters.json
Labels: chore, @idx, @nns-team

#2321 feat(sns): Populate upgrade journal
  rs/nervous_system/integration_tests/tests/advance_target_version.rs
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/types.rs
Labels: feat, @nns-team

#2427 test(sns): Re-enable SNS qualification tests after the next SNS-W release
  rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
Labels: test, @nns-team

#2374 feat(boundary): add rate-limit canister post_upgrade
  rs/boundary_node/rate_limits/canister/add_config.rs
  rs/boundary_node/rate_limits/canister/canister.rs
  rs/boundary_node/rate_limits/canister/state.rs
Labels: feat, @boundary-node

#2430 chore(nns): Cleanup internal types that should not be in API
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/pb/conversions.rs
Labels: chore, @nns-team

#2360 chore(boundary): Add pocket-ic integration tests for rate-limit canister
  Cargo.lock
  rs/boundary_node/rate_limits/Cargo.toml
  rs/boundary_node/rate_limits/api/src/lib.rs
  rs/boundary_node/rate_limits/integration_tests/BUILD.bazel
  rs/boundary_node/rate_limits/integration_tests/Cargo.toml
  rs/boundary_node/rate_limits/integration_tests/src/lib.rs
  rs/boundary_node/rate_limits/integration_tests/src/pocket_ic_helpers.rs
  rs/boundary_node/rate_limits/integration_tests/tests/rate_limit_canister_tests.rs
Labels: chore, @boundary-node

#2369 feat(cketh/ckerc20): mint to subaccounts
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/dashboard.rs
  rs/ethereum/cketh/minter/src/dashboard/tests.rs
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/endpoints.rs
  rs/ethereum/cketh/minter/src/eth_logs/mod.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/state/audit.rs
  rs/ethereum/cketh/minter/src/state/audit/tests.rs
  rs/ethereum/cketh/minter/src/state/event.rs
  rs/ethereum/cketh/minter/templates/dashboard.html
  rs/ethereum/cketh/minter/tests/ckerc20.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/ethereum/cketh/minter/tests/subaccount.rs
  rs/ethereum/cketh/test_utils/src/ckerc20.rs
  rs/ethereum/cketh/test_utils/src/events.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/ethereum/cketh/test_utils/src/response.rs
Labels: feat, @cross-chain-team, CI_OVERRIDE_DIDC_CHECK

#2419 fix: Resolve TODO to avoid String allocation
  rs/boundary_node/ic_boundary/src/http.rs
Labels: fix

#2437 test(ICP_ledger): FI-1568: Assume yes for apt install in ICP ledger suite qualification script
  rs/rosetta-api/scripts/run_upgrade_test.sh
Labels: test, @finint

#2366 chore(ICP-Rosetta): add spawn neuron functionality
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/Cargo.toml
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_neuron_spawn_test.rs
  rs/tests/src/rosetta_tests/tests.rs
  rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
Labels: chore

#2342 chore(ICP_ledger): Update upgrade history of ICP ledger suite
  rs/ledger_suite/icp/UPGRADES.md
Labels: chore, @finint

#2413 test(ICRC_ledger): FI-1460: Track InMemoryLedger number of transactions
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#2438 chore: update error message when launcher process received signal
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
Labels: chore

#2436 feat(PocketIC): configurable server log levels and optimized tests
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/slow.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/main.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat, @pocket-ic

#2365 chore(ICp-Rosetta): FI-1560: icp rosetta client function for stake maturity
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/Cargo.toml
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_neuron_maturity_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_spawn_test.rs
  rs/tests/src/rosetta_tests/tests.rs
  rs/tests/src/rosetta_tests/tests/neuron_maturity.rs
  rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
Labels: chore

#2363 chore(ICP-Rosetta): FI-1559: icp rosetta client add and remove hotkey
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/Cargo.toml
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_neuron_hotkey_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_maturity_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_spawn_test.rs
  rs/tests/src/rosetta_tests/tests.rs
  rs/tests/src/rosetta_tests/tests/neuron_hotkey.rs
  rs/tests/src/rosetta_tests/tests/neuron_maturity.rs
  rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
Labels: chore

#2293 chore(ICP-Rosetta): FI-1557: get neuron info function
  Cargo.lock
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/src/ledger_client.rs
  rs/rosetta-api/icp/src/ledger_client/neuron_response.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/Cargo.toml
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_neuron_hotkey_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_info_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_maturity_test.rs
  rs/tests/financial_integrations/rosetta/rosetta_neuron_spawn_test.rs
  rs/tests/src/rosetta_tests/tests.rs
  rs/tests/src/rosetta_tests/tests/neuron_hotkey.rs
  rs/tests/src/rosetta_tests/tests/neuron_info.rs
  rs/tests/src/rosetta_tests/tests/neuron_maturity.rs
  rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
Labels: chore, @finint

#2205 chore: upgrade wasmtime to 26
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/tests/instrumentation.rs
  rs/embedders/tests/validation.rs
Labels: chore, @execution

#2300 feat(sns): SNS Governance upgrades its Swap
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/sns/governance/src/governance.rs
Labels: feat, @nns-team

#2447 chore: EXC: Reduce stable grow test cases to 10
  rs/embedders/tests/stable_grow.rs
Labels: chore, @execution

#2421 feat(proposal_cli): FI-1567: Add arguments hash to summary
  rs/cross-chain/proposal-cli/templates/install.md
  rs/cross-chain/proposal-cli/templates/upgrade.md
Labels: feat, @cross-chain-team

#2339 feat(nns): Make distinction between potential and deciding voting power.
  Cargo.lock
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/metrics/tests.rs
  rs/nns/governance/tests/governance.rs
Labels: feat, @nns-team

#2417 feat: Add an `mr_receive_batch_latency_seconds` metric
  rs/messaging/src/message_routing.rs
Labels: feat, @ic-message-routing-owners

#2347 feat(crypto): CRP-2597 make NiDkgTag and NiDkgId non-Copy
  rs/consensus/src/consensus/dkg_key_manager.rs
  rs/consensus/src/consensus/share_aggregator.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/dkg/payload_builder.rs
  rs/consensus/src/dkg/payload_validator.rs
  rs/consensus/src/dkg/utils.rs
  rs/consensus/utils/src/crypto.rs
  rs/consensus/utils/src/lib.rs
  rs/crypto/benches/ni_dkg.rs
  rs/crypto/benches/threshold_sig.rs
  rs/crypto/internal/crypto_service_provider/src/api/threshold.rs
  rs/crypto/internal/crypto_service_provider/src/threshold/ni_dkg/mod.rs
  rs/crypto/internal/crypto_service_provider/src/threshold/ni_dkg/tests/fixtures.rs
  rs/crypto/internal/crypto_service_provider/src/threshold/ni_dkg/tests/test_create_dealing.rs
  rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg/fixtures.rs
  rs/crypto/src/sign/mod.rs
  rs/crypto/src/sign/threshold_sig.rs
  rs/crypto/src/sign/threshold_sig/ni_dkg/dealing.rs
  rs/crypto/src/sign/threshold_sig/ni_dkg/dealing/tests.rs
  rs/crypto/src/sign/threshold_sig/ni_dkg/transcript.rs
  rs/crypto/src/sign/threshold_sig/ni_dkg/transcript/tests.rs
  rs/crypto/src/sign/threshold_sig/store.rs
  rs/crypto/src/sign/threshold_sig/store/tests.rs
  rs/crypto/src/sign/threshold_sig/tests.rs
  rs/crypto/temp_crypto/src/lib.rs
  rs/crypto/test_utils/csp/src/lib.rs
  rs/crypto/test_utils/ni-dkg/src/initial_config/tests.rs
  rs/crypto/test_utils/ni-dkg/src/lib.rs
  rs/crypto/tests/threshold_sigs_with_ni_dkg.rs
  rs/interfaces/src/crypto/sign/threshold_sig.rs
  rs/orchestrator/src/upgrade.rs
  rs/test_utilities/artifact_pool/src/consensus_pool.rs
  rs/test_utilities/consensus/src/lib.rs
  rs/test_utilities/src/crypto.rs
  rs/types/types/src/consensus.rs
  rs/types/types/src/consensus/catchup.rs
  rs/types/types/src/consensus/dkg.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg/config.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg/config/tests.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg/id.rs
  rs/types/types/src/exhaustive.rs
Labels: feat, @consensus, @crypto-team

#2443 chore(IDX): increase timeout for python-requirements_test
  BUILD.bazel
Labels: chore, @idx

#2288 chore(ckbtc): Propose to reduce retrieve_btc_min_amount to 0.0005 btc
  rs/bitcoin/ckbtc/mainnet/minter_upgrade_2024_10_28.md
Labels: chore, @cross-chain-team

#2416 chore: Add wasm_memory_threshold field to DefiniteCanisterSettings
  packages/pocket-ic/src/management_canister.rs
  rs/execution_environment/src/canister_manager.rs
  rs/nervous_system/clients/src/canister_status.rs
  rs/replica_tests/tests/canister_lifecycle.rs
  rs/sns/integration_tests/src/manage_dapp_canister_settings.rs
  rs/types/management_canister_types/src/lib.rs
Labels: chore, @execution, @pocket-ic, @nns-team

#2457 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @dre, @consensus

#1835 feat: [MR-617] Enforce subnet-wide best-effort message memory limit
  rs/config/src/execution_environment.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/state_machine.rs
  rs/messaging/src/state_machine/tests.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: feat, @execution, @ic-message-routing-owners

#2414 chore: Drop a couple of unnecessary `take_canisters()` calls
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/scheduler.rs
Labels: chore, @execution

#2456 fix: test flakiness due to auto progress logs
  rs/pocket_ic_server/tests/test.rs
Labels: fix

#2408 fix: use into_data_stream instead of the custom complicated wrapper
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/async_utils/BUILD.bazel
  rs/async_utils/Cargo.toml
  rs/async_utils/src/axum.rs
  rs/async_utils/src/lib.rs
  rs/boundary_node/systemd_journal_gatewayd_shim/BUILD.bazel
  rs/boundary_node/systemd_journal_gatewayd_shim/Cargo.toml
  rs/boundary_node/systemd_journal_gatewayd_shim/src/api.rs
  rs/tests/src/nns_tests/registry_authentication_test.rs
Labels: fix, @idx, @boundary-node, @networking, @nns-team

#2461 fix(IDX): always run //pre-commit:buf-breaking on .proto changes
  ci/bazel-scripts/diff.sh
Labels: fix, @idx

#2459 chore(IDX): pinning some jobs to ch1
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#2463 chore: dedupe threshold signature tests
  rs/execution_environment/src/execution_environment/tests.rs
Labels: chore, @execution

#2464 feat(proposal-cli): Add support for the cycles-ledger and exchange-rate-canister
  rs/cross-chain/proposal-cli/src/candid/tests.rs
  rs/cross-chain/proposal-cli/src/canister/mod.rs
Labels: feat, @cross-chain-team

#2466 chore: polish the sender side of the consensus_manager (mainly remove legacy terms)
  rs/p2p/consensus_manager/src/lib.rs
  rs/p2p/consensus_manager/src/sender.rs
Labels: chore, @networking

#2337 chore(CRP-2617): Generalize CUP’s ChainKeyInitialization
  rs/consensus/src/idkg/utils.rs
  rs/protobuf/def/registry/subnet/v1/subnet.proto
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
  rs/registry/canister/src/mutations/subnet.rs
Labels: chore, @consensus, @nns-team, @ic-interface-owners

#2465 feat: Bump the state size limit to 1 TiB and stable memory limit to 500 GiB
  rs/config/src/execution_environment.rs
  rs/embedders/tests/snapshots/instrumentation__app.snap
  rs/embedders/tests/snapshots/instrumentation__app2.snap
  rs/embedders/tests/snapshots/instrumentation__basic.snap
  rs/embedders/tests/snapshots/instrumentation__basic_import.snap
  rs/embedders/tests/snapshots/instrumentation__basic_import_call.snap
  rs/embedders/tests/snapshots/instrumentation__control_flow.snap
  rs/embedders/tests/snapshots/instrumentation__element.snap
  rs/embedders/tests/snapshots/instrumentation__export_mutable_globals.snap
  rs/embedders/tests/snapshots/instrumentation__fac.snap
  rs/embedders/tests/snapshots/instrumentation__fizzbuzz.snap
  rs/embedders/tests/snapshots/instrumentation__memory_fill.snap
  rs/embedders/tests/snapshots/instrumentation__memory_grow.snap
  rs/embedders/tests/snapshots/instrumentation__nested_ifs.snap
  rs/embedders/tests/snapshots/instrumentation__recursive.snap
  rs/embedders/tests/snapshots/instrumentation__simple_loop.snap
  rs/embedders/tests/snapshots/instrumentation__start.snap
  rs/embedders/tests/snapshots/instrumentation__zero_cost_ops.snap
  rs/rust_canisters/canister_creator/test/test.rs
  rs/types/types/src/lib.rs
Labels: feat, @execution, @ic-interface-owners

#2450 feat(consensus): CON-675 Increase notary delay caused by certified-finalized gap
  rs/consensus/src/consensus/notary.rs
  rs/consensus/tests/payload.rs
Labels: feat, @consensus

#2381 chore: EXC-1754: Apply priority credit at the end of the round
  rs/execution_environment/src/scheduler/round_schedule.rs
Labels: chore, @execution

#2460 feat(proposal_cli): FI-1571: Do not write the args.hex file from proposal-cli
  rs/cross-chain/proposal-cli/src/candid/mod.rs
  rs/cross-chain/proposal-cli/src/candid/tests.rs
  rs/cross-chain/proposal-cli/src/main.rs
  rs/cross-chain/proposal-cli/src/proposal/mod.rs
Labels: feat, @cross-chain-team

#2454 chore: [MR-620] Log extra states to keep and add error counter for fallback
  rs/state_manager/src/lib.rs
Labels: chore, @ic-message-routing-owners

#2453 refactor(sns): err_if_another_upgrade_is_in_progress refactor
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/proposal.rs
Labels: refactor, @nns-team

#2375 feat(nns): Added total_potential_voting_power to proposals.
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/tests/governance.rs
Labels: feat, @nns-team

#2474 chore(nns): add feature flag for stable following index
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/test_utils.rs
Labels: chore, @nns-team

#2476 test(sns): migrate SNS integration test to StateMachine
  rs/rust_canisters/canister_test/src/canister.rs
  rs/sns/integration_tests/src/proposals.rs
  rs/sns/test_utils/src/itest_helpers.rs
Labels: test

#2449 feat(cketh/ckerc20): consolidate log scrapings
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/dashboard.rs
  rs/ethereum/cketh/minter/src/dashboard/tests.rs
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/endpoints.rs
  rs/ethereum/cketh/minter/src/eth_logs/scraping.rs
  rs/ethereum/cketh/minter/src/eth_logs/tests.rs
  rs/ethereum/cketh/minter/src/lifecycle/init.rs
  rs/ethereum/cketh/minter/src/lifecycle/tests.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/state.rs
  rs/ethereum/cketh/minter/src/state/audit.rs
  rs/ethereum/cketh/minter/src/state/eth_logs_scraping/mod.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/templates/dashboard.html
  rs/ethereum/cketh/minter/tests/ckerc20.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
Labels: feat, @cross-chain-team

#2455 chore: do not use time of next round in tests
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
  rs/execution_environment/tests/canister_logging.rs
  rs/execution_environment/tests/dts.rs
  rs/ledger_suite/icp/index/tests/tests.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/state_machine_tests/src/lib.rs
Labels: chore, @execution, @pocket-ic, @ic-message-routing-owners, @cross-chain-team, @finint

#1445 chore: RUN-988: Adapt System API benchmarks to Wasm64
  rs/execution_environment/benches/lib/src/wat.rs
  rs/execution_environment/benches/system_api/WASM32-vs-WASM64.md
  rs/execution_environment/benches/system_api/execute_inspect_message.rs
  rs/execution_environment/benches/system_api/execute_query.rs
  rs/execution_environment/benches/system_api/execute_update.rs
Labels: chore, @execution

#2389 chore: add idleness bitcoin adapter integration tests
  rs/bitcoin/adapter/tests/adapter_test.rs
Labels: chore, @networking

#2331 test(IDX): optimise the spec_compliance tests by using the GHC threaded RTS
  hs/spec_compliance/BUILD.bazel
  hs/spec_compliance/bin/ic-ref-test.hs
  rs/tests/research/BUILD.bazel
  rs/tests/research/spec_compliance/spec_compliance.rs
Labels: test, @idx, @research

#2482 chore(IDX): optimise the setup of the spec_compliance systests
  rs/tests/driver/src/util.rs
  rs/tests/research/spec_compliance/spec_compliance.rs
Labels: chore, @idx, @research

#2484 chore(IDX): lower parallelism of ic-ref-test in //rs/pocket_ic_server:spec_test
  rs/pocket_ic_server/tests/spec_test.rs
Labels: chore, @pocket-ic

#2448 chore(sns): Remove completed data migration from Swap
  rs/sns/integration_tests/src/golden_state_swap_upgrade_twice.rs
  rs/sns/swap/canister/canister.rs
  rs/sns/swap/src/swap.rs
Labels: chore, @nns-team

#2477 chore: Update Base Image Refs [2024-11-07-0808]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#2485 fix(IDX): remove unused icmplib py dep
  ic-os/dev-tools/bare_metal_deployment/tools.bzl
  requirements.in
  requirements.txt
Labels: fix, @node, @ic-owners-owners

#2424 feat(BOUN-1236): add initial canister interface
  Cargo.lock
  Cargo.toml
  rs/boundary_node/anonymization/backend/Cargo.toml
  rs/boundary_node/anonymization/backend/interface.did
  rs/boundary_node/anonymization/backend/src/lib.rs
  rs/boundary_node/anonymization/client/Cargo.toml
  rs/boundary_node/anonymization/client/src/lib.rs
  rs/boundary_node/anonymization/interface/Cargo.toml
  rs/boundary_node/anonymization/interface/src/lib.rs
Labels: feat, @boundary-node

#2403 feat(EXC-1727): Enable Canister Backtraces
  rs/config/src/embedders.rs
  rs/embedders/tests/wasmtime_embedder.rs
  rs/execution_environment/src/execution/response/tests.rs
  rs/execution_environment/tests/canister_logging.rs
  rs/nns/sns-wasm/tests/deploy_new_sns.rs
Labels: feat, @execution, @nns-team

#1649 feat(fuzzing): Add a new fuzzer to fuzz system API calls via StateMachine tests
  Cargo.Bazel.Fuzzing.json.lock
  bazel/fuzz_testing.bzl
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/embedders/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
Labels: feat, @idx, @product-security, @execution

#2054 chore(idkg): Replace pseudo-random and pre-signature IDs in `RequestId` with single `CallbackId`
  rs/consensus/src/consensus/catchup_package_maker.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/idkg.rs
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/payload_builder/pre_signatures.rs
  rs/consensus/src/idkg/payload_builder/signatures.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/stats.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/protobuf/def/types/v1/idkg.proto
  rs/protobuf/src/gen/types/types.v1.rs
  rs/types/types/src/consensus/idkg.rs
  rs/types/types/src/consensus/idkg/common.rs
Labels: chore, @consensus, @ic-interface-owners

#2469 refactor(sns): Separate UpgradeInProgress and PendingVersion
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/tests/fail_stuck_upgrade_in_progress_tests.rs
Labels: refactor, CI_OVERRIDE_BUF_BREAKING

#2425 feat(BOUN-1236): add registry scraping for acls
  Cargo.lock
  rs/boundary_node/anonymization/backend/Cargo.toml
  rs/boundary_node/anonymization/backend/src/lib.rs
  rs/boundary_node/anonymization/backend/src/registry.rs
Labels: feat

#2426 feat(BOUN-1236): add client code for canister
  rs/boundary_node/anonymization/client/src/lib.rs
Labels: feat

#2475 feat: [NODE-1521] Move bootloader off dockerhub
  .github/workflows/container-mirror-images.json
  ic-os/bootloader/build-bootloader-tree.sh
  ic-os/bootloader/grub.cfg
Labels: feat, @idx, @node

#2428 feat(BOUN-1236): add skeleton service methods and wrap with authorization
  rs/boundary_node/anonymization/backend/src/acl.rs
  rs/boundary_node/anonymization/backend/src/lib.rs
  rs/boundary_node/anonymization/backend/src/queue.rs
Labels: feat

#2431 feat(BOUN-1236): add core logic impl to canister, add leader election cron
  rs/boundary_node/anonymization/backend/src/lib.rs
  rs/boundary_node/anonymization/backend/src/queue.rs
Labels: feat

#2489 feat(sns): Serve SNS upgrade journal over Http
  rs/nervous_system/common/src/lib.rs
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/tests.rs
  rs/sns/governance/protobuf_generator/src/lib.rs
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
Labels: feat, @nns-team, CI_OVERRIDE_BUF_BREAKING

#2432 feat(BOUN-1236): add metrics and logging to canister
  rs/boundary_node/anonymization/backend/src/acl.rs
  rs/boundary_node/anonymization/backend/src/lib.rs
  rs/boundary_node/anonymization/backend/src/queue.rs
  rs/boundary_node/anonymization/backend/src/registry.rs
Labels: feat

#2433 feat(BOUN-1236): implement secret tracking
  Cargo.lock
  rs/boundary_node/anonymization/client/src/lib.rs
Labels: feat

#2462 chore(ICp-Rosetta): migrated list neurons test
  rs/rosetta-api/icp/client/src/lib.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/neuron_management.rs
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_list_neurons_test.rs
  rs/tests/src/rosetta_tests/tests.rs
  rs/tests/src/rosetta_tests/tests/list_neurons.rs
Labels: chore

#2506 fix: revert "feat: [NODE-1521] Move bootloader off dockerhub (#2475)"
  .github/workflows/container-mirror-images.json
  ic-os/bootloader/build-bootloader-tree.sh
  ic-os/bootloader/grub.cfg
Labels: fix, @idx, @node

#2509 fix(ic-boundary): fix error message
  rs/boundary_node/ic_boundary/src/routes.rs
Labels: fix

#2478 chore(IDX): host storage for cargo cache
  .devcontainer/devcontainer.json
  ci/container/container-run.sh
Labels: chore, @idx

#2507 chore: upgrade core crates
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/anonymization/client/Cargo.toml
Labels: chore, @idx

#2434 feat(BOUN-1236): add logging and throttling to canister methods
  rs/boundary_node/anonymization/client/src/lib.rs
Labels: feat

#2515 chore: add more documentation to the quic transport code and make some errors infallible
  rs/p2p/quic_transport/src/connection_handle.rs
  rs/p2p/quic_transport/src/connection_manager.rs
  rs/p2p/quic_transport/src/lib.rs
  rs/p2p/quic_transport/src/request_handler.rs
Labels: chore, @networking

#2391 chore(boundary): use uuid for incident IDs and rule IDs
  Cargo.lock
  rs/boundary_node/rate_limits/BUILD.bazel
  rs/boundary_node/rate_limits/Cargo.toml
  rs/boundary_node/rate_limits/canister/access_control.rs
  rs/boundary_node/rate_limits/canister/add_config.rs
  rs/boundary_node/rate_limits/canister/canister.rs
  rs/boundary_node/rate_limits/canister/disclose.rs
  rs/boundary_node/rate_limits/canister/fetcher.rs
  rs/boundary_node/rate_limits/canister/state.rs
  rs/boundary_node/rate_limits/canister/storage.rs
  rs/boundary_node/rate_limits/canister/types.rs
  rs/boundary_node/rate_limits/canister_client/src/main.rs
  rs/tests/boundary_nodes/rate_limit_canister_test.rs
Labels: chore, @idx, @boundary-node

#2480 test(ICRC_ledger): FI-1524: Return an error for threshold signing requests in case key is missing
  rs/state_machine_tests/src/lib.rs
Labels: test, @pocket-ic, @ic-message-routing-owners

#2488 fix(NODE-1522): fix permissions for nftables and systemd-journald
  ic-os/components/selinux/ic-node/ic-node.te
  ic-os/components/selinux/misc-fixes/misc-fixes.te
Labels: fix

#2473 feat(nns): Support all neurons in stable memory behind feature flag
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/governance/tla/mod.rs
  rs/nns/governance/src/neuron/dissolve_state_and_age.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/storage/neurons.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/nns/governance/tests/merge_neurons.rs
Labels: feat, @nns-team

#2526 fix(nns): Fix ballot generation inefficiency (for stable neurons)
  rs/nns/governance/src/neuron_store.rs
Labels: fix, @nns-team

#2513 chore(fuzzing): enable canister sandboxing for fuzzers
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/execution_environment/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
  rs/execution_environment/fuzz/src/lib.rs
Labels: chore, @execution

#2521 fix(release-scripts): Remove deprecated `--use-explicit-action-type` from ic-admin command in submit-mainnet-nns-upgrade-proposal.sh
  testnet/tools/nns-tools/submit-mainnet-nns-upgrade-proposal.sh
Labels: fix, @nns-team

#2451 feat(BOUN-1233): rework ic-boundary CLI, bump ic-gateway
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  ic-os/boundary-guestos/context/Dockerfile
  ic-os/components/boundary-guestos/etc/systemd/system/ic-boundary.service
  ic-os/components/boundary-guestos/opt/ic/bin/setup-ic-boundary.sh
  ic-os/components/boundary-guestos/opt/ic/bin/setup-ic-gateway.sh
  publish/canisters/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_issuer/Cargo.toml
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/benches/perf.rs
  rs/boundary_node/ic_boundary/src/bouncer.rs
  rs/boundary_node/ic_boundary/src/bouncer/firewall.rs
  rs/boundary_node/ic_boundary/src/cache.rs
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/dns.rs
  rs/boundary_node/ic_boundary/src/log.rs
  rs/boundary_node/ic_boundary/src/metrics/test.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/orchestrator/src/boundary_node.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @consensus, @execution, @boundary-node, @node

#2406 refactor(crypto): CRP-2597 move MasterPublicKeyId protobuf from registry/crypto to types
  rs/crypto/temp_crypto/src/lib.rs
  rs/protobuf/def/registry/crypto/v1/crypto.proto
  rs/protobuf/def/registry/subnet/v1/subnet.proto
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/def/types/v1/idkg.proto
  rs/protobuf/def/types/v1/types.proto
  rs/protobuf/generator/src/lib.rs
  rs/protobuf/src/gen/crypto/registry.crypto.v1.rs
  rs/protobuf/src/gen/crypto/types.v1.rs
  rs/protobuf/src/gen/messaging/types.v1.rs
  rs/protobuf/src/gen/registry/registry.crypto.v1.rs
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/registry/types.v1.rs
  rs/protobuf/src/gen/state/registry.crypto.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/protobuf/src/gen/state/types.v1.rs
  rs/protobuf/src/gen/types/registry.crypto.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/types.v1.rs
  rs/protobuf/src/registry/subnet.rs
  rs/registry/canister/src/invariants/crypto.rs
  rs/registry/canister/src/invariants/crypto/tests.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/registry/subnet_features/src/lib.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/consensus/idkg.rs
Labels: refactor, @consensus, @execution, @nns-team, @crypto-team, @ic-message-routing-owners, @ic-interface-owners, CI_OVERRIDE_BUF_BREAKING

#2534 fix(IDX): mkdir && chown
  ci/container/container-run.sh
Labels: fix, @idx

#2532 chore: update bitcoin dashboards for farm testnets to match prod
  rs/tests/dashboards/IC/bitcoin.json
Labels: chore, @idx, @execution

#2536 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#2487 refactor(cketh/ckerc20): use consistently `LedgerSubaccount`
  rs/ethereum/cketh/minter/src/dashboard/tests.rs
  rs/ethereum/cketh/minter/src/eth_logs/mod.rs
  rs/ethereum/cketh/minter/src/eth_logs/tests.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/memo/tests.rs
  rs/ethereum/cketh/minter/src/state/audit/tests.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/src/state/transactions/mod.rs
  rs/ethereum/cketh/minter/src/state/transactions/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/withdraw.rs
  rs/ethereum/cketh/minter/test_resources/mainnet_events.gz
  rs/ethereum/cketh/minter/test_resources/sepolia_events.gz
Labels: refactor, @cross-chain-team

#2543 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#2202 feat: [UTP-242] Make subnet replica version available to canisters via management API
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/dts.rs
  rs/system_api/src/routing.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: feat, @idx, @execution, @ic-interface-owners

#2505 refactor: Do not clone in `ReplicatedState::get_ingress_status()`
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/tests/history.rs
  rs/messaging/src/scheduling/valid_set_rule.rs
  rs/messaging/src/scheduling/valid_set_rule/test.rs
  rs/replicated_state/src/replicated_state.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: refactor

#1137 feat: [MR-586] Lazy pagemaps
  rs/memory_tracker/src/tests.rs
  rs/replicated_state/src/page_map.rs
  rs/replicated_state/src/page_map/storage.rs
  rs/replicated_state/src/page_map/storage/tests.rs
  rs/replicated_state/src/page_map/test_utils.rs
  rs/replicated_state/src/page_map/tests.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/split.rs
  rs/state_manager/src/split/tests.rs
  rs/state_manager/src/state_sync.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/tests/state_manager.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @idx, @execution, @ic-message-routing-owners

#2512 chore: add tests for management canister types in PocketIC
  Cargo.lock
  MODULE.bazel
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/management_canister.rs
  packages/pocket-ic/tests/management_canister.rs
  rs/types/management_canister_types/fuzz/candid_seed_corpus_generation/BUILD.bazel
Labels: chore, @idx, @execution, @pocket-ic

#2538 chore: Remove old TODOs in the payload builder
  rs/xnet/payload_builder/src/certified_slice_pool.rs
  rs/xnet/payload_builder/src/lib.rs
Labels: chore, @ic-message-routing-owners

#2551 feat: add insert rate charts to bitcoin dashboards on testnets
  rs/tests/dashboards/IC/bitcoin.json
Labels: feat, @idx, @execution

#2077 fix(icos): Several testing and performance improvements to SetupOS
  Cargo.lock
  Cargo.toml
  ic-os/components/setupos-scripts/BUILD.bazel
  ic-os/components/setupos-scripts/check-hardware.sh
  ic-os/components/setupos-scripts/check-network.sh
  ic-os/components/setupos-scripts/check-setupos-age.sh
  ic-os/components/setupos-scripts/functions.sh
  ic-os/components/setupos-scripts/install-guestos.sh
  ic-os/components/setupos-scripts/install-hostos.sh
  ic-os/components/setupos-scripts/setupos.sh
  ic-os/components/setupos.bzl
  ic-os/defs.bzl
  ic-os/setupos/README.adoc
  ic-os/setupos/context/packages.common
  ic-os/setupos/envs/dev/BUILD.bazel
  rs/ic_os/build_tools/inject_files/src/main.rs
  rs/ic_os/build_tools/partition_tools/BUILD.bazel
  rs/ic_os/build_tools/partition_tools/Cargo.toml
  rs/ic_os/build_tools/partition_tools/src/exes.rs
  rs/ic_os/build_tools/partition_tools/src/ext.rs
  rs/ic_os/build_tools/partition_tools/src/fat.rs
  rs/ic_os/build_tools/partition_tools/src/lib.rs
  rs/ic_os/build_tools/partition_tools/src/partition.rs
  rs/ic_os/dev_test_tools/setupos-disable-checks/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-disable-checks/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-disable-checks/src/main.rs
  rs/ic_os/linux_kernel_command_line/BUILD.bazel
  rs/ic_os/linux_kernel_command_line/Cargo.toml
  rs/ic_os/linux_kernel_command_line/src/lib.rs
  toolchains/sysimage/build_disk_image.py
  toolchains/sysimage/toolchain.bzl
Labels: documentation, enhancement, rust, fix, @idx, @dre, @nns-team, @node, @ic-interface-owners

#2535 feat: PocketIC library functions to manage canister snapshots
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
Labels: feat

#2546 feat: PocketIC library functions to manage WASM chunk store and install chunked code
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
Labels: feat, @pocket-ic

#2533 feat: add PocketIC library function to fetch canister logs
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/tests.rs
Labels: feat, @boundary-node, @nns-team, @finint

#2435 fix(ckbtc): Fix a problem with retrieve_btc_min_amount setting
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
Labels: fix, @cross-chain-team

#2560 test(ckbtc): Add the missing system test ckbtc_minter_batching to Bazel
  rs/tests/ckbtc/BUILD.bazel
Labels: test

#2561 feat: add function Topology::get_subnet to PocketIC library
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat

#2541 feat(fuzzing): Introduce `--config=sandbox_fuzzing` bazel flag
  bazel/conf/.bazelrc.build
  rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
Labels: feat

#2550 chore(fuzzing): Remove universal canister dependency for fuzzers
  rs/embedders/fuzz/BUILD.bazel
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/fuzz/src/lib.rs
  rs/embedders/fuzz/src/ws2wasm.rs
Labels: chore, @execution

#2552 chore: improve error tracking in transport
  rs/p2p/quic_transport/src/connection_handle.rs
  rs/p2p/quic_transport/src/metrics.rs
Labels: chore, @idx, @networking

#1886 chore(PocketIC): better error handling and tests when setting time in PocketIC
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: chore, @pocket-ic, @nns-team

#2496 feat(cketh): support subaccounts for ckETH withdrawals
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/endpoints.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/ethereum/cketh/minter/tests/subaccount.rs
  rs/ethereum/cketh/test_utils/src/lib.rs
Labels: feat

#2570 feat(nns): Changed the default "voting power refreshed" timestamp to Sep 1.
  rs/nns/governance/src/lib.rs
Labels: feat, @nns-team

#2542 fix: update small_high_perf testnet to support deploying bitcoin canisters
  rs/prep/src/internet_computer.rs
  rs/tests/boundary_nodes/performance_test_common/src/lib.rs
  rs/tests/boundary_nodes/utils/src/setup.rs
  rs/tests/driver/src/driver/prometheus_vm.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/networking/subnet_update_workload/src/lib.rs
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/testnets/Cargo.toml
  rs/tests/testing_verification/testnets/medium.rs
  rs/tests/testing_verification/testnets/small.rs
  rs/tests/testing_verification/testnets/small_high_perf.rs
  rs/tests/testing_verification/testnets/small_with_api_bn.rs
  rs/tests/testing_verification/testnets/small_with_query_stats.rs
Labels: fix, @idx, @dre, @consensus, @execution, @boundary-node, @networking, @nns-team, @ic-message-routing-owners, @utopia, @cross-chain-team

#2556 fix: gracefully handle error conditions in PocketIC server
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/state_machine_tests/src/lib.rs
Labels: fix, @pocket-ic, @ic-message-routing-owners

#2516 fix: Depend on .git/index in commit_timestamp_txt
  BUILD.bazel
  ic-os/components/BUILD.bazel
Labels: fix, @idx, @node
