Repository dfinity/ic, pull requests merged in 2024-08, with the labels that each got.

#688 chore(neurons_fund): Populate hotkeys when necessary in the NNS Governance → Swap → SNS Governance dataflow
  Cargo.lock
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neurons_fund.rs
  rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
  rs/nns/governance/src/neurons_fund/neurons_fund_participation_constraints_tests.rs
  rs/nns/governance/src/neurons_fund/neurons_fund_participation_tests.rs
  rs/nns/governance/src/neurons_fund/polynomial_neurons_fund_participation_tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/sns/governance/src/governance.rs
  rs/sns/swap/BUILD.bazel
  rs/sns/swap/Cargo.toml
  rs/sns/swap/src/swap.rs
  rs/sns/swap/tests/swap.rs
Labels: chore, @nns-team

#712 chore: Update Base Image Refs [2024-08-01-0150]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#703 chore(NODE-1399): Update test driver to use zst images
  Cargo.lock
  rs/ic_os/launch-single-vm/src/main.rs
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/boundary_node.rs
  rs/tests/driver/src/driver/nested.rs
  rs/tests/driver/src/driver/resource.rs
Labels: chore, @idx, @node

#715 test(test-driver): [NET-1738] Increase `max_concurrent_requests` in system test agent to 10_000
  rs/tests/driver/src/util.rs
Labels: test

#710 feat(nns): Enable new topics to be followed
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
Labels: feat

#699 fix(nns): Fixed a bug where known neuron is not seen as public.
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/metrics/tests.rs
  rs/nns/governance/tests/governance.rs
Labels: fix, @nns-team

#722 fix(dependency-mgmt): fix `ic` root path in tests
  gitlab-ci/src/dependencies/model/ic.py
  gitlab-ci/src/dependencies/scanner/dependency_scanner_test.py
Labels: fix, @product-security

#678 test: Rename COW safety test
  rs/tests/BUILD.bazel
  rs/tests/Cargo.toml
  rs/tests/consensus/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/memory_safety_test.rs
  rs/tests/src/consensus/cow_safety.wasm
  rs/tests/src/consensus/mod.rs
  rs/tests/src/cow_safety.wasm
  rs/tests/src/lib.rs
  rs/tests/src/memory_safety.wasm
  rs/tests/src/message_routing/memory_safety_test.rs
  rs/tests/src/message_routing/mod.rs
  rs/tests/test_canisters/memory_safety/dfx.json
  rs/tests/test_canisters/memory_safety/src/memory_safety/main.mo
Labels: test, @idx

#716 chore(http-handler): Add a 1 second timeout when creating a subscriber in call-v3 handler
  rs/http_endpoints/public/src/call/call_v3.rs
Labels: chore

#717 chore(http-handler): Only log every 10 second in the call-v3 handler
  rs/http_endpoints/public/src/call/call_v3.rs
Labels: chore, @networking

#675 chore(IDX): specify which NNS canisters to use via env vars
  rs/ethereum/cketh/mainnet/README.md
  rs/rust_canisters/canister_test/src/canister.rs
  rs/tests/BUILD.bazel
  rs/tests/Cargo.toml
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/consensus_performance.rs
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/tecdsa/tecdsa_performance_test.rs
  rs/tests/consensus/utils/src/rw_message.rs
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/sns_client.rs
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/ckbtc/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/gix/BUILD.bazel
  rs/tests/gix/nns_dapp_test.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/nested/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/canister_http/canister_http.rs
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/nns/sns/BUILD.bazel
  rs/tests/node/BUILD.bazel
  rs/tests/sdk/BUILD.bazel
  rs/tests/sdk/dfx_smoke_test.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
  rs/tests/src/ledger_tests/transaction_ledger_correctness.rs
  rs/tests/src/nns_tests/registry_authentication_test.rs
  rs/tests/src/nns_tests/sns_aggregator.rs
  rs/tests/src/nns_tests/sns_deployment.rs
  rs/tests/src/rosetta_test.rs
  rs/tests/src/rosetta_tests/setup.rs
  rs/tests/system_tests.bzl
  rs/tests/testing_verification/BUILD.bazel
  rs/tests/testing_verification/colocate_test.rs
  rs/tests/testing_verification/spec_compliance/spec_compliance.rs
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/testnets/from_config.rs
  rs/tests/testing_verification/testnets/large.rs
  rs/tests/testing_verification/testnets/medium.rs
  rs/tests/testing_verification/testnets/single_app_large_node_with_nns.rs
  rs/tests/testing_verification/testnets/small.rs
  rs/tests/testing_verification/testnets/small_nns.rs
  rs/tests/testing_verification/testnets/small_with_query_stats.rs
  rs/tests/testing_verification/testnets/sns_testing.rs
  rs/tests/testing_verification/testnets/src_testing.rs
Labels: chore, @idx, @consensus, @boundary-node, @networking, @nns-team, @ic-message-routing-owners, @node, @cross-chain-team, @finint, @sdk

#707 chore(NODE-1401): Update repro-check.sh SetupOS zst references
  gitlab-ci/tools/repro-check.sh
Labels: chore, @idx

#726 feat: Limit number of snapshots stored per canister
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/replicated_state/src/canister_snapshots.rs
Labels: feat, @runtime

#708 feat(NODE-1401): Remove non-upgrade gz images
  ic-os/defs.bzl
Labels: feat, @node

#729 feat(nns): Omit large fields for InstallCode
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#660 fix(ICP-Rosetta): Fix test name
  rs/tests/Cargo.toml
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/financial_integrations/rosetta/rosetta_neuron_disburse_test.rs
Labels: fix, @idx, @finint

#579 feat(ICP-Rosetta): FI-1379: support rosetta block in network status
  Cargo.lock
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/BUILD.bazel
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/Cargo.toml
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/src/lib.rs
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/tests/tests.rs
  rs/rosetta-api/ledger_canister_blocks_synchronizer/src/blocks.rs
  rs/rosetta-api/rosetta_core/src/response_types.rs
  rs/rosetta-api/src/request_handler.rs
  rs/rosetta-api/tests/basic_tests.rs
Labels: feat

#530 test(icrc_ledger): FI-1047: Add basic upgrade downgrade test for ICRC ledger suite
  Cargo.lock
  mainnet-canisters.bzl
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/Cargo.toml
  rs/rosetta-api/icrc1/tests/upgrade_downgrade.rs
Labels: test

#719 test(icrc_ledger): FI-1399: Add an InMemoryLedger for verifying ICRC ledger state
  rs/rosetta-api/icrc1/ledger/sm-tests/BUILD.bazel
  rs/rosetta-api/icrc1/ledger/sm-tests/src/in_memory_ledger.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/in_memory_ledger/tests.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/metrics.rs
  rs/rosetta-api/icrc1/ledger/tests/tests.rs
Labels: test, @finint

#612 feat(ckerc20): NNS proposal to add ckWSTETH
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_07_26.md
Labels: feat

#562 test(ckerc20): Ensure same processing between EVM-RPC and minter results
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/tx/tests.rs
Labels: test

#736 chore: Manually update `testnet/mainnet_revisions.json`
  testnet/mainnet_revisions.json
Labels: chore

#740 fix: Restore publishing bitcoin-mock-canister
  publish/canisters/BUILD.bazel
Labels: fix, @idx

#743 chore(IDX): switch queue check to self-hosted runner
  .github/workflows/slack-workflow-queue.yml
Labels: chore, @idx

#742 chore(IDX): switch sync to self-hosted
  .github/workflows/sync-public-with-private.yml
Labels: chore, @idx

#747 chore: Replace team runtime with team execution in code owners
  .github/CODEOWNERS
Labels: chore

#741 chore: update default dkg-interval-length to use 499 for all subnets
  rs/prep/src/subnet_configuration/constants.rs
Labels: chore, @utopia

#730 test(IDX): let most system-tests depend on the mainnet NNS in PRs
  rs/tests/Cargo.toml
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/boundary_nodes/boundary_node_intgrtn_on_playnet_test.rs
  rs/tests/boundary_nodes/boundary_node_intgrtn_test.rs
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/ckbtc/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/gix/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/nested/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/node/BUILD.bazel
  rs/tests/sdk/BUILD.bazel
  rs/tests/system_tests.bzl
  rs/tests/testing_verification/BUILD.bazel
  rs/tests/testing_verification/testnets/BUILD.bazel
Labels: test, @idx, @consensus, @boundary-node, @networking, @ic-message-routing-owners, @node, @finint, @sdk

#701 chore(NODE-1399): Update gz references
  ic-os/components/upgrade/manageboot/guestos/manageboot.sh
  ic-os/docs/Upgrades.adoc
  ic-os/guestos/docs/Build.adoc
  rs/ic_os/vsock/vsock_lib/src/host/agent.rs
  rs/nns/integration_tests/src/upgrades_handler.rs
  rs/nns/test_utils/src/registry.rs
  rs/registry/admin/src/main.rs
  rs/registry/canister/tests/hostos_version.rs
  rs/registry/canister/tests/update_subnet_and_bless_replica_version.rs
Labels: chore, @nns-team, @node

#749 test: Include networking system tests as workspace member
  Cargo.lock
  Cargo.toml
  rs/tests/networking/Cargo.toml
Labels: test

#706 feat(crypto): CRP-2563 Support key derivation in ic_crypto_ecdsa_secp256k1
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/crypto/ecdsa_secp256k1/BUILD.bazel
  rs/crypto/ecdsa_secp256k1/Cargo.toml
  rs/crypto/ecdsa_secp256k1/src/lib.rs
  rs/crypto/ecdsa_secp256k1/tests/tests.rs
Labels: feat, @idx, @crypto-team

#606 feat: [EXC-1677] add allowed_viewers to canister log visibility management canister types
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/state_layout/src/state_layout.rs
  rs/state_manager/src/tip.rs
  rs/types/management_canister_types/src/bounded_vec.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @execution, @runtime, @nns-team, @ic-message-routing-owners, @ic-interface-owners

#671 chore(crypto): CRP-2547 Annotate where parallelism can be used in NIDKG
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/forward_secure.rs
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/nizk_chunking.rs
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/fs_ni_dkg/nizk_sharing.rs
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/groth20_bls12_381/encryption.rs
Labels: chore

#756 fix(IDX): use correct env var to the icrc1-ledger WASM path
  rs/tests/gix/BUILD.bazel
  rs/tests/src/nns_dapp.rs
  rs/tests/testing_verification/testnets/BUILD.bazel
Labels: fix, @idx

#739 chore(IDX): drop GitLab support from //bazel/exporter
  bazel/exporter/main.go
Labels: chore, @idx

#757 fix(IDX): use the correct path to the XRC mock canister WASM
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
Labels: fix, @idx, @nns-team

#750 chore: Update quinn to 0.11.3
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#629 refactor(sns): NNS1-3207: Use NeuronRecipes in SNS Swap
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/tests/governance.rs
  rs/sns/swap/src/swap.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/swap.rs
Labels: refactor

#765 chore: Update Base Image Refs [2024-08-06-0146]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#759 chore(dependency-mgmt): Change `oisy-wallet` node version to 20
  gitlab-ci/src/dependencies/job/npm_scanner_periodic_job.py
Labels: chore, @product-security

#767 fix(IDX): replace pull_request references in schedule daily
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: fix, @idx

#732 fix: update cloudflare dependency [S3_UPLOAD]
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/Cargo.toml
Labels: fix, @idx

#774 chore(IDX): inherit secrets for qualifier workflow
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: chore, @idx

#773 fix(IDX): don't pull systest images on Darwin
  rs/tests/BUILD.bazel
Labels: fix, @idx

#770 chore(crypto): bump ic_bls12_381 to 0.10.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#738 feat(ckerc20): Use EVM-RPC canister to call `eth_getTransactionReceipt`
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/responses.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/evm-rpc-client/src/lib.rs
  rs/ethereum/evm-rpc-client/src/types.rs
Labels: feat, @cross-chain-team

#775 chore: Remove copy of CreateSubnetPayload in ic-admin
  rs/registry/admin/src/create_subnet.rs
Labels: chore

#776 fix(IDX): remove continue-on-error
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#705 test(neurons-fund): Check Neurons' Fund hotkey propagation in SNS lifecycle tests
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_ledger_upgrade.rs
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nns/governance/init/src/lib.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/neurons_fund.rs
  rs/nns/test_utils/src/common.rs
  rs/registry/admin/tests/integration_tests.rs
Labels: test, @nns-team

#778 chore(NODE-1448): Remove obsolete set-node-id command
  rs/ic_os/vsock/README.md
  rs/ic_os/vsock/guest/src/main.rs
  rs/ic_os/vsock/vsock_lib/src/host/agent.rs
  rs/ic_os/vsock/vsock_lib/src/protocol/structures.rs
  rs/ic_os/vsock/vsock_lib/src/protocol/utils.rs
Labels: chore, @node

#780 chore(sns): Remove obsolete field `SnsInitPayload.neurons_fund_participants`
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/proposals/create_service_nervous_system.rs
  rs/nns/sns-wasm/canister/sns-wasm.did
  rs/sns/init/proto/ic_sns_init/pb/v1/sns_init.proto
  rs/sns/init/src/gen/ic_sns_init.pb.v1.rs
  rs/sns/init/src/lib.rs
Labels: chore, @nns-team

#786 docs: fix upgrade-install documentation
  ic-os/components/upgrade/manageboot/guestos/manageboot.sh
Labels: docs, @node

#731 feat(nns): Implement the execution of UpdateCanisterSettings proposals
  Cargo.lock
  rs/nervous_system/clients/src/canister_status.rs
  rs/nervous_system/clients/src/management_canister_client/tests.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/src/proposals/update_canister_settings.rs
  rs/nns/handlers/root/impl/canister/canister.rs
  rs/nns/handlers/root/impl/canister/root.did
  rs/nns/handlers/root/impl/src/canister_management.rs
  rs/nns/handlers/root/interface/src/client.rs
  rs/nns/handlers/root/interface/src/lib.rs
  rs/nns/integration_tests/src/update_canister_settings.rs
  rs/sns/root/canister/root.did
  rs/sns/swap/canister/canister.rs
Labels: feat, @nns-team

#761 feat(nns): Switch NNS functions to new topics behind a feature flag
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/stop_or_start_canister.rs
  rs/nns/governance/src/proposals/update_canister_settings.rs
Labels: feat

#733 feat(RUN-1032): Parallel dirty page copying for page allocator
  Cargo.lock
  rs/canister_sandbox/src/lib.rs
  rs/config/src/embedders.rs
  rs/replicated_state/BUILD.bazel
  rs/replicated_state/Cargo.toml
  rs/replicated_state/src/page_map/page_allocator.rs
  rs/replicated_state/src/page_map/page_allocator/mmap.rs
  rs/replicated_state/src/page_map/page_allocator/mmap/tests.rs
Labels: feat, @execution, @runtime, @ic-message-routing-owners

#702 feat: Checkpointing for canister snapshots
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
  rs/state_layout/src/state_layout.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/tests/state_manager.rs
Labels: feat, @execution, @ic-message-routing-owners

#745 test: more complex input queues scenario for queue compatibility tests
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/sns/root/src/lib.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/types/base_types/src/principal_id.rs
  rs/types/types_test_utils/src/ids.rs
Labels: test, @idx, @nns-team, @ic-message-routing-owners, @ic-interface-owners

#753 fix: [EXC-1673] Consider canister snapshots when calculating available subnet memory
  rs/execution_environment/tests/execution_test.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/replicated_state.rs
  rs/state_machine_tests/src/lib.rs
Labels: fix, @execution, @pocket-ic, @ic-message-routing-owners

#784 fix(IDX): don't pull systest images on Darwin
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/icrc1/rosetta/BUILD.bazel
  rs/tests/BUILD.bazel
  rs/tests/httpbin-rs/BUILD.bazel
  rs/tests/networking/canister_http/BUILD.bazel
Labels: fix

#725 test(neurons-fund): Add tests for checking worst-case response size of `NnsGov.settle_neurons_fund_participation`
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/neurons_fund.rs
Labels: test, @nns-team

#581 chore(IDX): Exclude some tests from the merge train
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  gitlab-ci/src/git_changes/git_changes_test.py
Labels: chore, @idx

#785 fix: RUN-874: Fix the return type of some System APIs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/execution_environment/src/hypervisor/tests.rs
Labels: fix

#792 feat(ckerc20): Use EVM-RPC canister to call `eth_getTransactionCount`
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/withdraw.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/evm-rpc-client/src/lib.rs
  rs/ethereum/evm-rpc-client/src/types.rs
Labels: feat, @cross-chain-team

#802 refactor: Use ic_cdk::api::time for ingress message validator crate
  Cargo.lock
  rs/validator/ingress_message/BUILD.bazel
  rs/validator/ingress_message/Cargo.toml
  rs/validator/ingress_message/src/internal/mod.rs
Labels: refactor, @crypto-team

#805 refactor: Switch some test canisters in rust_canisters to use public CDK
  Cargo.lock
  rs/rust_canisters/call_tree_test/BUILD.bazel
  rs/rust_canisters/call_tree_test/Cargo.toml
  rs/rust_canisters/call_tree_test/src/main.rs
  rs/rust_canisters/downstream_calls_test/BUILD.bazel
  rs/rust_canisters/downstream_calls_test/Cargo.toml
  rs/rust_canisters/downstream_calls_test/src/main.rs
  rs/rust_canisters/ecdsa/BUILD.bazel
  rs/rust_canisters/ecdsa/Cargo.toml
  rs/rust_canisters/ecdsa/src/main.rs
  rs/rust_canisters/response_payload_test/BUILD.bazel
  rs/rust_canisters/response_payload_test/Cargo.toml
  rs/rust_canisters/response_payload_test/src/main.rs
Labels: refactor, @execution, @nns-team

#804 chore: Update visibility of `dfn_*` libraries
  rs/rust_canisters/dfn_candid/BUILD.bazel
  rs/rust_canisters/dfn_core/BUILD.bazel
  rs/rust_canisters/dfn_http/BUILD.bazel
  rs/rust_canisters/dfn_http_metrics/BUILD.bazel
  rs/rust_canisters/dfn_json/BUILD.bazel
  rs/rust_canisters/dfn_macro/BUILD.bazel
  rs/rust_canisters/dfn_protobuf/BUILD.bazel
Labels: chore, @nns-team

#807 docs(nns): Added some comments that explain what to do when nns upgrade test fails.
  rs/nns/integration_tests/BUILD.bazel
Labels: docs, @nns-team

#718 feat(ic-admin): Change IC Admin to support creating InstallCode and StopOrStartCansiter proposals
  rs/registry/admin/src/main.rs
  rs/registry/admin/src/types.rs
Labels: feat, @nns-team, @ic-owners-owners

#816 fix(IDX): correct name of the system-test-k8s workflow
  .github/workflows/system-tests-k8s.yml
Labels: fix, @idx

#815 fix(IDX): shorten names of boundary-node systest because they're too long for k8s
  rs/tests/Cargo.toml
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/boundary_nodes/api_bn_decentralization_test.rs
  rs/tests/boundary_nodes/bn_integration_on_playnet_test.rs
  rs/tests/boundary_nodes/bn_integration_test.rs
  rs/tests/boundary_nodes/bn_performance_test.rs
  rs/tests/boundary_nodes/bn_update_workload_test.rs
  rs/tests/boundary_nodes/mainnet_bn_icx_proxy_performance_test.rs
  rs/tests/boundary_nodes/mainnet_bn_performance_test.rs
Labels: fix, @idx, @boundary-node

#817 fix(IDX): do not run colocated systests on k8s
  .github/workflows/system-tests-k8s.yml
  rs/tests/system_tests.bzl
Labels: fix, @idx

#820 chore(IDX): drop ic-nns-governance dep from ic-system-test-driver
  Cargo.lock
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
Labels: chore, @idx

#789 feat(ic-admin): Support sending update_canister_settings proposals through ic-admin
  Cargo.lock
  rs/registry/admin/BUILD.bazel
  rs/registry/admin/Cargo.toml
  rs/registry/admin/src/main.rs
  rs/registry/admin/src/types.rs
Labels: feat

#795 test(consensus): Add exhaustive serialization->deserialization test for `ConsensusMessage`
  rs/types/types/src/consensus.rs
  rs/types/types/src/exhaustive.rs
Labels: test, @consensus

#810 chore(IDX): run darwin tests on new profile
  .github/workflows/test-namespace-darwin.yml
Labels: chore, @idx

#824 chore(IDX): fix workflow syntax
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: chore, @idx

#791 feat(ckbtc): import code from btc-tx-input-canister as the new kyt canister XC-150
  .github/CODEOWNERS
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/kyt/BUILD.bazel
  rs/bitcoin/kyt/Cargo.toml
  rs/bitcoin/kyt/btc_kyt_canister.did
  rs/bitcoin/kyt/src/main.rs
Labels: feat, @ic-interface-owners, @cross-chain-team, @ic-owners-owners

#797 test(consensus): Only consider summary blocks in CUP exhaustive test
  rs/types/types/src/exhaustive.rs
Labels: test, @consensus

#812 test: EXC-1684: Make memory test more robust
  rs/README.adoc
  rs/execution_environment/tests/execution_test.rs
  rs/universal_canister/README.md
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/BUILD.bazel
  rs/universal_canister/lib/src/lib.rs
  rs/universal_canister/lib/src/universal-canister.wasm
  rs/universal_canister/lib/src/universal-canister.wasm.gz
Labels: test

#798 test(cloner-canister): Add manual system test to stress test subnet by installing order of 100k canisters
  Cargo.lock
  Cargo.toml
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/canisters/BUILD.bazel
  rs/tests/networking/canisters/Cargo.toml
  rs/tests/networking/canisters/candid.did
  rs/tests/networking/canisters/src/cloner_canister.rs
  rs/tests/networking/cloner_canister_workload.rs
Labels: test, @idx, @networking

#587 chore(http_endpoint): put compute intesive code in `/read_state` into `spawn_blocking`
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/http_endpoints/public/src/read_state/subnet.rs
Labels: chore

#803 feat(cmc): Initialize `average_icp_xdr_conversion_rate`
  rs/nns/cmc/src/exchange_rate_canister.rs
  rs/nns/cmc/src/lib.rs
  rs/nns/cmc/src/main.rs
Labels: feat, @nns-team

#813 fix: add content-type, x-content-type-options, x-frame-options headers to API responses
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
Labels: fix, @boundary-node

#830 fix: adding missing tag for build-image.sh
  gitlab-ci/container/build-image.sh
Labels: fix

#831 chore: sort dependencies in execution Cargo.toml files
  rs/bitcoin/consensus/Cargo.toml
  rs/cycles_account_manager/Cargo.toml
  rs/determinism_test/Cargo.toml
  rs/memory_tracker/Cargo.toml
  rs/query_stats/Cargo.toml
  rs/replica_tests/Cargo.toml
  rs/replicated_state/Cargo.toml
  rs/rust_canisters/call_tree_test/Cargo.toml
  rs/rust_canisters/canister_creator/Cargo.toml
  rs/rust_canisters/stable_memory_integrity/Cargo.toml
  rs/sys/Cargo.toml
  rs/test_utilities/execution_environment/Cargo.toml
  rs/workload_generator/Cargo.toml
Labels: chore

#809 fix: add content-type, x-content-type-options, and x-frame-options headers
  Cargo.lock
  rs/boundary_node/certificate_issuance/certificate_issuer/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_issuer/Cargo.toml
  rs/boundary_node/certificate_issuance/certificate_issuer/src/headers.rs
  rs/boundary_node/certificate_issuance/certificate_issuer/src/main.rs
Labels: fix, @boundary-node

#833 chore: sort dependencies in networking Cargo.toml files
  rs/async_utils/Cargo.toml
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/client/Cargo.toml
  rs/canister_client/Cargo.toml
  rs/config/Cargo.toml
  rs/replica/Cargo.toml
  rs/starter/Cargo.toml
Labels: chore, @networking

#827 chore: Update Base Image Refs [2024-08-08-0807]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#748 chore(ckerc20): NNS proposal to upgrade the ckETH minter
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/minter_upgrade_2024_08_05.md
  rs/ethereum/cketh/minter/src/state/audit/tests.rs
  rs/ethereum/cketh/minter/test_resources/mainnet_events.gz
  rs/ethereum/cketh/minter/test_resources/sepolia_events.gz
  rs/ethereum/cketh/testnet/dfx.json
Labels: chore, @cross-chain-team

#835 chore: sort dependencies in crypto Cargo.toml files
  rs/crypto/Cargo.toml
  rs/test_utilities/in_memory_logger/Cargo.toml
Labels: chore, @crypto-team

#837 fix: Store the version of the snapshot that was loaded in canister history
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
Labels: fix

#832 chore: sort dependencies in consensus Cargo.toml files
  rs/artifact_pool/Cargo.toml
  rs/backup/Cargo.toml
  rs/consensus/Cargo.toml
  rs/cup_explorer/Cargo.toml
  rs/http_utils/Cargo.toml
  rs/https_outcalls/consensus/Cargo.toml
  rs/ingress_manager/Cargo.toml
  rs/orchestrator/Cargo.toml
  rs/recovery/Cargo.toml
  rs/replay/Cargo.toml
  rs/types/exhaustive_derive/Cargo.toml
Labels: chore

#834 chore: sort dependencies in message routing Cargo.toml files
  rs/canonical_state/Cargo.toml
  rs/messaging/Cargo.toml
  rs/state_layout/Cargo.toml
Labels: chore, @ic-message-routing-owners

#787 chore(IDX): read runtime system-test dependencies from $RUNFILES
  rs/tests/consensus/backup_manager_test.rs
  rs/tests/consensus/consensus_performance.rs
  rs/tests/consensus/orchestrator/cup_compatibility_test.rs
  rs/tests/consensus/orchestrator/sr_nns_failover_nodes_test.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/boundary_node.rs
  rs/tests/driver/src/driver/farm.rs
  rs/tests/driver/src/driver/group.rs
  rs/tests/driver/src/driver/nested.rs
  rs/tests/driver/src/driver/prometheus_vm.rs
  rs/tests/driver/src/driver/resource.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/driver/universal_vm.rs
  rs/tests/driver/src/sns_client.rs
  rs/tests/execution/fill_execution_rounds_workload.rs
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/tests/nested/src/lib.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/canister_http/canister_http.rs
  rs/tests/networking/canister_http_fault_tolerance_test.rs
  rs/tests/networking/canister_http_socks_test.rs
  rs/tests/networking/cloner_canister_workload.rs
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/sdk/dfx_check_old_wallet_version_test.rs
  rs/tests/sdk/src/dfx.rs
  rs/tests/src/boundary_nodes/boundary_nodes_integration.rs
  rs/tests/src/btc_integration/btc.rs
  rs/tests/src/ckbtc/agent.rs
  rs/tests/src/ckbtc/lib.rs
  rs/tests/src/ckbtc/minter/test_addresses.rs
  rs/tests/src/ckbtc/minter/test_batching.rs
  rs/tests/src/ckbtc/minter/test_get_btc_address.rs
  rs/tests/src/ckbtc/minter/test_heartbeat.rs
  rs/tests/src/ckbtc/minter/test_kyt.rs
  rs/tests/src/ckbtc/minter/test_retrieve_btc.rs
  rs/tests/src/ckbtc/minter/test_update_balance.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
  rs/tests/src/custom_domains_integration/setup.rs
  rs/tests/src/icrc1_agent_test/mod.rs
  rs/tests/src/message_routing/compatibility.rs
  rs/tests/src/message_routing/global_reboot_test.rs
  rs/tests/src/message_routing/mod.rs
  rs/tests/src/networking/p2p_performance_workload.rs
  rs/tests/src/nns_dapp.rs
  rs/tests/src/nns_tests/bitcoin_set_config_proposal.rs
  rs/tests/src/nns_tests/sns_aggregator.rs
  rs/tests/src/orchestrator/subnet_recovery_app_subnet.rs
  rs/tests/src/orchestrator/subnet_recovery_nns_subnet.rs
  rs/tests/src/orchestrator/subnet_splitting.rs
  rs/tests/src/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/src/orchestrator/unstuck_subnet_test.rs
  rs/tests/src/orchestrator/upgrade_downgrade.rs
  rs/tests/src/orchestrator/upgrade_with_alternative_urls.rs
  rs/tests/src/rosetta_test.rs
  rs/tests/src/rosetta_tests/setup.rs
  rs/tests/system_tests.bzl
  rs/tests/testing_verification/colocate_test.rs
  rs/tests/testing_verification/remote_replicable_mock_test.rs
  rs/tests/testing_verification/spec_compliance/spec_compliance.rs
  rs/tests/testing_verification/testnets/from_config.rs
Labels: chore, @idx, @consensus, @execution, @boundary-node, @networking, @nns-team, @ic-message-routing-owners, @cross-chain-team, @finint, @sdk

#814 feat(nns): Add topic mapping for canister management topics
  rs/nns/constants/src/lib.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/mod.rs
  rs/nns/governance/src/proposals/stop_or_start_canister.rs
  rs/nns/governance/src/proposals/update_canister_settings.rs
Labels: feat

#818 chore(nns): Add post-upgrade validation for NP Rewards and audit events
  rs/nns/governance/src/storage.rs
Labels: chore, @nns-team

#794 chore(sns): Obsolete `SwapInit.neurons_fund_participants`
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/sns/init/src/lib.rs
  rs/sns/integration_tests/src/payment_flow.rs
  rs/sns/integration_tests/src/swap.rs
  rs/sns/swap/canister/swap.did
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/sns/swap/src/swap.rs
  rs/sns/swap/src/swap_builder.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/swap.rs
  rs/sns/test_utils/src/itest_helpers.rs
Labels: chore, @nns-team

#744 feat(ckerc20): NNS proposal to upgrade ckERC20 ledger suites to support ICRC-21
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_08_05.md
Labels: feat

#801 feat(proposal-cli): Retrieve last canister upgrade proposal ID
  Cargo.lock
  rs/cross-chain/proposal-cli/BUILD.bazel
  rs/cross-chain/proposal-cli/Cargo.toml
  rs/cross-chain/proposal-cli/README.adoc
  rs/cross-chain/proposal-cli/src/dashboard/mod.rs
  rs/cross-chain/proposal-cli/src/dashboard/responses.rs
  rs/cross-chain/proposal-cli/src/dashboard/tests.rs
  rs/cross-chain/proposal-cli/src/main.rs
  rs/cross-chain/proposal-cli/src/proposal/mod.rs
  rs/cross-chain/proposal-cli/templates/upgrade.md
Labels: feat, @cross-chain-team

#840 fix(execution): Update doc comment
  rs/execution_environment/src/execution_environment.rs
Labels: fix

#826 fix: disable node exporter netlink metrics collection
  ic-os/components/monitoring/node_exporter/node_exporter
Labels: fix, @node

#723 chore(consensus): [Con-1226] only validate open request context
  rs/https_outcalls/consensus/src/gossip.rs
  rs/https_outcalls/consensus/src/pool_manager.rs
Labels: chore, @consensus

#839 chore(IDX): only upload build events on CI
  bazel/conf/.bazelrc.internal
Labels: chore, @idx

#836 feat(ckerc20): Use EVM-RPC canister to call `eth_sendRawTransaction`
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/withdraw.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/evm-rpc-client/src/lib.rs
  rs/ethereum/evm-rpc-client/src/types.rs
Labels: feat, @cross-chain-team

#783 feat(ckerc20): NNS proposal to add ckUNI
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2024_08_06.md
Labels: feat

#800 fix: Subnet splitting with canister snapshots
  rs/state_manager/src/lib.rs
  rs/state_manager/src/split.rs
  rs/state_manager/src/split/tests.rs
  rs/test_utilities/state/src/lib.rs
Labels: fix

#823 chore: RUN-1003: Remove `hypervisor_wasm_num_tables` metric
  rs/embedders/src/lib.rs
  rs/embedders/src/wasm_utils.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/execution_environment/src/hypervisor.rs
Labels: chore, @execution

#768 feat: [EXC-1675] migrate replica to no-op LogVisibilityV2
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/query_handler.rs
  rs/execution_environment/tests/canister_logging.rs
  rs/nns/cmc/src/lib.rs
  rs/nns/cmc/src/main.rs
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/replica_tests/tests/canister_lifecycle.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/sns/integration_tests/src/manage_dapp_canister_settings.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/test_utilities/state/src/lib.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @execution, @nns-team, @ic-message-routing-owners, @ic-interface-owners

#849 perf: EXC-1638: Add canister snapshot benchmarks
  rs/bitcoin/kyt/src/main.rs
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/benches/management_canister/MANAGEMENT_CANISTER.md
  rs/execution_environment/benches/management_canister/canister_snapshots.rs
  rs/execution_environment/benches/management_canister/main.rs
  rs/execution_environment/benches/management_canister/utils.rs
  rs/state_machine_tests/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
  rs/universal_canister/lib/src/universal-canister.wasm.gz
Labels: perf, @execution, @pocket-ic, @ic-message-routing-owners, @cross-chain-team

#825 chore: EXC-1685: Upgrade `wasmtime` to v23
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
  rs/embedders/src/signal_handler.rs
  rs/embedders/src/wasm_executor.rs
  rs/embedders/src/wasm_utils/instrumentation.rs
  rs/embedders/src/wasm_utils/system_api_replacements.rs
  rs/embedders/src/wasmtime_embedder/host_memory.rs
  rs/embedders/tests/validation.rs
  rs/wasm_transform/Cargo.toml
Labels: chore, @idx, @execution

#838 test(nns): Make `NnsGov.update_neuron` fail more verbosely for attempted neuron subaccount updates
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
Labels: test, @nns-team

#842 feat(nns): Redact private neuron info fields.
  Cargo.lock
  Cargo.toml
  rs/nervous_system/temporary/BUILD.bazel
  rs/nervous_system/temporary/Cargo.toml
  rs/nervous_system/temporary/src/lib.rs
  rs/nervous_system/temporary/tests/temporary.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/merge_neurons.rs
Labels: feat, @nns-team

#862 feat(registry): Add consistently-named alias `Registry.revise_elected_guestos_versions` [override-didc-check]
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_revise_elected_replica_versions.rs
Labels: feat, @nns-team

#867 feat(registry): Remove unused function `Registry.bless_replica_version` [override-didc-check]
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
Labels: feat, @nns-team

#865 feat(registry): Add consistently-named alias `Registry.deploy_hostos_to_some_nodes`
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_update_nodes_hostos_version.rs
Labels: feat, @nns-team

#845 chore(crypto): CRP-2564 Address comments from Schnorr security review
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/src/lib.rs
  rs/crypto/internal/crypto_lib/threshold_sig/tecdsa/src/signing/key_derivation.rs
  rs/interfaces/src/crypto/sign/canister_threshold_sig.rs
Labels: chore

#677 feat(PocketIC): query statistics in the management canister
  rs/consensus/src/consensus/payload_builder.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/tests/test.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @consensus, @pocket-ic, @ic-message-routing-owners

#846 chore: add headers test
  rs/tests/boundary_nodes/bn_integration_on_playnet_test.rs
  rs/tests/boundary_nodes/bn_integration_test.rs
  rs/tests/src/boundary_nodes/boundary_nodes_integration.rs
Labels: chore, @idx, @boundary-node

#848 feat(IDX): run execution tests on namespace
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  .github/workflows/test-namespace-darwin.yml
  gitlab-ci/config/main.yml
  gitlab-ci/config/zz-generated-gitlab-ci.yaml
  rs/execution_environment/BUILD.bazel
Labels: feat, @idx, @execution

#600 chore(crypto): Set documentation of ic-signature-verification to docs.rs
  packages/ic-signature-verification/Cargo.toml
Labels: chore

#863 feat(registry): Remove unused function `Registry.update_subnet_replica_version` [override-didc-check]
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
Labels: feat, @nns-team

#855 feat(registry): Add consistently-named alias `Registry.revise_elected_hostos_versions`
  rs/registry/admin/src/main.rs
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_update_elected_hostos_versions.rs
Labels: feat, @nns-team

#876 feat(idx): disable fastbuild on macos_ci
  bazel/conf/.bazelrc.build
Labels: feat, @idx

#864 feat(registry): Add consistently-named alias `Registry.deploy_guestos_to_some_api_boundary_nodes`
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_update_api_boundary_nodes_version.rs
Labels: feat, @nns-team

#819 feat(NODE-1450): Consolidate manageboot.sh
  ic-os/components/guestos.bzl
  ic-os/components/hostos-scripts/guestos/guestos.service
  ic-os/components/hostos.bzl
  ic-os/components/upgrade/install-upgrade.sh
  ic-os/components/upgrade/manageboot/hostos/manageboot.sh
  ic-os/components/upgrade/manageboot/manageboot.sh
  rs/orchestrator/image_upgrader/src/image_upgrader.rs
Labels: feat, @consensus, @node

#843 chore(IDX): bazel-bep.pb as artifact
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
Labels: chore, @idx

#881 chore: EXC-1607: Execute the consensus queue even if the limits are reached
  rs/execution_environment/src/scheduler.rs
Labels: chore, @execution

#890 docs: `from_config.rs` testnet
  rs/tests/testing_verification/testnets/from_config.rs
Labels: docs, @idx

#844 feat(crypto): CRP-2560 Add BIP340 support to secp256k1 utility crate
  rs/crypto/ecdsa_secp256k1/src/lib.rs
  rs/crypto/ecdsa_secp256k1/tests/tests.rs
  rs/crypto/internal/crypto_lib/basic_sig/ecdsa_secp256k1/src/api.rs
Labels: feat, @crypto-team

#857 feat: EXC-1683: Include snapshot memory usage in canister's memory usage
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/tip.rs
Labels: feat, @execution, @ic-interface-owners

#889 chore: tokio upgrade
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#868 refactor(nns): migrate rosetta-api and rosetta_tests to use governance api crate
  Cargo.lock
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/src/ledger_client.rs
  rs/rosetta-api/src/ledger_client/handle_add_hotkey.rs
  rs/rosetta-api/src/ledger_client/handle_change_auto_stake_maturity.rs
  rs/rosetta-api/src/ledger_client/handle_disburse.rs
  rs/rosetta-api/src/ledger_client/handle_follow.rs
  rs/rosetta-api/src/ledger_client/handle_list_neurons.rs
  rs/rosetta-api/src/ledger_client/handle_merge_maturity.rs
  rs/rosetta-api/src/ledger_client/handle_neuron_info.rs
  rs/rosetta-api/src/ledger_client/handle_register_vote.rs
  rs/rosetta-api/src/ledger_client/handle_remove_hotkey.rs
  rs/rosetta-api/src/ledger_client/handle_set_dissolve_timestamp.rs
  rs/rosetta-api/src/ledger_client/handle_spawn.rs
  rs/rosetta-api/src/ledger_client/handle_stake.rs
  rs/rosetta-api/src/ledger_client/handle_stake_maturity.rs
  rs/rosetta-api/src/ledger_client/handle_start_dissolve.rs
  rs/rosetta-api/src/ledger_client/handle_stop_dissolve.rs
  rs/rosetta-api/src/ledger_client/list_known_neurons_response.rs
  rs/rosetta-api/src/ledger_client/list_neurons_response.rs
  rs/rosetta-api/src/ledger_client/pending_proposals_response.rs
  rs/rosetta-api/src/ledger_client/proposal_info_response.rs
  rs/rosetta-api/src/request.rs
  rs/rosetta-api/src/request_handler.rs
  rs/rosetta-api/src/request_handler/construction_parse.rs
  rs/rosetta-api/src/request_handler/construction_payloads.rs
  rs/rosetta-api/tests/test_utils/mod.rs
  rs/tests/src/rosetta_tests/rosetta_client.rs
  rs/tests/src/rosetta_tests/tests/list_known_neurons.rs
  rs/tests/src/rosetta_tests/tests/neuron_voting.rs
Labels: refactor, @idx, @finint

#877 fix: add new line at the end of the file
  rs/ic_os/nft_exporter/src/main.rs
Labels: fix, @node

#878 feat(nns): Obsolete legacy IC OS proposals
  rs/nns/governance/src/governance.rs
Labels: feat, @nns-team

#888 feat(registry): Fix (undeployed) Registry API type name [override-didc-check]
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_update_api_boundary_nodes_version.rs
Labels: feat, @nns-team

#899 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#900 chore: [NODE-1453] Remove SetupOS SELinux policy
  ic-os/components/guestos.bzl
  ic-os/components/prep/setupos/fscontext-fixes/fscontext-fixes.fc
  ic-os/components/prep/setupos/fscontext-fixes/fscontext-fixes.if
  ic-os/components/prep/setupos/fscontext-fixes/fscontext-fixes.te
  ic-os/components/prep/setupos/misc-fixes/misc-fixes.if
  ic-os/components/prep/setupos/misc-fixes/misc-fixes.te
  ic-os/components/prep/setupos/prep.sh
  ic-os/components/prep/setupos/systemd-fixes/systemd-fixes.if
  ic-os/components/prep/setupos/systemd-fixes/systemd-fixes.te
  ic-os/components/selinux/filebeat/filebeat.fc
  ic-os/components/selinux/filebeat/filebeat.if
  ic-os/components/selinux/filebeat/filebeat.te
  ic-os/components/selinux/fscontext-fixes/fscontext-fixes.fc
  ic-os/components/selinux/fscontext-fixes/fscontext-fixes.if
  ic-os/components/selinux/fscontext-fixes/fscontext-fixes.te
  ic-os/components/selinux/ic-node/ic-node.fc
  ic-os/components/selinux/ic-node/ic-node.if
  ic-os/components/selinux/ic-node/ic-node.te
  ic-os/components/selinux/infogetty/infogetty.fc
  ic-os/components/selinux/infogetty/infogetty.te
  ic-os/components/selinux/manageboot/manageboot.fc
  ic-os/components/selinux/manageboot/manageboot.if
  ic-os/components/selinux/manageboot/manageboot.te
  ic-os/components/selinux/misc-fixes/misc-fixes.if
  ic-os/components/selinux/misc-fixes/misc-fixes.te
  ic-os/components/selinux/node_exporter/node_exporter.fc
  ic-os/components/selinux/node_exporter/node_exporter.if
  ic-os/components/selinux/node_exporter/node_exporter.te
  ic-os/components/selinux/prep.sh
  ic-os/components/selinux/setup-var/setup-var.if
  ic-os/components/selinux/setup-var/setup-var.te
  ic-os/components/selinux/systemd-fixes/systemd-fixes.if
  ic-os/components/selinux/systemd-fixes/systemd-fixes.te
  ic-os/components/setupos.bzl
  ic-os/setupos/context/Dockerfile
Labels: chore

#880 feat(registry): Remove unused function `Registry.retire_replica_version` [override-didc-check]
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
Labels: feat, @nns-team

#896 chore: actix upgrade
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/ledger_canister_blocks_synchronizer/Cargo.toml
Labels: chore, @idx

#811 feat: EXC-1567: Add charging for take and load canister snapshot
  rs/config/src/subnet_config.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/execution_environment/src/lib.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @execution

#572 fix: CON-1321 Make the orchestrator recover from having a broken local CUP
  rs/orchestrator/src/catch_up_package_provider.rs
  rs/orchestrator/src/error.rs
  rs/orchestrator/src/metrics.rs
  rs/orchestrator/src/upgrade.rs
  rs/tests/src/orchestrator/subnet_recovery_app_subnet.rs
Labels: fix, @idx, @consensus

#898 chore: update deny.toml
  deny.toml
Labels: chore, @networking

#640 chore: introduce boundary-node-pkg package group
  rs/BUILD.bazel
  rs/boundary_node/canary_proxy/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_issuer/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_syncer/BUILD.bazel
  rs/boundary_node/ic_balance_exporter/BUILD.bazel
  rs/boundary_node/prober/BUILD.bazel
  rs/boundary_node/systemd_journal_gatewayd_shim/BUILD.bazel
Labels: chore, @boundary-node, @ic-interface-owners

#891 fix(BOUN-1208): fix ACME, fix ratelimit
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/boundary_node/certificate_issuance/certificate_issuer/Cargo.toml
  rs/boundary_node/certificate_issuance/certificate_issuer/src/main.rs
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/benches/perf.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/test.rs
  rs/boundary_node/ic_boundary/src/retry.rs
  rs/boundary_node/ic_boundary/src/retry/test.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/ic_boundary/src/tls.rs
  rs/boundary_node/ic_boundary/src/tls/test.rs
Labels: fix, @idx, @boundary-node

#886 chore(IDX): consolidate lock-generate and bazel-pin
  bin/bazel-pin.sh
  gitlab-ci/src/ci-scripts/lock-generate.sh
Labels: chore, @idx

#496 refactor: move reserved fields to the bottom of the message definitions
  rs/protobuf/def/registry/node/v1/node.proto
  rs/protobuf/def/registry/replica_version/v1/replica_version.proto
  rs/protobuf/def/registry/subnet/v1/subnet.proto
  rs/protobuf/def/registry/unassigned_nodes_config/v1/unassigned_nodes_config.proto
  rs/protobuf/src/gen/registry/registry.node.v1.rs
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
Labels: refactor, @nns-team, @ic-interface-owners

#866 feat(nns): Implement proposal execution for updating settings for root
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/stop_or_start_canister.rs
  rs/nns/governance/src/proposals/update_canister_settings.rs
  rs/nns/handlers/lifeline/impl/lifeline.did
  rs/nns/handlers/lifeline/impl/lifeline.mo
  rs/nns/integration_tests/src/update_canister_settings.rs
Labels: feat

#799 fix(consensus): Use priority in the payload builder to decide to trigger edge-case
  rs/bitcoin/consensus/src/payload_builder.rs
  rs/bitcoin/consensus/src/payload_builder/tests.rs
  rs/consensus/src/consensus/payload.rs
  rs/consensus/src/consensus/payload_builder.rs
  rs/interfaces/src/self_validating_payload.rs
  rs/test_utilities/src/self_validating_payload_builder.rs
Labels: fix, @consensus, @execution, @ic-interface-owners

#711 feat(NODE-1400): Add zst compatibility for NNS subnet recovery
  Cargo.lock
  rs/http_utils/BUILD.bazel
  rs/http_utils/Cargo.toml
  rs/http_utils/src/file_downloader.rs
  rs/orchestrator/src/upgrade.rs
  rs/recovery/src/lib.rs
  rs/recovery/src/nns_recovery_failover_nodes.rs
  rs/recovery/src/steps.rs
Labels: feat, @consensus

#686 chore: replace icx-proxy by ic-http-gateway in PocketIC
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  packages/pocket-ic/src/nonblocking.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/state_api/canister_id.rs
  rs/pocket_ic_server/src/state_api/mod.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: chore, @idx, @pocket-ic
