Repository dfinity/ic, pull requests merged in 2024-06, with the labels that each got.

#201 fix(IDX): push to gitlab
  .github/workflows/gitlab-push.yml
Labels: fix

#202 chore(IDX): sync from gitlab
  .github/workflows/gitlab-sync-branches.yml
Labels: chore

#204 chore(IDX): relabel CI jobs
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
Labels: chore

#214 chore(IDX): remove clippy sysroot workaround
  .bazelrc
Labels: chore

#216 chore(IDX): rebuild ic-build
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
  gitlab-ci/container/TAG_GH
Labels: chore

#221 fix(IDX): incorrect path
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix

#224 fix(IDX): docker.io auth
  gitlab-ci/src/ci-scripts/before-script.sh
Labels: fix

#230 chore(IDX): upgrade actions
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-generate-ci.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
Labels: chore

#235 chore(IDX): container user
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
  gitlab-ci/container/TAG_GH
Labels: chore

#236 chore(IDX): dind-large
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
Labels: chore

#240 chore(IDX): revert PR236
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
Labels: chore

#239 chore(IDX): keep using bazel small runners
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: chore

#241 chore(IDX): dind large group
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
Labels: chore

#190 test(NNS): run upgrade_canisters_with_golden_nns_state daily
  .bazelrc
  .github/actions/bazel-test-all/action.yaml
  .github/workflows/schedule-daily.yml
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
Labels: test

#246 chore(IDX): move back to dind runners
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: chore

#249 chore(IDX): enable the firewall_max_connections_test on GitHub again
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-hourly.yml
  rs/tests/networking/BUILD.bazel
Labels: chore

#250 chore(IDX): bazel-test-all update
  .github/actions/bazel-test-all/action.yaml
Labels: chore

#256 chore(IDX): remove eng-testing
  .github/workflows/team-channels.json
Labels: chore

#257 chore(IDX): no execution_environment_test on darwin
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore

#259 chore(IDX): Remove verbose failures
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
Labels: chore

#262 revert(IDX): no execution_environment_test on darwin
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: revert

#263 chore: CRP-2509 add `additional_colocate_flag` and fetch targets via `bazel query` to fix `system-tests-benchmarks-nightly`
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/system_tests.bzl
Labels: chore

#266 test(schnorr): CON-1337 Add tSchnorr keys to backup manager test
  .github/workflows/team-channels.json
  rs/tests/consensus/backup_manager_test.rs
Labels: test

#275 chore(IDX): allow manual trigger for container autobuild
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
  gitlab-ci/container/TAG_GH
Labels: chore

#274 chore(IDX): remove RUN_CI var
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-base-images.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
Labels: chore

#278 chore(IDX): disable run on diff for bazel-build-all-config-check
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore

#282 chore(CON13-02): Remove `make_ecdsa_signing_subnet_list_key` from the codebase
  rs/consensus/tests/framework/mod.rs
  rs/registry/keys/src/lib.rs
Labels: chore
