Repository dfinity/ic, pull requests merged in 2024-09, with the labels that each got.

#1211 feat(RUN-931): Add Doc Links to Contract Violation Errors
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/execution_environment/src/execution/response/tests.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/request_in_prep.rs
Labels: feat, @execution

#1257 chore(IDX): remove AWS creds where not needed
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  gitlab-ci/src/bazel-ci/main.sh
Labels: chore, @idx

#1230 chore(IDX): remove old ci code
  gitlab-ci/tools/gitlab-rerun-pipeline.py
  gitlab-ci/tools/run_mypy
  gitlab-ci/tools/sync-users-to-everyone.sh
  gitlab-ci/tools/sys_path_patch.py
Labels: chore, @idx

#1254 chore(fuzzing): increase maximum timeout for AFL fuzzers from 5s to 20s
  bin/afl_wrapper.sh
Labels: chore, @product-security

#1264 chore(IDX): remove old gitlab ci code
  gitlab-ci/src/dependencies/integration/gitlab/gitlab_api.py
  gitlab-ci/src/dependencies/integration/gitlab/gitlab_pipeline_config.py
  gitlab-ci/src/dependencies/integration/gitlab/gitlab_trivy_finding_notification_handler.py
  gitlab-ci/src/dependencies/integration/gitlab/gitlab_trivy_finding_notification_handler_test.py
Labels: chore, @product-security

#1263 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#1168 feat(ICP-Rosetta): FI-1458 search transaction client
  Cargo.lock
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/client/src/lib.rs
  rs/rosetta-api/icrc1/rosetta/tests/system_tests.rs
  rs/rosetta-api/rosetta_core/src/request_types.rs
  rs/rosetta-api/tests/basic_tests.rs
  rs/rosetta-api/tests/system_tests/common/constants.rs
  rs/rosetta-api/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/tests/system_tests/common/utils.rs
  rs/rosetta-api/tests/system_tests/system_tests.rs
  rs/rosetta-api/tests/system_tests/test_cases/mod.rs
  rs/rosetta-api/tests/system_tests/test_cases/search_transactions.rs
Labels: feat, @finint

#1256 fix: Fix missing log function
  ic-os/components/misc/fetch-property.sh
  ic-os/components/setupos.bzl
Labels: fix, @node

#1221 refactor: add more documentation about design decisions in the quic transport
  rs/p2p/quic_transport/README.adoc
  rs/p2p/quic_transport/src/connection_handle.rs
  rs/p2p/quic_transport/src/connection_manager.rs
  rs/p2p/quic_transport/src/lib.rs
  rs/p2p/quic_transport/src/request_handler.rs
  rs/p2p/quic_transport/src/utils.rs
Labels: refactor, @networking

#1262 chore(IDX): remove old python packages
  gitlab-ci/src/requirements.txt
  gitlab-ci/src/setup.cfg
  requirements.in
  requirements.txt
Labels: chore, @idx, @ic-owners-owners

#1270 chore(IDX): remove old ci code
  gitlab-ci/src/.coveragerc
  gitlab-ci/src/ci.py
  gitlab-ci/src/conftest.py
  gitlab-ci/src/sys_path_patch.py
Labels: chore, @idx

#1265 fix(IDX): remove double '/' in rosetta img path
  rs/tests/src/rosetta_tests/setup.rs
Labels: fix, @idx

#1267 fix: use only one version of ic-certification
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  packages/ic-signature-verification/Cargo.toml
  rs/pocket_ic_server/Cargo.toml
Labels: fix, @idx

#1276 chore: update quinn
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx, @product-security

#1269 chore: Move GenesisTokenCanisterInitPayloadBuilder to rs/nns/test_utils
  rs/nns/gtc/src/lib.rs
  rs/nns/gtc/tests/test.rs
  rs/nns/test_utils/BUILD.bazel
  rs/nns/test_utils/src/common.rs
  rs/nns/test_utils/src/gtc_helpers.rs
  rs/nns/test_utils/src/lib.rs
Labels: chore, @nns-team

#1260 refactor(IDX): move docker login out of before-script
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  gitlab-ci/src/ci-scripts/docker-login.sh
Labels: refactor, @idx

#1282 chore(IDX): add credentials to bazel build no cache
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: chore, @idx

#1272 chore(IDX): unpin python dependencies
  requirements.in
Labels: chore, @ic-owners-owners

#1271 chore: upgrade to latest Universal- and Prometheus-VM images
  rs/tests/driver/src/driver/prometheus_vm.rs
  rs/tests/driver/src/driver/resource.rs
Labels: chore, @idx

#1285 fix(IDX): CI_COMMIT_BRANCH
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#1214 refactor(IDX): Move ci scripts to new folder
  .github/CODEOWNERS
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
  ci/bazel-scripts/diff.sh
  ci/bazel-scripts/main.sh
  ci/scripts/build-determinism.sh
  ci/scripts/commit-lint.sh
  ci/scripts/docker-login.sh
  ci/scripts/lock-generate.sh
  ci/scripts/pre-commit.sh
  ci/scripts/run-build-ic.sh
  ci/scripts/rust-benchmarks.sh
  ci/scripts/rust-lint.sh
  gitlab-ci/ci
Labels: refactor, @idx, @ic-owners-owners

#1290 chore(IDX): remove build-diff
  gitlab-ci/tools/build-diff.sh
Labels: chore, @idx

#1255 chore: don't bound the bouncer API to the Identifiable artifact trait
  rs/artifact_pool/src/ingress_pool.rs
  rs/consensus/src/certification/certifier.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/idkg.rs
  rs/consensus/tests/framework/types.rs
  rs/https_outcalls/consensus/src/gossip.rs
  rs/interfaces/src/p2p/consensus.rs
  rs/p2p/artifact_downloader/src/fetch_artifact/download.rs
  rs/p2p/artifact_downloader/tests/test.rs
  rs/p2p/test_utils/src/consensus.rs
  rs/p2p/test_utils/src/mocks.rs
Labels: chore, @consensus, @networking

#1250 fix(execution): Canister snapshots should include Wasm globals
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
  rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/tip.rs
Labels: fix, @execution, @ic-message-routing-owners, @ic-interface-owners

#1261 chore(IDX): pull images from docker.io
  WORKSPACE.bazel
Labels: chore

#1259 fix(snapshots): Compute the correct subnet available memory after snapshot operations
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
Labels: fix

#771 feat: [CON-1372] Implement the `ArtifactAssembler` for `DownloadStrippedArtifactMessage`
  Cargo.lock
  rs/interfaces/src/p2p/consensus.rs
  rs/p2p/artifact_downloader/BUILD.bazel
  rs/p2p/artifact_downloader/Cargo.toml
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/assembler.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/download.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/metrics.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/mod.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/stripper.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types/rpc.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/types/stripped.rs
  rs/p2p/artifact_downloader/src/lib.rs
  rs/p2p/consensus_manager/src/receiver.rs
  rs/p2p/test_utils/src/mocks.rs
  rs/protobuf/def/types/v1/consensus.proto
  rs/protobuf/generator/src/lib.rs
  rs/protobuf/src/gen/types/types.v1.rs
  rs/types/types/src/batch/ingress.rs
Labels: feat, @consensus, @networking, @ic-interface-owners

#1288 chore: EXC-1708: Remove unused session nonce
  rs/canonical_state/src/traversal.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/tree_hash.rs
  rs/test_utilities/state/src/lib.rs
Labels: chore, @execution, @ic-message-routing-owners, @ic-interface-owners

#1311 fix(IDX): docker login
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#1302 refactor(IDX): update custom ci logic
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
  ci/bazel-scripts/main.sh
  ci/scripts/run-build-ic.sh
Labels: refactor, @idx

#1128 fix(nns-tools): typo correction: wasm_module -> wasm
  testnet/tools/nns-tools/lib/proposals.sh
Labels: fix

#1166 feat(registry): Enforce Node network address-related Registry invariant checks
  rs/registry/canister/src/invariants/endpoint.rs
  rs/registry/canister/src/mutations/prepare_canister_migration.rs
Labels: feat, @nns-team

#1308 fix: Canister Client failing during handshake because of a missing scheme
  rs/canister_client/src/http_client.rs
Labels: fix

#1301 refactor: move the ingress bounce to the ingress manager crate
  rs/artifact_pool/BUILD.bazel
  rs/artifact_pool/Cargo.toml
  rs/artifact_pool/src/ingress_pool.rs
  rs/ingress_manager/src/bouncer.rs
  rs/ingress_manager/src/lib.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: refactor, @consensus, @networking

#1279 docs(nns): Small corrections in nns-tools.
  testnet/tools/nns-tools/README.md
  testnet/tools/nns-tools/lib/proposals.sh
  testnet/tools/nns-tools/list-new-commits.sh
Labels: docs, @nns-team

#1253 feat: [MR-551] Factor input scheduling into separate struct
  rs/protobuf/def/state/queues/v1/queues.proto
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/input_schedule/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/lib.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: feat, @execution, @ic-message-routing-owners, @ic-interface-owners

#1319 fix: Revert "feat(system-api): add `call_cycles_add128_up_to` (#1158)"
  rs/cycles_account_manager/src/lib.rs
  rs/cycles_account_manager/tests/cycles_account_manager.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/src/wasmtime_embedder/system_api_complexity.rs
  rs/embedders/tests/validation.rs
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/src/hypervisor/tests.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/src/query_handler/tests.rs
  rs/interfaces/src/execution_environment.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/request_in_prep.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
  rs/universal_canister/lib/src/universal-canister.wasm.gz
Labels: fix

#1323 chore: upgrade nixpkgs in run-p8s.nix to match the version used in the prometheus-vm
  rs/tests/run-p8s.nix
Labels: chore, @idx

#1322 chore: update query stats log message to be less confusing in PocketIC
  rs/query_stats/src/payload_builder.rs
Labels: chore

#1320 chore(registry): Remove dfn_core::println in 2 places where they are no longer used
  rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs
  rs/registry/canister/src/invariants/endpoint.rs
Labels: chore

#1327 fix(deps): drop release_max_level_debug from slog features
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: fix

#1291 feat(EXC-1715): Canister Backtrace Flag
  rs/config/src/embedders.rs
  rs/embedders/src/wasm_executor.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
  rs/embedders/tests/wasmtime_random_memory_writes.rs
  rs/system_api/src/lib.rs
  rs/system_api/tests/common/mod.rs
  rs/system_api/tests/system_api.rs
  rs/test_utilities/embedders/src/lib.rs
Labels: feat, @execution

#1278 feat(nns): Added is-commit-released.sh to nns-tools.
  testnet/tools/nns-tools/is-commit-released.sh
Labels: feat

#1298 chore(ic-boundary): increase the number of http clients communicating with replica
  ic-os/components/boundary-guestos/etc/systemd/system/ic-boundary.service
Labels: chore, @boundary-node, @node

#728 feat(NODE-1403): Remove upgrade ic-os gz images
  ic-os/defs.bzl
Labels: feat, @node

#1310 chore(IDX): removing gitlab references
  gitlab-ci/tools/repro-check.sh
  ic-os/boundary-guestos/docs/ProberFunding.adoc
  rs/tests/README.md
  rs/tests/src/ckbtc/btc_config.rs
  rs/workload_generator/src/stats.rs
  testnet/README.md
  testnet/tools/nns-tools/README.md
  testnet/tools/nns-tools/test-canister-upgrade.sh
  testnet/tools/nns-tools/test-sns-canister-deployment.sh
  testnet/tools/nns-tools/test-sns-canister-upgrades.sh
Labels: chore, @idx, @dre, @execution, @boundary-node, @nns-team, @node, @cross-chain-team

#1199 feat(NODE-1463): Add cpu field to deployment.json
  ic-os/setupos/data/deployment.json.template
  rs/ic_os/setupos-inject-configuration/src/main.rs
  rs/ic_os/utils/src/deployment.rs
  rs/tests/driver/src/driver/bootstrap.rs
Labels: feat, @idx, @node

#1206 feat(nns): Registry get_changes_since allows only self-authenticating and opaque callers.
  Cargo.lock
  rs/nns/integration_tests/src/registry_get_changes_since.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/canister/canister.rs
  rs/registry/transport/proto/ic_registry_transport/pb/v1/transport.proto
  rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs
  rs/types/base_types/BUILD.bazel
  rs/types/base_types/Cargo.toml
  rs/types/base_types/src/lib.rs
  rs/types/base_types/src/principal_id.rs
Labels: feat, @nns-team, @ic-interface-owners

#1227 feat: guest-os qualification system test
  .github/CODEOWNERS
  Cargo.lock
  rs/tests/BUILD.bazel
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/Cargo.toml
  rs/tests/consensus/consensus_performance.rs
  rs/tests/consensus/utils/BUILD.bazel
  rs/tests/consensus/utils/Cargo.toml
  rs/tests/consensus/utils/src/lib.rs
  rs/tests/consensus/utils/src/performance.rs
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/BUILD.bazel
  rs/tests/dre/Cargo.toml
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/dre/utils/BUILD.bazel
  rs/tests/dre/utils/Cargo.toml
  rs/tests/dre/utils/defs.rs
  rs/tests/dre/utils/lib.rs
  rs/tests/dre/utils/steps/ensure_elected_version.rs
  rs/tests/dre/utils/steps/mod.rs
  rs/tests/dre/utils/steps/retire_elected_version.rs
  rs/tests/dre/utils/steps/update_subnet_type.rs
  rs/tests/dre/utils/steps/workload.rs
  rs/tests/dre/utils/steps/xnet.rs
  rs/tests/driver/src/driver/test_env.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/nns.rs
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/src/message_routing/global_reboot_test.rs
  rs/tests/src/message_routing/xnet_slo_test.rs
  rs/tests/src/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/testing_verification/testnets/BUILD.bazel
  rs/tests/testing_verification/testnets/Cargo.toml
  rs/tests/testing_verification/testnets/from_config.rs
Labels: feat, @idx, @consensus, @nns-team, @ic-message-routing-owners, @ic-owners-owners

#1318 release(nns): Change to nns release script to verify arg_hash
  testnet/tools/nns-tools/lib/proposals.sh
Labels: @nns-team

#1316 chore(nns): remove unused method from NeuronStore
  rs/nns/governance/src/neuron/mod.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Labels: chore, @nns-team

#870 refactor(nervous_system): Remove most usages of hotkey_principal
  rs/nervous_system/common/src/lib.rs
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neurons_fund.rs
  rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/sns/audit/src/lib.rs
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/sns/swap/src/swap.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/common/mod.rs
  rs/sns/swap/tests/swap.rs
Labels: refactor, @idx, @nns-team, @finint

#1295 chore(sns): Duplicate ClaimSwapNeuronsRequest into Swap, so the version in SNS Governance can be changed independently
  rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto
  rs/sns/swap/protobuf_generator/src/lib.rs
  rs/sns/swap/src/clients.rs
  rs/sns/swap/src/gen/ic_sns_swap.pb.v1.rs
  rs/sns/swap/src/swap.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/common/doubles.rs
  rs/sns/swap/tests/swap.rs
Labels: chore, @nns-team

#1236 chore(cmc): Simplify get_next_multiply_of
  rs/nns/cmc/src/exchange_rate_canister.rs
Labels: chore

#1237 fix(sns): Avoid unnecessary neuron copies for those not ready to disburse yet
  rs/sns/governance/src/governance.rs
Labels: fix

#1326 chore(IDX): move artifacts to new folder
  bazel/BUILD.bazel
  bazel/conf/.bazelrc.build
  ci/src/artifacts/BUILD.bazel
  ci/src/artifacts/collect_core_dumps.sh
  ci/src/artifacts/find-build-id.sh
  ci/src/artifacts/newest_sha_with_disk_image.sh
  ci/src/artifacts/openssl-sign.sh
  ci/src/artifacts/openssl-verify.sh
  ci/src/artifacts/rclone_download.py
  ci/src/artifacts/rclone_upload.py
  ci/src/artifacts/trusted-builders-public.key
  ci/src/artifacts/upload.bash.template
  ci/src/artifacts/upload.bzl
  ic-os/defs.bzl
  ic-os/dev-tools/get-artifacts.sh
  publish/binaries/BUILD.bazel
  publish/canisters/BUILD.bazel
  rs/backup/upgrade.sh
  rs/tests/README_NEW.md
  testnet/README.md
  testnet/tools/build-guestos-configs.sh
  testnet/tools/icos_collect_debug_info.py
  testnet/tools/icos_deploy.sh
Labels: chore, @idx, @dre, @consensus, @node

#1266 feat: Add more metrics for canister snapshots usage
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/execution_environment/tests/execution_test.rs
  rs/replicated_state/src/canister_snapshots.rs
Labels: feat, @ic-message-routing-owners

#1307 feat(IC-1579): add TLA instrumentation
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  WORKSPACE.bazel
  rs/tla_instrumentation/BUILD.bazel
  rs/tla_instrumentation/local_key/Cargo.toml
  rs/tla_instrumentation/local_key/src/lib.rs
  rs/tla_instrumentation/tla/Counter.tla
  rs/tla_instrumentation/tla/Counter_Apalache.tla
  rs/tla_instrumentation/tla/Variants.tla
  rs/tla_instrumentation/tla_instrumentation/Cargo.toml
  rs/tla_instrumentation/tla_instrumentation/src/checker.rs
  rs/tla_instrumentation/tla_instrumentation/src/lib.rs
  rs/tla_instrumentation/tla_instrumentation/src/tla_state.rs
  rs/tla_instrumentation/tla_instrumentation/src/tla_value.rs
  rs/tla_instrumentation/tla_instrumentation/tests/structs.rs
  rs/tla_instrumentation/tla_instrumentation_proc_macros/Cargo.toml
  rs/tla_instrumentation/tla_instrumentation_proc_macros/src/lib.rs
  rs/tla_instrumentation/tla_instrumentation_proc_macros/src/main.rs
Labels: feat, @idx, @ic-interface-owners, @ic-owners-owners

#1340 fix(IDX): hourly schedule BAZEL_TARGET
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: fix, @idx

#1338 refactor: Redo the ValidateEq annotations for CanisterQueues
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
Labels: refactor

#746 feat(ICRC-Ledger): add ability to read from memory manager in post_upgrade
  Cargo.lock
  rs/rosetta-api/icp_ledger/ledger/BUILD.bazel
  rs/rosetta-api/icp_ledger/ledger/Cargo.toml
  rs/rosetta-api/icp_ledger/ledger/tests/tests.rs
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/ledger/BUILD.bazel
  rs/rosetta-api/icrc1/ledger/Cargo.toml
  rs/rosetta-api/icrc1/ledger/sm-tests/BUILD.bazel
  rs/rosetta-api/icrc1/ledger/sm-tests/Cargo.toml
  rs/rosetta-api/icrc1/ledger/sm-tests/src/in_memory_ledger.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/metrics.rs
  rs/rosetta-api/icrc1/ledger/src/lib.rs
  rs/rosetta-api/icrc1/ledger/src/main.rs
  rs/rosetta-api/icrc1/ledger/tests/tests.rs
Labels: feat, @finint

#1328 feat(IDX): support eternal system-test-based testnets
  rs/tests/driver/src/driver/farm.rs
  rs/tests/driver/src/driver/group.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/driver/test_setup.rs
  rs/tests/ict/cmd/testnetCreateCmd.go
  rs/tests/src/mainnet_tests/mainnet_api.rs
Labels: feat, @idx

#1342 chore(IDX): reorganize and rename some workflows
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only-cov.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/ci-pr-title-validation.yml
Labels: chore, @idx

#1306 refactor: unify and group together the creation of the bouncers and assemblers
  rs/consensus/src/certification.rs
  rs/consensus/src/certification/certifier.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/idkg.rs
  rs/consensus/tests/framework/driver.rs
  rs/consensus/tests/framework/execution.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/framework/types.rs
  rs/consensus/tests/payload.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: refactor, @consensus, @networking

#1239 feat(ICP-Rosetta): FI:1465 icp rosetta client transfers
  Cargo.lock
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/Cargo.toml
  rs/rosetta-api/client/BUILD.bazel
  rs/rosetta-api/client/Cargo.toml
  rs/rosetta-api/client/src/lib.rs
  rs/rosetta-api/icrc1/rosetta/client/src/lib.rs
  rs/rosetta-api/icrc1/rosetta/tests/system_tests.rs
  rs/rosetta-api/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/tests/system_tests/common/utils.rs
  rs/rosetta-api/tests/system_tests/test_cases/mod.rs
  rs/rosetta-api/tests/system_tests/test_cases/transfers.rs
Labels: feat

#1345 refactor: [MR-551] Renaming and minor cleanup before new CanisterQueues
  rs/execution_environment/src/scheduler.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/state_machine.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/message_pool/tests.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: refactor, @execution, @ic-message-routing-owners

#1351 chore(IDX): remove install nsc step
  .github/workflows/test-namespace-darwin.yaml
Labels: chore, @idx

#1337 fix: caller of canister http composite query transform
  rs/execution_environment/src/query_handler/query_cache.rs
  rs/execution_environment/src/query_handler/query_context.rs
  rs/rust_canisters/proxy_canister/src/main.rs
  rs/tests/networking/canister_http_correctness_test.rs
  rs/types/types/src/messages/http.rs
Labels: fix, @idx, @execution, @networking, @ic-interface-owners

#1341 chore: Update Base Image Refs [2024-09-05-0807]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#1348 chore: [MR-550] Drop `ResponsePlaceholder`
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/message_pool/tests.rs
Labels: chore

#1217 chore(PocketIC): switch ic-http-gateway from rev to tag 0.1.0-b0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/pocket_ic_server/Cargo.toml
Labels: chore, @idx

#1354 fix(IDX): daily schedule
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: fix, @idx

#1324 refactor(IDX): update main.sh logic
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/bazel-scripts/main.sh
  ci/scripts/run-build-ic.sh
Labels: refactor, @idx

#1362 fix(IDX): move logic in bazel main script
  ci/bazel-scripts/main.sh
Labels: fix

#1361 fix: Fix brown paper bag bug in `InputSchedule`
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
Labels: fix, @execution

#1297 chore(sns): Remove neuron_parameters from ClaimSwapNeuronsRequest on SNS Governance's side
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/tests/governance.rs
Labels: chore, @idx, @consensus, @product-security, @execution, @networking, @ic-message-routing-owners, @finint, @ic-owners-owners

#1336 chore(ic-admin): Use InstallCode by default for canister upgrades, and always use explicit action types for stopping/starting
  rs/registry/admin/src/main.rs
Labels: chore

#1314 fix(nervous_system): Fix a bug with advancing buf
  rs/nervous_system/common/src/dfn_core_stable_mem_utils.rs
  rs/nervous_system/common/src/lib.rs
  rs/nervous_system/common/src/memory_manager_upgrade_storage.rs
Labels: fix

#1357 feat(fuzzing): enable wasm64 feature for wasm fuzzers
  rs/embedders/fuzz/src/compile.rs
  rs/embedders/fuzz/src/differential.rs
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/fuzz/src/wasmtime.rs
Labels: feat, @execution

#1335 feat: running qualification to daily schedule
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-generate-ci.yml
  .github/workflows/release-testing.yml
Labels: feat, @idx

#1280 test(nns): Updated mainnet-canisters.bzl.
  mainnet-canisters.bzl
  rs/nns/sns-wasm/canister/canister.rs
  rs/nns/sns-wasm/src/sns_wasm.rs
  rs/nns/sns-wasm/tests/add_wasm.rs
Labels: test, @nns-team

#1231 chore(nervous_system): Update mainnet-canisters.bzl
  mainnet-canisters.bzl
Labels: chore

#1366 refactor(nns): Eliminate `ExecutedCreateServiceNervousSystemProposal`
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/proposals/create_service_nervous_system.rs
  rs/nns/governance/tests/governance.rs
  rs/sns/cli/src/lib.rs
Labels: refactor, @nns-team

#1332 feat(sns): Postpone enforcing the 100K SNS neuron limit till swap begins
  rs/nervous_system/integration_tests/tests/constraints_dependencies.rs
  rs/sns/init/src/lib.rs
Labels: feat, @nns-team

#1317 refactor(nns): Some refactoring on how neuron subaccount addresses are calculated
  rs/nervous_system/common/src/ledger.rs
  rs/nervous_system/common/src/tests.rs
  rs/nns/governance/src/governance.rs
Labels: refactor, @nns-team

#1363 test(consensus): Output e2e latency in the consensus performance test
  rs/tests/consensus/utils/src/performance.rs
Labels: test, @idx, @consensus

#1358 chore(PocketIC): Reference compatibility matrix in README.md
  packages/pocket-ic/README.md
Labels: chore, @pocket-ic

#1339 perf: EXC-1638: Add baseline and replace snapshot benchmarks
  rs/execution_environment/benches/management_canister/MANAGEMENT_CANISTER.md
  rs/execution_environment/benches/management_canister/canister_snapshots.rs
  rs/execution_environment/benches/management_canister/run_snapshot_benchmarks_forever.sh
Labels: perf, @execution

#1356 chore: improve canister log memory usage metric buckets
  rs/execution_environment/src/metrics.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/execution_environment/tests/canister_logging.rs
Labels: chore, @execution

#1350 chore: move down the construction of the Membership struct
  rs/consensus/src/consensus.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/integration.rs
  rs/consensus/tests/payload.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: chore, @consensus, @networking

#1371 test(orchestrator): [CON-1341] Inline some orchestrator system tests
  Cargo.lock
  rs/tests/Cargo.toml
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/Cargo.toml
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/orchestrator/Cargo.toml
  rs/tests/consensus/orchestrator/node_assign_test.rs
  rs/tests/consensus/orchestrator/rotate_ecdsa_idkg_key_test.rs
  rs/tests/consensus/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/consensus/orchestrator/unstuck_subnet_test.rs
  rs/tests/consensus/subnet_splitting_test.rs
  rs/tests/src/orchestrator/mod.rs
  rs/tests/src/orchestrator/node_assign_test.rs
  rs/tests/src/orchestrator/rotate_ecdsa_idkg_key.rs
  rs/tests/src/orchestrator/subnet_splitting.rs
  rs/tests/src/orchestrator/unassigned_node_upgrade_test.rs
  rs/tests/src/orchestrator/unstuck_subnet_test.rs
Labels: test, @idx, @consensus

#1344 docs: NET-1449
  rs/p2p/quic_transport/README.adoc
Labels: docs, @networking

#1248 feat: load number of pages from disk in merge strategy
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/replicated_state/BUILD.bazel
  rs/replicated_state/Cargo.toml
  rs/replicated_state/src/page_map/storage.rs
  rs/replicated_state/src/page_map/storage/tests.rs
  rs/replicated_state/src/page_map/test_utils.rs
  rs/state_layout/src/state_layout.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/tip.rs
Labels: feat, @idx, @execution, @ic-message-routing-owners

#1360 chore: upgrade the xnet endpoint to hyper >1
  Cargo.lock
  rs/async_utils/src/lib.rs
  rs/http_endpoints/metrics/src/lib.rs
  rs/http_endpoints/public/src/lib.rs
  rs/replica/src/setup_ic_stack.rs
  rs/xnet/endpoint/BUILD.bazel
  rs/xnet/endpoint/Cargo.toml
  rs/xnet/endpoint/src/lib.rs
  rs/xnet/endpoint/src/tests.rs
Labels: chore, @networking, @ic-message-routing-owners

#1368 fix(cmc): Merging CMC hotfix back to master
  Cargo.lock
  rs/nns/cmc/cmc.did
  rs/nns/cmc/src/lib.rs
  rs/nns/cmc/src/main.rs
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/tests/Cargo.toml
  rs/tests/common.bzl
  rs/tests/src/nns_tests/cycles_minting.rs
Labels: fix, @idx, @nns-team

#1374 chore: upgrade tokio, quinn and libc
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore, @idx

#1364 fix(nns): Fix a flaky test by increasing the sleep duration
  rs/nervous_system/clients/src/management_canister_client/tests.rs
Labels: fix

#879 feat: [MR-551] Support for best-effort messages in `CanisterQueues`
  rs/messaging/src/state_machine.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
  rs/replicated_state/tests/system_state.rs
Labels: feat, @execution, @ic-message-routing-owners, @ic-interface-owners

#1359 refactor(IDX): rename and remove env vars
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/ci-pr-title-validation.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
  bazel/candid.bzl
  bazel/candid_integration_tests/candid_integration_tests.py
  ci/bazel-scripts/diff.sh
  ci/bazel-scripts/main.sh
  ci/scripts/commit-lint.sh
  ci/src/checks/candid_changes_are_backwards_compatible.py
  ci/src/git_changes/git_changes.py
Labels: refactor, @idx

#1355 chore(cketh): proposals to update ckETH ledger suite settings
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/cketh_archive_settings_2024_09_06.md
  rs/ethereum/cketh/mainnet/cketh_index_settings_2024_09_06.md
  rs/ethereum/cketh/mainnet/cketh_ledger_settings_2024_09_06.md
Labels: chore, @cross-chain-team

#1385 test: Less aggressive LSMT proptest
  rs/state_manager/tests/state_manager.rs
Labels: test

#1383 fix(system-tests-k8s): aws variable
  .github/workflows/system-tests-k8s.yml
  rs/tests/testing_verification/BUILD.bazel
Labels: fix, @idx

#1382 chore(system-tests-k8s): shorter VM name
  rs/tests/src/rosetta_tests/tests/derive.rs
  rs/tests/src/rosetta_tests/tests/list_known_neurons.rs
  rs/tests/src/rosetta_tests/tests/list_neurons.rs
  rs/tests/src/rosetta_tests/tests/make_transaction.rs
  rs/tests/src/rosetta_tests/tests/network.rs
  rs/tests/src/rosetta_tests/tests/neuron_disburse.rs
  rs/tests/src/rosetta_tests/tests/neuron_dissolve.rs
  rs/tests/src/rosetta_tests/tests/neuron_follow.rs
  rs/tests/src/rosetta_tests/tests/neuron_hotkey.rs
  rs/tests/src/rosetta_tests/tests/neuron_info.rs
  rs/tests/src/rosetta_tests/tests/neuron_maturity.rs
  rs/tests/src/rosetta_tests/tests/neuron_spawn.rs
  rs/tests/src/rosetta_tests/tests/neuron_staking.rs
  rs/tests/src/rosetta_tests/tests/neuron_voting.rs
Labels: chore, @idx

#1388 chore(ic-backup): Increase timeout for downloading binaries from 15s to 60s
  rs/recovery/src/file_sync_helper.rs
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup_manager_test.rs
Labels: chore, @idx, @consensus

#1390 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#1379 refactor: Drop `CanisterQueueItem` enum
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
Labels: refactor, @ic-message-routing-owners

#1398 chore(nns): Increase random error for protobuf methods to 30%
  rs/nns/governance/canister/canister.rs
Labels: chore

#1367 chore(nns): reduce logging in tests
  rs/nervous_system/neurons_fund/src/lib.rs
  rs/nervous_system/neurons_fund/src/polynomial_matching_function_tests.rs
  rs/nns/governance/src/governance/test_data.rs
  rs/nns/governance/src/neurons_fund.rs
  rs/nns/governance/src/neurons_fund/neurons_fund_anonymization_tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/sns/swap/tests/swap.rs
Labels: chore, @nns-team

#1312 feat(ckerc20): Add already installed canisters to ledger suite orchestrator
  Cargo.lock
  rs/ethereum/ledger-suite-orchestrator/BUILD.bazel
  rs/ethereum/ledger-suite-orchestrator/Cargo.toml
  rs/ethereum/ledger-suite-orchestrator/ledger_suite_orchestrator.did
  rs/ethereum/ledger-suite-orchestrator/src/candid/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/dashboard/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/dashboard/tests.rs
  rs/ethereum/ledger-suite-orchestrator/src/lifecycle/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/main.rs
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/test_fixtures.rs
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/tests.rs
  rs/ethereum/ledger-suite-orchestrator/src/state/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/state/tests.rs
  rs/ethereum/ledger-suite-orchestrator/templates/dashboard.html
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
  rs/ethereum/ledger-suite-orchestrator/tests/tests.rs
  rs/state_machine_tests/src/lib.rs
  rs/tests/src/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
Labels: feat, @idx, @pocket-ic, @ic-message-routing-owners, @cross-chain-team

#1185 chore(RUN): Upgrade wasmtime to 24
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
Labels: chore, @idx

#1386 feat(IC-1579): pull out canister-based implementations of Ledger/CMC
  Cargo.lock
  rs/nervous_system/canisters/BUILD.bazel
  rs/nervous_system/canisters/Cargo.toml
  rs/nervous_system/canisters/src/cmc.rs
  rs/nervous_system/canisters/src/ledger.rs
  rs/nervous_system/canisters/src/lib.rs
  rs/nervous_system/common/src/cmc.rs
  rs/nervous_system/common/src/ledger.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/canister/canister.rs
  rs/registry/canister/Cargo.toml
  rs/rust_canisters/dfn_core/BUILD.bazel
  rs/rust_canisters/dfn_protobuf/BUILD.bazel
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/canister/canister.rs
  rs/sns/swap/BUILD.bazel
  rs/sns/swap/Cargo.toml
  rs/sns/swap/canister/canister.rs
  rs/sns/swap/src/types.rs
Labels: feat, @nns-team

#1387 fix(cketh): Retry HTTPs outcalls
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/state.rs
Labels: fix, @cross-chain-team

#1389 fix(PocketIC): support IP addresses in frontend URLs to PocketIC HTTP gateway
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
Labels: fix

#1409 chore: Update Base Image Refs [2024-09-10-1216]
  ic-os/boundary-guestos/context/docker-base.prod
  ic-os/guestos/context/docker-base.dev
  ic-os/guestos/context/docker-base.prod
  ic-os/hostos/context/docker-base.dev
  ic-os/hostos/context/docker-base.prod
  ic-os/setupos/context/docker-base.dev
  ic-os/setupos/context/docker-base.prod
Labels: chore

#1411 fix: revert the old error string when outcall response is bigger than the limit
  rs/https_outcalls/adapter/src/rpc_server.rs
  rs/https_outcalls/adapter/tests/server_test.rs
Labels: fix, @networking

#1406 chore: Update granularity of executable canisters histogram
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
Labels: chore

#1416 chore(nervous-system): Update mannet-canisters.bzl
  mainnet-canisters.bzl
Labels: chore

#1365 feat(NODE-1465): Add mgmt_mac field to deployment.json
  ic-os/setupos/data/deployment.json.template
  rs/ic_os/hostos_tool/src/main.rs
  rs/ic_os/network/src/info.rs
  rs/ic_os/network/src/lib.rs
  rs/ic_os/network/src/mac_address.rs
  rs/ic_os/setupos-inject-configuration/src/main.rs
  rs/ic_os/setupos_tool/src/main.rs
  rs/ic_os/utils/src/deployment.rs
Labels: feat, @node

#1399 chore: Choose new dummy URL
  ic-os/setupos/defs.bzl
  rs/ic_os/utils/src/deployment.rs
Labels: chore

#1422 fix(NODE-1465): Update fetch-mgmt-mac
  ic-os/components/hostos-scripts/misc/fetch-mgmt-mac.sh
Labels: fix, @node

#510 chore: [S3_UPLOAD] support /v3/call in nginx
  ic-os/components/boundary-guestos/etc/nginx/conf.d/001-rosetta-nginx.conf
  ic-os/components/boundary-guestos/etc/nginx/conf.d/002-mainnet-nginx.conf
Labels: chore, @boundary-node, @node

#1349 chore(boundary): increase the number of duration buckets in metrics
  rs/boundary_node/ic_boundary/src/metrics.rs
Labels: chore, @boundary-node

#662 chore(drun): Lift 8 GB memory boundary from `drun`
  rs/drun/src/message.rs
Labels: chore, @languages

#1380 feat: [MR-552] Define `RejectCode::SysUnknown` and error codes
  rs/canonical_state/src/encoding/tests/conversion.rs
  rs/canonical_state/tests/hash_tree.rs
  rs/execution_environment/src/history.rs
  rs/protobuf/def/state/ingress/v1/ingress.proto
  rs/protobuf/def/types/v1/errors.proto
  rs/protobuf/src/gen/bitcoin/types.v1.rs
  rs/protobuf/src/gen/state/state.ingress.v1.rs
  rs/protobuf/src/gen/state/types.v1.rs
  rs/protobuf/src/gen/types/state.ingress.v1.rs
  rs/protobuf/src/gen/types/types.v1.rs
  rs/types/error_types/src/lib.rs
  rs/types/types/src/exhaustive.rs
Labels: feat, @consensus, @execution, @ic-message-routing-owners, @ic-interface-owners

#1435 chore: Add formal-models group as co-owners of tla_instrumentation
  .github/CODEOWNERS
Labels: chore, @ic-owners-owners

#1273 feat(BOUN-1009): ic-boundary: upgrade axum to 0.7 [RUN_ALL_BAZEL_TARGETS]
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_balance_exporter/Cargo.toml
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/benches/perf.rs
  rs/boundary_node/ic_boundary/src/acme.rs
  rs/boundary_node/ic_boundary/src/bouncer.rs
  rs/boundary_node/ic_boundary/src/bouncer/firewall.rs
  rs/boundary_node/ic_boundary/src/cache.rs
  rs/boundary_node/ic_boundary/src/cache/test.rs
  rs/boundary_node/ic_boundary/src/check.rs
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/configuration.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/dns.rs
  rs/boundary_node/ic_boundary/src/dns/test.rs
  rs/boundary_node/ic_boundary/src/geoip.rs
  rs/boundary_node/ic_boundary/src/http.rs
  rs/boundary_node/ic_boundary/src/lib.rs
  rs/boundary_node/ic_boundary/src/main.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/rate_limiting.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/test.rs
  rs/boundary_node/ic_boundary/src/retry.rs
  rs/boundary_node/ic_boundary/src/retry/test.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
  rs/boundary_node/ic_boundary/src/socket.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/ic_boundary/src/tls.rs
  rs/boundary_node/ic_boundary/src/tls/test.rs
  rs/boundary_node/ic_boundary/src/tls_verify.rs
  rs/boundary_node/ic_boundary/src/tls_verify/test.rs
  rs/orchestrator/src/boundary_node.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/tests/src/boundary_nodes/api_boundary_nodes_integration.rs
Labels: feat, @idx, @consensus, @boundary-node, @pocket-ic

#1438 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore

#1428 chore: remove obsolete feature flags for tSchnorr management canister API
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: chore, @execution

#1439 fix(PocketIC): drop PocketIC library timeout
  packages/pocket-ic/src/lib.rs
Labels: fix

#1430 fix(cketh): Proposal to replace Ankr in the ckETH minter
  rs/ethereum/cketh/docs/proposals.adoc
  rs/ethereum/cketh/mainnet/minter_upgrade_2024_09_11.md
Labels: fix

#1405 fix(ICRC-1 Ledger): add effective subaccount to ICRC-21
  packages/icrc-ledger-types/src/icrc21/lib.rs
  rs/rosetta-api/icrc1/ledger/sm-tests/src/lib.rs
Labels: fix, @finint

#1381 feat(PocketIC): dashboard endpoint in PocketIC HTTP gateway
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat

#1369 chore(PocketIC): make HTTP gateway termination into debug log
  rs/pocket_ic_server/src/state_api/state.rs
Labels: chore

#1284 fix(PocketIC): PocketIC server restart when using PocketIC library
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/tests/restart.rs
Labels: fix, @pocket-ic

#1296 chore(ICP-Rosetta): FI-1467 remove basic tests smoke test
  Cargo.lock
  rs/rosetta-api/BUILD.bazel
  rs/rosetta-api/client/src/lib.rs
  rs/rosetta-api/icp_ledger/rosetta-integration-tests/tests/tests.rs
  rs/rosetta-api/icrc1/test_utils/src/lib.rs
  rs/rosetta-api/rosetta_core/BUILD.bazel
  rs/rosetta-api/rosetta_core/Cargo.toml
  rs/rosetta-api/rosetta_core/src/identifiers.rs
  rs/rosetta-api/rosetta_core/src/request_types.rs
  rs/rosetta-api/runner/src/lib.rs
  rs/rosetta-api/tests/basic_tests.rs
  rs/rosetta-api/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/tests/system_tests/common/utils.rs
  rs/rosetta-api/tests/system_tests/test_cases/account_balances.rs
  rs/rosetta-api/tests/system_tests/test_cases/block_synchronization.rs
  rs/rosetta-api/tests/system_tests/test_cases/construction.rs
  rs/rosetta-api/tests/system_tests/test_cases/mempool.rs
  rs/rosetta-api/tests/system_tests/test_cases/mod.rs
  rs/rosetta-api/tests/system_tests/test_cases/network.rs
  rs/rosetta-api/tests/system_tests/test_cases/transfers.rs
Labels: chore, @finint

#1431 chore: add felipe.sodre as testnet admin
  testnet/config/ssh_authorized_keys/admin
Labels: chore

#1353 chore(EXC-1721): Backtrace Test Canister
  .github/CODEOWNERS
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/canisters.bzl
  bazel/external_crates.bzl
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/tests/backtraces.rs
  rs/rust_canisters/backtrace_canister/BUILD.bazel
  rs/rust_canisters/backtrace_canister/Cargo.toml
  rs/rust_canisters/backtrace_canister/README.md
  rs/rust_canisters/backtrace_canister/backtrace_canister.did
  rs/rust_canisters/backtrace_canister/src/main.rs
Labels: chore, @idx, @execution, @nns-team

#1402 refactor: Adjust the naming from the HttpsOutcalls service definition
  rs/https_outcalls/adapter/src/config.rs
  rs/https_outcalls/adapter/src/lib.rs
  rs/https_outcalls/adapter/src/rpc_server.rs
  rs/https_outcalls/adapter/tests/server_test.rs
  rs/https_outcalls/client/src/client.rs
  rs/https_outcalls/service/BUILD.bazel
  rs/https_outcalls/service/build.rs
  rs/https_outcalls/service/proto/https_outcalls_service/v1/proto.proto
  rs/https_outcalls/service/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: refactor, @networking, @pocket-ic

#1281 feat(PocketIC): mock additional canister HTTP outcall responses [override-didc-check]
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/tests/test_canister.did
  packages/pocket-ic/tests/test_canister.rs
  packages/pocket-ic/tests/tests.rs
  rs/bitcoin/kyt/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @pocket-ic, @ic-message-routing-owners, @cross-chain-team

#1429 fix(ckerc20): bug in renaming field
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/test_fixtures.rs
  rs/ethereum/ledger-suite-orchestrator/src/state/mod.rs
  rs/ethereum/ledger-suite-orchestrator/src/state/tests.rs
Labels: fix, @cross-chain-team

#1447 revert: 5d25ae6b6c6daac78c580c5fba5a98927fc9408e
  Cargo.lock
  rs/async_utils/src/lib.rs
  rs/http_endpoints/metrics/src/lib.rs
  rs/http_endpoints/public/src/lib.rs
  rs/replica/src/setup_ic_stack.rs
  rs/xnet/endpoint/BUILD.bazel
  rs/xnet/endpoint/Cargo.toml
  rs/xnet/endpoint/src/lib.rs
  rs/xnet/endpoint/src/tests.rs
Labels: revert, @networking, @ic-message-routing-owners

#1394 refactor(NODE-1467): Organize rs/ic_os
  Cargo.toml
  ic-os/defs.bzl
  ic-os/dev-tools/bare_metal_deployment/README.md
  ic-os/dev-tools/bare_metal_deployment/tools.bzl
  ic-os/docs/Network-Configuration.adoc
  ic-os/guestos/README.adoc
  rs/BUILD.bazel
  rs/ic_os/build_tools/dflate/BUILD.bazel
  rs/ic_os/build_tools/dflate/Cargo.toml
  rs/ic_os/build_tools/dflate/README.md
  rs/ic_os/build_tools/dflate/src/lib.rs
  rs/ic_os/build_tools/dflate/src/main.rs
  rs/ic_os/build_tools/dflate/src/tar_util.rs
  rs/ic_os/build_tools/dflate/src/types.rs
  rs/ic_os/build_tools/diroid/BUILD.bazel
  rs/ic_os/build_tools/diroid/Cargo.toml
  rs/ic_os/build_tools/diroid/README.md
  rs/ic_os/build_tools/diroid/src/main.rs
  rs/ic_os/build_tools/inject_files/BUILD.bazel
  rs/ic_os/build_tools/inject_files/Cargo.toml
  rs/ic_os/build_tools/inject_files/src/main.rs
  rs/ic_os/build_tools/partition_tools/BUILD.bazel
  rs/ic_os/build_tools/partition_tools/Cargo.toml
  rs/ic_os/build_tools/partition_tools/src/ext.rs
  rs/ic_os/build_tools/partition_tools/src/fat.rs
  rs/ic_os/build_tools/partition_tools/src/lib.rs
  rs/ic_os/build_tools/partition_tools/src/partition.rs
  rs/ic_os/dev_test_tools/deterministic_ips/BUILD.bazel
  rs/ic_os/dev_test_tools/deterministic_ips/Cargo.toml
  rs/ic_os/dev_test_tools/deterministic_ips/src/lib.rs
  rs/ic_os/dev_test_tools/deterministic_ips/src/main.rs
  rs/ic_os/dev_test_tools/launch-single-vm/BUILD.bazel
  rs/ic_os/dev_test_tools/launch-single-vm/Cargo.toml
  rs/ic_os/dev_test_tools/launch-single-vm/src/main.rs
  rs/ic_os/dev_test_tools/setupos-disable-checks/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-disable-checks/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-disable-checks/src/main.rs
  rs/ic_os/dev_test_tools/setupos-inject-configuration/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-inject-configuration/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-inject-configuration/src/main.rs
  rs/ic_os/os_tools/guestos_tool/BUILD.bazel
  rs/ic_os/os_tools/guestos_tool/Cargo.toml
  rs/ic_os/os_tools/guestos_tool/src/generate_network_config.rs
  rs/ic_os/os_tools/guestos_tool/src/main.rs
  rs/ic_os/os_tools/guestos_tool/src/node_gen.rs
  rs/ic_os/os_tools/guestos_tool/src/prometheus_metric.rs
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/os_tools/hostos_tool/Cargo.toml
  rs/ic_os/os_tools/hostos_tool/src/main.rs
  rs/ic_os/os_tools/setupos_tool/BUILD.bazel
  rs/ic_os/os_tools/setupos_tool/Cargo.toml
  rs/ic_os/os_tools/setupos_tool/src/main.rs
  rs/ic_os/release/BUILD.bazel
  rs/tests/Cargo.toml
  rs/tests/common.bzl
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/system_tests.bzl
  toolchains/sysimage/toolchain.bzl
Labels: refactor, @idx, @node, @ic-interface-owners

#1401 feat: Reduce slice limit for install_code messages in system subnets
  rs/config/src/subnet_config.rs
Labels: feat, @execution

#1377 chore(ic-admin): Keep `--use-explicit-action-type` in ic-admin
  rs/registry/admin/src/main.rs
Labels: chore

#1333 refactor(registry): Refactor get_changes_since.
  rs/registry/canister/canister/canister.rs
Labels: refactor, @nns-team

#1424 chore(cmc): Clean up the CMC state migration code
  rs/nns/cmc/src/main.rs
Labels: chore

#1425 chore(nns): Remove the flag to enable new topics
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/governance/src/proposals/stop_or_start_canister.rs
  rs/nns/governance/src/proposals/update_canister_settings.rs
Labels: chore

#1437 chore: RUN-988: Fix System API benchmarks
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/benches/system_api/diff-old-vs-new.sh
  rs/execution_environment/benches/system_api/execute_inspect_message.rs
  rs/execution_environment/benches/system_api/execute_update.rs
Labels: chore, @execution

#1450 fix(schedule-hourly): env var
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: fix, @idx

#1453 chore: Update Mainnet IC revisions file
  testnet/mainnet_revisions.json
Labels: chore, @dre, @consensus
