Repository dfinity/ic, pull requests merged in 2025-08, with the labels that each got.

#6082 chore: [MR-699] Move Proto Conversions in Replicated State to own Files
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/replicated_state/src/canister_state/execution_state/proto.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/input_schedule.rs
  rs/replicated_state/src/canister_state/queues/input_schedule/proto.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/message_pool/proto.rs
  rs/replicated_state/src/canister_state/queues/message_pool/tests.rs
  rs/replicated_state/src/canister_state/queues/proto.rs
  rs/replicated_state/src/canister_state/queues/queue.rs
  rs/replicated_state/src/canister_state/queues/queue/proto.rs
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager/proto.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager/tests.rs
  rs/replicated_state/src/canister_state/system_state/proto.rs
  rs/replicated_state/src/canister_state/system_state/task_queue.rs
  rs/replicated_state/src/canister_state/system_state/task_queue/proto.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store/proto.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/proto.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager/proto.rs
  rs/replicated_state/src/metadata_state/tests.rs
Labels: chore, @execution, @ic-message-routing-owners

#6131 chore: Mark test as long
  rs/tests/execution/BUILD.bazel
Labels: chore, @execution

#6117 chore: Increase total test timeout for `xnet_compatibility` test
  rs/tests/message_routing/xnet/xnet_compatibility.rs
Labels: chore, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#6056 chore: Use (N)IDkg specific `MasterPublicKeyId`s where possible
  rs/consensus/dkg/src/utils.rs
  rs/consensus/idkg/src/lib.rs
  rs/consensus/idkg/src/utils.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/execution_environment/src/scheduler/threshold_signatures.rs
  rs/interfaces/src/execution_environment.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager/proto.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/state_machine_tests/src/lib.rs
  rs/test_utilities/consensus/src/idkg.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/types/types/src/batch.rs
Labels: chore, @consensus, @execution, @pocket-ic, @ic-message-routing-owners

#6126 refactor(idkg): [CON-1525] Make `IDkgTranscriptBuilder` thread safe
  rs/consensus/idkg/src/pre_signer.rs
Labels: refactor, @consensus

#6134 fix: ensure /boot/grub/grubenv is always synced after writing
  ic-os/components/upgrade/grub.sh
  ic-os/components/upgrade/manageboot/manageboot.sh
Labels: fix, @node, CI_ALL_BAZEL_TARGETS

#5915 chore: drop redundant field storing call context manager in canister state bits
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/proto.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/tip.rs
Labels: chore, @execution, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#6143 chore: update bazel/noble.lock.json
  bazel/noble.lock.json
Labels: chore, @idx

#6145 chore: update bazel/noble.lock.json from 2024-09-23 to 2025-08-04
  bazel/noble.lock.json
  bazel/noble.yaml
Labels: chore, @idx

#5982 feat(FI-1784): add environment presets to configure ICP rosetta api
  rs/rosetta-api/icp/src/main.rs
  rs/rosetta-api/icp/tests/integration_tests/tests/tests.rs
Labels: feat

#6140 fix(PocketIC): do not override canister upgrade options
  packages/pocket-ic/src/nonblocking.rs
Labels: fix

#6136 fix: do not connect to example.com in live PocketIC tests
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/tests.rs
Labels: fix, @execution, @pocket-ic, CI_OVERRIDE_DIDC_CHECK, @research

#6150 chore: improve `api_bn_decentralization_test` diagnostics
  rs/tests/boundary_nodes/api_bn_decentralization_test.rs
  rs/tests/boundary_nodes/utils/src/setup.rs
Labels: chore

#6147 feat(nns): Created a submit-motion-proposal tool.
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/external_crates.bzl
  rs/nervous_system/tools/submit-motion-proposal/BUILD.bazel
  rs/nervous_system/tools/submit-motion-proposal/Cargo.toml
  rs/nervous_system/tools/submit-motion-proposal/sample-proposal.txt
  rs/nervous_system/tools/submit-motion-proposal/src/main.rs
  rs/nervous_system/tools/submit-motion-proposal/submit-batch-of-motion-proposals.sh
Labels: feat, @idx, @governance-team

#6127 fix(sns/nns): Fix edge case where simultaneous upgrades can cause deadlock
  Cargo.lock
  rs/nervous_system/lock/src/lib.rs
  rs/nervous_system/lock/src/tests.rs
  rs/nervous_system/root/BUILD.bazel
  rs/nervous_system/root/Cargo.toml
  rs/nervous_system/root/src/change_canister.rs
  rs/nns/handlers/root/unreleased_changelog.md
  rs/sns/root/unreleased_changelog.md
Labels: fix, @governance-team

#6103 feat(sns): Implement the `deposit` treasury manager operation
  Cargo.lock
  MODULE.bazel
  rs/nervous_system/integration_tests/tests/sns_extension_test.rs
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/canbench/canbench_results.yml
  rs/sns/governance/src/extensions.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/lib.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/sns.bzl
Labels: feat, @idx, @governance-team

#6162 test: add more test cases to `read_state` system test to cover new canister ranges format in the state tree
  Cargo.lock
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/read_state_test.rs
Labels: test, @consensus

#5993 chore: inline dependencies in types crates
  rs/types/base_types/BUILD.bazel
  rs/types/exhaustive_derive/BUILD.bazel
  rs/types/management_canister_types/fuzz/BUILD.bazel
  rs/types/types/BUILD.bazel
  rs/types/wasm_types/BUILD.bazel
Labels: chore, @consensus, @execution, @ic-interface-owners

#6151 refactor: [CON-1487] move nns delegation manager to its own crate
  Cargo.lock
  Cargo.toml
  rs/http_endpoints/nns_delegation_manager/BUILD.bazel
  rs/http_endpoints/nns_delegation_manager/Cargo.toml
  rs/http_endpoints/nns_delegation_manager/src/lib.rs
  rs/http_endpoints/nns_delegation_manager/src/metrics.rs
  rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/src/common.rs
  rs/http_endpoints/public/src/lib.rs
  rs/http_endpoints/public/src/metrics.rs
  rs/replica/BUILD.bazel
  rs/replica/Cargo.toml
  rs/replica/src/setup_ic_stack.rs
Labels: refactor, @consensus

#6169 feat: parallel comparison of inodes in manifest computation
  rs/state_manager/src/manifest.rs
  rs/state_manager/src/manifest/tests/computation.rs
Labels: feat

#6129 refactor(node): guestos-recovery-engine permission setting
  ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.sh
Labels: refactor, @node

#6144 feat: [MR-665]: Extend canister status endpoint
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/tests/canister_version.rs
  rs/replica_tests/tests/canister_lifecycle.rs
  rs/sns/integration_tests/src/manage_dapp_canister_settings.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/ic.did
Labels: feat, @execution, @ic-interface-owners, @governance-team

#6178 fix: use `/api/v2/subnet/<subnet_id>/read_state` instead of `/api/v2/canister/<effective_canister_id>/read_state` when fetching nns delegation
  rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
Labels: fix, @consensus

#6135 chore: CON-1549 CON-1550 Report IDKG transcript resolution errors occurring during batch delivery
  rs/consensus/idkg/src/metrics.rs
  rs/consensus/idkg/src/test_utils.rs
  rs/consensus/idkg/src/utils.rs
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/metrics.rs
Labels: chore, @consensus

#6166 chore: CON-1547 Use the full pre-signature to determine "oldest registry version in use"
  Cargo.lock
  rs/consensus/src/consensus/catchup_package_maker.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/utils/BUILD.bazel
  rs/consensus/utils/Cargo.toml
  rs/consensus/utils/src/lib.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/test_utilities/consensus/src/idkg.rs
Labels: chore, @consensus, @crypto-team

#6142 chore: track NNS frontend dapp and SNS aggregator as external mainnet canisters in the bazel workspace
  WORKSPACE.bazel
  mainnet-canister-revisions.json
  rs/nervous_system/tools/sync-with-released-nervous-system-wasms/src/main.rs
Labels: chore

#6121 feat(ICP-Ledger): FI-1552: Implement endpoint to reset legacy approvals
  rs/ledger_suite/icp/ledger.did
  rs/ledger_suite/icp/ledger/src/canbench/benches.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/src/lib.rs
Labels: feat, @finint

#6189 chore: inline dependencies in backup crates
  rs/backup/BUILD.bazel
Labels: chore, @consensus

#6194 chore: FI-1814: Remove unused dependency on ic-test-utilities
  Cargo.lock
  rs/crypto/node_key_generation/BUILD.bazel
  rs/crypto/node_key_generation/Cargo.toml
  rs/crypto/node_key_validation/BUILD.bazel
  rs/crypto/node_key_validation/Cargo.toml
  rs/rust_canisters/canister_creator/BUILD.bazel
  rs/rust_canisters/canister_creator/Cargo.toml
Labels: chore, @execution, @crypto-team

#5966 feat: Add SEV measurements to ReplicaVersionRecord
  ic-os/BUILD.bazel
  ic-os/defs.bzl
  ic-os/guestos/defs.bzl
  ic-os/guestos/envs/dev/BUILD.bazel
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/guestos/envs/recovery/BUILD.bazel
  requirements.in
  requirements.txt
  rs/ic_os/dev_test_tools/launch-single-vm/src/main.rs
  rs/nns/integration_tests/src/upgrades_handler.rs
  rs/nns/test_utils/src/registry.rs
  rs/prep/src/bin/prep.rs
  rs/prep/src/internet_computer.rs
  rs/prep/src/prep_state_directory.rs
  rs/protobuf/def/registry/replica_version/v1/replica_version.proto
  rs/protobuf/generator/src/lib.rs
  rs/protobuf/src/gen/registry/registry.replica_version.v1.rs
  rs/registry/admin/src/main.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/canister/registry_test.did
  rs/registry/canister/src/invariants/replica_version.rs
  rs/registry/canister/src/mutations/do_add_api_boundary_nodes.rs
  rs/registry/canister/src/mutations/do_bless_replica_version.rs
  rs/registry/canister/src/mutations/do_deploy_guestos_to_all_unassigned_nodes.rs
  rs/registry/canister/src/mutations/do_revise_elected_replica_versions.rs
  rs/registry/canister/src/mutations/do_update_api_boundary_nodes_version.rs
  rs/registry/canister/src/mutations/do_update_ssh_readonly_access_for_all_unassigned_nodes.rs
  rs/registry/canister/src/mutations/do_update_unassigned_nodes_config.rs
  rs/registry/canister/src/mutations/node_management/do_update_node_domain_directly.rs
  rs/registry/canister/tests/update_subnet_and_bless_replica_version.rs
  rs/registry/canister/unreleased_changelog.md
  rs/registry/regedit/src/tests.rs
  rs/replica_tests/src/lib.rs
  rs/state_machine_tests/src/lib.rs
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/orchestrator/unstuck_subnet_test.rs
  rs/tests/consensus/upgrade/common.rs
  rs/tests/consensus/upgrade/unassigned_node_upgrade_test.rs
  rs/tests/consensus/upgrade/upgrade_with_alternative_urls.rs
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/utils/steps/retire_elected_version.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/nns.rs
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
  rs/tests/system_tests.bzl
Labels: feat, @idx, @dre, @consensus, @execution, @pocket-ic, @ic-message-routing-owners, @node, @ic-interface-owners, @utopia, @ic-owners-owners, CI_ALL_BAZEL_TARGETS, @governance-team

#6187 chore: [NODE-1677] Tidy up tests to consolidate code
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/orchestrator/unstuck_subnet_test.rs
  rs/tests/consensus/upgrade/common.rs
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/utils/steps/ensure_elected_version.rs
  rs/tests/message_routing/xnet/xnet_compatibility.rs
Labels: chore, @dre, @consensus, @ic-message-routing-owners

#6186 chore: [NODE-1677] Add types to utils
  rs/backup/src/backup_helper.rs
  rs/recovery/src/file_sync_helper.rs
  rs/recovery/src/lib.rs
  rs/recovery/subnet_splitting/src/state_tool_helper.rs
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/orchestrator/cup_compatibility_test.rs
  rs/tests/consensus/orchestrator/unstuck_subnet_test.rs
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/subnet_recovery/sr_nns_same_nodes_test.rs
  rs/tests/consensus/subnet_splitting_test.rs
  rs/tests/consensus/tecdsa/tecdsa_two_signing_subnets_test.rs
  rs/tests/consensus/upgrade/common.rs
  rs/tests/consensus/upgrade/unassigned_node_upgrade_test.rs
  rs/tests/consensus/upgrade/upgrade_with_alternative_urls.rs
  rs/tests/consensus/utils/src/performance.rs
  rs/tests/consensus/utils/src/subnet.rs
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/BUILD.bazel
  rs/tests/dre/Cargo.toml
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/dre/utils/steps/ensure_elected_version.rs
  rs/tests/dre/utils/steps/retire_elected_version.rs
  rs/tests/dre/utils/steps/update_subnet_type.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/driver/src/nns.rs
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
Labels: chore, @idx, @dre, @consensus, @ic-message-routing-owners, @node

#6202 fix: [NODE-1680] Fix broken nested tests
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
Labels: fix, @node, CI_ALL_BAZEL_TARGETS

#6192 chore: inline dependencies in boundary_node crates
  rs/boundary_node/canary_proxy/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_issuer/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_orchestrator/BUILD.bazel
  rs/boundary_node/certificate_issuance/certificate_orchestrator_interface/BUILD.bazel
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/rate_limits/BUILD.bazel
  rs/boundary_node/rate_limits/api/BUILD.bazel
  rs/boundary_node/rate_limits/canister_client/BUILD.bazel
  rs/boundary_node/rate_limits/integration_tests/BUILD.bazel
  rs/boundary_node/salt_sharing/BUILD.bazel
  rs/boundary_node/salt_sharing/api/BUILD.bazel
  rs/boundary_node/salt_sharing/integration_tests/BUILD.bazel
  rs/boundary_node/systemd_journal_gatewayd_shim/BUILD.bazel
Labels: chore, @boundary-node

#5563 feat(ledgers): FI-1659: fix the generic ICRC-21 message, add FieldsDisplay
  packages/icrc-ledger-types/src/icrc21/lib.rs
  packages/icrc-ledger-types/src/icrc21/requests.rs
  packages/icrc-ledger-types/src/icrc21/responses.rs
  rs/ledger_suite/icp/ledger.did
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/ledger.did
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: feat, @finint, CI_OVERRIDE_DIDC_CHECK

#6185 feat: Parallel traversal of files in finalize_checkpoint
  rs/state_layout/src/state_layout.rs
Labels: feat

#6163 feat: [EXC-2090] Add snapshot source to canister history
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/state_layout/src/state_layout/proto.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/ic.did
Labels: feat, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS, CI_OVERRIDE_BUF_BREAKING

#6221 fix(sns): Fix an issue where neuron topic follower index is updated incorrectly
  rs/sns/governance/src/governance.rs
  rs/sns/governance/tests/governance.rs
  rs/sns/governance/unreleased_changelog.md
Labels: fix, @governance-team

#6188 test: [MR-467] rejoin_test_large_state should fetch multiple GiB of chunks during state sync
  rs/rust_canisters/statesync_test/src/main.rs
  rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
Labels: test, @ic-message-routing-owners

#6222 refactor(canlog): remove dependency on `ic_cdk`
  Cargo.lock
  packages/canlog/BUILD.bazel
  packages/canlog/CHANGELOG.md
  packages/canlog/Cargo.toml
  packages/canlog/src/lib.rs
Labels: refactor, @cross-chain-team

#6198 chore: remove build container entrypoint
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/update-mainnet-revisions.yaml
  ci/container/Dockerfile
  ci/container/TAG
  ci/container/files/entrypoint.sh
Labels: chore, @idx, @finint, CI_ALL_BAZEL_TARGETS

#6225 fix(NRC): Fix rewardable nodes computation
  rs/node_rewards/canister/src/registry_querier.rs
  rs/node_rewards/canister/src/registry_querier/tests.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/mod.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator_results.rs
Labels: fix

#6210 chore: clean up container build scripts
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/update-mainnet-revisions.yaml
  ci/container/Dockerfile
  ci/container/TAG
  ci/container/build-image.sh
  ci/container/container-run.sh
  ci/container/files/known_hosts
Labels: chore, @idx, @finint

#6153 chore: removing all mentions of filebeat and log pushing configuration and generation
  ic-os/components/guestos.bzl
  ic-os/components/init/setup-encryption/setup-var-encryption.sh
  ic-os/components/misc/guestos/ic-node.conf
  ic-os/components/monitoring/filebeat/filebeat.service
  ic-os/components/monitoring/filebeat/filebeat.yml.template
  ic-os/components/monitoring/filebeat/generate-filebeat-config.sh
  ic-os/components/monitoring/filebeat/setup-filebeat-permissions.sh
  ic-os/components/selinux/filebeat/filebeat.fc
  ic-os/components/selinux/filebeat/filebeat.if
  ic-os/components/selinux/filebeat/filebeat.te
  ic-os/components/selinux/fscontext-fixes/fscontext-fixes.fc
  ic-os/components/selinux/fscontext-fixes/fscontext-fixes.te
  ic-os/guestos/context/Dockerfile
  ic-os/guestos/context/Dockerfile.base
  ic-os/guestos/docs/Boot.adoc
  ic-os/guestos/docs/SELinux-Policy.adoc
  ic-os/guestos/docs/SELinux.adoc
  ic-os/setupos/data/deployment.json.template
  rs/ic_os/config/src/generate_testnet_config.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/setupos/deployment_json.rs
  rs/ic_os/config_types/compatibility_tests/fixtures/guestos_v1.5.0.json
  rs/ic_os/config_types/compatibility_tests/fixtures/hostos_v1.5.0.json
  rs/ic_os/config_types/src/lib.rs
  rs/ic_os/dev_test_tools/launch-single-vm/src/main.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_vm_config.rs
  rs/tests/driver/assets/vector.toml
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  testnet/tools/build-guestos-configs.sh
Labels: chore, @idx, @dre, @node, CI_ALL_BAZEL_TARGETS

#6236 chore: upgrade autocfg to 1.5.0 to fix reproducibility
  .github/actions/bazel/action.yaml
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
Labels: chore, @idx

#6201 chore: Add missing Cargo files to workspace
  Cargo.lock
  Cargo.toml
  packages/ic-ed25519/Cargo.toml
  rs/execution_environment/benches/management_canister/test_canister/Cargo.toml
  rs/execution_environment/benches/management_canister/test_canister/src/lib.rs
  rs/nervous_system/tools/submit-motion-proposal/Cargo.toml
  rs/rust_canisters/call_loop_canister/Cargo.toml
  rs/rust_canisters/stable_memory_integrity/Cargo.toml
  rs/sns/treasury_manager/mock/Cargo.toml
  rs/tests/query_stats/lib/Cargo.toml
Labels: chore, @execution

#6230 chore: [NODE-1677] Organize IC image test env interface
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/ic_images.rs
  rs/tests/driver/src/driver/mod.rs
  rs/tests/driver/src/driver/test_env_api.rs
Labels: chore, @idx

#6173 feat(crypto): CRP-2810 Add support for subkey derivation to ic-ed25519 and ic-secp256k1
  Cargo.lock
  packages/ic-ed25519/BUILD.bazel
  packages/ic-ed25519/Cargo.toml
  packages/ic-ed25519/src/lib.rs
  packages/ic-ed25519/tests/tests.rs
  packages/ic-secp256k1/BUILD.bazel
  packages/ic-secp256k1/Cargo.toml
  packages/ic-secp256k1/src/lib.rs
  packages/ic-secp256k1/tests/tests.rs
Labels: feat, @crypto-team

#6238 chore(cross-chain): use `evm_rpc_types` v2.0.0
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/test_utils/Cargo.toml
  rs/ethereum/evm-rpc-client/Cargo.toml
  rs/ethereum/evm-rpc-client/src/lib.rs
Labels: chore, @idx, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6251 test(ICRC_Ledger): Remove sunset ICVC SNS from golden state test
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint

#6249 chore: HostOS SEV improvements
  ic-os/components/networking/nftables/hostos/nftables.template
  rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_sev.xml
  rs/ic_os/os_tools/guest_vm_runner/golden/upgrade_guestos.xml
  rs/ic_os/os_tools/guest_vm_runner/templates/guestos_vm_template.xml
Labels: chore

#6157 refactor: CON-1558 Remove `ThresholdSigInputsRef`
  rs/consensus/idkg/src/lib.rs
  rs/consensus/idkg/src/payload_builder.rs
  rs/consensus/idkg/src/payload_builder/signatures.rs
  rs/consensus/idkg/src/payload_verifier.rs
  rs/consensus/idkg/src/signer.rs
  rs/consensus/idkg/src/test_utils.rs
  rs/consensus/idkg/src/utils.rs
  rs/interfaces/src/consensus/errors.rs
  rs/test_utilities/consensus/src/idkg.rs
  rs/types/types/src/consensus/idkg/common.rs
  rs/types/types/src/consensus/idkg/ecdsa.rs
  rs/types/types/src/consensus/idkg/schnorr.rs
Labels: refactor, @consensus

#6266 chore(ckbtc): proposal to upgrade the ckBTC minter
  rs/bitcoin/ckbtc/mainnet/minter_upgrade_2025_08_13.md
Labels: chore

#6261 test(node): Use dev hashes in mainnet-icos-revisions.json
  ci/src/mainnet_revisions/mainnet_revisions.py
  ic-os/dev-tools/hostos-upgrade-tests.sh
  mainnet-icos-revisions.json
  rs/tests/common.bzl
Labels: test, @idx, @node

#6277 fix: use correct container options for rosetta
  .github/workflows/rosetta-release.yml
Labels: fix, @idx, @finint

#6280 fix: revert changes to the docker setup
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/update-mainnet-revisions.yaml
  ci/container/Dockerfile
  ci/container/TAG
  ci/container/files/docker.sh
Labels: fix, @idx, @finint

#6231 fix: [NODE-1677] Fix DRE tests
  Cargo.lock
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/dre/utils/BUILD.bazel
  rs/tests/dre/utils/Cargo.toml
  rs/tests/dre/utils/lib.rs
  rs/tests/dre/utils/steps/ensure_elected_version.rs
Labels: fix, @dre, @consensus

#6232 test: support specifying explicit bazel targets to test on PRs
  .github/CODEOWNERS
  .vscode/settings.json
  PULL_REQUEST_BAZEL_TARGETS
  ci/bazel-scripts/targets.py
Labels: test, @idx, @finint, @ic-owners-owners

#6243 chore: Add clobber argument to write_atomically and use it in ic_os code
  Cargo.lock
  rs/ic_os/grub/BUILD.bazel
  rs/ic_os/grub/Cargo.toml
  rs/ic_os/grub/src/lib.rs
  rs/ic_os/os_tools/guest_disk/BUILD.bazel
  rs/ic_os/os_tools/guest_disk/Cargo.toml
  rs/ic_os/os_tools/guest_disk/src/generated_key.rs
  rs/registry/proto_data_provider/src/lib.rs
  rs/state_manager/src/lib.rs
  rs/sys/src/fs.rs
  rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
  rs/tests/driver/src/driver/test_env.rs
Labels: chore, @idx, @consensus, @execution, @ic-message-routing-owners, @node, @governance-team

#6294 chore: add tip how to find matching files to PULL_REQUEST_BAZEL_TARGETS
  PULL_REQUEST_BAZEL_TARGETS
Labels: chore, @idx

#6292 test: Run some MR long tests sometimes
  PULL_REQUEST_BAZEL_TARGETS
Labels: test

#6298 chore(node): remove grub-upgrader component
  ic-os/components/hostos-scripts/grub-upgrader/grub-upgrader.service
  ic-os/components/hostos-scripts/grub-upgrader/grub-upgrader.sh
  ic-os/components/hostos.bzl
Labels: chore, @node

#6281 feat(sns): Add custom topics for ExecuteExtensionOperation proposals based on which operation is running
  rs/sns/governance/src/extensions.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/src/types.rs
Labels: feat, @governance-team

#6301 chore(sns): Migrate to stable structures and memory manager
  Cargo.lock
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/Cargo.toml
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/tests.rs
Labels: chore, @governance-team

#6328 doc(nns): Say that Topic.TOPIC_UNSPECIFIED is not applicable to Governance/SNS/Neuron's fund
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
Labels: @governance-team

#6340 test: check if targets in PULL_REQUEST_BAZEL_TARGETS are non-empty after excluding all manual targets
  ci/bazel-scripts/targets.py
Labels: test, @idx

#6329 test: sometimes run some consensus tests on PRs
  PULL_REQUEST_BAZEL_TARGETS
Labels: test, @idx, @consensus

#6342 chore: rename the experimental_system_test_colocation to colocate
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup/BUILD.bazel
  rs/tests/consensus/subnet_recovery/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/research/BUILD.bazel
  rs/tests/system_tests.bzl
Labels: chore, @idx, @consensus, @boundary-node, @finint, CI_ALL_BAZEL_TARGETS, @research

#6257 feat(XC): Support for Dogecoin in replica
  Cargo.lock
  rs/bitcoin/adapter/BUILD.bazel
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/tests/integration.rs
  rs/bitcoin/client/src/lib.rs
  rs/bitcoin/consensus/BUILD.bazel
  rs/bitcoin/consensus/Cargo.toml
  rs/bitcoin/consensus/src/payload_builder.rs
  rs/bitcoin/consensus/src/payload_builder/proptests.rs
  rs/bitcoin/consensus/src/payload_builder/tests.rs
  rs/bitcoin/replica_types/BUILD.bazel
  rs/bitcoin/replica_types/Cargo.toml
  rs/bitcoin/replica_types/src/lib.rs
  rs/config/src/adapters.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/protobuf/def/bitcoin/v1/bitcoin.proto
  rs/protobuf/src/gen/bitcoin/bitcoin.v1.rs
  rs/protobuf/src/gen/state/bitcoin.v1.rs
  rs/protobuf/src/gen/types/bitcoin.v1.rs
  rs/replica/src/setup_ic_stack.rs
  rs/replica_tests/tests/bitcoin.rs
  rs/replicated_state/BUILD.bazel
  rs/replicated_state/Cargo.toml
  rs/replicated_state/tests/replicated_state.rs
  rs/state_machine_tests/src/lib.rs
  rs/tests/ckbtc/src/adapter.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @consensus, @execution, @pocket-ic, @ic-message-routing-owners, @ic-interface-owners, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6289 feat(proposal-cli): FI-1791: Add pointer to forum discussion to select proposals in proposal-cli
  rs/cross-chain/proposal-cli/src/canister/mod.rs
  rs/cross-chain/proposal-cli/templates/install.md
  rs/cross-chain/proposal-cli/templates/upgrade.md
Labels: feat, @cross-chain-team

#6335 feat: [NODE-1686] Speed up perf tests
  rs/tests/testnets/io_perf_benchmark.rs
Labels: feat, @idx

#5172 refactor(nns): Make ExchangeRate proposals obsolete
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
  rs/nns/integration_tests/src/reinstall_and_upgrade.rs
  rs/tests/driver/src/nns.rs
  rs/tests/nns/nns_cycles_minting_multi_app_subnets_test.rs
  rs/tests/nns/nns_cycles_minting_test.rs
  rs/tests/nns/nns_dapp/nns_dapp.rs
  rs/tests/testnets/io_perf_benchmark.rs
  rs/tests/testnets/large.rs
  rs/tests/testnets/src_testing.rs
Labels: refactor, @idx, CI_ALL_BAZEL_TARGETS, @governance-team

#6345 chore(ICRC_Ledger): Remove ex-SEERS SNS from golden state test
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: chore, @finint, CI_ALL_BAZEL_TARGETS

#6355 chore: run `//rs/p2p/...` benches nightly
  .github/workflows/schedule-rust-bench.yml
Labels: chore, @idx

#6160 refactor(test): move test local server functionality in its own file
  rs/tests/BUILD.bazel
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/guestos_recovery_engine_smoke_test.rs
  rs/tests/consensus/utils/src/impersonate_upstreams.rs
  rs/tests/consensus/utils/src/lib.rs
Labels: refactor, @idx, @consensus

#6330 test: add more test cases to `nns_delegation_test`
  Cargo.lock
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/nns_delegation_test.rs
Labels: test, @consensus

#6343 test(node): fix nested flakiness and rename image variables
  rs/tests/consensus/backup/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/src/lib.rs
  rs/tests/system_tests.bzl
Labels: test, @idx, @consensus, @ic-message-routing-owners, @node

#6359 chore(BOUN-1456): ic-boundary routing table improvements
  rs/boundary_node/ic_boundary/src/bouncer/exec.rs
  rs/boundary_node/ic_boundary/src/bouncer/firewall.rs
  rs/boundary_node/ic_boundary/src/bouncer/mod.rs
  rs/boundary_node/ic_boundary/src/check.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/dns.rs
  rs/boundary_node/ic_boundary/src/http/handlers.rs
  rs/boundary_node/ic_boundary/src/http/middleware/process.rs
  rs/boundary_node/ic_boundary/src/http/middleware/retry.rs
  rs/boundary_node/ic_boundary/src/http/mod.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/persist.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/fetcher.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/mod.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/snapshot.rs
  rs/boundary_node/ic_boundary/src/tls_verify.rs
Labels: chore, @boundary-node

#6373 chore: disallow ic_cdk::futures::spawn & upgrade ic_cdk to 0.18.7
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  clippy.toml
Labels: chore, @idx, @ic-interface-owners

#6382 fix(NRC): Consider performance of assigned nodes below limit
  rs/node_rewards/rewards_calculation/src/rewards_calculator/mod.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/tests.rs
Labels: fix, @dre, @governance-team

#6389 test(node): include dev-cert in dev hostos
  ic-os/components/hostos.bzl
  ic-os/hostos/context/Dockerfile
Labels: test, @node

#6366 chore: update rs/tests/run-p8s.sh and support --grafana-dashboards-dir
  rs/tests/run-p8s.nix
  rs/tests/run-p8s.sh
Labels: chore, @idx

#6379 chore: in system-tests start p8s again after tarring its datadir
  rs/tests/driver/src/driver/prometheus_vm.rs
Labels: chore, @idx

#6381 fix(Ledgers): verify fee when generating ICRC-21 consent message
  packages/icrc-ledger-types/src/icrc21/lib.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: fix, @finint

#6392 refactor(node): guestos-recovery-upgrader url construction
  ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.sh
Labels: refactor, @node

#6398 ci: fix slack notifications by sanitizing titles with < > &
  .github/workflows/ci-notify-slack.yml
Labels: @idx, @execution, ci

#6400 chore: support dynamically downloading the p8s data and document how to use Grafana dashboards locally
  rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
Labels: chore, @consensus

#6397 fix: replace outdated hard-coded constant by size_of::<Global>()
  rs/execution_environment/src/execution/install_code/tests.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/replicated_state/src/canister_state/execution_state.rs
Labels: fix

#6404 fix: Downgrade yanked crate.
  Cargo.Bazel.json.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: fix

#6395 chore: set up slack alerts for CI failures on ic-nervous-system-wasms
  .github/workflows/slack-workflow-run.yml
Labels: chore

#6372 feat(sns): Use same validation function for proposal creation as execution
  rs/sns/governance/src/extensions.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/proposal.rs
Labels: feat, @governance-team

#6393 feat(sns): Validate that treasury manager extension is on fiduciary subnet
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_extension_test.rs
  rs/sns/governance/src/extensions.rs
Labels: feat, @governance-team

#6291 fix(ckbtc): adapt fee when reimbursing pending withdrawal requests
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
Labels: fix, @cross-chain-team

#6339 feat(PocketIC): top up anonymous account of ICP ledger
  packages/pocket-ic/tests/icp_features.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat, @pocket-ic

#6354 chore: Remove wasm64 feature flag
  rs/config/src/embedders.rs
  rs/drun/src/main.rs
  rs/embedders/benches/embedders_bench/src/lib.rs
  rs/embedders/fuzz/src/compile.rs
  rs/embedders/fuzz/src/differential.rs
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/fuzz/src/wasmtime.rs
  rs/embedders/fuzz/src/ws2wasm.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/tests/instrumentation.rs
  rs/embedders/tests/validation.rs
  rs/embedders/tests/wasmtime_embedder.rs
  rs/embedders/tests/wasmtime_random_memory_writes.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/tests/execution_test.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/pocket_ic_server/src/nonmainnet_features.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: chore, @execution, @pocket-ic, @languages

#6391 test: improve testing of ICRC1 Rosetta CLI args [FI-1784]
  rs/rosetta-api/icrc1/src/config.rs
  rs/rosetta-api/icrc1/src/lib.rs
  rs/rosetta-api/icrc1/src/main.rs
Labels: test, @finint

#6428 fix: increase timeout of nns_delegation_branch_nns_version_test to reduce flakiness
  rs/tests/networking/BUILD.bazel
Labels: fix, @consensus

#6338 fix: ensure the cargo jobs run on Release Testing
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#6361 perf: Replace `RoutingTable::route` by `NetworkTopology::route`
  rs/embedders/src/wasmtime_embedder/system_api/routing.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
  rs/messaging/src/routing/stream_builder.rs
  rs/messaging/src/routing/stream_builder/tests.rs
  rs/messaging/src/routing/stream_handler.rs
  rs/messaging/src/routing/stream_handler/tests.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/registry/routing_table/src/lib.rs
  rs/registry/routing_table/src/tests.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/replicated_state.rs
  rs/state_manager/src/manifest/split.rs
Labels: perf, @ic-message-routing-owners, @governance-team

#6384 feat(): Migrate Type0 and Type1 nodes to Type1dot1
  rs/registry/canister/src/lib.rs
  rs/registry/canister/src/missing_node_types_map.rs
  rs/registry/canister/src/registry_lifecycle.rs
Labels: feat, @governance-team

#6440 chore(Ledger_archives): No special COMPRESSED_CANISTERS treatment for ledger archives
  publish/canisters/BUILD.bazel
Labels: chore, @idx

#6443 chore(PocketIC): make external types tests manual
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/src/external_canister_types.rs
  rs/pocket_ic_server/src/lib.rs
  rs/pocket_ic_server/tests/external_types_tests.rs
Labels: chore, @pocket-ic

#6451 fix(node): remove setupos/guestos mainnet version assert
  rs/tests/nested/src/lib.rs
Labels: fix, @node

#6353 chore(crypto): CRP-2810 add missing PublicKey::derive_mainnet_key to changelogs
  packages/ic-ed25519/CHANGELOG.md
  packages/ic-secp256k1/CHANGELOG.md
Labels: chore, @crypto-team

#6454 fix: increase timeout of the query_workload_long_test to reduce flakiness
  rs/tests/networking/BUILD.bazel
Labels: fix

#6455 fix: increase timeout of the api_bn_update_workload_test to reduce flakiness
  rs/tests/boundary_nodes/BUILD.bazel
Labels: fix

#6447 chore: refactor SubnetAvailableMemory
  rs/canister_sandbox/src/protocol/sbxsvc.rs
  rs/canister_sandbox/src/sandbox_server.rs
  rs/cycles_account_manager/src/lib.rs
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/src/wasmtime_embedder/tests.rs
  rs/embedders/tests/common/mod.rs
  rs/embedders/tests/system_api.rs
  rs/embedders/tests/wasmtime_random_memory_writes.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution/call_or_task/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/query_handler.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/test_utilities.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/execution_environment/tests/execution_test.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/state_machine_tests/src/lib.rs
  rs/test_utilities/embedders/src/lib.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: chore

#6446 feat: CON-1571 Count the total number of available pre-signatures in the state and blockchain
  rs/artifact_pool/src/consensus_pool_cache.rs
  rs/consensus/idkg/src/payload_builder/pre_signatures.rs
  rs/consensus/idkg/src/test_utils.rs
  rs/consensus/idkg/src/utils.rs
  rs/interfaces/src/consensus_pool.rs
  rs/types/types/src/consensus/idkg/common.rs
Labels: feat, @consensus

#6408 chore(node): convert generate-ic-config to rust
  Cargo.lock
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/src/guestos/generate_ic_config.rs
  rs/ic_os/config/src/guestos/mod.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
Labels: chore, @node

#6411 chore(nervous-system): Update changelog for release 2025-08-22
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
Labels: chore

#6394 test(btc-adapter): Move bitcoincore-rpc into ic-btc-adapter-test-utils
  Cargo.lock
  rs/bitcoin/adapter/BUILD.bazel
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/adapter/test_utils/BUILD.bazel
  rs/bitcoin/adapter/test_utils/Cargo.toml
  rs/bitcoin/adapter/test_utils/src/bitcoind.rs
  rs/bitcoin/adapter/test_utils/src/lib.rs
  rs/bitcoin/adapter/test_utils/src/rpc_client.rs
  rs/bitcoin/adapter/tests/integration.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/tests/bitcoin_integration_tests.rs
  rs/tests/ckbtc/BUILD.bazel
  rs/tests/ckbtc/Cargo.toml
  rs/tests/ckbtc/adapter_basics_test.rs
  rs/tests/ckbtc/ckbtc_minter_batching.rs
  rs/tests/ckbtc/ckbtc_minter_checker.rs
  rs/tests/ckbtc/ckbtc_minter_deposit_and_withdrawal.rs
  rs/tests/ckbtc/ckbtc_minter_retrieve_btc.rs
  rs/tests/ckbtc/ckbtc_minter_update_balance.rs
  rs/tests/ckbtc/src/adapter.rs
  rs/tests/ckbtc/src/utils.rs
  rs/tests/execution/BUILD.bazel
  rs/tests/execution/Cargo.toml
  rs/tests/execution/btc_get_balance_test.rs
Labels: test, @consensus, @execution, @pocket-ic, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6453 docs(sns): add security risks of deposit to the extensions
  rs/sns/treasury_manager/treasury_manager.did
Labels: docs, @governance-team

#6444 chore(PocketIC): make external types tests run on schedule
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-main.yml
  .github/workflows/schedule-daily.yml
  rs/pocket_ic_server/BUILD.bazel
Labels: chore, @idx, @pocket-ic

#6367 feat: Migration Canister
  .github/CODEOWNERS
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/migration_canister/BUILD.bazel
  rs/migration_canister/Cargo.toml
  rs/migration_canister/README.md
  rs/migration_canister/migration_canister.did
  rs/migration_canister/src/canister_state.rs
  rs/migration_canister/src/external_interfaces/management.rs
  rs/migration_canister/src/external_interfaces/mod.rs
  rs/migration_canister/src/external_interfaces/registry.rs
  rs/migration_canister/src/lib.rs
  rs/migration_canister/src/migration_canister.rs
  rs/migration_canister/src/privileged.rs
  rs/migration_canister/src/processing.rs
Labels: feat, @idx, @ic-interface-owners, @ic-owners-owners

#6464 feat: CON-1530 Introduce a way to order pre-signature stashes by their priority (lowest fill level)
  rs/consensus/idkg/src/payload_builder/pre_signatures.rs
Labels: feat, @consensus

#6465 feat(NRC): Add rewards calculation endpoint
  rs/node_rewards/canister/api/src/lib.rs
  rs/node_rewards/canister/api/src/provider_rewards_calculation.rs
  rs/node_rewards/canister/api/src/providers_rewards.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs
  rs/node_rewards/canister/src/main.rs
Labels: feat, @dre

#6473 fix: bump the per-task timeout of the ckbtc system-tests from 10 to 15 minutes to reduce flakiness
  rs/tests/ckbtc/ckbtc_minter_basics_test.rs
  rs/tests/ckbtc/ckbtc_minter_batching.rs
  rs/tests/ckbtc/ckbtc_minter_checker.rs
  rs/tests/ckbtc/ckbtc_minter_deposit_and_withdrawal.rs
  rs/tests/ckbtc/ckbtc_minter_retrieve_btc.rs
  rs/tests/ckbtc/ckbtc_minter_update_balance.rs
  rs/tests/ckbtc/src/lib.rs
Labels: fix, @cross-chain-team

#6479 test(consensus): Make query_stats_basic test more stable
  rs/tests/query_stats/lib/src/aggregation.rs
Labels: test

#6481 chore: remove explicit settings of test_timeout = "long" since it's the default
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
Labels: chore, @ic-message-routing-owners, @finint

#6483 chore: inline dependencies in http_utils
  rs/http_utils/BUILD.bazel
Labels: chore, @consensus

#6378 feat(canister_migration): introduce new endpoints with canister ranges in the new format
  Cargo.lock
  rs/http_endpoints/fuzz/fuzz_targets/execute_call_service.rs
  rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/src/call.rs
  rs/http_endpoints/public/src/call/call_async.rs
  rs/http_endpoints/public/src/call/call_sync.rs
  rs/http_endpoints/public/src/lib.rs
  rs/http_endpoints/public/src/query.rs
  rs/http_endpoints/public/src/read_state.rs
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/http_endpoints/public/src/read_state/subnet.rs
  rs/http_endpoints/public/tests/load_shed_test.rs
  rs/http_endpoints/public/tests/test.rs
  rs/http_endpoints/test_agent/BUILD.bazel
  rs/http_endpoints/test_agent/Cargo.toml
  rs/http_endpoints/test_agent/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/tests/driver/src/driver/dsl.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/http_endpoints_public_spec_test.rs
  rs/tests/networking/nns_delegation_test.rs
Labels: feat, @idx, @consensus, @product-security, @pocket-ic, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#6466 feat(sns): Add proposal to upgrade extensions
  rs/nervous_system/integration_tests/tests/sns_extension_test.rs
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/extensions.rs
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/src/types.rs
  rs/sns/sns.bzl
Labels: feat

#6438 fix(PocketIC): II canister types
  rs/pocket_ic_server/src/external_canister_types.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: fix, @pocket-ic

#6456 fix: Some more cleanups in execution fuzzers
  rs/embedders/fuzz/src/compile.rs
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs
Labels: fix, @execution

#6476 fix(fuzzing): Pass --config=lint when building fuzzers on CI
  bin/fuzzing/build-all-fuzzers.sh
  bin/fuzzing/run-all-fuzzers.sh
Labels: fix, @product-security, @execution

#6490 chore(test): bump signer canister to ic-cdk 0.18
  Cargo.lock
  rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
  rs/tests/consensus/tecdsa/tschnorr_message_sizes_test.rs
  rs/tests/consensus/tecdsa/utils/BUILD.bazel
  rs/tests/consensus/tecdsa/utils/Cargo.toml
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/util.rs
  rs/tests/test_canisters/signer/BUILD.bazel
  rs/tests/test_canisters/signer/Cargo.toml
  rs/tests/test_canisters/signer/src/lib.rs
  rs/tests/test_canisters/signer/src/main.rs
  rs/tests/test_canisters/signer/src/signer.did
Labels: chore, @idx, @consensus

#6504 feat: CON-1559 Purge pre-signatures that exceed the maximum stash size
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/execution_environment/src/scheduler/threshold_signatures.rs
Labels: feat, @execution

#6475 feat: Soft limit for merge size [MR-695]
  rs/state_manager/src/tip.rs
Labels: feat, @ic-message-routing-owners

#6509 fix: EXC: Fix PR title sanitizer escaping
  .github/workflows/ci-notify-slack.yml
Labels: fix, @idx

#6510 chore: add arm64 pocket-ic binaries releases
  .github/workflows/tag-release.yml
Labels: chore, @idx

#6471 feat(node): generate-ic-config follow ups
  Cargo.lock
  Cargo.toml
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/src/guestos/generate_ic_config.rs
  rs/orchestrator/Cargo.toml
Labels: feat, @node

#6059 chore: Stop preparing routing table in the old format outside of production
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/determinism_test/src/setup.rs
  rs/drun/src/lib.rs
  rs/messaging/src/message_routing/tests.rs
  rs/nns/integration_tests/src/registry_get_changes_since.rs
  rs/nns/test_utils/src/registry.rs
  rs/orchestrator/registry_replicator/src/internal_state.rs
  rs/prep/src/internet_computer.rs
  rs/registry/regedit/src/protobuf.rs
  rs/state_machine_tests/src/lib.rs
Labels: chore, @consensus, @execution, @boundary-node, @pocket-ic, @ic-message-routing-owners, @utopia, @languages, @governance-team

#6484 chore: tag //rs/bitcoin/ckbtc/minter:ckbtc_minter_replay_events_tests as a long_test
  rs/bitcoin/ckbtc/minter/BUILD.bazel
Labels: chore, @cross-chain-team

#5734 feat(ICP_Ledger): FI-1727: Trap in case the deprecated ICP ledger notify method is called
  Cargo.lock
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/Cargo.toml
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/notified.did
  rs/ledger_suite/icp/tests/notified.rs
  rs/ledger_suite/icp/tests/notified/notified.did
  rs/ledger_suite/icp/tests/notified/notified.rs
  rs/ledger_suite/icp/tests/tests.rs
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/tests/nns/cycles_minting/cycles_minting.rs
  rs/tests/nns/nns_cycles_minting_test.rs
Labels: feat, @finint, CI_ALL_BAZEL_TARGETS, @governance-team

#6410 feat(nns): Use call_and_wait rather than call when submitting motion proposal
  rs/nervous_system/tools/submit-motion-proposal/src/main.rs
Labels: feat

#6412 feat(btc-adapter): remove dependency on bitcoincore-rpc
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/cargo.config
  bazel/external_crates.bzl
  rs/bitcoin/adapter/test_utils/BUILD.bazel
  rs/bitcoin/adapter/test_utils/Cargo.toml
  rs/bitcoin/adapter/test_utils/src/lib.rs
  rs/bitcoin/adapter/test_utils/src/rpc_client.rs
  rs/bitcoin/adapter/test_utils/src/rpc_json.rs
  rs/pocket_ic_server/tests/bitcoin_integration_tests.rs
Labels: feat, @execution, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6512 chore: tag //rs/tests/node/... as long_test
  rs/tests/node/BUILD.bazel
Labels: chore, @node

#6467 feat: Attestation crate
  Cargo.Bazel.json.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ic_os/attestation/BUILD.bazel
  rs/ic_os/attestation/Cargo.toml
  rs/ic_os/attestation/build.rs
  rs/ic_os/attestation/proto/attestation.proto
  rs/ic_os/attestation/src/attestation_package.rs
  rs/ic_os/attestation/src/custom_data.rs
  rs/ic_os/attestation/src/e2e_tests.rs
  rs/ic_os/attestation/src/lib.rs
  rs/ic_os/attestation/src/registry.rs
  rs/ic_os/attestation/src/verification.rs
  rs/ic_os/attestation/testing/BUILD.bazel
  rs/ic_os/attestation/testing/Cargo.toml
  rs/ic_os/attestation/testing/src/lib.rs
  rs/ic_os/attestation/testing/src/registry.rs
  rs/ic_os/sev/BUILD.bazel
  rs/ic_os/sev/src/guest/mod.rs
  rs/ic_os/sev/src/guest/testing.rs
Labels: feat, @governance-team

#6498 test(nns): Increase the diff allowed for wasm memory decrease after upgrade
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
Labels: test, CI_ALL_BAZEL_TARGETS

#6482 test(MR): Speed up rejoin_large_test
  rs/tests/message_routing/rejoin_test_large_state.rs
  rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
Labels: test, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#6499 feat(nns): Add memo for the split neuron command
  rs/nervous_system/common/src/ledger.rs
  rs/nns/governance/api/src/types.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_lock_tests.rs
  rs/nns/governance/src/pb/conversions/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: feat, @governance-team

#6525 chore: send a slack notification on nns-tests-nightly failures
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: chore, @idx

#6523 chore: Factor out VSockClient trait
  Cargo.lock
  rs/ic_os/vsock/guest/src/main.rs
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/Cargo.toml
  rs/ic_os/vsock/vsock_lib/src/guest/mod.rs
  rs/ic_os/vsock/vsock_lib/src/lib.rs
Labels: chore, @node

#6522 refactor: Move fetching SEV certs higher up in the call stack
  Cargo.lock
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/src/hostos/guestos_config.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_vm_config.rs
  rs/ic_os/os_tools/guest_vm_runner/src/main.rs
  rs/ic_os/sev/BUILD.bazel
  rs/ic_os/sev/Cargo.toml
  rs/ic_os/sev/src/host/mod.rs
Labels: refactor, @node
