Repository dfinity/ic, pull requests merged in 2025-01, with the labels that each got.

#3226 fix(nns): Revert spawn state when ledger unavailable and drop lock
  rs/nns/governance/src/governance.rs
Labels: fix, @nns-team

#2844 refactor(nns): Switch NNS Governance global state from static to thread_local
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
Labels: refactor, @nns-team

#3126 refactor(Consensus): Factor CUP functionality out of dkg submodule
  rs/consensus/src/cup_utils.rs
  rs/consensus/src/dkg.rs
  rs/consensus/src/dkg/payload_builder.rs
  rs/consensus/src/lib.rs
  rs/orchestrator/src/registry_helper.rs
  rs/replay/src/lib.rs
  rs/replica/src/setup_ic_stack.rs
  rs/state_machine_tests/src/lib.rs
Labels: refactor, @consensus, @networking, @pocket-ic, @ic-message-routing-owners

#3312 feat(nns): Split the active_neurons_in_stable_memory into 2 flags
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/neuron_store/metrics.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Labels: feat

#3241 perf: Move heavy object deallocation off the critical Execution path
  .github/CODEOWNERS
  Cargo.lock
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/src/execution/common.rs
  rs/execution_environment/src/execution/response.rs
  rs/execution_environment/src/execution/update.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/hypervisor.rs
  rs/state_manager/src/lib.rs
  rs/utils/thread/BUILD.bazel
  rs/utils/thread/Cargo.toml
  rs/utils/thread/src/deallocator_thread.rs
  rs/utils/thread/src/lib.rs
Labels: perf, @execution, @ic-message-routing-owners, @ic-interface-owners, @ic-owners-owners

#3140 feat(EXC-1801): Use state layout tmp dir for compilation cache
  rs/determinism_test/src/setup.rs
  rs/drun/src/lib.rs
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/hypervisor.rs
  rs/execution_environment/src/lib.rs
  rs/replay/src/player.rs
  rs/replica/src/setup_ic_stack.rs
  rs/state_machine_tests/src/lib.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @consensus, @execution, @networking, @pocket-ic, @ic-message-routing-owners, @languages

#3276 chore: EXC-1818: Update benches baseline after query fix
  rs/execution_environment/benches/baseline/EMBEDDERS_HEAP.min
  rs/execution_environment/benches/baseline/EMBEDDERS_STABLE_MEMORY.min
Labels: chore, @execution

#3334 fix(IDX): allow repro-check.sh on private IC repo
  ci/tools/repro-check.sh
Labels: fix, @idx

#3335 test(consensus): adjust the parameters of consensus performance tests
  rs/tests/consensus/consensus_performance.rs
Labels: test, @consensus

#3328 refactor(ic-admin): improve missing HSM argument messages
  rs/registry/admin/src/main.rs
Labels: refactor, @nns-team

#3313 chore: add .bazelignore file
  .bazelignore
Labels: chore

#3327 fix: Complete the TLA annotations for FakeLedger
  rs/nns/governance/tests/fake.rs
Labels: fix

#3338 chore: Ignore wasmtime validation errors
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
  rs/execution_environment/tests/execution_test.rs
Labels: chore, @execution

#3264 fix(IDX): unset runner permissions
  .github/actions/bazel-test-all/action.yaml
Labels: fix, @idx, CI_ALL_BAZEL_TARGETS

#3311 fix(nns): Fix for a particular locked neuron
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
Labels: fix, @nns-team

#3306 refactor(nns): Change Root interface crate to use ic-cdk
  Cargo.lock
  rs/nns/handlers/root/interface/BUILD.bazel
  rs/nns/handlers/root/interface/Cargo.toml
  rs/nns/handlers/root/interface/src/client.rs
Labels: refactor, @nns-team

#3344 feat(nns): Make neuron migration to stable memory reversible
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Labels: feat

#3323 fix(nns): Fix maturity for neurons that temporarily fail to spawn
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
Labels: fix, @nns-team

#3341 feat(PocketIC): optionally check caller when retrieving ingress status
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @ic-message-routing-owners

#2901 feat: ICRC-ledger: FI-1439: Implement V4 for ICRC ledger - migrate balances to stable structures
  WORKSPACE.bazel
  mainnet-canister-revisions.json
  rs/ethereum/ledger-suite-orchestrator/src/scheduler/mod.rs
  rs/ledger_suite/common/ledger_canister_core/src/ledger.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/index-ng/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/ledger_suite/icrc1/ledger/ledger.did
  rs/ledger_suite/icrc1/ledger/src/benches/mod.rs
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/src/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/icrc1/tests/upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: feat, @idx, @nns-team, @cross-chain-team, @finint, @ic-owners-owners

#3282 chore: Update ic-agent and ic-agent's reverse dependencies to v0.39
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  packages/ic-signature-verification/Cargo.toml
  rs/boundary_node/certificate_issuance/certificate_issuer/src/check.rs
  rs/boundary_node/certificate_issuance/certificate_issuer/src/main.rs
  rs/http_endpoints/fuzz/fuzz_targets/execute_call_service.rs
  rs/monitoring/tracing/jaeger_exporter/src/lib.rs
  rs/nervous_system/agent/src/agent_impl.rs
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/BUILD.bazel
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/Cargo.toml
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/src/canister_access.rs
  rs/rosetta-api/icp/tests/system_tests/common/utils.rs
  rs/rosetta-api/icrc1/src/main.rs
  rs/rosetta-api/icrc1/tests/common/local_replica.rs
  rs/tests/boundary_nodes/api_bn_decentralization_test.rs
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
  rs/tests/boundary_nodes/rate_limit_canister_test.rs
  rs/tests/driver/src/util.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
  rs/tests/execution/general_execution_tests/wasm_chunk_store.rs
Labels: chore, @idx, @product-security, @execution, @boundary-node, @networking, @pocket-ic, @nns-team, @finint

#3329 chore: CON-1434 Increment metric in case of `NiDkgTag` mismatches
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/dkg/payload_validator.rs
Labels: chore

#3342 feat(governance): Automatically remind governance team to update unreleased_changelog.md.
  .github/workflows/ci-pr-only-nns-team-reminder.yml
Labels: feat, @idx, @nns-team

#3352 test: change error_code in tecdsa_signature_fails_without_cycles_test
  rs/tests/consensus/tecdsa/tecdsa_signature_fails_without_cycles_test.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_timeout_test.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS

#3349 chore: Update codeowners NET -> CON
  .github/CODEOWNERS
Labels: chore, @ic-owners-owners

#3281 chore(cketh): Proposal to fix developer dashboard
  rs/ethereum/cketh/mainnet/minter_upgrade_2024_12_20.md
Labels: chore

#3331 fix: Include reservation cycles in error reported during taking a canister snapshot
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/tests/storage_reservation.rs
Labels: fix

#3333 refactor: Rename field in InsufficientCyclesInMemoryGrow error
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution/install_code.rs
Labels: refactor, @execution

#3332 docs(governance): Added unreleased_changelog.md and CHANGELOG.md to governance.
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
Labels: docs, @nns-team

#3301 feat(recovery): [CON-1407] Add CLI option to use existing binaries for local recoveries
  ic-os/guestos/defs.bzl
  rs/recovery/src/args_merger.rs
  rs/recovery/src/cmd.rs
  rs/recovery/src/lib.rs
  rs/recovery/src/main.rs
  rs/recovery/src/recovery_state.rs
  rs/recovery/subnet_splitting/src/main.rs
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/subnet_recovery/sr_nns_same_nodes_test.rs
  rs/tests/consensus/subnet_splitting_test.rs
Labels: feat, @consensus, @node

#3346 chore(BOUN-1284): replace tokio rwlock, bump ic-gateway release
  ic-os/boundary-guestos/context/Dockerfile
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
Labels: chore

#3353 feat(governance-tools): Use unreleased_changelog.md when generating proposals.
  rs/nns/governance/unreleased_changelog.md
  testnet/tools/nns-tools/lib/proposals.sh
Labels: feat

#3365 feat(icrc-ledger-types): FI-1624: Bump icrc-ledger-types version with the added rustdoc
  Cargo.lock
  packages/icrc-ledger-types/CHANGELOG.md
  packages/icrc-ledger-types/Cargo.toml
Labels: feat, @finint

#3362 fix: reject code in synchronous rejects
  hs/spec_compliance/src/IC/Test/Spec.hs
  rs/system_api/src/sandbox_safe_system_state.rs
Labels: fix, @execution, @research

#3340 refactor(CON-1447): Factor out DKG submodule into its own crate
  Cargo.lock
  rs/consensus/BUILD.bazel
  rs/consensus/Cargo.toml
  rs/consensus/dkg/BUILD.bazel
  rs/consensus/dkg/Cargo.toml
  rs/consensus/dkg/src/dkg_key_manager.rs
  rs/consensus/dkg/src/lib.rs
  rs/consensus/dkg/src/payload_builder.rs
  rs/consensus/dkg/src/payload_validator.rs
  rs/consensus/dkg/src/test_utils.rs
  rs/consensus/dkg/src/utils.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/consensus/block_maker.rs
  rs/consensus/src/consensus/validator.rs
  rs/consensus/src/cup_utils.rs
  rs/consensus/src/lib.rs
  rs/consensus/tests/framework/driver.rs
  rs/consensus/tests/framework/mod.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/framework/types.rs
  rs/consensus/tests/payload.rs
  rs/replay/BUILD.bazel
  rs/replay/Cargo.toml
  rs/replay/src/backup.rs
  rs/replay/src/validator.rs
  rs/replica/Cargo.toml
  rs/replica/setup_ic_network/BUILD.bazel
  rs/replica/setup_ic_network/Cargo.toml
  rs/replica/setup_ic_network/src/lib.rs
  rs/test_utilities/artifact_pool/BUILD.bazel
  rs/test_utilities/artifact_pool/Cargo.toml
  rs/test_utilities/artifact_pool/src/consensus_pool.rs
Labels: refactor, @consensus, @networking

#3372 revert: "test: Add test for taking a snapshot that triggers storage reservation"
  rs/execution_environment/tests/storage_reservation.rs
Labels: revert, @execution

#3339 feat(NNS): allow execution of proposals that remove non-existing nodes
  rs/registry/canister/src/mutations/node.rs
  rs/registry/canister/src/mutations/node_management/do_remove_nodes.rs
  rs/tests/nns/node_removal_from_registry_test.rs
Labels: feat, @nns-team

#3300 feat(nervous-system): Enable Root to upgrade canisters using chunked Wasms
  Cargo.lock
  rs/nervous_system/common/test_utils/BUILD.bazel
  rs/nervous_system/common/test_utils/src/wasm_helpers.rs
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/Cargo.toml
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
  rs/nervous_system/root/src/change_canister.rs
  rs/nns/governance/src/proposals/install_code.rs
  rs/nns/handlers/root/impl/canister/root.did
  rs/nns/integration_tests/src/governance_upgrade.rs
  rs/registry/admin/src/main.rs
  rs/sns/integration_tests/src/root.rs
  rs/sns/root/canister/root.did
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @execution, @nns-team, @node

#3195 fix: Check hook status after an upgrade/reinstall/uninstall/install
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/canister_state/system_state/task_queue.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
Labels: fix, @execution, @ic-message-routing-owners

#3373 feat: [NODE-1499] Run chown/chmod in setup-permissions in parallel
  ic-os/components/ic/setup-permissions/erestorecon.sh
  ic-os/components/ic/setup-permissions/setup-permissions.sh
Labels: feat

#3285 feat(NNS): compare node provider ID in addition to the operator when removing node directly
  rs/nns/test_utils/src/registry.rs
  rs/registry/canister/src/common/test_helpers.rs
  rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs
  rs/registry/canister/src/mutations/node_management/common.rs
  rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
  rs/registry/canister/tests/remove_nodes.rs
Labels: feat, @nns-team

#3256 chore(IDX): don't cache ic-os images
  ic-os/defs.bzl
  ic-os/guestos/envs/local-base-dev/BUILD.bazel
  ic-os/guestos/envs/local-base-prod/BUILD.bazel
  ic-os/hostos/defs.bzl
  ic-os/hostos/envs/local-base-dev/BUILD.bazel
  ic-os/hostos/envs/local-base-prod/BUILD.bazel
  ic-os/setupos/defs.bzl
  ic-os/setupos/envs/local-base-dev/BUILD.bazel
  ic-os/setupos/envs/local-base-prod/BUILD.bazel
Labels: chore, @node

#3330 chore: upgrade wasmtime to v.28
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/host_memory.rs
  rs/execution_environment/benches/README.md
  rs/execution_environment/benches/baseline/EMBEDDERS_COMPILATION.min
  rs/execution_environment/benches/baseline/EMBEDDERS_HEAP.min
  rs/execution_environment/benches/baseline/EMBEDDERS_STABLE_MEMORY.min
  rs/execution_environment/benches/baseline/SYSTEM_API_INSPECT_MESSAGE.min
  rs/execution_environment/benches/baseline/SYSTEM_API_QUERY.min
  rs/execution_environment/benches/baseline/SYSTEM_API_UPDATE.min
  rs/execution_environment/benches/baseline/WASM_INSTRUCTIONS.min
  rs/execution_environment/benches/run-all-benchmarks.sh
  rs/execution_environment/benches/run-benchmark.sh
  rs/execution_environment/benches/summarize-results.sh
Labels: chore, @idx, @execution

#3378 chore(boundary): bump `ic-gateway` to `v0.1.63`
  ic-os/boundary-guestos/context/Dockerfile
Labels: chore

#3356 test(nns): Revert "test(nns): Support caching of the golden NNS state when runni…
  rs/nns/test_utils/golden_nns_state/src/lib.rs
Labels: test

#3371 feat(governance): Enable periodic confirmation.
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#3303 feat: Implement `MutableIntMap`
  rs/replicated_state/BUILD.bazel
  rs/replicated_state/benches/bench_intmap.rs
  rs/replicated_state/src/page_map.rs
  rs/replicated_state/src/page_map/int_map.rs
  rs/replicated_state/src/page_map/int_map/test.rs
  rs/replicated_state/src/page_map/page_allocator.rs
  rs/replicated_state/src/page_map/page_allocator/mmap.rs
  rs/replicated_state/src/page_map/storage.rs
  rs/replicated_state/src/page_map/storage/tests.rs
Labels: feat, @execution, @ic-message-routing-owners

#3367 feat(governance-tools): Script that adds entry for new release to CHANGELOG after a proposal was successfully executed.
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: feat, @nns-team

#3381 fix: Repartition input schedules in canister migration in state machine tests
  rs/state_machine_tests/src/lib.rs
Labels: fix, @execution, @pocket-ic, @ic-message-routing-owners

#3389 feat(node): Add log-config service to GuestOS
  ic-os/components/guestos.bzl
  ic-os/components/hostos.bzl
  ic-os/components/misc/log-config/log-config-guestos.service
  ic-os/components/misc/log-config/log-config-hostos.service
  ic-os/components/misc/log-config/log-config.sh
  ic-os/guestos/defs.bzl
  rs/ic_os/config/src/main.rs
Labels: feat, @node

#3397 test(ICRC_Ledger): FI-1625: Adapt golden state test to V4 migration
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint

#3384 test(consensus): move the `IngressPayload` serialization/deserialization unit test from `test_utilities/types/` to `rs/types/types`
  Cargo.lock
  rs/test_utilities/types/BUILD.bazel
  rs/test_utilities/types/Cargo.toml
  rs/test_utilities/types/src/batch/ingress_payload.rs
  rs/types/types/src/batch/ingress.rs
Labels: test, @consensus, @ic-interface-owners

#3391 fix: SNS Gov canister should deserialize to proto Governance, not API Governance
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/tests.rs
Labels: fix, @nns-team

#3406 fix(proposal-tools): Fix code path to be absolute instead of relative
  testnet/tools/nns-tools/lib/proposals.sh
Labels: fix, @nns-team

#3405 feat(governance-tools): Populate "Features & Fixes" section of SNS proposals from unreleased_changelog.md.
  testnet/tools/nns-tools/add-release-to-changelog.sh
  testnet/tools/nns-tools/lib/proposals.sh
  testnet/tools/nns-tools/lib/util.sh
Labels: feat, @nns-team

#3407 fix(nns-tools): Fix forum post generator
  testnet/tools/nns-tools/lib/proposals.sh
Labels: fix, @nns-team

#3325 chore(ckbtc): remove distribute_kyt_fee and reimburse_failed_kyt
  rs/bitcoin/ckbtc/minter/src/guard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/memo.rs
  rs/bitcoin/ckbtc/minter/src/state/audit.rs
  rs/bitcoin/ckbtc/minter/src/tasks.rs
  rs/bitcoin/ckbtc/minter/src/tasks/tests.rs
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3354 fix(PocketIC): run install_backtrace_handler if PocketIC is run as canister sandbox
  rs/canister_sandbox/BUILD.bazel
  rs/canister_sandbox/bin/canister_sandbox.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/src/main.rs
Labels: fix, @execution, @pocket-ic, CI_ALL_BAZEL_TARGETS

#3402 chore(cketh/ckerc20): proposal to upgrade ledger suite orchestrator and managed canisters
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2025_01_10.md
Labels: chore, @cross-chain-team

#3337 feat(IC-1579): TLA instrumentation for `disburse_neuron`
  Cargo.lock
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tla/common.rs
  rs/nns/governance/src/governance/tla/disburse_neuron.rs
  rs/nns/governance/src/governance/tla/mod.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tla/Disburse_Neuron.tla
  rs/nns/governance/tla/Disburse_Neuron_Apalache.tla
  rs/nns/governance/tla/Spawn_Neurons.tla
  rs/nns/governance/tla/Split_Neuron.tla
  rs/tla_instrumentation/BUILD.bazel
  rs/tla_instrumentation/tla_instrumentation/Cargo.toml
  rs/tla_instrumentation/tla_instrumentation/tests/multiple_calls.rs
  rs/tla_instrumentation/tla_instrumentation_proc_macros/src/lib.rs
Labels: feat, @nns-team, @research, @formal-models

#3218 test: add a test for fetching long assets with chunkwise certification
  MODULE.bazel
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/boundary_nodes/bn_integration_on_playnet_test.rs
  rs/tests/boundary_nodes/bn_integration_test.rs
  rs/tests/boundary_nodes/custom_domains/setup.rs
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
  rs/tests/driver/src/driver/asset_canister.rs
Labels: test, @idx, @boundary-node

#3395 test: Add test for taking a snapshot that triggers storage reservation
  rs/execution_environment/tests/storage_reservation.rs
Labels: test, @execution

#3366 feat(EXC-1795): Limit cache disk space
  Cargo.lock
  rs/embedders/src/compilation_cache.rs
  rs/embedders/src/serialized_module.rs
  rs/execution_environment/src/hypervisor.rs
  rs/execution_environment/src/query_handler/query_cache.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/interfaces/src/execution_environment/errors.rs
  rs/types/types/src/ingress.rs
  rs/types/types/src/lib.rs
  rs/types/wasm_types/src/lib.rs
  rs/utils/lru_cache/BUILD.bazel
  rs/utils/lru_cache/Cargo.toml
  rs/utils/lru_cache/src/lib.rs
Labels: feat, @execution, @ic-interface-owners

#3392 refactor: clean up the SNS Governance API type definitions
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
Labels: refactor

#3424 feat(nns-tools): nns_claim_or_refresh helper
  testnet/tools/nns-tools/lib/include.sh
  testnet/tools/nns-tools/lib/nns_neurons.sh
Labels: feat, @nns-team

#3426 chore(nns): Add a comment on MAX_NEURONS_FUND_PARTICIPANTS about its effect on instructions
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store/benches.rs
Labels: chore

#3430 feat(sns): add release runscript to replace runbook in notion
  Cargo.lock
  Cargo.toml
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/Cargo.toml
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3400 test(ICRC_Ledger): canbench benchmarks for icrc2_approve, icrc2_transfer_from and icrc3_get_blocks
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/ledger_suite/icrc1/ledger/src/benches/benches_u256.rs
  rs/ledger_suite/icrc1/ledger/src/benches/benches_u64.rs
  rs/ledger_suite/icrc1/ledger/src/benches/mod.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
Labels: test, @finint

#3404 test(ICRC_Ledger): FI-1043: Verify ICRC ledger and archive block equality
  rs/ledger_suite/icrc1/archive/BUILD.bazel
  rs/ledger_suite/icrc1/archive/src/main.rs
Labels: test, @finint

#3403 test(ICRC_Index): FI-1042: Verify ICRC ledger and index block equality
  rs/ledger_suite/icrc1/index-ng/BUILD.bazel
  rs/ledger_suite/icrc1/index-ng/src/main.rs
Labels: test, @finint

#3398 test(ICP_Ledger): FI-1036: Add ICP ledger and index encoded block response compatibility
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icp/index/src/main.rs
Labels: test, @finint

#3422 test(PocketIC): add Schnorr `aux` types and tests
  Cargo.lock
  MODULE.bazel
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/management_canister.rs
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/management_canister.rs
  packages/pocket-ic/tests/tests.rs
Labels: test, @idx, @pocket-ic

#3200 test: [EXC-1819] Fix flakiness of state_manager_integration_tests (random_canister_input_lsmt)
  rs/state_machine_tests/src/lib.rs
  rs/state_manager/tests/state_manager.rs
Labels: test, @pocket-ic, @ic-message-routing-owners

#3435 fix(EXC-1834): Ignore empty data segment pages
  rs/embedders/src/wasm_utils.rs
  rs/execution_environment/tests/execution_test.rs
Labels: fix

#3412 feat(EXC-1800): Use Wasmtime `deserialize_open_file`.
  rs/embedders/src/wasm_executor.rs
  rs/embedders/src/wasmtime_embedder.rs
Labels: feat, @execution

#3376 fix: mocked xnet in PocketIC
  packages/pocket-ic/tests/tests.rs
  rs/state_machine_tests/src/lib.rs
  rs/xnet/payload_builder/src/lib.rs
Labels: fix, @pocket-ic, @ic-message-routing-owners

#3416 feat(governance-tools): Support creating entries in SNS CHANGELOG.md files.
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: feat, @nns-team

#3442 chore(IDX): Use repository_ctx.getenv
  bazel/sanitizers_enabled_env/defs.bzl
Labels: chore, @idx

#3417 feat(governance-tools): Pretty add-release-to-changelog.sh output.
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: feat, @nns-team

#3447 test(consensus): modify the test cases in ingress payload serialization/deserialization benchmarks
  rs/consensus/benches/validate_payload.rs
Labels: test, @consensus

#3449 chore(IDX): bump rules_rust
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  WORKSPACE.bazel
  bazel/rules_rust.patch
Labels: chore, @idx

#3357 chore: EXC-1818: Run all benchmarks faster
  rs/execution_environment/benches/run-all-benchmarks.sh
  rs/execution_environment/benches/summarize-results.sh
Labels: chore

#3322 feat(node): add fstrim datadir observability
  Cargo.lock
  rs/ic_os/fstrim_tool/BUILD.bazel
  rs/ic_os/fstrim_tool/Cargo.toml
  rs/ic_os/fstrim_tool/src/lib.rs
  rs/ic_os/fstrim_tool/src/metrics/mod.rs
  rs/ic_os/fstrim_tool/src/metrics/tests.rs
  rs/ic_os/fstrim_tool/src/tests.rs
  rs/ic_os/fstrim_tool/tests/integration_tests.rs
Labels: feat, @crypto-team, @node

#3408 fix: cargo build registry-canister for wasm32 target
  Cargo.lock
  rs/registry/canister/Cargo.toml
Labels: fix

#3411 feat(IC-1579): TLA annotations for disburse_to_neuron
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tla/disburse_to_neuron.rs
  rs/nns/governance/src/governance/tla/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tla/Claim_Neuron.tla
  rs/nns/governance/tla/Disburse_To_Neuron.tla
  rs/nns/governance/tla/Disburse_To_Neuron_Apalache.tla
Labels: feat, @nns-team

#3450 fix(PocketIC): safely drop StateMachine
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/state_machine_tests/src/lib.rs
Labels: fix, @pocket-ic

#3444 refactor(consensus): simplify `IngressPayload` implementation
  rs/consensus/src/consensus/malicious_consensus.rs
  rs/consensus/src/consensus/metrics.rs
  rs/consensus/src/consensus/purger.rs
  rs/ingress_manager/src/ingress_selector.rs
  rs/interfaces/src/ingress_manager.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/download.rs
  rs/p2p/artifact_downloader/src/fetch_stripped_artifact/stripper.rs
  rs/protobuf/def/types/v1/consensus.proto
  rs/protobuf/src/gen/types/types.v1.rs
  rs/state_machine_tests/src/lib.rs
  rs/types/types/src/batch/ingress.rs
  rs/types/types/src/exhaustive.rs
  rs/types/types/src/messages.rs
Labels: refactor, @consensus, @pocket-ic, @ic-message-routing-owners, @ic-interface-owners

#3414 chore(nftables): update IPv6 prefix list in the HostOS firewall
  ic-os/components/networking/nftables/hostos/nftables.template
Labels: chore

#3419 chore: Split the user ingress artifacts and the artifacts coming from P2P
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/p2p/artifact_manager/BUILD.bazel
  rs/p2p/artifact_manager/Cargo.toml
  rs/p2p/artifact_manager/src/lib.rs
  rs/p2p/consensus_manager/src/lib.rs
  rs/p2p/test_utils/BUILD.bazel
  rs/p2p/test_utils/Cargo.toml
  rs/p2p/test_utils/src/lib.rs
  rs/p2p/test_utils/src/turmoil.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: chore, @idx, @consensus

#3452 chore(nns): Remove one-off fix for broken neuron after deployment
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/tests/governance.rs
Labels: chore, @nns-team

#3455 fix: [EXC-1831] Low Wasm memory hook will run once the canister's unfrozen if it was scheduled before freezing
  rs/execution_environment/src/execution/update.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: fix, @execution

#3462 refactor: Use test_strategy over proptest macro in replicated state tests
  rs/replicated_state/src/canister_state/queues/queue/tests.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/replicated_state/src/page_map/storage/tests.rs
  rs/replicated_state/tests/metadata_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: refactor, @execution, @ic-message-routing-owners

#3472 chore(system-tests-k8s): untag broken k8s tests
  rs/tests/ckbtc/BUILD.bazel
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/message_routing/BUILD.bazel
  rs/tests/networking/BUILD.bazel
Labels: chore, @consensus, @ic-message-routing-owners, @cross-chain-team

#3440 chore: state-tool copy commands
  Cargo.lock
  rs/state_layout/src/state_layout.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_manager/src/lib.rs
  rs/state_tool/BUILD.bazel
  rs/state_tool/Cargo.toml
  rs/state_tool/src/commands.rs
  rs/state_tool/src/commands/copy.rs
  rs/state_tool/src/commands/import_state.rs
  rs/state_tool/src/main.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#3471 fix: Consider all fields in `is_empty` and `count_bytes` implementation for `BatchPayload`
  rs/bitcoin/replica_types/src/lib.rs
  rs/types/types/src/batch.rs
  rs/types/types/src/batch/ingress.rs
  rs/types/types/src/batch/self_validating.rs
  rs/types/types/src/batch/xnet.rs
  rs/types/types/src/canister_http.rs
  rs/types/types/src/consensus/dkg.rs
  rs/types/types/src/consensus/payload.rs
Labels: fix, @consensus, @execution

#3287 feat(sns): Enable upgrading SNS-controlled canisters using chunked WASMs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
  rs/nervous_system/root/src/change_canister.rs
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/src/types/tests.rs
  rs/sns/governance/unreleased_changelog.md
  rs/sns/integration_tests/src/upgrade_canister.rs
Labels: feat, @nns-team

#3475 chore(boundary): `ic-boundary` enable rate-limits autoscaling
  ic-os/components/ic/share/ic-boundary.env
Labels: chore

#3459 feat(icrc-ledger-types): Add default encoding and decoding of a Principal in a Subaccount.
  packages/icrc-ledger-types/CHANGELOG.md
  packages/icrc-ledger-types/src/icrc1/account.rs
Labels: feat, @finint

#3470 test: parallelize the ic_xc_cketh_test setup function
  rs/tests/cross_chain/ic_xc_cketh_test.rs
Labels: test, @cross-chain-team

#3464 fix(sns): rename `proposal_types_disallowed_in_pre_initialization_swap` → `functions_disallowed_in_pre_initialization_swap`
  rs/sns/cli/src/propose.rs
  rs/sns/governance/src/types.rs
Labels: fix

#3425 feat(PocketIC): new call response types
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/HOWTO.md
  packages/pocket-ic/README.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/slow.rs
  packages/pocket-ic/tests/tests.rs
  rs/bitcoin/checker/tests/tests.rs
  rs/boundary_node/rate_limits/integration_tests/src/pocket_ic_helpers.rs
  rs/ledger_suite/icp/archive/tests/tests.rs
  rs/ledger_suite/icp/test_utils/src/pocket_ic_helpers/mod.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/test.rs
  rs/rosetta-api/icp/tests/integration_tests/tests/tests.rs
Labels: feat, @boundary-node, @pocket-ic, @nns-team, @cross-chain-team, @finint

#3433 feat(node): Add time synchronization check to setupOS
  ic-os/components/setupos-scripts/check-ntp.sh
  ic-os/components/setupos-scripts/setupos.sh
  ic-os/components/setupos.bzl
Labels: feat, @node

#3483 fix(system-tests-k8s): exclude long tests
  .github/workflows/system-tests-k8s.yml
Labels: fix, @idx

#3480 fix(icp-rosetta): fix icp rosetta metrics reponse time
  rs/rosetta-api/icp/src/rosetta_server.rs
Labels: fix

#3481 chore(system-tests-k8s): containerDisk poc
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/k8s/virtualmachine.rs
  rs/tests/system_tests.bzl
Labels: chore, @idx

#3451 feat(ic-nervous-system-agent): Add `submit_proposal` helper
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/agent/src/sns/governance.rs
  rs/nervous_system/integration_tests/src/lib.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/sns/governance/src/types.rs
Labels: feat

#3443 fix: EXC-1765: Fix `canister_age` metric
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/execution_environment/src/scheduler/tests.rs
Labels: fix, @execution

#3486 fix(node): update development nns_url
  ic-os/setupos/defs.bzl
  rs/ic_os/config/src/generate_testnet_config.rs
Labels: fix, @node

#3478 feat: icrc-cbor: initial version of the library
  packages/icrc-cbor/CHANGELOG.md
Labels: feat

#3441 chore(ckbtc): upgrade ckBTC ledger suite
  rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_01_17.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_01_17.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_01_17.md
Labels: chore, @cross-chain-team

#3493 fix: icrc-ledger-types: update Cargo.toml version, update icrc-cbor dependency version
  Cargo.lock
  packages/icrc-ledger-types/Cargo.toml
Labels: fix

#3491 chore(PocketIC): retry in PocketIC bitcoin integration tests
  packages/pocket-ic/HOWTO.md
  rs/pocket_ic_server/tests/bitcoin_integration_tests.rs
Labels: chore, @pocket-ic

#3492 feat(PocketIC): new library function PocketIc::ingress_status_as
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
Labels: feat

#3382 chore: Remove stream size tracking
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/messaging/src/routing/stream_builder.rs
  rs/messaging/src/routing/stream_builder/tests.rs
  rs/messaging/src/routing/stream_handler.rs
  rs/messaging/src/routing/stream_handler/tests.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: chore, @execution, @ic-message-routing-owners

#3399 refactor: improve ic-admin command structure
  rs/registry/admin/src/main.rs
Labels: refactor

#3377 feat: Allow direct replacement of a node in subnet
  rs/registry/canister/src/common/test_helpers.rs
  rs/registry/canister/src/mutations/node_management/do_add_node.rs
  rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
  rs/registry/unreleased_changelog.md
Labels: feat, @nns-team

#3495 chore: Improve some state tool error messages
  rs/state_tool/src/commands/copy.rs
  rs/state_tool/src/main.rs
Labels: chore

#3496 chore: [EXC-1835] Make ic management types private to the execution environment
  rs/types/management_canister_types/BUILD.bazel
Labels: chore, @execution

#3315 chore(boundary): `rate-limit` canister install proposal
  rs/boundary_node/rate_limits/proposals/install_10-01-2025_134775.md
Labels: chore, @boundary-node

#3479 fix: Use lower case for Wasm persistence modes
  rs/types/management_canister_types/src/lib.rs
Labels: fix, @execution

#3501 chore(IDX): bump cc-rs
  .github/workflows/test-namespace-darwin.yaml
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/cc_rs.patch
  bazel/external_crates.bzl
Labels: chore, @idx

#3420 feat(fuzzing): Add syscall monitoring to canister sandbox
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/execution_environment/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/fuzz_targets/execute_subnet_message_update_settings.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api_call.rs
  rs/execution_environment/fuzz/src/lib.rs
Labels: feat, @idx, @execution

#3498 test(sns): Bump expected SNS dapp canister upgrade time from 30 to 60 seconds in testing
  rs/sns/integration_tests/src/upgrade_canister.rs
Labels: test

#3467 chore: improve the creation of the p2p handlers and managers
  rs/p2p/consensus_manager/src/lib.rs
  rs/p2p/consensus_manager/tests/test.rs
  rs/p2p/state_sync_manager/src/lib.rs
  rs/p2p/state_sync_manager/tests/common.rs
  rs/p2p/test_utils/src/turmoil.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: chore, @consensus

#3510 test(sns): bump expected max ballot age to reduce flakiness in //rs/sns/integration_tests:integration_test_src/proposals
  rs/sns/integration_tests/src/proposals.rs
Labels: test, @nns-team

#3514 fix(system-tests-k8s): hourly targets
  .github/workflows/system-tests-k8s.yml
Labels: fix, @idx

#3515 fix(ci): broaden `git_remote` match in repro-check script
  ci/tools/repro-check.sh
Labels: fix

#3488 feat(nervous-system): Add crate candid-utils and add proper Candid service argument validation
  Cargo.lock
  Cargo.toml
  rs/nervous_system/candid_utils/BUILD.bazel
  rs/nervous_system/candid_utils/Cargo.toml
  rs/nervous_system/candid_utils/src/lib.rs
  rs/nervous_system/candid_utils/src/validation.rs
  rs/nervous_system/candid_utils/src/validation/tests.rs
Labels: feat, @nns-team

#3517 feat(BOUN-1335): add ratelimiter metrics, bump ic-gateway
  ic-os/boundary-guestos/context/Dockerfile
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/sharded.rs
Labels: feat

#3519 chore(system-tests-k8s): use --local_test_jobs
  .github/workflows/system-tests-k8s.yml
Labels: chore, @idx

#3525 fix(k8s-system-tests): containerDisk for boundary node
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/boundary_node.rs
  rs/tests/driver/src/k8s/tnet.rs
Labels: fix, @idx

#2386 chore(IDX): remove docker-login
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
  Cargo.lock
  ci/container/README.md
  ci/container/build-image.sh
  ci/scripts/docker-login.sh
  ic-os/boundary-guestos/context/Dockerfile
  toolchains/sysimage/build_container_base_image.py
Labels: chore, @idx, @boundary-node, @node, CI_ALL_BAZEL_TARGETS

#3532 chore: Restore Cargo.lock
  Cargo.lock
Labels: chore

#3530 fix(IDX): use llvm-clang on Intel macOS
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx, CI_MACOS_INTEL

#3520 fix(ICRC_Ledger): FI-1645: use default deserialization value of 0 for ledger state's ledger_version
  WORKSPACE.bazel
  mainnet-canister-revisions.json
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
Labels: fix, @idx, @nns-team, @finint

#3534 test(ICP_Rosetta): FI-1646: Address ICP Rosetta integration tests flakiness
  rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel
Labels: test, @finint

#3385 chore(RUN-1012): infrastructure to increase Wasm64 heap memory size
  rs/config/src/embedders.rs
  rs/config/src/execution_environment.rs
  rs/drun/src/main.rs
  rs/embedders/benches/embedders_bench/src/lib.rs
  rs/embedders/src/wasm_utils.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/tests/validation.rs
  rs/embedders/tests/wasmtime_embedder.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/query_handler.rs
  rs/execution_environment/src/query_handler/query_context.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/execution_test.rs
  rs/messaging/src/routing/stream_handler/tests.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/types/types/src/lib.rs
Labels: chore, @execution, @ic-message-routing-owners, @ic-interface-owners, @languages

#3538 feat(ICRC_Ledger): FI-1600: Download the latest ICRC ledger release instead of tip of master
  rs/rosetta-api/scripts/download_latest_icrc1_ledger.sh
Labels: feat, @finint

#3401 chore: Creating a unified mechanism to generate blocklists for ckBTC and ckETH
  rs/cross-chain/scripts/generate_blocklist.py
Labels: chore

#3528 test(crypto): lower `canister_sig_verification_cache_test` test params
  rs/tests/crypto/canister_sig_verification_cache_test.rs
Labels: test, @crypto-team

#3540 fix: Correct the value returned for replicated vs non replicated execution in system api
  rs/system_api/src/lib.rs
  rs/system_api/tests/common/mod.rs
  rs/system_api/tests/system_api.rs
Labels: fix

#3541 chore(system-tests-k8s): misc changes
  .github/workflows/system-tests-k8s.yml
Labels: chore, @idx

#3542 fix: [EXC-1842] Charge for ic0_cycles_burn128
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/src/wasmtime_embedder/system_api_complexity.rs
  rs/execution_environment/benches/system_api/execute_update.rs
Labels: fix, @execution

#3543 fix: Make mint_cycles128 test more robust
  rs/tests/execution/general_execution_test.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
Labels: fix, @execution

#3536 feat(governance-tools): Made the output from add-release-to-changelog a little better.
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: feat

#3522 refactor(consensus): Refactor code in NiDkg to prepare VetKD implementation
  rs/consensus/dkg/src/dkg_key_manager.rs
  rs/consensus/dkg/src/lib.rs
  rs/consensus/dkg/src/payload_builder.rs
  rs/consensus/dkg/src/payload_validator.rs
  rs/consensus/src/cup_utils.rs
  rs/consensus/utils/src/lib.rs
  rs/replay/src/lib.rs
  rs/test_utilities/consensus/src/lib.rs
  rs/types/types/src/consensus/dkg.rs
Labels: refactor, @consensus

#3524 test(Consensus): Add a stub test for vetkd
  Cargo.lock
  Cargo.toml
  rs/tests/consensus/vetkd/BUILD.bazel
  rs/tests/consensus/vetkd/Cargo.toml
  rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs
Labels: test, @consensus

#3489 perf(nns): Add a benchmark for listing proposals
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance/benches.rs
Labels: perf

#3434 chore(ckbtc): Remove empty ReceivedUtxos events from event log
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/src/lifecycle/upgrade.rs
  rs/bitcoin/ckbtc/minter/src/storage.rs
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3527 fix: EXC-1815: Fix sandbox processes metric
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
Labels: fix, @execution
