Repository dfinity/ic, pull requests merged in 2025-10, with the labels that each got.

#6897 feat: Add a split function to State Machine Tests that actually splits the Replicated State
  Cargo.lock
  rs/state_machine_tests/BUILD.bazel
  rs/state_machine_tests/Cargo.toml
  rs/state_machine_tests/src/lib.rs
Labels: feat, @execution, @ic-message-routing-owners

#6916 perf(crypto): adapt vault message size histrogram buckets
  rs/crypto/internal/logmon/src/metrics.rs
Labels: perf, @crypto-team

#7030 chore(nns): remove left todo's
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/timer_tasks/calculate_distributable_rewards.rs
Labels: chore

#7010 fix(ICP_Ledger): FI-1872: Add in_executor_context for ICP ledger notify endpoints
  rs/ledger_suite/icp/ledger/src/main.rs
Labels: fix, @finint

#6939 perf(crypto): CRP-2933: send only raw internal dealing in vault's idkg_load_transcript
  rs/crypto/internal/crypto_service_provider/src/vault/api.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/idkg/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/idkg/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_client.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/transcript.rs
  rs/crypto/test_utils/local_csp_vault/src/lib.rs
Labels: perf, @crypto-team

#7012 chore(Ledgers): Remove unused dependencies
  Cargo.lock
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/Cargo.toml
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icrc1/archive/BUILD.bazel
  rs/ledger_suite/icrc1/index-ng/BUILD.bazel
  rs/ledger_suite/test_utils/in_memory_ledger/BUILD.bazel
  rs/ledger_suite/test_utils/in_memory_ledger/Cargo.toml
  rs/ledger_suite/test_utils/state_machine_helpers/BUILD.bazel
  rs/rosetta-api/common/rosetta_core/BUILD.bazel
  rs/rosetta-api/common/rosetta_core/Cargo.toml
Labels: chore, @finint

#6928 feat(nervous_system): Create rate-limit library
  Cargo.lock
  Cargo.toml
  rs/nervous_system/rate_limits/BUILD.bazel
  rs/nervous_system/rate_limits/Cargo.toml
  rs/nervous_system/rate_limits/src/lib.rs
  rs/nervous_system/rate_limits/src/tests.rs
  rs/nervous_system/time_helpers/src/lib.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/tests/list_neurons.rs
  rs/nns/governance/src/governance/tests/list_proposals.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/governance/tests/stake_maturity.rs
  rs/nns/governance/src/reward/distribution.rs
  rs/nns/governance/tests/governance.rs
Labels: feat, @governance-team

#7032 fix: add aliases for request type variants for backwards compatibility
  rs/boundary_node/rate_limits/api/src/schema_versions/v1.rs
Labels: fix

#7041 test(ICRC-Ledger): FI-1874: endpoint that disables icrc3 in the test ledger
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/BUILD.bazel
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/icrc3_test_ledger.did
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/src/main.rs
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/tests/tests.rs
Labels: test, @finint

#6911 fix(icrc-ledger-types): FI-1866: Add try_from_subaccount_to_principal
  packages/icrc-ledger-types/CHANGELOG.md
  packages/icrc-ledger-types/src/icrc1/account.rs
Labels: fix, @finint

#6814 feat(dogecoin): facade for ckdoge minter canister
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  publish/canisters/BUILD.bazel
  rs/bitcoin/ckbtc/minter/src/guard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/lifecycle/init.rs
  rs/bitcoin/ckbtc/minter/src/lifecycle/upgrade.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
  rs/dogecoin/ckdoge/minter/BUILD.bazel
  rs/dogecoin/ckdoge/minter/Cargo.toml
  rs/dogecoin/ckdoge/minter/ckdoge_minter.did
  rs/dogecoin/ckdoge/minter/src/candid_api.rs
  rs/dogecoin/ckdoge/minter/src/lib.rs
  rs/dogecoin/ckdoge/minter/src/lifecycle/init.rs
  rs/dogecoin/ckdoge/minter/src/lifecycle/mod.rs
  rs/dogecoin/ckdoge/minter/src/main.rs
  rs/dogecoin/ckdoge/minter/tests/tests.rs
  rs/dogecoin/ckdoge/test_utils/BUILD.bazel
  rs/dogecoin/ckdoge/test_utils/Cargo.toml
  rs/dogecoin/ckdoge/test_utils/src/lib.rs
  rs/dogecoin/ckdoge/test_utils/src/minter.rs
Labels: feat, @idx, @ic-interface-owners, @cross-chain-team, @ic-owners-owners, CI_ALL_BAZEL_TARGETS

#7036 chore: Improve error suggestion for CanisterMetadataSectionNotFound
  rs/execution_environment/src/canister_manager/types.rs
Labels: chore

#7017 chore(node): clean up nested test and improve code reuse
  rs/tests/nested/guestos_upgrade.rs
  rs/tests/nested/hostos_upgrade.rs
  rs/tests/nested/src/util.rs
Labels: chore, @node

#7019 chore: Move tools onto config types
  ic-os/dev-tools/bare_metal_deployment/deploy.py
  rs/ic_os/dev_test_tools/setupos-image-config/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-image-config/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/main.rs
  rs/tests/driver/src/driver/bootstrap.rs
Labels: chore, @idx, @node

#7028 fix: subnet memory taken for canisters with memory allocation
  rs/execution_environment/tests/canister_snapshots.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: fix, @execution, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#7059 fix: revert "chore: Resize backup LV to 500GB (#6926)"
  ic-os/components/guestos/init/setup-lvs/setup-lvs.sh
  ic-os/components/upgrade/shared-resources/setup-shared-resources/setup-shared-backup.sh
Labels: fix

#6962 perf(idkg): CON-1593 Use multi-threading in `validate_dealings`
  rs/consensus/idkg/src/pre_signer.rs
Labels: perf, @consensus

#6961 chore: use node reward type to determine node generation
  ic-os/components/setupos/check-hardware.sh
  ic-os/components/setupos/test-setupos.sh
Labels: chore, @node

#7062 chore: unify management canister doc comments for Rust types
  rs/types/management_canister_types/src/http.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/src/provisional.rs
Labels: chore, @execution

#7067 fix: temporarily adding repro-check back to tools
  ci/tools/repro-check
Labels: fix

#6953 feat(nns): Stop exposing KnownNeuronData in list_neurons
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#7020 feat(nns): Archive topics of garbage collected proposals
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/garbage_collection.rs
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/heap_governance_data.rs
  rs/nns/governance/tests/governance.rs
Labels: feat

#6947 refactor(nns/sns): Use patching for test canister candid files
  rs/nervous_system/patch_canister_did/BUILD.bazel
  rs/nervous_system/patch_canister_did/defs.bzl
  rs/nervous_system/patch_canister_did/helper.sh
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/canister/governance_test.did.patch
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/canister/governance_test.did.patch
Labels: refactor, @governance-team

#7079 fix: add empty governance_test.did files to make cargo clippy succeed
  rs/nns/governance/canister/governance_test.did
  rs/sns/governance/canister/governance_test.did
Labels: fix, @governance-team

#7068 chore: Shorten NNS delegation refresh interval
  rs/http_endpoints/nns_delegation_manager/src/nns_delegation_manager.rs
Labels: chore

#6932 feat: Allow canister_status via query call
  rs/config/src/subnet_config.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/query_handler.rs
  rs/execution_environment/tests/execution_test.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @execution

#7009 test(recovery): use separate SSH keys in recovery system tests
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/utils/src/node.rs
  rs/tests/consensus/utils/src/ssh_access.rs
  rs/tests/driver/src/driver/test_env.rs
  rs/tests/nested/nns_recovery/common.rs
Labels: test, @idx, @consensus, @node, CI_ALL_BAZEL_TARGETS

#6710 feat: whitelisting mechanism for node swapping feature
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/src/flags.rs
  rs/registry/canister/src/init.rs
  rs/registry/canister/src/mutations/do_swap_node_in_subnet_directly.rs
  rs/registry/canister/tests/common/test_helpers.rs
  rs/registry/canister/tests/swap_node_in_subnet_directly.rs
Labels: feat, @execution, CI_ALL_BAZEL_TARGETS, @governance-team

#7100 refactor(nns): Tiny refactor on the `record_neuron_vote`
  rs/nns/governance/src/neuron_store.rs
Labels: refactor

#7066 feat(ckdoge): derive Dogecoin address for deposits
  Cargo.lock
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
  rs/dogecoin/ckdoge/minter/ckdoge_minter.did
  rs/dogecoin/ckdoge/minter/src/address/mod.rs
  rs/dogecoin/ckdoge/minter/src/address/tests.rs
  rs/dogecoin/ckdoge/minter/src/candid_api.rs
  rs/dogecoin/ckdoge/minter/src/lib.rs
  rs/dogecoin/ckdoge/minter/src/lifecycle/init.rs
  rs/dogecoin/ckdoge/minter/src/main.rs
  rs/dogecoin/ckdoge/minter/src/updates/get_doge_address.rs
  rs/dogecoin/ckdoge/minter/src/updates/mod.rs
  rs/dogecoin/ckdoge/minter/tests/tests.rs
  rs/dogecoin/ckdoge/test_utils/BUILD.bazel
  rs/dogecoin/ckdoge/test_utils/Cargo.toml
  rs/dogecoin/ckdoge/test_utils/src/lib.rs
  rs/dogecoin/ckdoge/test_utils/src/minter.rs
Labels: feat

#7090 fix: update subnet available memory after unstalling code and updating canister history
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution/install_code.rs
  rs/execution_environment/src/execution/install_code/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/canister_history.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/system_state.rs
Labels: fix, @execution, @ic-message-routing-owners

#7103 feat(nns): neuron follow restrictions feature flag
  rs/nns/governance/src/lib.rs
Labels: feat

#7056 test(ICRC-Ledger): add archiving to the test icrc3 ledger
  Cargo.lock
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/BUILD.bazel
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/Cargo.toml
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/icrc3_test_ledger.did
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/src/lib.rs
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/src/main.rs
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/tests/tests.rs
Labels: test, @finint

#7088 feat: [EXC-1848] Enrich `CallOrigin` with method name 1/2
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager/proto.rs
Labels: feat, @execution, @ic-message-routing-owners

#7119 feat(IDX): use gh hosted runner for python tests
  .github/workflows/ci-main.yml
Labels: feat, @idx

#7120 feat(IDX): move bazel-target job to gh hosted runners
  .github/workflows/ci-main.yml
Labels: feat, @idx

#7053 chore(node): surface HostOS console logs in nested environment
  ic-os/components/hostos.bzl
  ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.service
  ic-os/components/misc/output-wrapper.sh
  ic-os/components/networking/generate-network-config/generate-network-config-hostos.service
  ic-os/components/setupos.bzl
Labels: chore, @node

#7113 chore(node): update chrony service logs
  ic-os/components/setupos/check-ntp.sh
Labels: chore, @node

#7099 refactor(cmc/root): Fix a few places where ic_cdk_macros are not used
  rs/nns/cmc/src/main.rs
  rs/nns/handlers/lifeline/impl/BUILD.bazel
  rs/nns/handlers/root/impl/canister/canister.rs
  rs/nns/handlers/root/impl/canister/root.did
  rs/nns/integration_tests/src/cycles_minting_canister.rs
Labels: refactor, @governance-team

#7096 feat: Update PocketIC's routing table when syncing the registry
  Cargo.lock
  rs/migration_canister/tests/tests.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat, @execution

#7127 chore(IDX): replace dependencies-check runner
  .github/workflows/ci-pr-only.yml
Labels: chore, @idx

#7124 refactor(IDX): combine CI cargo jobs
  .github/workflows/ci-main.yml
Labels: refactor, @idx, CI_RUN_CARGO_JOBS

#7126 fix(PocketIC): stop HTTP gateways before deleting PocketIC instance
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: fix, @execution

#7129 refactor: Use SubnetConfig in ExecutionTestBuilder to group configuration options in tests
  rs/test_utilities/execution_environment/src/lib.rs
Labels: refactor

#7141 fix: install cargo audit and wasm-pack
  .github/workflows/ci-pr-only.yml
Labels: fix

#7142 test(pocket-ic): test index and ledger with the same balance
  packages/pocket-ic/tests/icp_features.rs
Labels: test

#7143 chore(IDX): replace lock-generate runner
  .github/workflows/ci-pr-only.yml
Labels: chore, @idx

#7086 fix(nns-recovery): fix `registry_store_uri` parameter in NNS recovery on same nodes
  rs/recovery/src/steps.rs
  rs/replay/src/cmd.rs
  rs/replay/src/lib.rs
Labels: fix, @consensus
