Repository dfinity/ic, pull requests merged in 2025-04, with the labels that each got.

#4538 chore(PocketIC): code cleanup
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/tests/test.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_machine_tests/tests/multi_subnet.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#4596 fix: Use default value for SnapshotSource instead of failing.
  rs/state_layout/src/state_layout.rs
  rs/types/management_canister_types/src/lib.rs
Labels: fix, @execution, @ic-message-routing-owners

#4614 test(NODE-1579): nested systests: increase resources for host VM
  rs/tests/driver/src/driver/resource.rs
Labels: test, @idx

#4617 feat(IDX): enable auto-approvals for mainnet-icos-revisions
  .github/CODEOWNERS
  .github/workflows/auto-approve.yml
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: feat, @idx, @ic-owners-owners

#4611 refactor: Rename embedders/system_api.rs to embedders/linker.rs
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/src/wasmtime_embedder/linker.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
Labels: refactor, @execution

#4501 feat(ci): add improved reproducibility verification script (repro-check)
  .github/CODEOWNERS
  README.adoc
  ci/tools/repro-check
  ci/tools/repro-check.sh
Labels: feat, @idx, @ic-owners-owners

#4563 feat(sns): neuron `SetFollowing` command is validated in composition
  rs/sns/governance/src/following.rs
  rs/sns/governance/src/following/tests.rs
  rs/sns/governance/src/governance.rs
Labels: feat, @nns-team

#4601 test(consensus): add https outcalls compliance tests for response headers
  rs/tests/networking/canister_http_correctness_test.rs
Labels: test

#4624 chore(nns): Use the correct icrc1 index candid file
  rs/sns/cli/dfx.json
  rs/sns/dfx.json
Labels: chore

#4541 feat(nns): Disable Neuron Fund for new SNSs
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/src/create_service_nervous_system_builder.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/advance_sns_target_version.rs
  rs/nervous_system/integration_tests/tests/advance_target_version_upgrades_all_canisters_test.rs
  rs/nervous_system/integration_tests/tests/custom_upgrade_path.rs
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
  rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/test_data.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/create_service_nervous_system.rs
  rs/nns/integration_tests/src/lib.rs
  rs/nns/sns-wasm/src/init.rs
  rs/nns/test_utils/src/common.rs
  rs/registry/admin/tests/integration_tests.rs
Labels: feat, @nns-team

#4478 chore(ICP-Archive): remove migration to stable structures code
  Cargo.lock
  rs/ledger_suite/icp/archive/BUILD.bazel
  rs/ledger_suite/icp/archive/Cargo.toml
  rs/ledger_suite/icp/archive/src/main.rs
  rs/ledger_suite/icp/archive/tests/tests.rs
  rs/ledger_suite/icp/tests/golden_nns_state.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
Labels: chore, @finint

#4621 revert: "feat: [NODE-1566] Build with hermetic cc toolchains (#3508)"
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  MODULE.bazel
  WORKSPACE.bazel
  bazel/BUILD.bazel
  bazel/cc_rs.patch
  bazel/conf/.bazelrc.build
  bazel/external_crates.bzl
  bazel/fuzz_testing.bzl
  bazel/hermetic_cc_toolchain.patch
  cpp/BUILD.bazel
  hs/spec_compliance/BUILD.bazel
  hs/spec_compliance/defs.bzl
  publish/defs.bzl
  third_party/libfuzzer/BUILD.bazel
  third_party/libfuzzer/repository.bzl
  third_party/openssl/BUILD.bazel
  third_party/openssl/repository.bzl
Labels: revert, @idx, @product-security, @node, @research

#4623 chore: log composite and expensive canister http transforms
  rs/execution_environment/src/query_handler/query_context.rs
Labels: chore, @execution

#4620 test(CON-1472): Enable VetKD in upgrade/downgrade & backup tests
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/upgrade/downgrade_app_subnet_test.rs
  rs/tests/consensus/upgrade/upgrade_app_subnet_test.rs
  rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS

#4633 fix(IDX): fix the neuron_voting test_voting_can_span_multiple_rounds
  rs/nns/integration_tests/src/neuron_voting.rs
Labels: fix, @nns-team

#4527 refactor: Use generics and `impl trait` instead of `dyn trait`
  rs/execution_environment/src/lib.rs
  rs/http_endpoints/xnet/src/lib.rs
  rs/http_endpoints/xnet/src/tests.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/message_routing/tests.rs
  rs/messaging/src/scheduling/valid_set_rule.rs
  rs/replica/src/setup_ic_stack.rs
  rs/replica_tests/src/lib.rs
Labels: refactor

#4264 feat(Ledger_Canister_Core): FI-1689: Report ledger blocks in at most one location
  rs/ledger_suite/common/ledger_canister_core/BUILD.bazel
  rs/ledger_suite/common/ledger_canister_core/src/ledger.rs
  rs/ledger_suite/common/ledger_canister_core/src/range_utils.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: feat, @finint

#4609 chore(IDX): pr title validaton event
  .github/workflows/ci-pr-title-validation.yml
Labels: chore, @idx

#4569 feat(icrc1-rosetta): [FI-1635] Multitoken ICRC1 Rosetta
  packages/icrc-ledger-agent/src/lib.rs
  rs/rosetta-api/common/rosetta_core/src/watchdog.rs
  rs/rosetta-api/icp/src/rosetta_server.rs
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/Cargo.toml
  rs/rosetta-api/icrc1/client/src/lib.rs
  rs/rosetta-api/icrc1/runner/src/lib.rs
  rs/rosetta-api/icrc1/src/common/storage/storage_operations.rs
  rs/rosetta-api/icrc1/src/common/utils/utils.rs
  rs/rosetta-api/icrc1/src/construction_api/endpoints.rs
  rs/rosetta-api/icrc1/src/data_api/endpoints.rs
  rs/rosetta-api/icrc1/src/data_api/services.rs
  rs/rosetta-api/icrc1/src/ledger_blocks_synchronization/blocks_synchronizer.rs
  rs/rosetta-api/icrc1/src/lib.rs
  rs/rosetta-api/icrc1/src/main.rs
  rs/rosetta-api/icrc1/tests/common/local_replica.rs
  rs/rosetta-api/icrc1/tests/integration_test_components/blocks_synchronizer/fetching_blocks_interval_test.rs
  rs/rosetta-api/icrc1/tests/integration_test_components/storage/storing_blockchain_data_test.rs
  rs/rosetta-api/icrc1/tests/integration_test_components/test_setup.rs
  rs/rosetta-api/icrc1/tests/multitoken_system_tests.rs
  rs/rosetta-api/icrc1/tests/system_tests.rs
Labels: feat

#4613 chore(IDX): reordering steps
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: chore, @idx

#4600 feat(proposal-cli): move arguments and wasm verification next to each other
  rs/cross-chain/proposal-cli/src/candid/mod.rs
  rs/cross-chain/proposal-cli/src/candid/tests.rs
  rs/cross-chain/proposal-cli/src/git/mod.rs
  rs/cross-chain/proposal-cli/templates/install.md
  rs/cross-chain/proposal-cli/templates/upgrade.md
Labels: feat, @cross-chain-team

#4632 chore: Change new canister snapshot fields to be optional
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
  rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/lib.rs
Labels: chore, @execution, @ic-message-routing-owners, @ic-interface-owners, CI_ALL_BAZEL_TARGETS, CI_OVERRIDE_BUF_BREAKING

#4495 feat(PocketIC): new function PocketIcBuilder::with_read_only_state_dir
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  rs/pocket_ic_server/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat, @pocket-ic

#4635 chore(dep-mgmt): Update owning team for `hardware-wallet-cli`
  ci/src/dependencies/job/npm_scanner_periodic_job.py
Labels: chore

#4552 feat: EXC-2005: Prefetch pages backward
  rs/execution_environment/benches/baseline/EMBEDDERS_HEAP.min
  rs/memory_tracker/src/lib.rs
  rs/memory_tracker/src/tests.rs
Labels: feat, @execution

#4625 chore(crypto): CRP-2629 Add VetKD to the state machine tests
  Cargo.lock
  Cargo.toml
  packages/ic-vetkd-utils/src/lib.rs
  rs/crypto/test_utils/vetkd/BUILD.bazel
  rs/crypto/test_utils/vetkd/Cargo.toml
  rs/crypto/test_utils/vetkd/src/lib.rs
  rs/crypto/test_utils/vetkd/tests/tests.rs
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/tests/threshold_signatures.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/state_machine_tests/BUILD.bazel
  rs/state_machine_tests/Cargo.toml
  rs/state_machine_tests/src/lib.rs
Labels: chore, @execution, @pocket-ic, @crypto-team, @ic-message-routing-owners

#4522 chore(EXC-1991): Remove in-memory compilation cache
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/embedders/src/compilation_cache.rs
  rs/embedders/src/lib.rs
  rs/embedders/src/serialized_module.rs
  rs/embedders/src/wasm_executor.rs
Labels: chore, @execution

#4272 feat(node): Nested HostOS upgrade test to/from version parameters
  BUILD.bazel
  WORKSPACE.bazel
  bazel/mainnet-icos-images.bzl
  ic-os/dev-tools/hostos-upgrade-tests.sh
  rs/ic_os/dev_test_tools/setupos-inject-configuration/src/main.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
  rs/tests/nested/upgrade.rs
  rs/tests/system_tests.bzl
Labels: feat, @idx, @node, CI_ALL_BAZEL_TARGETS

#4646 chore: remove flaky nested tests from hourly pipeline
  rs/tests/nested/BUILD.bazel
Labels: chore, @node

#4645 chore: extend mainnet_revisions.py to update hostos version
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: chore, @idx

#4640 fix(EXC-2011): Speed up wasm64 check
  Cargo.lock
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/src/canister_manager.rs
Labels: fix

#4652 feat(icrc-rosetta): add icrc rosetta release 1.2.0
  Cargo.lock
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/CHANGELOG.md
  rs/rosetta-api/icrc1/Cargo.toml
  rs/rosetta-api/icrc1/src/common/constants.rs
Labels: feat

#4650 chore(fuzzing): Cleanup AFL flags
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  bin/afl_wrapper.sh
  ci/container/Dockerfile
  ci/container/TAG
Labels: chore, @idx, @product-security, @finint

#4642 chore: EXC: Reduce number of benchmark samples
  rs/embedders/benches/compilation.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/benches/system_api/execute_query.rs
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/benches/wasm_instructions/main.rs
Labels: chore, @execution

#4654 fix(fuzzing): Limit `bazel-run-fuzzers-hourly` to zh1
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: fix, @idx

#4655 revert: Bump --bes_timeout flag for sandbox_fuzzing builds to 600s (#4649)
  bin/run-all-fuzzers.sh
Labels: revert, @idx

#4653 perf: EXC: Run more execution benchmarks periodically
  .github/workflows/schedule-rust-bench.yml
Labels: perf, @idx

#4657 fix: add missing dependencies for small_nns testnet
  rs/tests/testnets/BUILD.bazel
Labels: fix, @idx

#4659 fix: rename the orchestrator binary crate from `ic_state_tool` to `orchestrator`
  rs/orchestrator/BUILD.bazel
Labels: fix, @consensus

#4631 chore: Fix some typos in the comments on `HypervisorError`
  rs/interfaces/src/execution_environment/errors.rs
Labels: chore, @ic-interface-owners

#4662 fix(IDX): Extract CI build config
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/scripts/run-build-ic.sh
Labels: fix, @idx

#4583 feat(sns): Extend `cast_vote_and_cascade_follow` to take topic-based following into account
  rs/sns/governance/src/follower_index.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/cast_vote_and_cascade_follow_tests.rs
  rs/sns/governance/src/neuron.rs
  rs/sns/governance/src/topics.rs
Labels: feat, @nns-team

#4130 test: Add missing VetKD state machine test cases
  rs/execution_environment/tests/threshold_signatures.rs
Labels: test, @execution

#4572 feat: [CON-1404] Remove the timeout of computing the state hash in `ic-replay`
  Cargo.lock
  rs/replay/BUILD.bazel
  rs/replay/Cargo.toml
  rs/replay/src/ingress.rs
  rs/replay/src/player.rs
Labels: feat, @consensus, CI_ALL_BAZEL_TARGETS

#4628 feat(node_reward): Add the basic calculation to the Node Reward Canister
  Cargo.lock
  rs/nervous_system/canisters/BUILD.bazel
  rs/nervous_system/canisters/Cargo.toml
  rs/nervous_system/canisters/src/registry.rs
  rs/nns/test_utils/src/common.rs
  rs/nns/test_utils/src/itest_helpers.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/node_rewards/canister/BUILD.bazel
  rs/node_rewards/canister/Cargo.toml
  rs/node_rewards/canister/api/src/lib.rs
  rs/node_rewards/canister/api/src/lifecycle_args.rs
  rs/node_rewards/canister/api/src/monthly_rewards.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/canister.rs
  rs/node_rewards/canister/src/lib.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/src/test.rs
  rs/node_rewards/canister/tests/regisry_sync_test.rs
  rs/node_rewards/canister/unreleased_changelog.md
  rs/registry/canister-client/BUILD.bazel
  rs/registry/canister-client/Cargo.toml
  rs/registry/canister-client/src/lib.rs
  rs/registry/canister-client/src/stable_canister_client.rs
  rs/registry/canister-client/src/stable_canister_client/tests.rs
  rs/registry/canister-client/src/stable_memory.rs
  rs/registry/node_provider_rewards/src/logs.rs
Labels: feat, @dre, @nns-team

#4651 fix(Ledger): FI-1689: Return the archived ranges in order
  rs/ledger_suite/common/ledger_canister_core/src/ledger.rs
Labels: fix, @finint

#4669 chore(nns): Update changelogs after 3/28 release
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
Labels: chore, @nns-team

#4587 chore(IDX): pass diff.sh inputs explicitly
  .github/actions/bazel-test-all/action.yaml
  ci/bazel-scripts/diff.sh
  ci/scripts/run-build-ic.sh
Labels: chore, @idx

#4664 chore(IDX): move opts out of `--config=ci`
  .github/actions/bazel/bin/bazel
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  bazel/conf/.bazelrc.build
  bazel/conf/.bazelrc.internal
Labels: chore, @idx

#4665 feat(PocketIC): VetKd support
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/HOWTO.md
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat, @pocket-ic

#4561 chore(MR-664): Track outgoing responses in streams
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: chore, @execution, @ic-message-routing-owners

#4679 chore(NODE-1579): fix flakiness in nested systests by only running them in dm1
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/src/lib.rs
Labels: chore, @node

#4674 chore(IDX): version bumps
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  ci/container/Dockerfile
  ci/container/TAG
Labels: chore, @idx, @finint, CI_ALL_BAZEL_TARGETS, CI_MACOS_INTEL

#4518 chore: log requests with invalid ingress expiry
  Cargo.lock
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/src/common.rs
Labels: chore, @consensus

#4630 chore(ICP-Ledger): remove stable structures migration code
  WORKSPACE.bazel
  mainnet-canister-revisions.json
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/src/lib.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/golden_nns_state.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: chore, @idx, @finint

#4684 feat(ckbtc): Make bitcoin checker's init argument optional
  rs/bitcoin/checker/btc_checker_canister.did
  rs/bitcoin/checker/src/main.rs
  rs/bitcoin/checker/tests/tests.rs
Labels: feat, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#4622 chore(NODE-1579): support configuring number of vCPUs for GuestOS VM
  ic-os/components/hostos-scripts/generate-guestos-config/dev-generate-guestos-config.sh
  ic-os/components/hostos-scripts/generate-guestos-config/generate-guestos-config.sh
  ic-os/components/hostos-scripts/guestos/guestos.xml.template
  ic-os/components/hostos-scripts/guestos/kvm-cpu.xml
  ic-os/components/hostos-scripts/guestos/qemu-cpu.xml
  ic-os/components/hostos.bzl
  ic-os/setupos/data/deployment.json.template
  rs/ic_os/config/src/deployment_json.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/update_config.rs
  rs/ic_os/config_types/src/lib.rs
  rs/ic_os/dev_test_tools/setupos-inject-configuration/src/main.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/resource.rs
Labels: chore, @idx, @node

#4675 chore: Fix typos in the scheduler
  rs/execution_environment/src/scheduler.rs
Labels: chore, @execution

#4696 feat(nns): Always panic when pb methods are called
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#4627 chore: Add metrics for reading wasm files in execution
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
Labels: chore, @execution

#4504 feat(ICRC_Ledger): FI-1702: Always return ICRC-3 compliant certificate from ICRC ledger
  Cargo.lock
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/Cargo.toml
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/tests/common/local_replica.rs
  rs/rosetta-api/icrc1/tests/integration_test_components/blocks_synchronizer/fetching_blocks_interval_test.rs
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/Cargo.toml
  rs/tests/financial_integrations/icrc1_agent_test.rs
Labels: feat, @finint

#4676 chore: EXC-2009: Make benchmark groups unique
  rs/embedders/benches/compilation.rs
  rs/embedders/benches/embedders_bench/src/lib.rs
  rs/embedders/benches/heap.rs
  rs/embedders/benches/stable_memory.rs
  rs/execution_environment/benches/system_api/execute_inspect_message.rs
  rs/execution_environment/benches/system_api/execute_query.rs
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/benches/wasm_instructions/main.rs
Labels: chore, @execution

#4694 test: ic-prep Add the data center records to the registry
  rs/prep/src/internet_computer.rs
Labels: test, CI_TEST_ALL_BAZEL_TARGETS

#4699 chore: EXC: Update benchmarks baseline
  rs/execution_environment/benches/baseline/EMBEDDERS_COMPILATION.min
  rs/execution_environment/benches/baseline/EMBEDDERS_STABLE_MEMORY.min
  rs/execution_environment/benches/baseline/SYSTEM_API_INSPECT_MESSAGE.min
  rs/execution_environment/benches/baseline/SYSTEM_API_QUERY.min
  rs/execution_environment/benches/baseline/SYSTEM_API_UPDATE.min
Labels: chore, @execution

#4715 chore(IDX): remove alerts for ic version workflow
  .github/workflows/slack-workflow-run.yml
Labels: chore, @idx

#4717 chore(IDX): lock generate checkout
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
Labels: chore, @idx

#4724 test(IDX): explicitly check for reboot in nested upgrade tests
  rs/tests/nested/src/lib.rs
Labels: test, @node

#4505 feat: [EXC-1957] Read canister snapshot data
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @execution, @ic-message-routing-owners

#4692 chore(crypto): CRP-2645 Use ic-vetkd-utils for VetKD key derivation
  Cargo.lock
  packages/ic-vetkd-utils/src/lib.rs
  rs/crypto/tests/vetkd.rs
  rs/crypto/utils/canister_threshold_sig/BUILD.bazel
  rs/crypto/utils/canister_threshold_sig/Cargo.toml
  rs/crypto/utils/canister_threshold_sig/src/lib.rs
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
Labels: chore, @execution, @crypto-team

#4733 docs(node): clean up icos documentation
  ic-os/README.adoc
  ic-os/hostos/README.adoc
Labels: docs, @node

#4737 chore(IDX): don't validate on synchronize
  .github/workflows/ci-pr-title-validation.yml
Labels: chore, @idx

#4739 test(consensus): remove redundant system test for non existing transform function
  rs/tests/networking/canister_http_correctness_test.rs
Labels: test, @consensus

#4689 test: Add checks for Traps in the Random Traffic Canister Framework
  rs/messaging/tests/common/mod.rs
  rs/messaging/tests/memory_tests.rs
  rs/rust_canisters/random_traffic_test/src/main.rs
Labels: test, @ic-message-routing-owners

#4741 test(Multitoken_Rosetta): FI-1699: Add more resources for icrc_multitoken_rosetta_system test
  rs/rosetta-api/icrc1/BUILD.bazel
Labels: test, @finint

#4745 chore(IDX): rust bench runner info
  .github/workflows/schedule-rust-bench.yml
Labels: chore, @idx

#4740 feat(crypto): CRP-2733 run vetKD benches for more subnet sizes
  rs/crypto/benches/vetkd.rs
Labels: feat, @crypto-team, CI_ALL_BAZEL_TARGETS

#4747 refactor(registry): Get rid of `pb_encode` function.
  rs/registry/canister/src/registry.rs
Labels: refactor, @nns-team

#4742 feat(MR): [MR-649] Enable best-effort calls everywhere
  rs/config/src/embedders.rs
Labels: feat

#4530 chore(ICP-Rosetta): removing canister client library dependency
  Cargo.lock
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/Cargo.toml
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/src/canister_access.rs
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/test_utils/BUILD.bazel
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/test_utils/Cargo.toml
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/test_utils/src/sample_data.rs
  rs/rosetta-api/icp/src/ledger_client.rs
Labels: chore, @finint

#4693 feat(nns): Allow Governance to request rewards from Node Reward canister instead of registry (behind flag)
  Cargo.lock
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/handlers/root/impl/BUILD.bazel
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/nns/integration_tests/src/governance_mem_test.rs
  rs/nns/integration_tests/src/governance_upgrade.rs
  rs/nns/integration_tests/src/node_provider_remuneration.rs
  rs/nns/sns-wasm/BUILD.bazel
  rs/nns/sns-wasm/tests/deploy_new_sns.rs
  rs/nns/sns-wasm/tests/get_deployed_sns_by_proposal_id.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/main.rs
  rs/sns/integration_tests/BUILD.bazel
  rs/sns/integration_tests/src/sns_treasury.rs
Labels: feat, @dre, @nns-team, CI_OVERRIDE_DIDC_CHECK

#4701 chore(nns): Keep memory ids sorted
  rs/nns/governance/src/storage.rs
Labels: chore

#4714 feat(sns): Fine-grained unsetting of legacy proposal following while setting topic following
  rs/nervous_system/agent/src/sns/governance.rs
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/set_following.rs
  rs/sns/governance/src/follower_index.rs
  rs/sns/governance/src/following.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#4404 feat(nns): Define VotingPowerSnapshot and a collection of snapshots
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/voting_power_snapshots.rs
  rs/nns/governance/src/governance/voting_power_snapshots_tests.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/voting_power.rs
Labels: feat, @nns-team

#4730 chore(node): fix config_types vm_nr_of_vcpus default
  rs/ic_os/config_types/src/lib.rs
Labels: chore, @node

#4678 test(Ledger): FI-1689: Tests for archive chunking and ranges
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#4743 feat(ckbtc): Allow get_btc_address calls from anonymous principal
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/updates/get_btc_address.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
Labels: feat

#4762 test: Resurrect `system_api` tests
  Cargo.lock
  rs/embedders/BUILD.bazel
  rs/embedders/Cargo.toml
  rs/embedders/tests/common/mod.rs
  rs/embedders/tests/sandbox_safe_system_state.rs
  rs/embedders/tests/system_api.rs
  rs/embedders/tests/system_api_tracking.rs
Labels: test

#4775 chore(IDX): temporarily disable ic_xc_cketh_test
  rs/tests/cross_chain/BUILD.bazel
Labels: chore, @cross-chain-team

#4752 feat(sns): Proposals can be filtered by topic
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/tests/governance.rs
  rs/sns/governance/unreleased_changelog.md
Labels: feat, @nns-team, CI_ALL_BAZEL_TARGETS

#4778 chore: bump crossbeam-channel to 0.5.15 (#4767)
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore

#4765 fix: fix did test for bitcoin mock canister
  Cargo.lock
  rs/bitcoin/mock/BUILD.bazel
  rs/bitcoin/mock/Cargo.toml
  rs/bitcoin/mock/bitcoin_mock.did
Labels: fix, @cross-chain-team, CI_OVERRIDE_DIDC_CHECK

#4758 feat(registry): Added some conversions to HighCapacity types.
  rs/registry/transport/src/high_capacity.rs
  rs/registry/transport/src/high_capacity_tests.rs
  rs/registry/transport/src/lib.rs
Labels: feat, @nns-team

#4703 test(Ledger): FI-1691: Correct handling of expired allowances in InMemoryLedger
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger/tests.rs
Labels: test, @finint

#4760 fix(ICP_Rosetta): FI-1507: Write ICP Rosetta port file atomically
  Cargo.lock
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/Cargo.toml
  rs/rosetta-api/icp/src/rosetta_server.rs
Labels: fix, @finint

#4783 chore: Revert "feat: Introduce low bound for canister's freezing threshold (#4401)"
  Cargo.lock
  hs/spec_compliance/src/IC/Test/Spec/CanisterHistory.hs
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/execution/call_or_task/tests.rs
  rs/execution_environment/src/execution/response/tests.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/tests/dts.rs
  rs/execution_environment/tests/execution_test.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/execution_environment/tests/subnet_size_test.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/nns/integration_tests/src/update_canister_settings.rs
  rs/sns/integration_tests/BUILD.bazel
  rs/sns/integration_tests/Cargo.toml
  rs/sns/integration_tests/src/manage_dapp_canister_settings.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/tests/execution/general_execution_tests/canister_lifecycle.rs
Labels: chore, @execution, @nns-team, @finint, @research

#4766 feat: update ic-gateway package
  ic-os/boundary-guestos/context/Dockerfile
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
Labels: feat, CI_ALL_BAZEL_TARGETS

#4708 feat(PocketIC): new struct PocketIcState
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat, @pocket-ic

#4771 chore(IDX): use execution log for determinism checks
  .github/actions/bazel-test-all/action.yaml
  .github/actions/bazel/action.yaml
  .github/actions/bazel/bin/bazel
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  bazel/tools/cmpbuildlogs/BUILD.bazel
  bazel/tools/cmpbuildlogs/main.go
Labels: chore, @idx

#4772 test(sns): Faster set-following tests
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/tests/set_following.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/tests/governance.rs
Labels: test, @nns-team

#4782 test(ICRC_Ledger): Remove migration-related checks in ICRC ledger suite golden state test
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint, CI_ALL_BAZEL_TARGETS

#4780 fix: re-enable `ic_xc_cketh_test`
  MODULE.bazel
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/cross_chain/ic_xc_cketh_test.rs
Labels: fix, @idx, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#4709 chore(ckbtc): Upgrade the btc checker
  rs/bitcoin/ckbtc/mainnet/btc_checker_upgrade_2025_04_08.md
Labels: chore

#4712 fix: [EXC-2006] Improve constants in wasm chunk store
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
Labels: fix, @execution, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#4770 feat(nns): Add an index for maturity disbursement based on finalization timestamp
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/maturity_disbursement_index.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/storage.rs
  rs/nns/governance/src/storage/neuron_indexes.rs
Labels: feat

#4791 chore(IDX): clean up execlogs workflows
  .github/actions/bazel-test-all/action.yaml
  .github/actions/bazel-upload-checksums/action.yaml
  .github/actions/bazel/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#4793 chore(nns): update changelogs
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/node_rewards/canister/CHANGELOG.md
  rs/node_rewards/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: chore, @dre, @nns-team

#4774 feat(nns): Define NeuronAsyncLock to be compatible with safer access pattern to global state
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron_lock.rs
  rs/nns/governance/src/neuron_lock_tests.rs
Labels: feat

#4405 feat(nns): Add a timer task to perform voting power snapshots
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/voting_power.rs
  rs/nns/governance/src/storage.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#3782 chore(nns): Delete flags related to periodic confirmation of following.
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/neuron_store/metrics/tests.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/integration_tests/src/neuron_following.rs
Labels: chore, @nns-team

#4711 test(IDX): move //rs/execution_environment:execution_environment_misc_integration_tests/dts to its own target
  rs/execution_environment/BUILD.bazel
Labels: test, @execution

#4785 chore: [NODE-1580] export hostos config as metric
  ic-os/components/hostos-scripts/monitoring/custom-metrics.sh
Labels: chore, @node

#4677 chore: Add a Contributing.md file in rs/embedders
  rs/README.adoc
  rs/embedders/Contributing.md
Labels: chore, @execution, @ic-interface-owners

#4786 chore(fuzzing): Switch to ExecutionTest framework from StateMachine
  rs/execution_environment/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: chore, @execution

#4796 fix(ICRC_Ledger): FI-1709: Recompute ICRC ledger certified data in post upgrade
  Cargo.lock
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/Cargo.toml
  rs/ledger_suite/icrc1/ledger/src/benches/mod.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
Labels: fix, @finint

#4807 fix: Make the Heartbeat Counter on the Random Traffic Canister increment only for substantial Heartbeats.
  rs/rust_canisters/random_traffic_test/src/main.rs
Labels: fix, @ic-message-routing-owners

#4729 feat: [EXC-2018] Enable snapshot data download in statemachine tests
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/benches/management_canister/MANAGEMENT_CANISTER.md
  rs/execution_environment/benches/management_canister/canister_snapshots.rs
  rs/execution_environment/benches/management_canister/utils.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @execution, @pocket-ic, @ic-message-routing-owners

#4685 chore(ic-replay): [CON-1493] add more logs to `ic-replay`
  rs/replay/src/lib.rs
  rs/replay/src/player.rs
Labels: chore, @consensus, CI_ALL_BAZEL_TARGETS

#4777 fix: switch to checkpoint for wasm binaries in canister snapshots
  rs/state_manager/src/lib.rs
  rs/state_manager/tests/state_manager.rs
Labels: fix, @ic-message-routing-owners

#4728 chore(EXC-1802): Remove old sandbox rpc calls
  rs/canister_sandbox/BUILD.bazel
  rs/canister_sandbox/Cargo.toml
  rs/canister_sandbox/bin/test_controller.rs
  rs/canister_sandbox/bin/test_sandbox.rs
  rs/canister_sandbox/src/protocol/sbxsvc.rs
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/canister_sandbox/src/sandbox_client_stub.rs
  rs/canister_sandbox/src/sandbox_manager.rs
  rs/canister_sandbox/src/sandbox_server.rs
  rs/canister_sandbox/src/sandbox_service.rs
Labels: chore, @execution

#4761 feat(registry): Library for chunkifying whale registry mutations.
  Cargo.lock
  Cargo.toml
  rs/registry/canister/chunkify/BUILD.bazel
  rs/registry/canister/chunkify/Cargo.toml
  rs/registry/canister/chunkify/src/lib.rs
  rs/registry/canister/chunkify/src/tests.rs
Labels: feat

#4797 refactor(nns): Initialize NNS Governance with candid
  rs/nns/integration_tests/src/neuron_following.rs
  rs/nns/integration_tests/src/reinstall_and_upgrade.rs
  rs/nns/test_utils/src/itest_helpers.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: refactor, @nns-team

#4757 refactor(ckbtc): Clean up types used by ckbtc minter
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/src/address.rs
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/guard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/lifecycle/init.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/src/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/get_btc_address.rs
  rs/bitcoin/ckbtc/minter/src/updates/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs
  rs/bitcoin/ckbtc/minter/tests/dump_stable_memory.rs
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
  rs/tests/ckbtc/src/lib.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3902 feat: [CON-1469] periodically fetch the nns delegation
  Cargo.lock
  rs/http_endpoints/fuzz/BUILD.bazel
  rs/http_endpoints/public/src/call/call_v3.rs
  rs/http_endpoints/public/src/lib.rs
  rs/http_endpoints/public/src/metrics.rs
  rs/http_endpoints/public/src/nns_delegation_manager.rs
  rs/http_endpoints/public/src/query.rs
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/http_endpoints/public/src/read_state/subnet.rs
  rs/http_endpoints/public/tests/common/mod.rs
  rs/https_outcalls/client/src/client.rs
  rs/https_outcalls/client/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/replica/BUILD.bazel
  rs/replica/Cargo.toml
  rs/replica/src/setup_ic_stack.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/nns_delegation_test.rs
Labels: feat, @consensus, @product-security, @pocket-ic, CI_ALL_BAZEL_TARGETS

#4734 chore: [MR-675] Deserialize wasm with hash always present
  rs/protobuf/def/state/canister_snapshot_bits/v1/canister_snapshot_bits.proto
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_snapshot_bits.v1.rs
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state/tests.rs
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/tip.rs
  rs/types/wasm_types/src/lib.rs
Labels: chore, @execution, @ic-message-routing-owners, @ic-interface-owners, CI_ALL_BAZEL_TARGETS, CI_OVERRIDE_BUF_BREAKING

#4818 fix: api bn: update `ic-gateway`, increase h2 streams, lower shedding threshold
  ic-os/boundary-guestos/context/Dockerfile
  ic-os/components/ic/share/ic-boundary.env
Labels: fix, @boundary-node, @node

#4753 chore(node): Improve orchestrator node_operator_private_key.pem logging
  rs/orchestrator/src/registration.rs
Labels: chore, @consensus

#4805 chore: unifying downloading logic
  Cargo.lock
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/Cargo.toml
  rs/ic_os/vsock/vsock_lib/src/host/agent.rs
Labels: chore, @node

#4827 fix(nns): Turn off disburse maturity which was incorrectly turned on
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/nns.bzl
Labels: fix

#4828 feat(registry): Node Rewards can target a specific version
  rs/registry/canister/api/src/lib.rs
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/get_node_providers_monthly_xdr_rewards.rs
  rs/registry/canister/src/mutations/node_management/common.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @nns-team

#4754 test(node_rewards): Create a test to prove same results as registry
  Cargo.lock
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/Cargo.toml
  rs/nns/integration_tests/src/lib.rs
  rs/nns/integration_tests/src/node_provider_remuneration_migration.rs
  rs/nns/test_utils/prepare_golden_state/src/watch_and_prepare.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/node_rewards/canister/src/canister.rs
  rs/node_rewards/canister/unreleased_changelog.md
  rs/registry/canister-client/src/stable_canister_client.rs
  rs/registry/canister-client/src/stable_canister_client/tests.rs
Labels: test, @dre, @nns-team

#4829 fix(consnesus): Fix reshare chain key validation
  rs/consensus/idkg/src/payload_verifier.rs
Labels: fix, @consensus, CI_ALL_BAZEL_TARGETS

#4830 test: Increase subnet size to 4 nodes in recovery tests
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/subnet_recovery/sr_nns_same_nodes_test.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS

#4835 test(consensus): Increase number of retries of get signature in system tests
  rs/tests/consensus/tecdsa/utils/src/lib.rs
Labels: test, @consensus

#4836 fix: revert "chore: unifying downloading logic (#4805)"
  Cargo.lock
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/Cargo.toml
  rs/ic_os/vsock/vsock_lib/src/host/agent.rs
Labels: fix, @node

#4841 feat: ic-gateway 0.2.7
  ic-os/boundary-guestos/context/Dockerfile
Labels: feat

#4845 feat: bump ic-gateway to 0.2.8
  ic-os/boundary-guestos/context/Dockerfile
Labels: feat

#4844 feat(node_rewards): limit caller to governance for xdr rewards
  Cargo.lock
  rs/nns/integration_tests/src/node_provider_remuneration_migration.rs
  rs/node_rewards/canister/BUILD.bazel
  rs/node_rewards/canister/Cargo.toml
  rs/node_rewards/canister/api/src/monthly_rewards.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
  rs/node_rewards/canister/unreleased_changelog.md
Labels: feat, @dre, @nns-team

#4749 fix: memory usage checks in management canister
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
Labels: fix, @execution, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#4824 chore: refactor QuerySource
  rs/drun/src/message.rs
  rs/execution_environment/src/query_handler/query_cache.rs
  rs/execution_environment/src/query_handler/query_context.rs
  rs/execution_environment/src/query_handler/query_scheduler.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/https_outcalls/client/src/client.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/types/types/src/messages/http.rs
  rs/types/types/src/messages/query.rs
  rs/validator/ingress_message/tests/validate_request.rs
Labels: chore, @consensus, @execution, @crypto-team, @ic-interface-owners, @languages

#4817 chore: CON-1478 Grant backup user read access to artifact pools
  ic-os/components/ic/setup-permissions/setup-permissions.sh
  ic-os/guestos/context/Dockerfile
Labels: chore, @node, CI_ALL_BAZEL_TARGETS

#4849 refactor(ic-canisters-http-types): Copy crate ic-canisters-http-types to /packages in preparation for publication
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  packages/ic-http-types/BUILD.bazel
  packages/ic-http-types/CHANGELOG.md
  packages/ic-http-types/Cargo.toml
  packages/ic-http-types/LICENSE
  packages/ic-http-types/README.md
  packages/ic-http-types/src/lib.rs
Labels: refactor, @ic-owners-owners

#4851 refactor: rename replica_version to guestos_version
  rs/registry/admin/src/main.rs
Labels: refactor, @idx, @nns-team

#4705 test(sns): Porting sns-testing to the ICP mono repo, Part III
  Cargo.lock
  rs/nervous_system/agent/src/agent_impl.rs
  rs/nervous_system/agent/src/helpers/nns.rs
  rs/nervous_system/agent/src/helpers/sns.rs
  rs/nervous_system/agent/src/lib.rs
  rs/nervous_system/agent/src/mock.rs
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/agent/src/sns/governance.rs
  rs/nervous_system/agent/src/state_machine_impl.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/sns/testing/BUILD.bazel
  rs/sns/testing/Cargo.toml
  rs/sns/testing/README.md
  rs/sns/testing/scripts/env.sh
  rs/sns/testing/src/bin/init.rs
  rs/sns/testing/src/bin/main.rs
  rs/sns/testing/src/lib.rs
  rs/sns/testing/src/main.rs
  rs/sns/testing/src/nns_dapp.rs
  rs/sns/testing/src/sns.rs
  rs/sns/testing/src/utils.rs
  rs/sns/testing/tests/sns_testing_ci.rs
Labels: test

#4833 fix: update parsing of power measurements via IPMI tool
  ic-os/components/hostos-scripts/monitoring/monitor-power.sh
Labels: fix, @node

#4847 chore(node): unify downloading logic
  Cargo.lock
  rs/ic_os/vsock/vsock_lib/BUILD.bazel
  rs/ic_os/vsock/vsock_lib/Cargo.toml
  rs/ic_os/vsock/vsock_lib/src/host/agent.rs
Labels: chore, @node

#4819 refactor(crypto): CRP-2619 rename ChainKeySigningSubnetList to ChainKeyEnabledSubnetList
  rs/consensus/tests/framework/mod.rs
  rs/consensus/vetkd/src/lib.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/message_routing/tests.rs
  rs/prep/src/initialized_subnet.rs
  rs/protobuf/def/registry/crypto/v1/crypto.proto
  rs/protobuf/src/gen/crypto/registry.crypto.v1.rs
  rs/protobuf/src/gen/registry/registry.crypto.v1.rs
  rs/protobuf/src/gen/state/registry.crypto.v1.rs
  rs/protobuf/src/gen/types/registry.crypto.v1.rs
  rs/registry/admin/src/main.rs
  rs/registry/canister/src/invariants/common.rs
  rs/registry/canister/src/invariants/crypto/tests.rs
  rs/registry/canister/src/mutations/do_recover_subnet.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/canister/src/mutations/subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/registry/helpers/src/chain_keys.rs
  rs/registry/keys/src/lib.rs
  rs/state_machine_tests/src/lib.rs
Labels: refactor, @consensus, @pocket-ic, @nns-team, @ic-message-routing-owners, @ic-interface-owners, @utopia, CI_ALL_BAZEL_TARGETS

#4855 test(node_rewards): Migrate tests from Registry's node reward calculation
  Cargo.lock
  rs/nervous_system/canisters/src/registry.rs
  rs/nns/integration_tests/src/node_provider_remuneration.rs
  rs/node_rewards/canister/BUILD.bazel
  rs/node_rewards/canister/Cargo.toml
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_monthly_xdr_rewards.rs
  rs/node_rewards/canister/src/canister/test/mod.rs
  rs/node_rewards/canister/src/lib.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/src/test.rs
  rs/registry/canister-client/src/stable_canister_client/tests.rs
Labels: test, @dre, @nns-team

#4862 fix: correct the hash of liblmdb
  third_party/lmdb/repository.bzl
Labels: fix, @idx

#4755 feat: PocketIC tests on Windows
  .github/workflows/pocket-ic-build-windows.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/slack-workflow-run.yml
  packages/pocket-ic/HOWTO.md
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/tests/test.rs
Labels: feat, @idx, @pocket-ic

#4852 chore: Add contributing guide for management canister APIs
  rs/execution_environment/Contributing.md
Labels: chore
