Repository dfinity/ic, pull requests merged in 2025-05, with the labels that each got.

#4931 fix(node): hostos_upgrade_from_mainnet_to_mainnet
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/src/lib.rs
  rs/tests/system_tests.bzl
Labels: fix, @idx, @node

#4924 feat(nns): Validate the maturity disbursement index
  rs/nns/governance/src/maturity_disbursement_index.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/storage/neurons.rs
Labels: feat, @nns-team

#4949 feat(nns): Expose maturity disbursements as part of neuron
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron/types/tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/integration_tests/src/governance_neurons.rs
Labels: feat, @nns-team

#4950 test(sns): Check that NNS Governance and SNS-W can be upgraded without each other
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
Labels: test

#4905 chore(nervous-system): Update changelog for release 2025-04-25
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/node_rewards/canister/CHANGELOG.md
  rs/node_rewards/canister/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
Labels: chore, @dre

#4939 feat(nns): Enable node rewards from new canister
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#4955 test(nns): Check voting rewards and node rewards after an upgrade in golden state test
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
Labels: test, CI_ALL_BAZEL_TARGETS

#4942 chore(ckbtc): add upgrade proposals for archive, ledger, and index canisters (2025-04-14)
  rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_04_14.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_04_14.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_04_14.md
Labels: chore, @cross-chain-team

#4948 chore: EXC-2033: Summarize results by top time improvements
  rs/execution_environment/benches/run-benchmark.sh
  rs/execution_environment/benches/summarize-results.sh
Labels: chore, @execution

#2956 chore(ckbtc): update README
  rs/bitcoin/ckbtc/minter/README.adoc
Labels: chore, @cross-chain-team

#4958 test: tune the slow //rs/execution_environment:dts_test
  rs/execution_environment/BUILD.bazel
Labels: test, @execution

#4959 feat(IDX): run minimal macos intel build on PRs
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: feat, @idx

#4954 feat(registry): Add canister migrations endpoint with no functionality
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/mutations/do_migrate_canisters.rs
  rs/registry/canister/src/mutations/mod.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @nns-team

#4917 chore: Tidy up IC-OS tmpfs
  bazel/conf/.bazelrc.build
  ic-os/components/conformance_tests/check_file_references.py
  toolchains/sysimage/BUILD.bazel
  toolchains/sysimage/build_container_base_image.py
  toolchains/sysimage/build_container_filesystem_tar.py
  toolchains/sysimage/build_disk_image.py
  toolchains/sysimage/build_ext4_image.py
  toolchains/sysimage/build_fat32_image.py
  toolchains/sysimage/build_lvm_image.py
  toolchains/sysimage/build_upgrade_image.py
  toolchains/sysimage/build_vfat_image.py
  toolchains/sysimage/container_utils.py
  toolchains/sysimage/proc_wrapper.sh
  toolchains/sysimage/toolchain.bzl
  toolchains/sysimage/verity_sign.py
Labels: chore, @idx, @node

#4945 feat(icp-rosetta): add icp rosetta release 2.1.4
  Cargo.lock
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/CHANGELOG.md
  rs/rosetta-api/icp/Cargo.toml
Labels: feat

#4974 fix(node): bare-metal-deploy tempfile
  ic-os/dev-tools/bare_metal_deployment/deploy.py
Labels: fix, @node

#4971 test(ICRC_Ledger): FI-1719: Skip FuelEV in ICRC SNS golden state test
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint, CI_ALL_BAZEL_TARGETS

#4966 feat: [MR-606] Break out dropped message metrics by kind / context / class
  rs/messaging/src/message_routing.rs
  rs/messaging/src/state_machine.rs
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/lib.rs
  rs/replicated_state/src/replicated_state.rs
  rs/replicated_state/tests/replicated_state.rs
Labels: feat

#4975 test(nns): Initialize `neuron_minimum_dissolve_delay_to_vote_seconds` before upgrading NNS canisters in qualification tests
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: test, @idx, @nns-team, CI_ALL_BAZEL_TARGETS

#4967 feat(nns): Consider neurons with maturity disbursements as non empty
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
Labels: feat

#4953 feat(registry): Create new key family for canister_ranges
  rs/registry/keys/src/lib.rs
Labels: feat, @nns-team

#4881 feat(nns): Stop recording new snapshots when there is a spike
  rs/nns/governance/src/governance/voting_power_snapshots.rs
  rs/nns/governance/src/governance/voting_power_snapshots_tests.rs
  rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs
Labels: feat

#4980 feat(sns): Make topic `DaoCommunitySettings` critical
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_lifecycle.rs
  rs/nervous_system/integration_tests/tests/sns_topics.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/tests/governance.rs
  rs/sns/governance/unreleased_changelog.md
  rs/sns/integration_tests/src/proposals.rs
Labels: feat, @nns-team

#4857 feat(node): add compatibility_tests for config_types
  .github/workflows-source/ci-pr-only.yml
  .github/workflows/ci-pr-only.yml
  ci/scripts/generate-config-fixtures.sh
  rs/ic_os/config_types/compatibility_tests/BUILD.bazel
  rs/ic_os/config_types/compatibility_tests/Cargo.toml
  rs/ic_os/config_types/compatibility_tests/README.md
  rs/ic_os/config_types/compatibility_tests/fixtures/hostos_v1.0.0.json
  rs/ic_os/config_types/compatibility_tests/fixtures/hostos_v1.1.0.json
  rs/ic_os/config_types/compatibility_tests/src/fixture.rs
  rs/ic_os/config_types/compatibility_tests/src/lib.rs
  rs/ic_os/config_types/compatibility_tests/src/main.rs
  rs/ic_os/config_types/compatibility_tests/tests/compatibility_tests.rs
  rs/ic_os/config_types/src/lib.rs
Labels: feat, @idx, @node

#4989 chore: Unify message class label values
  rs/execution_environment/src/metrics.rs
  rs/messaging/tests/call_tree_tests.rs
Labels: chore, @ic-message-routing-owners

#4991 feat(IDX): add arm64-linux pocket-ic builds
  .github/workflows/test-namespace-arm64-linux.yaml
Labels: feat, @idx

#4979 fix(crypto): use production subnet size and threshold in vetKD crypto library tests
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
Labels: fix, @crypto-team

#4901 feat(crypto): CRP-2777 enhance vetKD key lifecycle system test
  Cargo.lock
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/tests/consensus/vetkd/BUILD.bazel
  rs/tests/consensus/vetkd/Cargo.toml
  rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs
Labels: feat, @consensus, CI_ALL_BAZEL_TARGETS

#4994 chore(IDX): add os_info repository rule
  MODULE.bazel
  bazel/os_info.bzl
  publish/binaries/BUILD.bazel
Labels: chore, @idx

#4926 refactor(cketh): remove direct https outcalls
  rs/ethereum/cketh/minter/BUILD.bazel
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/providers.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/requests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/responses.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_error/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_error/tests.rs
  rs/ethereum/cketh/minter/src/tests.rs
  rs/ethereum/cketh/test_utils/BUILD.bazel
  rs/ethereum/cketh/test_utils/Cargo.toml
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/ethereum/cketh/test_utils/src/provider.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#4895 chore: Use ic-cdk 0.18.0 on Message Routing related canisters
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/rust_canisters/downstream_calls_test/BUILD.bazel
  rs/rust_canisters/downstream_calls_test/Cargo.toml
  rs/rust_canisters/downstream_calls_test/src/main.rs
  rs/rust_canisters/random_traffic_test/Cargo.toml
  rs/rust_canisters/random_traffic_test/src/main.rs
  rs/rust_canisters/xnet_test/BUILD.bazel
  rs/rust_canisters/xnet_test/Cargo.toml
  rs/rust_canisters/xnet_test/src/lib.rs
  rs/rust_canisters/xnet_test/src/main.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/Cargo.toml
  rs/tests/message_routing/common/BUILD.bazel
  rs/tests/message_routing/common/Cargo.toml
  rs/tests/message_routing/common/common.rs
  rs/tests/message_routing/global_reboot_test.rs
Labels: chore, @idx, @ic-message-routing-owners

#4815 chore(IDX): k8s perf tests and config changes
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/driver/src/k8s/config.rs
  rs/tests/driver/src/k8s/images.rs
  rs/tests/driver/src/k8s/tnet.rs
Labels: chore, @idx, @consensus

#4903 refactor(cross-chain): use public crate ic-management-canister-types
  Cargo.lock
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/Cargo.toml
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/ethereum/ledger-suite-orchestrator/BUILD.bazel
  rs/ethereum/ledger-suite-orchestrator/Cargo.toml
  rs/ethereum/ledger-suite-orchestrator/src/management/mod.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/BUILD.bazel
  rs/ethereum/ledger-suite-orchestrator/test_utils/Cargo.toml
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/flow.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/universal_canister.rs
  rs/ethereum/ledger-suite-orchestrator/tests/tests.rs
  rs/tests/ckbtc/BUILD.bazel
  rs/tests/ckbtc/Cargo.toml
  rs/tests/ckbtc/src/lib.rs
Labels: refactor, @cross-chain-team

#4987 refactor(nns): Stop calculating metrics from heap_neurons
  rs/nns/governance/src/neuron_store/metrics.rs
Labels: refactor

#4969 refactor(nns): Stop validating heap neurons
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store.rs
Labels: refactor

#4988 feat(registry): migrate_canisters endpoint updates routing table
  rs/registry/canister/src/mutations/do_migrate_canisters.rs
  rs/registry/canister/src/mutations/routing_table.rs
  rs/registry/canister/unreleased_changelog.md
  rs/registry/routing_table/src/lib.rs
Labels: feat, @nns-team

#5006 chore(nns): Stop registering ballots in with_neuron_mut
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/neuron_store/benches.rs
Labels: chore

#4919 chore: Consolidate and standardize sysimage tools
  ic-os/components/defs.bzl
  ic-os/defs.bzl
  toolchains/sysimage/BUILD.bazel
  toolchains/sysimage/build_container_base_image.py
  toolchains/sysimage/build_container_filesystem_tar.py
  toolchains/sysimage/build_fat32_image.py
  toolchains/sysimage/build_lvm_image.py
  toolchains/sysimage/build_vfat_image.py
  toolchains/sysimage/toolchain.bzl
  toolchains/sysimage/utils.py
Labels: chore, @node

#4245 feat(CRP-2711): Migrate registry to reshare chain key endpoint
  rs/registry/canister/src/mutations/do_create_subnet.rs
  rs/registry/canister/src/mutations/do_recover_subnet.rs
  rs/registry/canister/src/mutations/subnet.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @nns-team, CI_ALL_BAZEL_TARGETS

#5019 fix: //ic-os/.../:disk.img targets
  toolchains/sysimage/toolchain.bzl
Labels: fix

#4927 chore(EXC-2035): Upgrade Wasmtime to v.32
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/cranelift-assembler-lib.patch
  bazel/cranelift-assembler-main.patch
  bazel/cranelift-codegen-meta-isle.patch
  bazel/cranelift-isle.patch
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
Labels: chore, @idx, @execution

#5008 chore(crypto): CRP-2788 Rename IBE parameter from context to identity
  packages/ic-vetkd-utils/src/lib.rs
  packages/ic-vetkd-utils/tests/tests.rs
Labels: chore

#5012 chore: Remove final reference to ICOS_TMPDIR
  rs/ic_os/build_tools/inject_files/src/main.rs
Labels: chore, @node

#5001 chore(NET-1765): ramp up new socks proxy discovery to 50%
  rs/https_outcalls/adapter/src/rpc_server.rs
  rs/https_outcalls/adapter/tests/server_test.rs
Labels: chore, @consensus

#5032 test(nns): Fix the golden NNS state test by voting the ManageNetworkEconomics proposal with well-known public neurons
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: test

#4848 feat: [NODE-1566] Build with hermetic cc toolchains (again)
  .github/actions/bazel/bin/bazel
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  MODULE.bazel
  WORKSPACE.bazel
  bazel/BUILD.bazel
  bazel/cc_rs.patch
  bazel/conf/.bazelrc.build
  bazel/external_crates.bzl
  bazel/fuzz_testing.bzl
  bazel/hermetic_cc_toolchain.patch
  bazel/rules_rust.patch
  ci/container/container-run.sh
  cpp/BUILD.bazel
  hs/spec_compliance/BUILD.bazel
  hs/spec_compliance/defs.bzl
  third_party/libfuzzer/BUILD.bazel
  third_party/libfuzzer/repository.bzl
  third_party/openssl/BUILD.bazel
  third_party/openssl/repository.bzl
Labels: feat, @idx, @product-security, @node, CI_ALL_BAZEL_TARGETS, @research, CI_MACOS_INTEL, CI_TEST_ALL_BAZEL_TARGETS

#5002 chore(IDX): rename checksum_rule to artifact_bundle
  ci/container/build-ic.sh
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
  publish/binaries/BUILD.bazel
  publish/canisters/BUILD.bazel
  publish/defs.bzl
Labels: chore, @idx, @node

#5014 feat: CRP-2618 Allow zero `pre_signatures_to_create_in_advance` in vetKD `ChainKeyConfig`
  rs/consensus/dkg/src/lib.rs
  rs/consensus/dkg/src/utils.rs
  rs/consensus/tests/framework/mod.rs
  rs/consensus/vetkd/src/test_utils.rs
  rs/registry/canister/src/invariants/crypto.rs
  rs/registry/canister/src/invariants/crypto/tests.rs
  rs/types/management_canister_types/src/lib.rs
Labels: feat, @consensus, @execution, @nns-team, CI_TEST_ALL_BAZEL_TARGETS

#5036 docs: chore(sns): Fix in-code documentation typos for internal SNS Governance types
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
Labels: docs, @nns-team

#5028 chore(crypto): CRP-2789 Use a fixed length domain separator for IBE message mask
  packages/ic-vetkd-utils/src/lib.rs
  packages/ic-vetkd-utils/tests/tests.rs
Labels: chore

#5041 chore: log the size of the file to be uploaded to Farm
  rs/tests/driver/src/driver/farm.rs
Labels: chore, @idx

#5045 chore(nns): Remove governance_migration test as it was created for neuron migration
  rs/nns/integration_tests/src/governance_migrations.rs
  rs/nns/integration_tests/src/lib.rs
Labels: chore

#5035 refactor(cketh): remove retry counts histograms
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/main.rs
Labels: refactor, @cross-chain-team

#5050 chore: add more logs to nns delegation manager
  rs/http_endpoints/public/src/nns_delegation_manager.rs
  rs/p2p/quic_transport/src/connection_manager.rs
Labels: chore, @consensus

#5021 refactor(cketh): clean up eth_get_finalized_transaction_count, eth_get_latest_transaction_count, and eth_get_logs call
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5023 feat: populating `timestamp_seconds` in the registry canister
  rs/nns/integration_tests/src/registry_get_chunk.rs
  rs/registry/canister/src/registry.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @nns-team

#5025 chore: moving farm tests from BN to API BN
  Cargo.lock
  Cargo.toml
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/boundary_nodes/Cargo.toml
  rs/tests/boundary_nodes/api_bn_decentralization_test.rs
  rs/tests/boundary_nodes/api_bn_integration_test.rs
  rs/tests/boundary_nodes/api_bn_performance_test.rs
  rs/tests/boundary_nodes/api_bn_update_workload_test.rs
  rs/tests/boundary_nodes/bn_integration_on_playnet_test.rs
  rs/tests/boundary_nodes/bn_integration_test.rs
  rs/tests/boundary_nodes/bn_reboot_test.rs
  rs/tests/boundary_nodes/custom_domains/BUILD.bazel
  rs/tests/boundary_nodes/custom_domains/Cargo.toml
  rs/tests/boundary_nodes/custom_domains/activate.sh
  rs/tests/boundary_nodes/custom_domains/cloudflare_api.py
  rs/tests/boundary_nodes/custom_domains/custom_domains_integration_test.rs
  rs/tests/boundary_nodes/custom_domains/pebble_cache.py
  rs/tests/boundary_nodes/custom_domains/setup.rs
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
  rs/tests/boundary_nodes/performance_test_common/src/lib.rs
  rs/tests/boundary_nodes/utils/src/constants.rs
  rs/tests/boundary_nodes/utils/src/helpers.rs
  rs/tests/boundary_nodes/utils/src/setup.rs
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/max_ingress_payload_size_test.rs
  rs/tests/cross_chain/BUILD.bazel
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/canister_http/canister_http.rs
  rs/tests/networking/query_workload_long_test.rs
  rs/tests/networking/subnet_update_workload/src/lib.rs
  rs/tests/networking/update_workload_large_payload.rs
  rs/tests/research/BUILD.bazel
  rs/tests/research/spec_compliance/spec_compliance.rs
Labels: chore, @idx, @consensus, @boundary-node, @cross-chain-team, @research

#5060 fix: flaky //rs/tests/consensus:replica_determinism_test
  rs/tests/consensus/replica_determinism_test.rs
Labels: fix, @consensus

#4663 feat(sns): Set initial topic-based following for swap neurons
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/src/types/tests.rs
  rs/sns/governance/unreleased_changelog.md
  rs/sns/testing/src/sns.rs
Labels: feat

#4574 chore(IDX): rules_rust: 0.56.0 -> 0.61.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  MODULE.bazel
  WORKSPACE.bazel
Labels: chore, @idx

#5054 chore(IDX): extract file size checks from icos_build
  bazel/defs.bzl
  ic-os/defs.bzl
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
  publish/canisters/BUILD.bazel
Labels: chore, @idx, @node

#5058 chore(IDX): Don't expect public update-test images
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/utils/src/upgrade.rs
  rs/tests/dre/utils/steps/ensure_elected_version.rs
Labels: chore, @dre, @consensus, CI_ALL_BAZEL_TARGETS

#5067 fix: let test-namespace-darwin use the hermetic cc toolchain
  .github/workflows/test-namespace-darwin.yaml
Labels: fix, @idx

#5017 test(CRP-2632): Extend registry unit tests to include vetkd cases
  rs/registry/canister/tests/common/test_helpers.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
Labels: test, @nns-team

#4996 chore: Translate some read state request tests to Rust
  Cargo.lock
  rs/tests/idx/wabt-tests/BUILD.bazel
  rs/tests/idx/wabt-tests/Cargo.toml
  rs/tests/idx/wabt-tests/src/lib.rs
  rs/tests/idx/wabt-tests/src/main.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/read_state_test.rs
Labels: chore, @idx, @consensus

#4340 chore: update Rust to 1.85.1
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  MODULE.bazel
  WORKSPACE.bazel
  ci/container/TAG
  rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg/fixtures.rs
  rs/interfaces/src/crypto/keygen.rs
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/ledger_suite/icrc1/src/lib.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/messaging/tests/queue_tests.rs
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/tests/merge_neurons.rs
  rs/p2p/state_sync_manager/tests/common.rs
  rs/replicated_state/benches/bench_intmap.rs
  rs/replicated_state/src/canister_state/queues/message_pool.rs
  rs/replicated_state/src/canister_state/system_state/call_context_manager.rs
  rs/replicated_state/src/page_map/int_map/test.rs
  rs/rosetta-api/icp/src/main.rs
  rs/rosetta-api/icp/src/request/serde_transfer.rs
  rs/rosetta-api/icp/src/request_handler/construction_submit.rs
  rs/rosetta-api/icrc1/src/construction_api/utils.rs
  rs/types/types/src/canister_http.rs
  rs/types/types/src/funds/cycles.rs
  rs/types/types/src/nominal_cycles.rs
  rust-toolchain.toml
Labels: chore, @idx, @dre, @consensus, @product-security, @execution, @boundary-node, @pocket-ic, @nns-team, @crypto-team, @ic-message-routing-owners, @node, @ic-interface-owners, @cross-chain-team, @finint, @ic-owners-owners, @research

#5073 chore: Update boot args key to `extra_boot_args_template`
  ic-os/defs.bzl
  ic-os/guestos/defs.bzl
Labels: chore

#5078 chore: EXC-1701: Add error doc link for canister snapshot limit error.
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
Labels: chore, @execution

#4947 feat(registry): Migrate get_changes_since callers to high-capacity
  Cargo.lock
  rs/nervous_system/canisters/BUILD.bazel
  rs/nervous_system/canisters/Cargo.toml
  rs/nervous_system/canisters/src/registry.rs
  rs/registry/canister/tests/integration_tests_2.rs
  rs/registry/nns_data_provider/BUILD.bazel
  rs/registry/nns_data_provider/Cargo.toml
  rs/registry/nns_data_provider/src/certification.rs
  rs/registry/nns_data_provider/src/certification/tests.rs
  rs/registry/nns_data_provider/src/registry.rs
  rs/registry/transport/BUILD.bazel
  rs/registry/transport/Cargo.toml
  rs/registry/transport/src/high_capacity.rs
  rs/registry/transport/src/high_capacity_tests.rs
  rs/registry/transport/src/lib.rs
  rs/replay/BUILD.bazel
  rs/replay/Cargo.toml
  rs/replay/src/player.rs
Labels: feat, @consensus, @nns-team

#5022 test(replay): Unit test for Player::get_changes_since in rs/replay.
  Cargo.lock
  rs/replay/BUILD.bazel
  rs/replay/Cargo.toml
  rs/replay/src/player.rs
Labels: test, @nns-team

#5077 chore(nns): Minor refactoring and documentation for NnsGov.register_vote
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/network_economics.rs
Labels: chore, @nns-team

#5051 fix(node): setup-disk.sh hardening
  ic-os/components/setupos-scripts/setup-disk.sh
Labels: fix, @node

#5038 chore(ckbtc): add proposal to upgrade ckBTC minter
  rs/bitcoin/ckbtc/mainnet/minter_upgrade_2025_05_08.md
Labels: chore, @cross-chain-team

#5085 chore: renaming mentions of ch1-obsdev1 into testnet
  .github/workflows/schedule-rust-bench.yml
  rs/ic_os/config/src/lib.rs
  rs/tests/consensus/tecdsa/tecdsa_performance_test_template.rs
  rs/tests/consensus/utils/src/performance.rs
  rs/tests/driver/src/driver/test_env_api.rs
  testnet/env/shared-config.yml
Labels: chore

#5037 test(registry): `ic-admin update-registry-local-store` reads large/chunked records (correctly).
  Cargo.lock
  rs/nervous_system/agent/src/lib.rs
  rs/nervous_system/agent/src/registry.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/registry/admin/BUILD.bazel
  rs/registry/admin/Cargo.toml
  rs/registry/admin/src/lib.rs
  rs/registry/admin/tests/integration_tests.rs
  rs/registry/canister/canister/canister.rs
Labels: test, @nns-team

#5064 fix: clear canister logs before instantiating new canister during reinstall
  rs/execution_environment/src/execution/install.rs
  rs/execution_environment/src/execution/install_code.rs
  rs/execution_environment/tests/canister_logging.rs
Labels: fix

#4937 chore(sns): Publish sns-testing bundle
  MODULE.bazel
  publish/binaries/BUILD.bazel
  rs/sns/testing/BUILD.bazel
Labels: chore, @idx, @nns-team

#5098 feat(IDX): Add prefix to artifact bundles
  ci/container/build-ic.sh
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
  publish/binaries/BUILD.bazel
  publish/canisters/BUILD.bazel
  publish/defs.bzl
Labels: feat, @idx, @node

#4999 perf(idkg): [CON-1497] Performance improvement when building a transcript of a certain ID
  rs/artifact_pool/src/idkg_pool.rs
  rs/artifact_pool/src/lmdb_pool.rs
  rs/consensus/idkg/src/pre_signer.rs
  rs/interfaces/src/idkg.rs
  rs/types/types/src/consensus/idkg.rs
Labels: perf, @consensus, @ic-interface-owners, CI_ALL_BAZEL_TARGETS

#5049 fix: make upload_chunk idempotent
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/replicated_state/src/canister_state/system_state/wasm_chunk_store.rs
Labels: fix, @execution, @ic-message-routing-owners

#5063 chore(nns,sns): Move release notes
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
Labels: @nns-team

#5010 test: Extend some unit tests with vet keys
  rs/recovery/src/admin_helper.rs
  rs/registry/admin/src/create_subnet.rs
  rs/registry/admin/src/recover_subnet.rs
  rs/registry/admin/src/update_subnet.rs
  rs/registry/canister/tests/common/test_helpers.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/registry/subnet_features/src/lib.rs
  rs/state_machine_tests/src/lib.rs
Labels: test, @consensus, @pocket-ic, @nns-team, @ic-message-routing-owners

#5109 test(nns): Move list_proposals tests to a separate file and into Governance crate
  rs/nns/governance/src/governance/tests/list_proposals.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/tests/governance.rs
Labels: test, @nns-team

#4533 feat: Support loading SetupOS config from drive, for tests
  ic-os/components/setupos-scripts/config.service
  ic-os/components/setupos-scripts/preload-config.sh
  ic-os/components/setupos.bzl
  ic-os/dev-tools/build-setupos-config-image.sh
Labels: feat, @node

#5096 feat(ICP_Ledger): FI-1728: Add logging of callers to the deprecated notify method
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
Labels: feat, @finint

#5088 chore(crypto): CRP-2794 Modify VetKD key derivation
  packages/ic-vetkd-utils/src/lib.rs
  packages/ic-vetkd-utils/tests/test_utils.rs
  packages/ic-vetkd-utils/tests/tests.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/vetkd/tests.rs
  rs/crypto/test_utils/vetkd/tests/tests.rs
  rs/crypto/tests/vetkd.rs
  rs/execution_environment/src/execution_environment.rs
Labels: chore, @execution, @crypto-team

#4446 test(ICRC_Rosetta): FI-1699: Bump the retry limit
  rs/rosetta-api/icrc1/client/src/lib.rs
  rs/rosetta-api/icrc1/tests/system_tests.rs
Labels: test, @finint

#5117 chore(IDX): chown in bazel action
  .github/actions/bazel/action.yaml
Labels: chore, @idx

#5121 chore: Don't deliver ALREADY_EXISTS checkpoint in state sync
  rs/state_manager/src/state_sync/chunkable.rs
  rs/state_manager/tests/state_manager.rs
Labels: chore, @ic-message-routing-owners

#5113 feat: Split up setupos-inject-configuration
  Cargo.lock
  Cargo.toml
  ic-os/dev-tools/bare_metal_deployment/deploy.py
  ic-os/dev-tools/bare_metal_deployment/tools.bzl
  ic-os/dev-tools/hostos-upgrade-tests.sh
  rs/ic_os/dev_test_tools/setupos-image-config/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-image-config/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/inject.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/ic_os/dev_test_tools/setupos-inject-configuration/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-inject-configuration/src/main.rs
  rs/tests/system_tests.bzl
Labels: feat, @idx, @node

#5122 chore: refine ErrorHelp::ToolchainError
  rs/execution_environment/tests/execution_test.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
  rs/types/wasm_types/src/errors.rs
Labels: chore

#5115 fix: memory allocation of NNS canisters
  rs/nns/constants/src/lib.rs
Labels: fix, @nns-team, CI_ALL_BAZEL_TARGETS

#5097 chore: Remove unused boot argument from GRUB configuration
  ic-os/bootloader/grub.cfg
  ic-os/hostos/grub.cfg
Labels: chore

#5135 chore(IDX): execution_log_compact_to_csv: add --blacklist_pat option
  bazel/execution_log_compact_to_csv.py
Labels: chore, @idx

#4982 feat(nns-tools): Make wait-for-canister-to-upgrade.sh also print out git commit ID.
  testnet/tools/nns-tools/lib/canisters.sh
Labels: feat

#5132 chore: make storage reservation test more robust
  rs/execution_environment/tests/storage_reservation.rs
Labels: chore

#5043 test(nervous_system/canister): Test getting large Registry mutations from a canister.
  Cargo.lock
  Cargo.toml
  rs/nervous_system/canisters/BUILD.bazel
  rs/nervous_system/canisters/Cargo.toml
  rs/nervous_system/canisters/tests/registry.rs
  rs/nervous_system/runtime/BUILD.bazel
  rs/registry/admin/Cargo.toml
  rs/registry/fetch_large_record_test_canister/BUILD.bazel
  rs/registry/fetch_large_record_test_canister/Cargo.toml
  rs/registry/fetch_large_record_test_canister/interface.did
  rs/registry/fetch_large_record_test_canister/src/lib.rs
  rs/registry/fetch_large_record_test_canister/src/main.rs
Labels: test, @nns-team

#5134 fix: renaming timestamps to reflect actual units
  rs/nns/integration_tests/src/registry_get_chunk.rs
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/chunkify/src/lib.rs
  rs/registry/canister/chunkify/src/tests.rs
  rs/registry/canister/src/registry.rs
  rs/registry/canister/src/storage/tests.rs
  rs/registry/nns_data_provider/src/certification/tests.rs
  rs/registry/transport/proto/ic_registry_transport/pb/v1/transport.proto
  rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs
  rs/registry/transport/src/high_capacity.rs
  rs/registry/transport/src/high_capacity_tests.rs
  rs/registry/transport/src/lib.rs
Labels: fix

#5110 perf(nns): Use a proper proposal payload in benchmarks
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance/benches.rs
Labels: perf, @nns-team

#5127 refactor: Refactor partition image targets to remove redundancy
  ic-os/defs.bzl
Labels: refactor, @node

#5114 chore: upgrade ic-bn-lib & ic-gateway
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/benches/perf.rs
  rs/boundary_node/ic_boundary/src/bouncer.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/http.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/metrics/test.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/salt_fetcher.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/ic_boundary/src/tls_verify.rs
  rs/boundary_node/ic_boundary/src/tls_verify/test.rs
  rs/boundary_node/rate_limits/Cargo.toml
  rs/boundary_node/rate_limits/canister/add_config.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/main.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/tests/networking/canister_http_correctness_test.rs
Labels: chore, @idx, @consensus, @boundary-node, @pocket-ic

#4380 test(CON-1471): Enable VetKD in recovery/subnet creation tests
  Cargo.lock
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS

#5142 chore(IDX): Group artifact uploads
  BUILD.bazel
  ci/src/artifacts/upload.bzl
  ci/src/artifacts/upload.sh
  ic-os/defs.bzl
  ic-os/guestos/envs/dev/BUILD.bazel
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
  publish/binaries/BUILD.bazel
  publish/canisters/BUILD.bazel
  testnet/tools/BUILD.bazel
Labels: chore, @idx, @dre, @node

#5011 refactor(nns): Make ExchangeRate proposals obsolete
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
  rs/nns/integration_tests/src/reinstall_and_upgrade.rs
  rs/tests/driver/src/nns.rs
  rs/tests/nns/nns_cycles_minting_multi_app_subnets_test.rs
  rs/tests/nns/nns_cycles_minting_test.rs
  rs/tests/nns/nns_dapp/nns_dapp.rs
  rs/tests/testnets/large.rs
  rs/tests/testnets/src_testing.rs
Labels: refactor, @idx

#5111 feat(nns): Persist topic throughout proposal lifecycle
  rs/nns/governance/api/src/types.rs
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/pb/proposal_conversions.rs
  rs/nns/governance/src/test_utils.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/proposals.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#5136 feat(registry): enforce presence of node_reward_type
  rs/registry/canister/src/mutations/node_management/do_add_node.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @nns-team

#5013 fix(registry-canister-client): Only version-bump after deltas are applied.
  rs/registry/canister-client/src/stable_canister_client.rs
  rs/registry/canister-client/src/stable_canister_client/tests.rs
Labels: fix, @nns-team

#5112 test(nns): Use golden nns state test to detect new protocol canisters
  rs/nns/constants/src/lib.rs
  rs/nns/governance/src/proposals/mod.rs
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/state_machine_tests/src/lib.rs
Labels: test

#5151 test(ICRC_Ledger): FI-1732: Re-enable test_icrc1_test_suite test
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
Labels: test, @finint

#5131 docs(crypto): CRP-2794 fix TODO item Jira ticket number
  rs/tests/consensus/tecdsa/utils/src/lib.rs
Labels: docs, @consensus

#5153 feat: add more timeouts to the nns delegation fetching logic
  Cargo.lock
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/src/nns_delegation_manager.rs
Labels: feat, @consensus, CI_TEST_ALL_BAZEL_TARGETS

#5158 fix(PocketIC): canister creation with specified id on resumed instance
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: fix

#5146 chore(Ledgers): FI-1731: Update ledger suite mainnet canisters json
  mainnet-canister-revisions.json
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/icrc1/tests/upgrade_downgrade.rs
Labels: chore, @finint

#5161 test(EXC-370): Update compute allocation through update_settings
  rs/execution_environment/tests/canister_history.rs
Labels: test, @execution

#4792 feat: Write protobufs asynchronously [MR-355]
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/split.rs
  rs/state_manager/src/split/tests.rs
  rs/state_manager/src/tip.rs
Labels: feat, @ic-message-routing-owners

#5156 chore(BOUN-1396): ic-boundary: remove own caching, use ic-bn-lib
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/src/cache.rs
  rs/boundary_node/ic_boundary/src/cache/test.rs
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
Labels: chore, @idx, @boundary-node

#5166 fix: properly log the time-out in NNS delegation manager
  rs/http_endpoints/public/src/nns_delegation_manager.rs
Labels: fix, @consensus

#5148 fix: Fix snapshot size calculation
  rs/replicated_state/src/canister_state.rs
  rs/replicated_state/src/canister_state/execution_state.rs
Labels: fix

#5165 fix(IDX): Re-enable x86-darwin builds
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  bazel/external_crates.bzl
Labels: fix, @idx, CI_MACOS_INTEL

#5168 chore(ci): remove deprecated ci/tools/repro-check.sh
  ci/tools/repro-check.sh
Labels: chore, @idx

#5024 test(ICRC_Rosetta): FI-1725: Fix flaky test_deriving_gaps_from_storage test
  rs/ledger_suite/icrc1/test_utils/src/lib.rs
  rs/rosetta-api/icrc1/src/common/storage/storage_client.rs
Labels: test, @finint

#5163 revert: "refactor(nns): Make ExchangeRate proposals obsolete (#5011)"
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/cycles_minting_canister.rs
  rs/nns/integration_tests/src/cycles_minting_canister_with_exchange_rate_canister.rs
  rs/nns/integration_tests/src/reinstall_and_upgrade.rs
  rs/tests/driver/src/nns.rs
  rs/tests/nns/nns_cycles_minting_multi_app_subnets_test.rs
  rs/tests/nns/nns_cycles_minting_test.rs
  rs/tests/nns/nns_dapp/nns_dapp.rs
  rs/tests/testnets/large.rs
  rs/tests/testnets/src_testing.rs
Labels: revert, @idx, @nns-team, CI_ALL_BAZEL_TARGETS

#5167 fix(repro-check): use temp dir in the home directory to fix cross-device linking issue
  ci/tools/repro-check
Labels: fix, @dre

#5057 feat(registry): Make callers of `get_value` understand chunked responses.
  Cargo.lock
  rs/nervous_system/chunks/BUILD.bazel
  rs/nervous_system/chunks/Cargo.toml
  rs/nervous_system/chunks/src/test_data.rs
  rs/nns/common/BUILD.bazel
  rs/nns/common/Cargo.toml
  rs/nns/common/src/registry.rs
  rs/nns/nns.bzl
  rs/nns/test_utils/BUILD.bazel
  rs/nns/test_utils/Cargo.toml
  rs/nns/test_utils/src/registry.rs
  rs/registry/nns_data_provider/BUILD.bazel
  rs/registry/nns_data_provider/Cargo.toml
  rs/registry/nns_data_provider/src/registry.rs
  rs/registry/nns_data_provider/tests/registry_canister.rs
  rs/registry/transport/src/high_capacity.rs
  rs/registry/transport/src/high_capacity_tests.rs
  rs/registry/transport/src/lib.rs
  rs/replay/BUILD.bazel
  rs/replay/Cargo.toml
  rs/replay/src/player.rs
  rs/replay/tests/player.rs
Labels: feat, @consensus, @nns-team

#5080 chore(crypto): CRP-2038 Remove workaround for RSA signature malleability
  rs/crypto/internal/crypto_lib/basic_sig/rsa_pkcs1/src/lib.rs
Labels: chore, @crypto-team

#5000 refactor(cketh): clean up eth_fee_history call
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/tests.rs
  rs/ethereum/cketh/minter/src/tx.rs
  rs/ethereum/cketh/minter/src/tx/tests.rs
  rs/ethereum/cketh/test_utils/src/tests.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5083 tests(networking): [CON-1496] add canister http cycles refund assertions to the spec tests
  rs/rust_canisters/proxy_canister/BUILD.bazel
  rs/rust_canisters/proxy_canister/src/lib.rs
  rs/rust_canisters/proxy_canister/src/main.rs
  rs/tests/networking/canister_http_correctness_test.rs
Labels: @consensus

#5175 fix(node): filebeat exec condition
  ic-os/components/monitoring/filebeat/filebeat.service
Labels: fix, @node

#5173 chore(IDX): Remove unnecessary bind mounts
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
Labels: chore, @idx

#5076 fix: timestamps in nanoseconds in the registry
  Cargo.lock
  rs/nns/integration_tests/src/lib.rs
  rs/nns/integration_tests/src/registry_get_chunk.rs
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/Cargo.toml
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/chunkify/src/lib.rs
  rs/registry/canister/chunkify/src/tests.rs
  rs/registry/canister/src/registry.rs
  rs/registry/canister/src/storage/tests.rs
  rs/registry/nns_data_provider/src/certification/tests.rs
  rs/registry/transport/proto/ic_registry_transport/pb/v1/transport.proto
  rs/registry/transport/src/gen/ic_registry_transport.pb.v1.rs
  rs/registry/transport/src/high_capacity.rs
  rs/registry/transport/src/high_capacity_tests.rs
  rs/registry/transport/src/lib.rs
  rs/replay/src/player.rs
Labels: fix, @consensus, @nns-team

#5164 test(replay): Integration test for `get_changes_since` in replay.
  rs/replay/src/player.rs
  rs/replay/tests/player.rs
Labels: test, @nns-team

#5170 chore: refactor allocations in try_to_create_and_install_canister
  rs/nns/handlers/root/impl/src/canister_management.rs
Labels: chore, @nns-team

#5128 test: fix `replica_determinism_test`
  rs/tests/consensus/replica_determinism_test.rs
  rs/tests/driver/src/driver/test_env_api.rs
Labels: test, @idx, @consensus, CI_TEST_ALL_BAZEL_TARGETS

#5180 test: fix vetKD recovery tests by increasing DKG interval length
  rs/tests/consensus/subnet_recovery/common.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS, CI_TEST_ALL_BAZEL_TARGETS

#4964 refactor(cketh): clean up eth_get_block_by_number call
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/endpoints.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/lifecycle/init.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/state.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/tests.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5152 feat: [MR-660] Use actual cross-subnet streams in `state_manager` tests
  rs/state_manager/src/tree_hash.rs
  rs/state_manager/tests/common/mod.rs
  rs/state_manager/tests/state_manager.rs
Labels: feat, @ic-message-routing-owners

#5183 chore: Upload the pocket-ic-server artifact.
  .github/workflows/test-namespace-darwin.yaml
Labels: chore, @idx

#5015 refactor(cketh): clean up eth_send_raw_transaction call
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_error/mod.rs
  rs/ethereum/cketh/minter/src/lib.rs
  rs/ethereum/cketh/minter/src/withdraw.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5186 fix: repro-check formatting issues
  ci/tools/repro-check
Labels: fix

#5143 chore(networking): add http_method label for https outcall client metrics
  packages/ic-error-types/src/lib.rs
  rs/https_outcalls/client/src/client.rs
  rs/https_outcalls/client/src/metrics.rs
  rs/types/types/src/canister_http.rs
Labels: chore, @consensus, @execution

#5171 test: Remove some usages of install_canister_with_allocation
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/tests/hypervisor.rs
Labels: test

#5176 chore(BOUN-1396): refactor ic-boundary
  rs/boundary_node/ic_boundary/src/bouncer/mod.rs
  rs/boundary_node/ic_boundary/src/bouncer/test.rs
  rs/boundary_node/ic_boundary/src/check.rs
  rs/boundary_node/ic_boundary/src/check/test.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/dns.rs
  rs/boundary_node/ic_boundary/src/dns/test.rs
  rs/boundary_node/ic_boundary/src/errors.rs
  rs/boundary_node/ic_boundary/src/http/handlers.rs
  rs/boundary_node/ic_boundary/src/http/middleware/cache.rs
  rs/boundary_node/ic_boundary/src/http/middleware/geoip.rs
  rs/boundary_node/ic_boundary/src/http/middleware/mod.rs
  rs/boundary_node/ic_boundary/src/http/middleware/process.rs
  rs/boundary_node/ic_boundary/src/http/middleware/retry.rs
  rs/boundary_node/ic_boundary/src/http/middleware/validate.rs
  rs/boundary_node/ic_boundary/src/http/mod.rs
  rs/boundary_node/ic_boundary/src/lib.rs
  rs/boundary_node/ic_boundary/src/main.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/metrics/test.rs
  rs/boundary_node/ic_boundary/src/persist.rs
  rs/boundary_node/ic_boundary/src/persist/test.rs
  rs/boundary_node/ic_boundary/src/rate_limiting.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/fetcher.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/mod.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/test.rs
  rs/boundary_node/ic_boundary/src/retry.rs
  rs/boundary_node/ic_boundary/src/retry/test.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
  rs/boundary_node/ic_boundary/src/snapshot.rs
  rs/boundary_node/ic_boundary/src/snapshot/test.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/ic_boundary/src/tls_verify.rs
  rs/boundary_node/ic_boundary/src/tls_verify/test.rs
Labels: chore, @boundary-node

#4840 feat(ICRC-Ledger): FI-1546: Implement the ICRC-103 standard
  Cargo.lock
  packages/icrc-ledger-types/CHANGELOG.md
  packages/icrc-ledger-types/Cargo.toml
  packages/icrc-ledger-types/src/icrc103/get_allowances.rs
  packages/icrc-ledger-types/src/icrc103/mod.rs
  packages/icrc-ledger-types/src/lib.rs
  rs/ethereum/ledger-suite-orchestrator/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/ledger_suite/icrc1/ledger/ledger.did
  rs/ledger_suite/icrc1/ledger/src/benches/benches_u256.rs
  rs/ledger_suite/icrc1/ledger/src/benches/benches_u64.rs
  rs/ledger_suite/icrc1/ledger/src/benches/mod.rs
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/BUILD.bazel
  rs/ledger_suite/tests/sm-tests/Cargo.toml
  rs/ledger_suite/tests/sm-tests/src/allowances.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/tests/financial_integrations/icrc1_agent_test.rs
Labels: feat, @cross-chain-team, @finint

#5055 refactor(cketh): ensure the EthRpcClient always gets an evm_rpc_id
  rs/ethereum/cketh/minter/cketh_minter.did
  rs/ethereum/cketh/minter/src/dashboard/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/lib.rs
  rs/ethereum/cketh/minter/src/lifecycle/init.rs
  rs/ethereum/cketh/minter/src/main.rs
  rs/ethereum/cketh/minter/src/state.rs
  rs/ethereum/cketh/minter/src/state/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/tests.rs
  rs/ethereum/cketh/minter/tests/ckerc20.rs
  rs/ethereum/cketh/minter/tests/cketh.rs
  rs/ethereum/cketh/test_utils/src/ckerc20.rs
  rs/ethereum/cketh/test_utils/src/flow.rs
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/tests/cross_chain/ic_xc_cketh_test.rs
Labels: refactor, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5197 fix(IDX): add missing images and upload suffix
  BUILD.bazel
  ic-os/guestos/envs/dev/BUILD.bazel
  ic-os/guestos/envs/prod/BUILD.bazel
Labels: fix, @idx, @node

#4985 perf: EXC-2033: Add more heap benchmarks
  rs/embedders/benches/embedders_bench/src/lib.rs
  rs/embedders/benches/heap.rs
Labels: perf, @execution

#5089 feat: Pre-build test SetupOS images in bazel
  ic-os/BUILD.bazel
  ic-os/setupos/BUILD.bazel
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/nested.rs
  rs/tests/system_tests.bzl
Labels: feat, @idx, @node

#5195 feat: [MR-660] Drop loopback stream from certified state
  rs/canonical_state/certification_version/src/lib.rs
  rs/canonical_state/src/lazy_tree_conversion.rs
  rs/canonical_state/src/traversal.rs
  rs/state_manager/src/tree_hash.rs
Labels: feat

#5209 chore(BOUN-1396): refactor `ic-boundary` more
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/BUILD.bazel
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/src/check.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/dns.rs
  rs/boundary_node/ic_boundary/src/http/middleware/cache.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/mod.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/salt_fetcher.rs
  rs/boundary_node/ic_boundary/src/snapshot.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/boundary_node/ic_boundary/src/tls_verify.rs
  rs/boundary_node/rate_limits/api/Cargo.toml
  rs/nervous_system/humanize/Cargo.toml
  rs/tests/driver/Cargo.toml
Labels: chore, @idx, @boundary-node

#5178 test(registry): More tests for large records/chunking.
  rs/registry/canister/src/registry.rs
  rs/registry/canister/src/storage.rs
Labels: test, @nns-team
