Repository dfinity/ic, pull requests merged in 2025-06, with the labels that each got.

#5358 fix: error message for OutOfMemory
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment/errors.rs
Labels: fix, @execution, @ic-interface-owners

#5307 chore: remove `ic_mainnet_nns_recovery`
  Cargo.lock
  Cargo.toml
  rs/tests/common.bzl
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/Cargo.toml
  rs/tests/nns/ic_mainnet_nns_recovery/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/Cargo.toml
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
  rs/tests/nns/nns_upgrade_test.rs
  rs/tests/testnets/BUILD.bazel
  rs/tests/testnets/Cargo.toml
  rs/tests/testnets/recovered_mainnet_nns.rs
Labels: chore, @idx, @governance-team

#5343 chore: Add section about error variants to contribution guide.
  rs/execution_environment/Contributing.md
Labels: chore, @execution

#5373 chore: Remove local-vm tool from bazel
  ic-os/defs.bzl
  ic-os/guestos/README.adoc
  ic-os/setupos/envs/dev/BUILD.bazel
Labels: chore

#5344 fix: Sanitize input to canister snapshot data download before charging cycles
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_manager/types.rs
Labels: fix, @execution

#5375 chore: Update code owners for lru cache
  .github/CODEOWNERS
Labels: chore

#5268 refactor(cketh): remove SingleCallError and HttpOutcallError, remove redundant reduction in `eth_get_finalized_transaction_count` and `eth_get_block_by_number`
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
Labels: refactor, CI_ALL_BAZEL_TARGETS

#5376 refactor(registration): unify and enhance node registration logs
  rs/orchestrator/src/registration.rs
Labels: refactor, @consensus

#5378 feat: Mirror new 24.04 ubuntu image
  .github/workflows/container-mirror-images.json
Labels: feat

#5377 fix(boundary): prometheus scraping playnet url
  rs/tests/driver/src/driver/prometheus_vm.rs
  rs/tests/testnets/large.rs
  rs/tests/testnets/medium.rs
  rs/tests/testnets/small.rs
  rs/tests/testnets/small_bitcoin.rs
  rs/tests/testnets/small_high_perf.rs
  rs/tests/testnets/small_nns.rs
  rs/tests/testnets/small_with_query_stats.rs
  rs/tests/testnets/sns_testing.rs
  rs/tests/testnets/src_testing.rs
Labels: fix

#5372 chore: stabilize the highly flaky nns_dapp_test
  rs/tests/nns/nns_dapp_test.rs
Labels: chore, @governance-team

#5380 chore(PocketIC): comprehensible error for clearly invalid subnet state directory
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: chore, @pocket-ic

#5194 chore: downgrade to rust 1.85.1
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  WORKSPACE.bazel
  ci/container/TAG
  rs/nns/governance/canbench/canbench_results.yml
  rs/pocket_ic_server/BUILD.bazel
  rs/sns/init/src/lib.rs
  rs/tests/driver/src/driver/constants.rs
  rust-toolchain.toml
Labels: chore, @idx, @consensus, @pocket-ic, @finint, CI_ALL_BAZEL_TARGETS, CI_MACOS_INTEL, @governance-team

#5368 chore(nns): update release notes
  rs/nns/cmc/CHANGELOG.md
  rs/nns/cmc/unreleased_changelog.md
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
Labels: chore, @governance-team

#5392 fix(IDX): run versions workflow every 2 hours
  .github/workflows/update-mainnet-revisions.yaml
Labels: fix, @idx

#5356 chore: Upgrade canbench to 0.15.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  MODULE.bazel
  bazel/external_crates.bzl
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/nns/governance/canbench/canbench_results.yml
Labels: chore, @idx, @finint, @governance-team

#5402 fix(fuzzing): Fix path for GCP key
  .github/workflows/schedule-weekly.yml
Labels: fix

#5393 fix: not using an action to setup gh cli
  .github/workflows/update-mainnet-revisions.yaml
Labels: fix, @idx

#5079 feat(sns): inactive status of SNS
  rs/nervous_system/canisters/src/ledger.rs
  rs/nervous_system/clients/src/ledger_client.rs
  rs/nervous_system/common/test_utils/src/lib.rs
  rs/nns/governance/benches/scale.rs
  rs/nns/governance/canister/tla_ledger.rs
  rs/nns/governance/src/test_utils.rs
  rs/nns/governance/tests/degraded_mode.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/interleaving/mod.rs
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/test_helpers.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/tests/fixtures/mod.rs
  rs/sns/integration_tests/src/neuron.rs
  rs/sns/sns.bzl
  rs/sns/swap/tests/common/doubles.rs
Labels: feat, @governance-team

#5403 chore: remove BN mentions
  rs/tests/driver/src/driver/ic_gateway_vm.rs
  rs/tests/ict/cmd/testnetCreateCmd.go
Labels: chore, @idx

#5406 chore: move PocketIC HTTP gateway tests into a separate target
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/tests/common.rs
  rs/pocket_ic_server/tests/gateway.rs
  rs/pocket_ic_server/tests/test.rs
Labels: chore

#5397 chore(nns): Delete //rs/nns/governance:scale_bench
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/benches/scale.rs
Labels: chore, @governance-team

#5379 chore(PocketIC): deterministic registry and validation
  Cargo.lock
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/state_machine_tests/BUILD.bazel
  rs/state_machine_tests/Cargo.toml
  rs/state_machine_tests/src/lib.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#5400 refactor(nns): Move Governance API->Internal type conversion into Governance::new
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/disburse_maturity_tests.rs
  rs/nns/governance/src/governance/tests/list_neurons.rs
  rs/nns/governance/src/governance/tests/list_proposals.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/governance/tests/neurons_fund.rs
  rs/nns/governance/src/governance/tests/node_provider_rewards.rs
  rs/nns/governance/src/governance/tests/stake_maturity.rs
  rs/nns/governance/src/governance_proto_builder.rs
  rs/nns/governance/src/neuron_lock_tests.rs
  rs/nns/governance/src/reward/distribution.rs
  rs/nns/governance/src/seed_accounts/seed_accounts_tests.rs
  rs/nns/governance/src/timer_tasks/calculate_distributable_rewards.rs
  rs/nns/governance/src/timer_tasks/distribute_rewards.rs
  rs/nns/governance/src/timer_tasks/snapshot_voting_power.rs
  rs/nns/governance/src/voting.rs
  rs/nns/governance/tests/degraded_mode.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/nns/governance/tests/monitoring.rs
  rs/nns/governance/tests/proposals.rs
Labels: refactor

#5404 chore: CON-1484 Distinguish transient VetKD errors where NiDkgTranscript wasn't loaded yet
  rs/consensus/idkg/src/signer.rs
Labels: chore, @consensus

#5422 chore(boundary): remove BN team from failover config
  ci/src/dependencies/data_source/slack_findings_failover_data_store.py
  ci/src/dependencies/resources/container_scanner_finding_failover_ignore_list_boundary_guestos.txt
  ci/src/dependencies/resources/resource_reader.py
Labels: chore

#5423 chore(boundary): fix test
  ci/src/dependencies/data_source/slack_findings_failover_data_store_test.py
Labels: chore

#5409 chore(IDX): run all bazel targets on mainnet revision PRs
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: chore, @idx

#5415 chore: disable composite query as canister http transform
  rs/execution_environment/src/query_handler/query_context.rs
  rs/tests/networking/canister_http_correctness_test.rs
Labels: chore, @consensus, @execution, CI_ALL_BAZEL_TARGETS

#5417 feat(NRC): Add Performance Based rewards calculation library
  Cargo.lock
  Cargo.toml
  rs/node_rewards/rewards_calculation/BUILD.bazel
  rs/node_rewards/rewards_calculation/Cargo.toml
  rs/node_rewards/rewards_calculation/src/lib.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/builder.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/tests.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator_results.rs
  rs/node_rewards/rewards_calculation/src/types.rs
Labels: feat, @dre, @governance-team

#5439 chore(IDX): don't use a config file for rclone
  ci/src/artifacts/upload.sh
Labels: chore, @idx

#5297 feat: Tool to verify key resharing recovery proposal
  Cargo.lock
  rs/cup_explorer/BUILD.bazel
  rs/cup_explorer/Cargo.toml
  rs/cup_explorer/README.md
  rs/cup_explorer/ic_public_key.pem
  rs/cup_explorer/src/lib.rs
  rs/cup_explorer/src/main.rs
  rs/cup_explorer/src/registry.rs
  rs/cup_explorer/src/util.rs
  rs/registry/nns_data_provider/src/registry.rs
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/Cargo.toml
  rs/tests/consensus/cup_explorer_test.rs
  rs/tests/consensus/tecdsa/utils/src/lib.rs
Labels: feat, @consensus, @governance-team

#5436 fix: increase timeout for the {upgrade,downgrade}_app_subnet_tests
  rs/tests/consensus/upgrade/BUILD.bazel
Labels: fix, @consensus, CI_ALL_BAZEL_TARGETS

#5440 feat(IDX): upload arm64-linux pocket-ic-server artifacts to S3
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  BUILD.bazel
  ci/src/artifacts/upload.bzl
Labels: feat, @idx

#5185 feat(sns): Implement SnsGov.get_metrics
  rs/sns/governance/canister/canister.rs
  rs/sns/governance/canister/tests.rs
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/get_metrics.rs
  rs/sns/governance/src/icrc_ledger_helper.rs
  rs/sns/governance/src/lib.rs
  rs/sns/governance/src/pb/conversions.rs
Labels: feat

#5444 fix: Flush state manager before restart
  rs/state_machine_tests/src/lib.rs
Labels: fix

#5443 chore(IDX): move arm64-darwin build to ci-main
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  .github/workflows/test-namespace-darwin.yaml
Labels: chore, @idx

#5374 test(sns): Icrc ledger helper integration tests
  Cargo.lock
  rs/sns/integration_tests/BUILD.bazel
  rs/sns/integration_tests/Cargo.toml
  rs/sns/integration_tests/src/get_metrics.rs
  rs/sns/integration_tests/src/lib.rs
Labels: test, @governance-team

#4961 test(Ledgers): FI-1652: Add instruction limit test for ledger archiving
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#5450 docs(governance-backend): Update Governance backend CHANGELOG files.
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/nns/gtc/CHANGELOG.md
  rs/nns/handlers/root/CHANGELOG.md
  rs/nns/sns-wasm/CHANGELOG.md
  rs/nns/sns-wasm/unreleased_changelog.md
  rs/node_rewards/canister/CHANGELOG.md
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
  rs/sns/root/CHANGELOG.md
Labels: docs, @dre, @governance-team

#5447 chore: mark //rs/nns/governance:governance_integration_test_tests:... as flaky
  rs/nns/governance/BUILD.bazel
Labels: chore, @governance-team

#5421 test(nns): Remove (prop_)assert_changes
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/storage/neurons.rs
  rs/nns/governance/tests/README.md
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/nns/governance/tests/merge_neurons.rs
Labels: test

#5457 fix(PocketIC): tests binding HTTP gateway to invalid backend
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/gateway.rs
Labels: fix, @pocket-ic, CI_MACOS_INTEL

#5062 feat(registry): Store routing table as canister_ranges
  Cargo.lock
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/Cargo.toml
  rs/registry/canister/src/mutations/do_create_subnet.rs
  rs/registry/canister/src/mutations/do_migrate_canisters.rs
  rs/registry/canister/src/mutations/mod.rs
  rs/registry/canister/src/mutations/node_management/common.rs
  rs/registry/canister/src/mutations/prepare_canister_migration.rs
  rs/registry/canister/src/mutations/reroute_canister_ranges.rs
  rs/registry/canister/src/mutations/routing_table.rs
  rs/registry/canister/src/registry_lifecycle.rs
  rs/registry/canister/unreleased_changelog.md
  rs/registry/keys/BUILD.bazel
  rs/registry/keys/Cargo.toml
  rs/registry/keys/src/lib.rs
Labels: feat, @nns-team

#5456 refactor(nns): Move Followees out of Neuron in governance.proto
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/merge_neurons.rs
  rs/nns/governance/src/governance/tests/list_proposals.rs
  rs/nns/governance/src/heap_governance_data.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/storage/neuron_indexes/tests.rs
  rs/nns/governance/src/storage/neurons.rs
  rs/nns/governance/src/voting.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
Labels: refactor, CI_OVERRIDE_BUF_BREAKING, @governance-team

#5469 fix(fuzzing): Remove docker creds from the weekly fuzzing job
  .github/workflows/schedule-weekly.yml
Labels: fix, @idx

#5471 chore: pass `--keep-going` to `cargo clippy`
  ci/scripts/rust-lint.sh
Labels: chore, @idx

#5451 fix(IDX): stamp artifacts to upload
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#5269 chore: validate specified_id for canister creation in test environments
  packages/pocket-ic/tests/tests.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/nns/governance/src/governance/test_data.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/integration_tests/src/create_service_nervous_system.rs
  rs/nns/integration_tests/src/governance_upgrade.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/replicated_state/src/metadata_state.rs
Labels: chore, @execution, @pocket-ic, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS, @governance-team

#5472 note(sns): add release notes on
  rs/sns/governance/unreleased_changelog.md
Labels: @governance-team

#5482 fix(IDX): update bot name
  .github/workflows/auto-approve.yml
Labels: fix, @idx

#5448 chore: CON-1504 Increase acceptable gap between next pending CUP height and notarized height to 130
  rs/consensus/src/consensus.rs
  rs/consensus/src/consensus/bounds.rs
  rs/consensus/src/consensus/notary.rs
  rs/consensus/src/consensus/priority.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/payload.rs
  rs/replica/setup_ic_network/src/lib.rs
Labels: chore, @consensus, CI_ALL_BAZEL_TARGETS

#5449 feat(IDX): upload arm64-darwin pocket-ic-server
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: feat, @idx

#5488 fix(IDX): Remove outdated reference to CI_MACOS_INTEL
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix

#5476 chore(IDX): remove zh1 pin from daily jobs
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: chore, @idx

#5495 feat(IDX): add node name for all ci jobs
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
Labels: feat, @idx

#5483 chore: allow dm1 in the HostOS firewall
  ic-os/components/networking/nftables/hostos/nftables.template
Labels: chore

#5470 feat(BOUN-1408): publish logs over websocket
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/benches/perf.rs
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/http/handlers.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: feat, @idx, @boundary-node, @pocket-ic

#5257 chore(IDX): remove zh1 pin from hourly pipeline
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: chore, @idx

#5426 feat: Don't mount grub under boot
  ic-os/bootloader/build-bootloader-tree.sh
  ic-os/bootloader/defs.bzl
  ic-os/components/early-boot/fstab/fstab-guestos
  ic-os/components/early-boot/fstab/fstab-hostos
  ic-os/components/early-boot/fstab/fstab-setupos
  ic-os/components/upgrade/manageboot/manageboot.sh
  ic-os/components/upgrade/systemd-generators/guestos/mount-generator
  ic-os/components/upgrade/systemd-generators/hostos/mount-generator
  ic-os/guestos/context/Dockerfile
  ic-os/guestos/docs/Boot.adoc
  ic-os/guestos/docs/SELinux-Build.adoc
  ic-os/hostos/context/Dockerfile
  ic-os/setupos/context/Dockerfile
Labels: feat, @node

#5512 chore(nns): Clean up disburse maturity
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/disburse_maturity_tests.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_data_validation.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/storage/neuron_indexes.rs
  rs/nns/governance/src/timer_tasks/mod.rs
Labels: chore, @governance-team

#5355 feat(node): guestos-recovery-engine component
  ic-os/components/BUILD.bazel
  ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.service
  ic-os/components/misc/guestos-recovery/guestos-recovery-engine/guestos-recovery-engine.sh
  ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.service
  ic-os/guestos/defs.bzl
  ic-os/guestos/envs/recovery/BUILD.bazel
Labels: feat, @node

#5521 fix: Bump the expected mean latency of the xnet_compatibility test
  rs/tests/message_routing/xnet/xnet_compatibility.rs
Labels: fix

#5520 feat(sns): Added default implementation to GetMetricsResponse
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
Labels: feat, @governance-team

#5526 feat(IDX): export node name to step annotation
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: feat, @idx

#5493 feat(nns): Use timer_tasks library for some timer tasks
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/governance/src/timer_tasks/neuron_data_validation.rs
  rs/nns/governance/src/timer_tasks/unstake_maturity_of_dissolved_neurons.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/governance_neurons.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: feat, @governance-team

#5534 revert: "fix(IDX): don't cache jemalloc build (#5174)"
  .github/actions/bazel-test-all/action.yaml
  third_party/jemalloc/BUILD.jemalloc.bazel
Labels: revert, @idx

#5487 fix(IDX): upload sns-testing in main bundle
  BUILD.bazel
  publish/binaries/BUILD.bazel
Labels: fix

#5523 chore: allow running the nested system-tests on all farm hosts
  rs/tests/nested/src/lib.rs
Labels: chore, @node, CI_ALL_BAZEL_TARGETS

#5524 chore: move remaining hourly nested system-tests to long_tests
  rs/tests/nested/BUILD.bazel
Labels: chore, @node, CI_ALL_BAZEL_TARGETS

#5537 fix(XC): path to wasm for SOL RPC canister for proposal-cli
  rs/cross-chain/proposal-cli/src/canister/mod.rs
Labels: fix

#5515 chore: EXC: Update `wasmtime` to 33.0.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/cranelift-assembler-lib.patch
  bazel/cranelift-isle.patch
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/execution_environment/benches/baseline/SYSTEM_API_INSPECT_MESSAGE.zh1-spm34.min
  rs/execution_environment/benches/baseline/SYSTEM_API_QUERY.zh1-spm34.min
  rs/execution_environment/benches/baseline/SYSTEM_API_UPDATE.zh1-spm34.min
  rs/execution_environment/benches/baseline/WASM_INSTRUCTIONS.zh1-spm34.min
Labels: chore, @idx, @execution

#5541 fix(IDX): fix typo in pocket-ic-server variant
  bazel/pocket-ic-tests.bzl
Labels: fix

#5539 chore: require build determinism for all targets except a few exclusions
  .github/actions/bazel/action.yaml
  bazel/execution_log_compact_to_csv.py
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#5535 feat(registry): Add invariant check for sharded canister migrations
  rs/registry/canister/canbench/canbench_results.yml
  rs/registry/canister/src/flags.rs
  rs/registry/canister/src/invariants/checks/benches.rs
  rs/registry/canister/src/invariants/routing_table.rs
  rs/registry/canister/unreleased_changelog.md
  rs/registry/routing_table/src/proto.rs
Labels: feat, @governance-team

#5546 chore(nns): Cleanup USE_NODE_PROVIDER_REWARD_CANISTER flag and code
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/integration_tests/src/node_provider_remuneration.rs
Labels: chore, @governance-team

#5544 chore: Remove unused channel from GuestVM config
  rs/ic_os/config/golden/guestos_vm_kvm.xml
  rs/ic_os/config/golden/guestos_vm_qemu.xml
  rs/ic_os/config/templates/guestos_vm_template.xml
Labels: chore

#5548 chore(governance): Fix order of SNS canisters and double quote some bash variables in release scripts
  rs/nervous_system/tools/release-runscript/src/main.rs
  testnet/tools/nns-tools/lib/sns_upgrades.sh
Labels: chore, @governance-team

#5213 test: CON-1417 Enable VetKD in large subnet recovery test
  rs/tests/consensus/subnet_recovery/common.rs
Labels: test, @consensus, CI_ALL_BAZEL_TARGETS

#5551 refactor: Drop unnecessary match in is_controller
  rs/embedders/src/wasmtime_embedder/system_api.rs
Labels: refactor

#5552 fix: don't assume the current UID is 1001 to fix the schedule-rust-bench workflow
  .github/actions/bazel/action.yaml
Labels: fix, @idx

#5339 chore: [EXC-1825] Remove mint_cycles API
  rs/cycles_account_manager/src/lib.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/linker.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/tests/sandbox_safe_system_state.rs
  rs/embedders/tests/system_api.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/rust_canisters/dfn_core/src/api.rs
  rs/tests/execution/general_execution_test.rs
  rs/tests/execution/general_execution_tests/nns_shielding.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
Labels: chore, @execution, CI_ALL_BAZEL_TARGETS, @governance-team

#5554 chore(IDX): add alerts for ic-private
  .github/workflows/slack-workflow-run.yml
Labels: chore, @idx

#5527 chore(ethereum): update evm-rpc-canister to v2.4.0 and evm_rpc_types to v1.4.0
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  MODULE.bazel
  bazel/external_crates.bzl
  rs/ethereum/cketh/test_utils/Cargo.toml
  rs/ethereum/cketh/test_utils/src/evm_rpc_provider.rs
  rs/ethereum/cketh/test_utils/src/lib.rs
  rs/ethereum/cketh/test_utils/src/mock.rs
  rs/ethereum/evm-rpc-client/Cargo.toml
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#5484 feat: add trait in `ic-metrics-assert` to perform async HTTP query
  Cargo.lock
  packages/ic-metrics-assert/BUILD.bazel
  packages/ic-metrics-assert/Cargo.toml
  packages/ic-metrics-assert/src/lib.rs
Labels: feat, @cross-chain-team

#5577 chore: Reenable large subnet recovery test
  rs/tests/consensus/subnet_recovery/BUILD.bazel
Labels: chore, @consensus

#5586 revert: "chore: [MR-600] Enable incremental manifest computation on the NNS"
  rs/state_manager/src/lib.rs
Labels: revert

#5585 docs(node): add recovery variant to documentation
  ic-os/README.adoc
Labels: docs, @node

#5576 chore(boundary): add reason for `PendingAcmeApproval`
  rs/boundary_node/certificate_issuance/certificate_issuer/src/metrics.rs
  rs/boundary_node/certificate_issuance/certificate_issuer/src/registration.rs
  rs/boundary_node/certificate_issuance/certificate_issuer/src/work.rs
Labels: chore, @boundary-node, @node

#5504 feat: Have XNetPayloadBuilder prioritize signals
  rs/state_machine_tests/src/lib.rs
  rs/xnet/payload_builder/src/impl_tests.rs
  rs/xnet/payload_builder/src/lib.rs
  rs/xnet/payload_builder/tests/xnet_payload_builder.rs
Labels: feat, @pocket-ic

#5559 fix: enable canister ID inference from referer header in PocketIC
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/pocket_ic_server/src/state_api/state.rs
  rs/pocket_ic_server/tests/gateway.rs
Labels: fix, @idx, @pocket-ic

#5583 chore: add date to `ic-metrics-assert` change log
  packages/ic-metrics-assert/CHANGELOG.md
  packages/ic-metrics-assert/README.md
Labels: chore, @cross-chain-team

#5428 refactor(cketh): replace local types with evm_rpc_types
  rs/ethereum/cketh/minter/src/deposit.rs
  rs/ethereum/cketh/minter/src/eth_logs/mod.rs
  rs/ethereum/cketh/minter/src/eth_logs/parser.rs
  rs/ethereum/cketh/minter/src/eth_logs/scraping.rs
  rs/ethereum/cketh/minter/src/eth_logs/tests.rs
  rs/ethereum/cketh/minter/src/eth_rpc.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/mod.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/responses.rs
  rs/ethereum/cketh/minter/src/eth_rpc_client/tests.rs
  rs/ethereum/cketh/minter/src/test_fixtures.rs
  rs/ethereum/cketh/minter/src/tests.rs
  rs/ethereum/cketh/minter/src/withdraw.rs
  rs/ethereum/cketh/test_utils/src/ckerc20.rs
  rs/ethereum/evm-rpc-client/src/lib.rs
Labels: refactor, CI_ALL_BAZEL_TARGETS

#5595 chore(IDX): don't use a repository cache
  .github/actions/bazel/action.yaml
  .github/actions/bazel/bin/bazel
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: chore, @idx

#5601 fix: remove /tmp mount in container-run.sh to prevent shadowing
  ci/container/container-run.sh
Labels: fix, @idx

#5567 fix: Do not return system state changes on errors for composite queries
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/tests/system_api.rs
Labels: fix, @execution

#5435 refactor: Move Guest VM management script to Rust
  .devcontainer/devcontainer.json
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/pocket-ic-tests-windows.yml
  .github/workflows/rate-limits-backend-release.yml
  .github/workflows/release-testing.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/salt-sharing-canister-release.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  .github/workflows/schedule-weekly.yml
  .github/workflows/system-tests-k8s.yml
  .github/workflows/update-mainnet-revisions.yaml
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  WORKSPACE.bazel
  bazel/external_crates.bzl
  ci/container/TAG
  ci/container/files/packages.common
  ic-os/components/hostos-scripts/guestos/guestos.service
  ic-os/components/hostos-scripts/guestos/guestos.sh
  ic-os/components/hostos.bzl
  ic-os/hostos/README.adoc
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/src/guest_vm_config.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/os_tools/hostos_tool/Cargo.toml
  rs/ic_os/os_tools/hostos_tool/src/guest_vm.rs
  rs/ic_os/os_tools/hostos_tool/src/main.rs
  rs/ic_os/os_tools/hostos_tool/src/systemd_notifier.rs
Labels: refactor, @idx, @node, @finint, CI_MACOS_INTEL

#5602 test: Re-enable Consensus hourly tests
  rs/tests/consensus/subnet_recovery/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
Labels: test

#5562 chore: add http outcalls cost metrics
  rs/cycles_account_manager/src/lib.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment_metrics.rs
Labels: chore, @execution

#5599 chore(ICRC_Ledger): FI-1770: Remove unused ic-cdk dependency from icrc-ledger-types
  Cargo.lock
  packages/icrc-ledger-types/BUILD.bazel
  packages/icrc-ledger-types/Cargo.toml
Labels: chore, @finint

#5598 chore: [EXC-2066] Add a snapshot to upgrade/downgrade tests.
  Cargo.lock
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/consensus/upgrade/Cargo.toml
  rs/tests/consensus/upgrade/common.rs
Labels: chore, CI_ALL_BAZEL_TARGETS

#5553 test(node): Re-enable hostos_upgrade_from_latest_release_to_current
  rs/tests/nested/BUILD.bazel
Labels: test, @node, CI_ALL_BAZEL_TARGETS

#5610 chore(icrc-ledger-types): create a new version for release
  Cargo.lock
  packages/icrc-ledger-types/CHANGELOG.md
  packages/icrc-ledger-types/Cargo.toml
Labels: chore

#5584 chore: improve environment variable tests
  rs/embedders/tests/system_api.rs
  rs/embedders/tests/wasmtime_embedder.rs
Labels: chore, @execution, @ic-message-routing-owners

#5618 chore: update mgmt canister contribution guide by required PocketIC changes
  rs/execution_environment/Contributing.md
Labels: chore, @execution

#5237 feat(ICRC_Ledger): FI-1604: Set index in existing SNS and ck ledgers
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/src/lib.rs
  rs/ledger_suite/icrc1/ledger/src/main.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/src/icrc_106.rs
Labels: feat, @cross-chain-team, CI_ALL_BAZEL_TARGETS, @governance-team

#5620 chore: update PocketIC docs on nonmainnet features
  packages/pocket-ic/HOWTO.md
Labels: chore

#5625 chore(IDX): use catchall subdirectory for zig wrapper build
  bazel/hermetic_cc_toolchain.patch
Labels: chore, @idx

#5506 feat(nns): Set following on multiple topics at once.
  rs/nns/governance/api/src/proposal_submission_helpers.rs
  rs/nns/governance/api/src/types.rs
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/src/pb/mod.rs
  rs/nns/governance/tests/neurons.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @governance-team

#5636 fix: Remove short argument name (-h) for hostos_config_object_path
  rs/ic_os/os_tools/hostos_tool/src/main.rs
Labels: fix

#5639 fix: Deploy dev version of hostos_tool in dev HostOS
  ic-os/hostos/defs.bzl
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/release/BUILD.bazel
Labels: fix

#5640 chore(IDX): Use simple action for fuzzers build
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#5631 fix(ic-backup): always wait until the most recent checkpoint has been created and verified, and manifest created
  rs/replay/src/player.rs
Labels: fix, @consensus, CI_ALL_BAZEL_TARGETS

#5647 docs(governance): Updated CHANGELOG files for canisters that we just proposed.
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
Labels: docs

#5592 test(Ledgers): FI-1459: Add transfer_from to valid_transactions_strategy
  Cargo.lock
  rs/ledger_suite/icrc1/index-ng/tests/tests.rs
  rs/ledger_suite/icrc1/test_utils/BUILD.bazel
  rs/ledger_suite/icrc1/test_utils/Cargo.toml
  rs/ledger_suite/icrc1/test_utils/src/lib.rs
  rs/ledger_suite/tests/sm-tests/src/in_memory_ledger.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/account_balances.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/transfers.rs
  rs/rosetta-api/icrc1/src/construction_api/services.rs
  rs/rosetta-api/icrc1/src/construction_api/utils.rs
  rs/rosetta-api/icrc1/tests/integration_test_components/storage/storing_blockchain_data_test.rs
  rs/rosetta-api/icrc1/tests/multitoken_system_tests.rs
  rs/rosetta-api/icrc1/tests/system_tests.rs
Labels: test, @finint

#5645 chore(IDX): Remove bazel macos-ci config
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  bazel/conf/.bazelrc.build
Labels: chore, @idx

#5629 chore: include target labels in bazel profiles
  .github/actions/bazel/bin/bazel
Labels: chore, @idx

#5634 test(nns): Mention `node-rewards` is implied by `all` in NNS upgrade test.
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
Labels: test, CI_ALL_BAZEL_TARGETS, @governance-team

#5649 fix(test): Increase DKG interval of large subnet recovery test
  rs/recovery/src/steps.rs
  rs/tests/consensus/subnet_recovery/common.rs
Labels: fix, @consensus, CI_ALL_BAZEL_TARGETS

#5658 chore(IDX): remove system-tests-k8s workflow
  .github/workflows/system-tests-k8s.yml
Labels: chore

#5661 chore: Sort Cargo.toml members and deps
  Cargo.toml
Labels: chore

#5655 chore(IDX): Simplify release-testing workflow
  .github/actions/bazel/action.yaml
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: chore, @idx, @dre

#5459 chore(crypto): CRP-2831 Modify VetKD to be robust about duplicated node shares
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/benches/vetkd.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
  rs/crypto/src/vetkd/mod.rs
  rs/crypto/test_utils/vetkd/src/lib.rs
Labels: chore, @crypto-team

#5616 feat(ic-admin): Use canister_ranges_ keys to read routing table
  rs/registry/admin/src/main.rs
Labels: feat

#5613 feat: add time synchronization metric to metrics proxy
  ic-os/components/monitoring/metrics-proxy/guestos/metrics-proxy.yaml
  ic-os/components/monitoring/metrics-proxy/hostos/metrics-proxy.yaml
Labels: feat, @dre

#5611 chore: move all hourly system-tests to long_test (push on master)
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/schedule-hourly.yml
  rs/tests/consensus/subnet_recovery/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/networking/BUILD.bazel
Labels: chore, @idx, @consensus, CI_ALL_BAZEL_TARGETS

#5637 chore: refactor hard-coded constants in DTS tests
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/tests/dts.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_machine_tests/tests/multi_subnet.rs
  rs/universal_canister/lib/src/lib.rs
Labels: chore, @execution, @pocket-ic, @ic-message-routing-owners

#5665 test: add test for candid types of management canister types
  Cargo.lock
  rs/execution_environment/Contributing.md
  rs/types/management_canister_types/BUILD.bazel
  rs/types/management_canister_types/Cargo.toml
  rs/types/management_canister_types/tests/candid_equality.rs
  rs/types/management_canister_types/tests/ic.did
Labels: test, @execution

#5657 feat: [CON-1517, CON-1518] populate HTTP context args and proto with replication enum
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/scheduler/tests.rs
  rs/execution_environment/tests/subnet_size_test.rs
  rs/https_outcalls/client/src/client.rs
  rs/https_outcalls/consensus/src/payload_builder/tests.rs
  rs/https_outcalls/consensus/src/pool_manager.rs
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/rust_canisters/proxy_canister/src/lib.rs
  rs/types/management_canister_types/src/http.rs
  rs/types/management_canister_types/tests/ic.did
  rs/types/types/src/canister_http.rs
  rs/types/types/src/lib.rs
Labels: feat, @consensus, @execution, @ic-message-routing-owners, @ic-interface-owners

#5673 fix: Don't map ID when extracting
  toolchains/sysimage/build_container_filesystem_tar.py
Labels: fix

#5677 chore: merge release-testing system tests
  .github/actions/bazel/action.yaml
  .github/workflows-source/release-testing.yml
  .github/workflows/release-testing.yml
Labels: chore, @idx

#5676 chore: simplify build-all-no-cache command
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/schedule-hourly.yml
Labels: chore, @idx

#5678 chore: Clean up workflow IDs
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#5675 chore: use HTTP gateway for nested registration test
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
Labels: chore, @node

#5679 chore: filter out head nns benchmarks by tag
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  rs/tests/system_tests.bzl
Labels: chore, @idx

#5682 chore(IDX): bump timeout for ledger_test
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
Labels: chore, @finint

#5686 refactor(orchestrator): [CON-1457] Remove dependency to canister_client in orchestrator
  Cargo.lock
  rs/canister_client/sender/src/lib.rs
  rs/orchestrator/BUILD.bazel
  rs/orchestrator/Cargo.toml
  rs/orchestrator/src/registration.rs
  rs/orchestrator/src/signer.rs
Labels: refactor, @consensus, CI_ALL_BAZEL_TARGETS

#5382 feat(PocketIC): bootstrap registry canister when creating PocketIC instance
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/build.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/tests/test.rs
  rs/registry/proto_data_provider/src/lib.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @pocket-ic, @ic-message-routing-owners, @governance-team

#5694 chore: Add candid types of new management endpoint
  rs/types/management_canister_types/tests/candid_equality.rs
  rs/types/management_canister_types/tests/ic.did
Labels: chore

#5695 chore: Move guest_vm_runner to a separate crate
  Cargo.lock
  Cargo.toml
  ic-os/components/hostos-scripts/guestos/guestos.service
  ic-os/hostos/defs.bzl
  ic-os/tests/BUILD.bazel
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/src/lib.rs
  rs/ic_os/os_tools/guest_vm_runner/BUILD.bazel
  rs/ic_os/os_tools/guest_vm_runner/Cargo.toml
  rs/ic_os/os_tools/guest_vm_runner/build.rs
  rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_kvm.xml
  rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_qemu.xml
  rs/ic_os/os_tools/guest_vm_runner/golden/guestos_vm_sev.xml
  rs/ic_os/os_tools/guest_vm_runner/src/boot_args.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_direct_boot.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_vm_config.rs
  rs/ic_os/os_tools/guest_vm_runner/src/main.rs
  rs/ic_os/os_tools/guest_vm_runner/src/mount.rs
  rs/ic_os/os_tools/guest_vm_runner/src/systemd_notifier.rs
  rs/ic_os/os_tools/guest_vm_runner/templates/guestos_vm_template.xml
  rs/ic_os/os_tools/hostos_tool/BUILD.bazel
  rs/ic_os/os_tools/hostos_tool/Cargo.toml
  rs/ic_os/os_tools/hostos_tool/src/main.rs
  rs/ic_os/release/BUILD.bazel
Labels: chore, @node

#5653 feat: EXC-2071: Add System API `env_var_name_exists`
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/linker.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/src/wasmtime_embedder/system_api_complexity.rs
  rs/embedders/tests/system_api.rs
  rs/embedders/tests/wasmtime_embedder.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/interfaces/src/execution_environment.rs
Labels: feat, @execution

#5617 feat: EXC-2056: Update CanisterSettings for environment variables
  rs/config/src/execution_environment.rs
  rs/cycles_account_manager/src/lib.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_settings.rs
  rs/execution_environment/src/execution_environment.rs
  rs/nns/cmc/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/ic.did
Labels: feat, @pocket-ic, @ic-message-routing-owners, @governance-team

#5441 feat: [MR-667] rename_canister endpoint
  rs/embedders/src/wasmtime_embedder/system_api/routing.rs
  rs/embedders/src/wasmtime_embedder/system_api/sandbox_safe_system_state.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/dts.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/state_machine_tests/src/lib.rs
  rs/state_machine_tests/tests/multi_subnet.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/candid_equality.rs
  rs/types/management_canister_types/tests/ic.did
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: feat, @execution, @ic-message-routing-owners, @ic-interface-owners

#5500 [feat]: Rehash manifest after publishing it [MR-682]
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/manifest.rs
  rs/state_manager/src/manifest/tests/computation.rs
  rs/state_manager/src/split/tests.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/tests/state_manager.rs
Labels: @ic-message-routing-owners

#5709 test: Improve fake mounter with persistent mounts
  rs/ic_os/os_tools/guest_vm_runner/src/main.rs
  rs/ic_os/os_tools/guest_vm_runner/src/mount.rs
Labels: test, @node

#5407 refactor(node): deployment_json.rs and deployment.json.template
  Cargo.lock
  ic-os/setupos/data/deployment.json.template
  ic-os/setupos/defs.bzl
  rs/ic_os/config/src/deployment_json.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config_types/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-image-config/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-image-config/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/tests/driver/src/driver/bootstrap.rs
Labels: refactor, @idx, @node

#5654 feat(node): grub-upgrader component
  ic-os/bootloader/guestos_grub.cfg
  ic-os/bootloader/hostos_grub.cfg
  ic-os/components/hostos-scripts/grub-upgrader/grub-upgrader.service
  ic-os/components/hostos-scripts/grub-upgrader/grub-upgrader.sh
  ic-os/components/hostos.bzl
  ic-os/defs.bzl
Labels: feat, @node

#5688 chore: remove schedule-hourly
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/schedule-hourly.yml
Labels: chore, @idx, @product-security

#5690 chore: don't set amd64-darwin PATH
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx, CI_MACOS_INTEL

#5702 refactor(node): Organize config tool into hostos and setupos directories
  rs/ic_os/config/src/hostos/guestos_bootstrap_image.rs
  rs/ic_os/config/src/hostos/guestos_config.rs
  rs/ic_os/config/src/hostos/mod.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/src/setupos/config_ini.rs
  rs/ic_os/config/src/setupos/deployment_json.rs
  rs/ic_os/config/src/setupos/mod.rs
  rs/ic_os/dev_test_tools/launch-single-vm/src/main.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_vm_config.rs
  rs/tests/driver/src/driver/bootstrap.rs
Labels: refactor, @idx, @node
