Repository dfinity/ic, pull requests merged in 2025-02, with the labels that each got.

#3685 feat(pocket-ic): support custom blockmaker metrics at each round
  Cargo.lock
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/test_canister/canister.did
  packages/pocket-ic/test_canister/src/canister.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/src/lib.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/state_machine_tests/src/lib.rs
Labels: feat, @execution, @ic-message-routing-owners

#3724 chore(IDX): eng-consensus-prs
  .github/workflows/team-channels.json
Labels: chore, @idx

#3726 feat: Add `VetKdProtocol` to `Crypto` trait
  rs/crypto/temp_crypto/src/lib.rs
  rs/interfaces/src/crypto.rs
Labels: feat, @crypto-team

#3729 refactor: Remove unused print in execution tests
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: refactor, @execution

#3631 fix: EXC-1838 Run hook after CanisterWasmMemoryLimitExceeded error is fixed
  rs/execution_environment/src/execution/update.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: fix, @execution

#3267 feat: enable testnet4 support in the bitcoin adapter
  Cargo.lock
  ic-os/components/ic/ic-btc-adapter/generate-btc-adapter-config.sh
  rs/bitcoin/adapter/src/config.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/validation/BUILD.bazel
  rs/bitcoin/validation/Cargo.toml
  rs/bitcoin/validation/src/constants.rs
  rs/bitcoin/validation/src/header.rs
Labels: feat, @idx, @cross-chain-team

#3718 feat(crypto): CRP-2687 make some conversions to KeyId infallible
  rs/crypto/internal/crypto_service_provider/src/key_id/mod.rs
  rs/crypto/internal/crypto_service_provider/src/key_id/tests.rs
  rs/crypto/internal/crypto_service_provider/src/keygen/tests.rs
  rs/crypto/internal/crypto_service_provider/src/signer/tests.rs
  rs/crypto/internal/crypto_service_provider/src/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/api.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/basic_sig/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/basic_sig/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/multi_sig/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/multi_sig/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/public_and_secret_key_store/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/public_and_secret_key_store/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/secret_key_store/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tls/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/tls/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg.rs
  rs/crypto/internal/crypto_service_provider/tests/remote_vault_basig_signature_delegation.rs
  rs/crypto/internal/crypto_service_provider/tests/remote_vault_rpc_connection.rs
  rs/crypto/src/sign/basic_sig.rs
  rs/crypto/src/sign/basic_sig/tests.rs
  rs/crypto/src/sign/multi_sig.rs
  rs/crypto/src/tls/rustls/client_handshake.rs
  rs/crypto/src/tls/rustls/server_handshake.rs
Labels: feat, @crypto-team

#3722 chore: remove reference to a custom jsonrpc version in Cargo.toml
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/cargo.config
Labels: chore, @idx

#3700 refactor(registry): Migrate Registry to use MemoryManager instead of raw stable memory
  Cargo.lock
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/Cargo.toml
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/src/lib.rs
  rs/registry/canister/src/registry_lifecycle.rs
  rs/registry/canister/src/storage.rs
  rs/registry/canister/unreleased_changelog.md
Labels: refactor, @nns-team

#3712 refactor(nns-tools): Turn release-runscript to clap-powered CLI
  Cargo.lock
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/Cargo.toml
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: refactor, @nns-team

#3713 feat(nns-tools): Release runscript automatically grabs the latest commit
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3714 feat(nns-tools): Release runscript asks you which canisters to release
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3711 chore(governance): Remove unused types
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/pb/conversions.rs
Labels: chore, @nns-team

#3710 feat(nns/sns): Add query stats to canister status
  rs/nervous_system/clients/src/canister_status.rs
  rs/nervous_system/clients/src/management_canister_client/tests.rs
  rs/nns/handlers/root/impl/canister/root.did
  rs/nns/handlers/root/interface/src/client.rs
  rs/nns/handlers/root/unreleased_changelog.md
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/unreleased_changelog.md
  rs/sns/root/canister/root.did
  rs/sns/root/unreleased_changelog.md
  rs/sns/sns.bzl
  rs/sns/swap/canister/swap.did
  rs/sns/swap/canister/tests.rs
  rs/sns/swap/unreleased_changelog.md
Labels: feat, @nns-team

#3739 feat(nns): Bump neurons limit
  rs/nns/governance/src/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#3732 docs(nns): Created entry in Governance's CHANGELOG for proposal 134777 (Jan 10).
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
Labels: docs, @nns-team

#3715 feat(nns-tools): Release runscript generates proposal texts for you
  Cargo.lock
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/Cargo.toml
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3716 feat(nns-tools): Release runscript submits proposals for you
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3717 feat(nns-tools): Release runscript generates forum posts
  Cargo.lock
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/Cargo.toml
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat

#3707 chore: allow automatically replacing a node even if it is active as an API BN
  rs/nns/governance/unreleased_changelog.md
  rs/registry/canister/src/mutations/node_management/do_add_node.rs
  rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
  rs/registry/canister/unreleased_changelog.md
Labels: chore, @nns-team

#3744 fix(custom domains): bump cloudflare-rs due to CF API changes
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/external_crates.bzl
Labels: fix, @idx

#3650 chore(boundary): `salt_sharing` canister implementation
  Cargo.lock
  Cargo.toml
  rs/boundary_node/salt_sharing/Cargo.toml
  rs/boundary_node/salt_sharing/api/Cargo.toml
  rs/boundary_node/salt_sharing/api/src/lib.rs
  rs/boundary_node/salt_sharing/canister/canister.rs
  rs/boundary_node/salt_sharing/canister/lib.rs
  rs/boundary_node/salt_sharing/canister/logs.rs
  rs/boundary_node/salt_sharing/canister/salt_sharing_canister.did
  rs/boundary_node/salt_sharing/canister/storage.rs
  rs/boundary_node/salt_sharing/canister/time.rs
  rs/boundary_node/salt_sharing/dfx.json
Labels: chore, @boundary-node

#3750 feat(metrics-proxy): add rules for `mr_blocks_proposed_total` and `mr_blocks_not_proposed_total`
  ic-os/components/monitoring/metrics-proxy/guestos/metrics-proxy.yaml
Labels: feat

#3758 feat(governance-tools): Added TODOs to generated "Features & Fixtures" section.
  testnet/tools/nns-tools/lib/proposals.sh
Labels: feat, @nns-team

#3547 feat(IC-1579): Governance: TLA Codelink for refresh_neuron
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tla/mod.rs
  rs/nns/governance/src/governance/tla/refresh_neuron.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tla/Refresh_Neuron.tla
  rs/nns/governance/tla/Refresh_Neuron_Apalache.tla
Labels: feat

#3740 chore(nns): Modify the comment on `include_empty_neurons_readable_by_caller`
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
Labels: chore

#3764 fix(nns/sns): Minor fix for release script
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: fix

#3687 fix: don't clone blocks during `get_successors`
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
Labels: fix, @consensus

#3562 feat: re-enable hashes-in-blocks feature on all subnets
  rs/replica/setup_ic_network/src/lib.rs
Labels: feat, @consensus

#3760 chore: [EXC-1880] Test hook behavior across upgrade
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: chore, @execution

#3771 docs(nns): Follow up on PR 2339
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
Labels: docs, @nns-team

#3776 fix: EXC-1878: Use pages for tracking changes
  rs/memory_tracker/src/lib.rs
Labels: fix, @execution

#3769 fix: reduce the bitcoin adapter maximum response size to 1MB for testnet4
  Cargo.lock
  rs/bitcoin/adapter/BUILD.bazel
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/adapter/src/get_successors_handler.rs
Labels: fix, @consensus

#3780 chore(nns): Deleted backfilling voting_power_refreshed_timestamp.
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/integration_tests/src/neuron_following.rs
Labels: chore, @nns-team

#3768 fix: increase the number of bitcoin in flight requests to 1000.
  rs/bitcoin/adapter/src/get_successors_handler.rs
Labels: fix, @consensus

#3708 chore: Remove old storage logic
  rs/config/src/state_manager.rs
  rs/replicated_state/src/page_map.rs
  rs/replicated_state/src/page_map/storage/tests.rs
  rs/replicated_state/src/page_map/tests.rs
  rs/state_layout/src/state_layout.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/checkpoint/tests.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/manifest.rs
  rs/state_manager/src/manifest/tests/computation.rs
  rs/state_manager/src/split.rs
  rs/state_manager/src/split/tests.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/tests/common/mod.rs
  rs/state_manager/tests/state_manager.rs
  rs/sys/src/fs.rs
Labels: chore, @execution, @ic-message-routing-owners

#3779 perf(MR): Look up `SubnetIds` from a `BTreeSet` instead of from a `Vec`
  rs/replicated_state/src/canister_state/queues.rs
  rs/replicated_state/src/canister_state/queues/tests.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/system_api/src/sandbox_safe_system_state.rs
Labels: perf

#3762 chore(boundary): add metrics and access control to `salt_sharing` canister
  Cargo.lock
  rs/boundary_node/salt_sharing/BUILD.bazel
  rs/boundary_node/salt_sharing/Cargo.toml
  rs/boundary_node/salt_sharing/api/BUILD.bazel
  rs/boundary_node/salt_sharing/api/Cargo.toml
  rs/boundary_node/salt_sharing/api/src/lib.rs
  rs/boundary_node/salt_sharing/canister/canister.rs
  rs/boundary_node/salt_sharing/canister/helpers.rs
  rs/boundary_node/salt_sharing/canister/lib.rs
  rs/boundary_node/salt_sharing/canister/logs.rs
  rs/boundary_node/salt_sharing/canister/metrics.rs
  rs/boundary_node/salt_sharing/canister/storage.rs
  rs/boundary_node/salt_sharing/dfx.json
Labels: chore, @boundary-node

#3763 chore: Update Mainnet IC revisions canisters file and fix ICP ledger tests
  WORKSPACE.bazel
  mainnet-canister-revisions.json
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
Labels: chore, @idx, @nns-team, @finint

#3778 chore(nns): Deleted set_initial_voting_power_economics.
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/data_migration.rs
  rs/nns/governance/src/data_migration_tests.rs
Labels: chore, @nns-team

#3788 revert: "chore(IDX): bazel-test-all ln1"
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: revert, @idx

#3783 docs(nns): Added a TODO with Jira ticket ID about the demise of refresh neuron flags.
  rs/nns/governance/src/lib.rs
Labels: docs

#3765 chore: Bump canbench to 0.1.9
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/external_crates.bzl
Labels: chore, @idx

#3789 refactor: Add memory usage checks when loading a snapshot for consistency
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
Labels: refactor

#3592 feat(nns): list_neurons supports querying by subaccount
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/api/src/pb.rs
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/governance/tests/list_neurons.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/governance_neurons.rs
  rs/nns/integration_tests/src/neuron_voting.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/rosetta-api/icp/src/request_handler/construction_payloads.rs
  rs/rosetta-api/icp/tests/system_tests/common/utils.rs
  rs/tests/driver/src/canister_api.rs
Labels: feat, @idx, @nns-team, @finint

#3738 feat(sns-cli): Cleanup store canister after upgrading an SNS-controlled canister
  rs/nervous_system/agent/src/management_canister/mod.rs
  rs/nervous_system/agent/src/management_canister/requests.rs
  rs/nervous_system/agent/src/pocketic_impl.rs
  rs/nervous_system/agent/src/sns/governance.rs
  rs/nervous_system/integration_tests/tests/upgrade_sns_controlled_canister_with_large_wasm.rs
  rs/sns/cli/src/lib.rs
  rs/sns/cli/src/main.rs
  rs/sns/cli/src/upgrade_sns_controlled_canister.rs
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
Labels: feat, @nns-team

#3709 feat(registry): Obsolete legacy ECDSA configs
  rs/protobuf/src/registry/subnet.rs
  rs/registry/canister/src/mutations/do_create_subnet.rs
  rs/registry/canister/src/mutations/do_recover_subnet.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/canister/tests/common/test_helpers.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/registry/canister/unreleased_changelog.md
  rs/registry/subnet_features/src/lib.rs
Labels: feat, @nns-team, @ic-interface-owners

#3773 refactor(nns): Follow up on PR 3090
  rs/nns/governance/src/neuron_store/metrics.rs
Labels: refactor, @nns-team

#3790 fix(sns): Correctly translate `ManageLedgerParameters` into `LedgerUpgradeArgs`
  rs/sns/governance/src/types.rs
  rs/sns/governance/src/types/tests.rs
  rs/sns/governance/unreleased_changelog.md
Labels: fix, @nns-team

#3735 chore(nervous-system): Release on 2025-02-03
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
  rs/sns/root/CHANGELOG.md
  rs/sns/root/unreleased_changelog.md
Labels: chore, @idx

#3609 feat(rosetta): Support pagination for Rosetta API list_neurons
  rs/rosetta-api/icp/src/convert.rs
  rs/rosetta-api/icp/src/convert/state.rs
  rs/rosetta-api/icp/src/request.rs
  rs/rosetta-api/icp/src/request_handler/construction_parse.rs
  rs/rosetta-api/icp/src/request_handler/construction_payloads.rs
  rs/rosetta-api/icp/src/request_types.rs
Labels: feat, @finint

#3551 perf: Add low-level memory ops benchmark
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/memory_tracker/BUILD.bazel
  rs/memory_tracker/Cargo.toml
  rs/memory_tracker/benches/memory_ops.rs
  rs/memory_tracker/benches/test-data/64KiB.txt
Labels: perf, @idx, @execution

#3766 perf(nns): Set NNS Governance governance noise threshold to 5%
  bazel/canbench.bzl
  bazel/canbench.sh
  rs/nns/governance/BUILD.bazel
Labels: perf, @nns-team

#3786 feat(sns): Do not store logos in SNS initialization parameters to save space
  rs/nns/sns-wasm/unreleased_changelog.md
  rs/sns/init/src/lib.rs
  rs/sns/integration_tests/src/governance.rs
Labels: feat, @nns-team

#3720 chore(ckbtc): Separate event types for mainnet and testnet logs
  rs/bitcoin/ckbtc/minter/test_resources/mainnet_events.gz
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
Labels: chore, @cross-chain-team

#3791 feat(nervous-system): runscript partially automates scheduling the votes
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat, @nns-team

#3793 refactor(nervous-system): use anyhow in release runscript
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: refactor

#3785 fix(crypto): CRP-2692 Fix ic-ed25519 crate attributes
  Cargo.lock
  packages/ic-ed25519/Cargo.toml
Labels: fix

#3794 refactor(nervous-system): add "press enter to continue" helper
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: refactor, @idx, @consensus, @execution, @boundary-node, @pocket-ic, @crypto-team, @ic-message-routing-owners, @finint, @ic-owners-owners

#3454 chore(ckbtc): add check_transaction_query method to Bitcoin checker
  rs/bitcoin/checker/BUILD.bazel
  rs/bitcoin/checker/btc_checker_canister.did
  rs/bitcoin/checker/src/fetch.rs
  rs/bitcoin/checker/src/main.rs
  rs/bitcoin/checker/src/types.rs
  rs/bitcoin/checker/tests/tests.rs
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3796 refactor(nervous-system-runscript): move utilities to utils.rs
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/src/commit_switcher.rs
  rs/nervous_system/tools/release-runscript/src/main.rs
  rs/nervous_system/tools/release-runscript/src/utils.rs
Labels: refactor

#3755 chore(ic-boundary): disable bouncer
  ic-os/components/ic/share/ic-boundary.env
Labels: chore, @node

#3690 fix: move metrics to all messages
  rs/bitcoin/adapter/src/connectionmanager.rs
Labels: fix, @consensus

#3820 test(btc): Port ckBTC tests from legacy ECDSA to chain key Registry API
  rs/consensus/tests/framework/mod.rs
  rs/messaging/src/message_routing/tests.rs
  rs/registry/admin/src/types.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/subnet_features/src/lib.rs
  rs/tests/ckbtc/src/lib.rs
Labels: test, @consensus, @nns-team, @ic-message-routing-owners, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3817 test(ICP_Ledger): Fix ICP ledger suite golden state test
  rs/ledger_suite/icp/tests/golden_nns_state.rs
Labels: test, @finint

#3823 chore(p2p): make some some functions/structs/traits private to the ic_artifact_manager crate
  rs/p2p/artifact_manager/src/lib.rs
  rs/p2p/test_utils/src/turmoil.rs
Labels: chore, @consensus

#3752 chore(IDX): push checksum logic to Bazel
  bazel/conf/.bazelrc.build
  ci/container/build-ic.sh
  ic-os/guestos/envs/prod/BUILD.bazel
  ic-os/hostos/envs/prod/BUILD.bazel
  ic-os/setupos/envs/prod/BUILD.bazel
  publish/binaries/BUILD.bazel
  publish/canisters/BUILD.bazel
  publish/defs.bzl
Labels: chore, @idx, @node

#3826 chore(IDX): remove ic-os pre-check
  ic-os/defs.bzl
Labels: chore, @node

#3824 feat: ramp up the socks proxy from registry to 10%
  rs/https_outcalls/adapter/Cargo.toml
  rs/https_outcalls/adapter/src/metrics.rs
  rs/https_outcalls/adapter/src/rpc_server.rs
  rs/https_outcalls/consensus/Cargo.toml
  rs/https_outcalls/consensus/src/pool_manager.rs
Labels: feat, @consensus

#3745 feat: CON-1421 Call crypto in the VetKd client
  rs/consensus/src/idkg/complaints.rs
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/payload_builder/key_transcript.rs
  rs/consensus/src/idkg/payload_builder/pre_signatures.rs
  rs/consensus/src/idkg/payload_builder/resharing.rs
  rs/consensus/src/idkg/payload_builder/signatures.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/pre_signer.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
Labels: feat, @consensus

#3678 chore(node): move metrics services to run before node_exporter
  ic-os/components/hostos-scripts/monitoring/monitor-nvme.service
  ic-os/components/hostos-scripts/monitoring/monitor-power.service
  ic-os/components/monitoring/custom-metrics/metrics_tool.service
  ic-os/components/monitoring/fstrim/fstrim_tool.service
  ic-os/components/monitoring/nft-exporter/nft-exporter.service
  ic-os/components/monitoring/setup-node-gen-status.service
Labels: chore, @node

#3798 chore(node): update mount settings
  ic-os/components/early-boot/save-machine-id/save-machine-id.service
  ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.service
  ic-os/components/init/setup-encryption/setup-encryption.service
  ic-os/components/monitoring/node_exporter/setup-node_exporter-keys/setup-node_exporter-keys.service
  ic-os/components/upgrade/shared-resources/monitor-expand-shared-data/monitor-expand-shared-data.service
  ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.service
Labels: chore, @node

#3787 chore(node): export cpu microcode metrics
  ic-os/components/hostos-scripts/monitoring/custom-metrics.service
  ic-os/components/hostos-scripts/monitoring/custom-metrics.sh
  ic-os/components/hostos.bzl
Labels: chore, @node

#3838 chore(IDX): simplify build-determinism.sh
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/scripts/build-determinism.sh
Labels: chore

#3806 feat(nervous-system): release runscript automatically creates changelog PRs
  rs/nervous_system/tools/release-runscript/BUILD.bazel
  rs/nervous_system/tools/release-runscript/src/commit_switcher.rs
  rs/nervous_system/tools/release-runscript/src/main.rs
  rs/nervous_system/tools/release-runscript/src/utils.rs
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: feat

#3827 chore(registry): Remove obsolete ECDSA API
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/crypto/src/keygen/tests.rs
  rs/crypto/temp_crypto/src/lib.rs
  rs/crypto/tests/integration_test.rs
  rs/nns/integration_tests/src/subnet_handler.rs
  rs/prep/src/subnet_configuration.rs
  rs/protobuf/def/registry/subnet/v1/subnet.proto
  rs/protobuf/src/gen/registry/registry.subnet.v1.rs
  rs/protobuf/src/gen/state/registry.subnet.v1.rs
  rs/protobuf/src/gen/types/registry.subnet.v1.rs
  rs/registry/admin/src/create_subnet.rs
  rs/registry/admin/src/recover_subnet.rs
  rs/registry/admin/src/update_subnet.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/src/invariants/crypto/tests.rs
  rs/registry/canister/src/mutations/do_create_subnet.rs
  rs/registry/canister/src/mutations/do_recover_subnet.rs
  rs/registry/canister/src/mutations/do_update_subnet.rs
  rs/registry/canister/tests/create_subnet.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/test_utilities/registry/src/lib.rs
  rs/tests/ckbtc/src/lib.rs
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/tests/consensus/utils/src/ssh_access.rs
  rs/tests/driver/src/nns.rs
Labels: chore, @idx, @consensus, @boundary-node, @nns-team, @crypto-team, @ic-interface-owners, @utopia, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3809 chore(nns): Clean up the migration code to backfill InstallCode hashes
  rs/nns/governance/src/governance.rs
Labels: chore, @nns-team

#3812 test(nns): Clean up integration test helpers
  rs/nns/test_utils/src/governance.rs
  rs/nns/test_utils/src/itest_helpers.rs
Labels: test, @nns-team

#3819 fix: open port 22 between replica nodes
  ic-os/components/ic/generate-ic-config/ic.json5.template
  rs/orchestrator/testdata/nftables_assigned_replica.conf.golden
Labels: fix

#3688 feat(MR): [MR-649] Support incremental rollout of best-effort calls
  rs/config/src/embedders.rs
  rs/drun/src/main.rs
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/src/wasm_executor.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
  rs/embedders/tests/wasmtime_random_memory_writes.rs
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/src/execution/response/tests.rs
  rs/execution_environment/tests/dts.rs
  rs/execution_environment/tests/execution_test.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/messaging/src/message_routing.rs
  rs/messaging/src/routing/stream_builder.rs
  rs/messaging/src/routing/stream_builder/tests.rs
  rs/messaging/tests/memory_tests.rs
  rs/starter/src/lib.rs
  rs/system_api/src/lib.rs
  rs/system_api/tests/common/mod.rs
  rs/system_api/tests/system_api.rs
  rs/test_utilities/embedders/src/lib.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @consensus, @execution, @languages

#3811 feat(ckbtc): Place update_balance and retrieve_btc guards on user accounts
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/guard.rs
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
  rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs
Labels: feat, @cross-chain-team

#3816 feat(MR): [MR-649] Roll out best-effort calls to the first few subnets
  rs/config/src/embedders.rs
  rs/config/src/execution_environment.rs
Labels: feat, @consensus, @execution, @ic-message-routing-owners, @languages

#3822 ci: change cross-chain team notification channel
  .github/workflows/team-channels.json
Labels: @idx, ci

#3850 fix: revert EXC-1838 Run hook after CanisterWasmMemoryLimitExceeded error is fixed
  rs/execution_environment/src/execution/call_or_task.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: fix

#3851 chore(IDX): don't store bazel-targets
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/bazel-scripts/main.sh
  ci/scripts/run-build-ic.sh
Labels: chore, @idx

#3682 feat: [MR-353] Asynchronously mark checkpoint readonly and sync
  rs/state_layout/src/state_layout.rs
  rs/state_layout/src/state_layout/tests.rs
  rs/state_manager/src/checkpoint.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/split.rs
  rs/state_manager/src/split/tests.rs
  rs/state_manager/src/state_sync.rs
  rs/state_manager/src/state_sync/chunkable.rs
  rs/state_manager/src/tip.rs
  rs/state_manager/tests/state_manager.rs
Labels: feat, @ic-message-routing-owners

#3582 feat(MR): [MR-638] Use both guaranteed and best-effort calls in all XNet tests
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  rs/messaging/tests/queue_tests.rs
  rs/rust_canisters/xnet_test/BUILD.bazel
  rs/rust_canisters/xnet_test/Cargo.toml
  rs/rust_canisters/xnet_test/src/lib.rs
  rs/rust_canisters/xnet_test/src/main.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/Cargo.toml
  rs/tests/message_routing/common/common.rs
  rs/tests/message_routing/global_reboot_test.rs
  rs/tests/message_routing/xnet/slo_test_lib/xnet_slo_test_lib.rs
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/message_routing/xnet/xnet_malicious_slices.rs
Labels: feat, @idx, @execution

#3848 chore: remove static testnet for bitcoin testing
  testnet/env/bitcoin/hosts
  testnet/env/bitcoin/hosts.ini
  testnet/env/bitcoin/provisional_whitelist.json
Labels: chore, @platform-operations

#3855 chore: remove integrations static testnet
  testnet/env/integrations/hosts
  testnet/env/integrations/hosts.ini
  testnet/env/integrations/provisional_whitelist.json
Labels: chore

#3701 chore: CON-1434 Remove deprecated `TaggedNiDkgTranscript` proto
  rs/protobuf/def/types/v1/dkg.proto
  rs/protobuf/src/gen/types/types.v1.rs
  rs/types/types/src/consensus/dkg.rs
Labels: chore, @consensus, @ic-interface-owners

#3772 docs(nns): Updated comment about following pruning batches.
  rs/nns/governance/canister/canister.rs
Labels: docs, @nns-team

#3865 chore(nns): Remove changelog entries which are already copied to CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
Labels: chore

#3699 chore(node): systemd tidying-up
  ic-os/components/boundary-guestos/etc/systemd/system/canary-proxy.service
  ic-os/components/boundary-guestos/etc/systemd/system/danted.service
  ic-os/components/boundary-guestos/etc/systemd/system/setup-ssh-user-keys.service
  ic-os/components/ic/generate-ic-config/generate-ic-config.service
  ic-os/components/ic/ic-btc-adapter/ic-btc-mainnet-adapter.service
  ic-os/components/ic/ic-btc-adapter/ic-btc-testnet-adapter.service
  ic-os/components/ic/ic-crypto-csp/ic-crypto-csp.service
  ic-os/components/ic/ic-https-outcalls-adapter/ic-https-outcalls-adapter.service
  ic-os/components/ic/ic-replica.service
  ic-os/components/ic/setup-permissions/setup-permissions.service
  ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.service
  ic-os/components/misc/vsock/vsock-agent.service
  ic-os/components/monitoring/filebeat/filebeat.service
  ic-os/components/monitoring/metrics-proxy/metrics-proxy.service
  ic-os/components/networking/generate-network-config/guestos/generate-network-config.service
  ic-os/components/ssh/setup-ssh-user-keys/setup-ssh-user-keys.service
  ic-os/components/upgrade/shared-resources/upgrade-shared-data-store/upgrade-shared-data-store.service
Labels: chore, @dre, @boundary-node, @node

#3864 feat(nns): Turn on the feature to migrate neurons to stable memory
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/governance_migrations.rs
Labels: feat, @nns-team

#3832 chore(crypto): CRP-2692 update ic-ed25519 changelog
  packages/ic-ed25519/CHANGELOG.md
Labels: chore, @crypto-team

#3833 chore(crypto): CRP-2693 update ic-secp256k1 changelog
  packages/ic-secp256k1/CHANGELOG.md
Labels: chore, @crypto-team

#3867 chore(nervous-system): Update changelog for release 2025-02-07
  rs/nns/cmc/CHANGELOG.md
  rs/nns/cmc/unreleased_changelog.md
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
  rs/sns/root/CHANGELOG.md
  rs/sns/root/unreleased_changelog.md
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: chore

#3870 fix(nns/sns): Minor fixes for release_runscript
  rs/nervous_system/tools/release-runscript/src/main.rs
  rs/nervous_system/tools/release-runscript/src/utils.rs
Labels: fix

#3872 chore(sns): Correct the changelog for SNS Governance
  rs/sns/governance/CHANGELOG.md
Labels: chore

#3871 fix(nervous-system): resolve issues in the release runscript discovered today
  rs/nervous_system/tools/release-runscript/src/main.rs
  rs/nervous_system/tools/release-runscript/src/utils.rs
Labels: fix

#3866 chore(nns): update root changelog
  rs/nns/handlers/root/CHANGELOG.md
  rs/nns/handlers/root/unreleased_changelog.md
Labels: chore

#3868 fix(nervous-system-tools): changelog script looks at correct field for NNS
  testnet/tools/nns-tools/add-release-to-changelog.sh
Labels: fix

#3873 chore(nns): Change NNS Root code location to one level up
  testnet/tools/nns-tools/lib/functions.sh
Labels: chore

#3877 fix: No best-effort messages in RC qualification test
  rs/tests/dre/utils/steps/xnet.rs
Labels: fix, @dre

#3861 chore(IDX): remove RUSTFLAGS from workflows
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#3863 test: Hook is run when Wasm memory limit is exceeded
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
Labels: test, @execution

#3702 chore(fuzzing): Add missing syscalls to the sandbox monitor whitelist
  rs/execution_environment/fuzz/src/lib.rs
Labels: chore, @execution

#3883 feat: branch for syncing grafana dashboards
  rs/tests/ict/cmd/helpers.go
  rs/tests/ict/cmd/testCmd.go
  rs/tests/ict/cmd/testnetCreateCmd.go
Labels: feat, @idx

#3613 feat: CON-1422 Implement the VetKd payload builder and validator
  rs/consensus/vetkd/BUILD.bazel
  rs/consensus/vetkd/Cargo.toml
  rs/consensus/vetkd/src/lib.rs
  rs/consensus/vetkd/src/utils.rs
  rs/interfaces/src/vetkd.rs
Labels: feat, @consensus

#3862 chore: Remove check `wasm_memory_threshold > wasm_memory_limit` when updating canister settings
  rs/execution_environment/src/canister_settings.rs
  rs/nns/integration_tests/src/update_canister_settings.rs
Labels: chore, @nns-team

#3828 chore: Quotation in error messages
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/tests/backtraces.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment/errors.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/nns/integration_tests/src/reset_root.rs
  rs/nns/sns-wasm/tests/deploy_new_sns.rs
  rs/registry/canister/tests/update_subnet.rs
  rs/tests/execution/inter_canister_queries_tests/call_on_cleanup.rs
Labels: chore, @execution, @nns-team, @ic-interface-owners, @finint

#3879 refactor: EXC-1890 Use saturating arithmetics when evaluating hook conditions
  Cargo.lock
  rs/replicated_state/BUILD.bazel
  rs/replicated_state/Cargo.toml
  rs/replicated_state/src/canister_state/system_state/task_queue.rs
Labels: refactor, @execution, @ic-message-routing-owners

#3880 refactor: Use saturating subtraction for simplicity
  rs/execution_environment/src/canister_settings.rs
Labels: refactor

#3858 feat(MR): Basic metrics for best-effort calls
  rs/execution_environment/src/metrics.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/src/scheduler/scheduler_metrics.rs
  rs/messaging/tests/call_tree_tests.rs
  rs/system_api/src/sandbox_safe_system_state.rs
Labels: feat

#3748 feat(EXC-1860): Increase Wasm64 heap size to 6 GiB
  rs/embedders/tests/wasmtime_embedder.rs
  rs/execution_environment/src/execution/install_code/tests.rs
  rs/types/types/src/lib.rs
Labels: feat, @execution, @ic-interface-owners

#3843 chore(ckbtc): proposal to upgrade ckBTC minter
  rs/bitcoin/ckbtc/mainnet/minter_upgrade_2025_02_06.md
Labels: chore, @cross-chain-team

#3387 feat(CON-1413): Create local transcripts for Vetkeys
  Cargo.lock
  rs/consensus/dkg/BUILD.bazel
  rs/consensus/dkg/Cargo.toml
  rs/consensus/dkg/src/dkg_key_manager.rs
  rs/consensus/dkg/src/lib.rs
  rs/consensus/dkg/src/payload_builder.rs
  rs/consensus/dkg/src/utils.rs
  rs/test_utilities/registry/BUILD.bazel
  rs/test_utilities/registry/Cargo.toml
  rs/test_utilities/registry/src/lib.rs
Labels: feat, @consensus, @ic-interface-owners

#3830 chore(boundary): add `pocket-ic` test for `salt_sharing` canister
  rs/boundary_node/salt_sharing/api/src/lib.rs
  rs/boundary_node/salt_sharing/integration_tests/BUILD.bazel
  rs/boundary_node/salt_sharing/integration_tests/Cargo.toml
  rs/boundary_node/salt_sharing/integration_tests/src/lib.rs
  rs/boundary_node/salt_sharing/integration_tests/src/pocket_ic_helpers.rs
  rs/boundary_node/salt_sharing/integration_tests/tests/salt_sharing_canister_tests.rs
Labels: chore, @boundary-node

#3801 feat(nns): Make NetworkEconomics inherit recursively.
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/network_economics.rs
  rs/nns/governance/src/network_economics_tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#3810 chore(test-utils): Remove unused dependency
  Cargo.lock
  rs/nns/test_utils/BUILD.bazel
  rs/nns/test_utils/Cargo.toml
Labels: chore, @nns-team

#3894 fix: Add ahci to HostOS initramfs to fix gen1 spms
  ic-os/components/early-boot/initramfs-tools/hostos/modules
Labels: fix

#3775 fix: bitcoin adapter: prune blocks if response empty
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/tests/adapter_test.rs
Labels: fix, @consensus

#3746 chore(EXC-1855): Adjust metric to track whether message is executed on Wasm32 or Wasm64 canisters
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/execution_environment/src/execution_environment/tests/canister_task.rs
  rs/replicated_state/src/canister_state/execution_state.rs
Labels: chore, @execution, @ic-message-routing-owners

#3899 chore(IDX): extract repository_cache
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/schedule-rust-bench.yml
  ci/bazel-scripts/main.sh
Labels: chore, @idx

#3897 test(IDX): colocate some flaky networking system-tests
  rs/tests/networking/BUILD.bazel
Labels: test, @consensus

#3909 chore: Increase the wait for checkpoint timeout for the tests
  rs/state_manager/tests/common/mod.rs
Labels: chore

#3837 fix(IDX): remove CI github email
  .github/workflows/ci-generate-ci.yml
  .github/workflows/container-autobuild.yml
  .github/workflows/rosetta-release.yml
  .github/workflows/sync-public-with-private.yml
Labels: fix, @idx, @finint

#3911 fix(IDX): chown /cache
  .github/actions/bazel-test-all/action.yaml
Labels: fix, @idx

#3908 fix(IDX): --repository_cache only for Linux
  ci/bazel-scripts/main.sh
Labels: fix, @idx

#3849 chore: remove benchmarkxsmall01 static testnet
  testnet/env/benchmarkxsmall01/hosts
  testnet/env/benchmarkxsmall01/hosts.ini
  testnet/env/benchmarkxsmall01/provisional_whitelist.json
Labels: chore, @platform-operations

#3914 chore: bump ic-gateway to 0.1.65
  ic-os/boundary-guestos/context/Dockerfile
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
Labels: chore, @boundary-node, @node

#3622 chore(EXC-1850): Upgrade Wasmtime 29
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
Labels: chore

#3892 refactor: Add `is_best_effort()` for `Request`
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: refactor, @execution, @ic-interface-owners

#3774 fix: bitcoin adapter: don't retry aggressively
  rs/bitcoin/adapter/src/blockchainmanager.rs
Labels: fix, @execution, @boundary-node, @pocket-ic, @nns-team, @crypto-team, @ic-message-routing-owners, @ic-interface-owners, @finint, @ic-owners-owners

#3924 fix(registry): Update the correct node operator ID in node removal
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/src/common/test_helpers.rs
  rs/registry/canister/src/mutations/node_management/do_remove_node_directly.rs
Labels: fix, @nns-team

#3859 feat(nns): Validate manage network economics.
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance_proto_builder.rs
  rs/nns/governance/src/network_economics.rs
  rs/nns/governance/src/network_economics_tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#3927 fix: bump cloudflare-rs crate
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/external_crates.bzl
Labels: fix, @idx

#3933 chore: Add the public ic-management-canister-types crate to the repo
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore

#3903 chore(IDX): rebuild on .github changes
  ci/bazel-scripts/diff.sh
Labels: chore

#3906 chore(IDX): Use single BAZEL_COMMAND
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/release-testing.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-testing.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
  ci/bazel-scripts/diff.sh
  ci/bazel-scripts/main.sh
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#3938 fix(IDX): remove unused step output
  ci/bazel-scripts/main.sh
Labels: fix

#3919 feat: Mihailjianu1/bitcoin serialize blocks first
  Cargo.lock
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/rpc_server.rs
  rs/bitcoin/adapter/tests/adapter_test.rs
Labels: feat, @consensus

#3940 chore(IDX): simplify workspace_status
  bazel/workspace_status.sh
Labels: chore

#3930 fix(ckbtc): use scope guard to prevent double minting
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/state/audit.rs
  rs/bitcoin/ckbtc/minter/src/state/eventlog.rs
  rs/bitcoin/ckbtc/minter/src/updates/tests.rs
  rs/bitcoin/ckbtc/minter/src/updates/update_balance.rs
Labels: fix, @cross-chain-team, CI_OVERRIDE_DIDC_CHECK

#3468 chore: Port https-outcalls spec compliances test from Haskell to Rust #2894
  Cargo.lock
  Cargo.toml
  hs/spec_compliance/BUILD.bazel
  hs/spec_compliance/src/IC/Test/Spec.hs
  hs/spec_compliance/src/IC/Test/Spec/HTTP.hs
  rs/rust_canisters/proxy_canister/src/lib.rs
  rs/rust_canisters/proxy_canister/src/main.rs
  rs/tests/httpbin-rs/src/main.rs
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/Cargo.toml
  rs/tests/networking/canister_http/canister_http.rs
  rs/tests/networking/canister_http_correctness_test.rs
  rs/tests/networking/canister_http_fault_tolerance_test.rs
  rs/tests/networking/canister_http_socks_test.rs
  rs/tests/networking/canister_http_test.rs
  rs/tests/networking/canister_http_time_out_test.rs
Labels: chore, @idx, @consensus, @research

#3917 refactor(node): standardize custom_partitions interface and improve documentation
  ic-os/defs.bzl
  ic-os/guestos/defs.bzl
  ic-os/hostos/defs.bzl
  ic-os/setupos/defs.bzl
Labels: refactor, @node

#3942 chore(IDX): clean up status
  bazel/ic_version_or_git_sha.sh
  bazel/workspace_status.sh
  rs/tests/driver/src/driver/farm.rs
  rs/tests/system_tests.bzl
Labels: chore, @idx

#3841 test(nns): Stop using NnsCanisterUpgrade nns function in integration tests
  rs/nns/integration_tests/src/canister_upgrade.rs
  rs/nns/integration_tests/src/copy_inactive_neurons_to_stable_memory.rs
  rs/nns/integration_tests/src/governance_mem_test.rs
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/nns/test_utils/src/governance.rs
  rs/nns/test_utils/src/state_test_helpers.rs
  rs/tests/cross_chain/ic_xc_ledger_suite_orchestrator_test.rs
Labels: test, @nns-team, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#3693 chore(node): Processes robust against restarts
  ic-os/components/ic/generate-ic-config/generate-ic-config.service
  ic-os/components/init/bootstrap-ic-node/bootstrap-ic-node.service
  ic-os/components/networking/generate-network-config/guestos/generate-network-config.service
  ic-os/components/networking/generate-network-config/hostos/generate-network-config.service
Labels: chore, @node

#3736 chore(crypto): CRP-2682 Change key derivation used in VetKD to BLS12-381 hash_to_scalar
  Cargo.lock
  rs/crypto/internal/crypto_lib/bls12_381/type/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/type/tests/tests.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/BUILD.bazel
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/Cargo.toml
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/ro.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/vetkd/tests.rs
Labels: chore, @crypto-team
