Repository dfinity/ic, pull requests merged in 2025-03, with the labels that each got.

#4183 perf(nns): Change from benchmarking listing neurons for unstake maturity to benchmarking the entire unstake maturity operation
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/benches.rs
Labels: perf

#4178 chore: Remove last management canister types from PocketIC and its users
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  packages/ic-metrics-assert/BUILD.bazel
  packages/ic-metrics-assert/Cargo.toml
  packages/ic-metrics-assert/src/lib.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/management_canister.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/bitcoin/checker/BUILD.bazel
  rs/bitcoin/checker/Cargo.toml
  rs/bitcoin/checker/tests/tests.rs
Labels: chore, @pocket-ic, @cross-chain-team

#4185 chore(sns): Rename `SetCustomProposalTopics` into `SetTopicsForCustomProposals`
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/proposal/set_topics_for_custom_proposals.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/unreleased_changelog.md
Labels: chore, @nns-team, CI_OVERRIDE_BUF_BREAKING

#4169 feat: Increase max snapshots allowed per canister
  packages/pocket-ic/tests/tests.rs
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/test_utilities/execution_environment/src/lib.rs
Labels: feat, @execution, @pocket-ic

#4189 fix(IDX): don't shortcut main.sh on failure
  ci/bazel-scripts/main.sh
Labels: fix, @idx

#4194 chore(IDX): disable failing NNS test
  rs/nns/integration_tests/src/neuron_following.rs
Labels: chore

#4187 chore: publish salt-sharing canister
  publish/canisters/BUILD.bazel
Labels: chore

#4191 fix(IDX): don't try to upload bep on macOS intel
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#4192 feat(testing): Add new testnet `single_app_small_node`
  rs/tests/testnets/BUILD.bazel
  rs/tests/testnets/Cargo.toml
  rs/tests/testnets/single_app_small_node.rs
Labels: feat, @idx

#4151 feat(IDX): move bazel coverage to gh artifact
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/schedule-daily.yml
  ci/scripts/bazel-coverage.sh
Labels: feat, @idx

#4198 chore(IDX): don't export BAZEL_EXTRA_ARGS
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#4022 feat: CON-1422 CON-1423 Introduce VetKD payload section and deliver completed agreements
  Cargo.lock
  rs/consensus/BUILD.bazel
  rs/consensus/Cargo.toml
  rs/consensus/benches/validate_payload.rs
  rs/consensus/src/consensus.rs
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/payload.rs
  rs/consensus/src/consensus/payload_builder.rs
  rs/consensus/tests/framework/runner.rs
  rs/consensus/tests/framework/types.rs
  rs/consensus/tests/payload.rs
  rs/consensus/vetkd/src/lib.rs
  rs/protobuf/def/types/v1/consensus.proto
  rs/protobuf/src/gen/types/types.v1.rs
  rs/replica/setup_ic_network/BUILD.bazel
  rs/replica/setup_ic_network/Cargo.toml
  rs/replica/setup_ic_network/src/lib.rs
  rs/state_machine_tests/src/lib.rs
  rs/test_utilities/types/src/batch/payload.rs
  rs/types/types/src/batch.rs
  rs/types/types/src/consensus.rs
Labels: feat, @consensus, @pocket-ic, @ic-message-routing-owners, @ic-interface-owners

#3554 feat(EXC-1821): Enable on-disk compilation cache
  ic-os/components/selinux/ic-node/ic-node.te
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/embedders/fuzz/BUILD.bazel
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/src/compilation_cache.rs
  rs/execution_environment/src/hypervisor.rs
Labels: feat, @execution, @node

#4163 chore: refactor to use test_strategy in XNet Payload Builder proptests
  Cargo.lock
  rs/xnet/payload_builder/BUILD.bazel
  rs/xnet/payload_builder/Cargo.toml
  rs/xnet/payload_builder/tests/certified_slice_pool.rs
  rs/xnet/payload_builder/tests/xnet_payload_builder.rs
Labels: chore, @ic-message-routing-owners

#4195 chore: refactor to use test_strategy in State Manager proptests
  Cargo.lock
  rs/state_manager/BUILD.bazel
  rs/state_manager/Cargo.toml
  rs/state_manager/src/labeled_tree_visitor/tests.rs
  rs/state_manager/src/manifest/tests/compatibility.rs
  rs/state_manager/src/stream_encoding/tests.rs
  rs/state_manager/src/tree_diff.rs
  rs/state_manager/tests/state_manager.rs
Labels: chore, @ic-message-routing-owners

#4201 chore(PocketIC): update PocketIC docs on live mode
  packages/pocket-ic/HOWTO.md
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/tests/test.rs
Labels: chore

#4207 chore(nns/sns): Update changelog for NNS/SNS releases
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/nns/sns-wasm/CHANGELOG.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
Labels: chore

#4179 feat(crypto): CRP-2715 Add utility crate for public key encryption
  .github/CODEOWNERS
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  packages/ic-hpke/BUILD.bazel
  packages/ic-hpke/CHANGELOG.md
  packages/ic-hpke/Cargo.toml
  packages/ic-hpke/LICENSE
  packages/ic-hpke/README.md
  packages/ic-hpke/src/lib.rs
  packages/ic-hpke/tests/tests.rs
Labels: feat, @idx, @crypto-team, @ic-owners-owners

#4210 chore: refactor to use test_strategy in Tree Deserializer proptests
  Cargo.lock
  rs/tree_deserializer/BUILD.bazel
  rs/tree_deserializer/Cargo.toml
  rs/tree_deserializer/src/tests.rs
Labels: chore, @ic-message-routing-owners

#4200 chore: refactor to use test_strategy in Canonical State proptests
  Cargo.lock
  rs/canonical_state/BUILD.bazel
  rs/canonical_state/Cargo.toml
  rs/canonical_state/tests/compatibility.rs
  rs/canonical_state/tests/size_limit_visitor.rs
  rs/canonical_state/tree_hash/BUILD.bazel
  rs/canonical_state/tree_hash/Cargo.toml
  rs/canonical_state/tree_hash/tests/hash_tree.rs
Labels: chore, @crypto-team, @ic-message-routing-owners

#4209 chore: refactor to use test_strategy in State Machine Tests proptests
  Cargo.lock
  rs/state_machine_tests/BUILD.bazel
  rs/state_machine_tests/Cargo.toml
  rs/state_machine_tests/src/tests.rs
Labels: chore, @pocket-ic, @ic-message-routing-owners

#4204 chore: refactor to use test_strategy in State Layout proptests
  Cargo.lock
  rs/state_layout/BUILD.bazel
  rs/state_layout/Cargo.toml
  rs/state_layout/src/state_layout/tests.rs
Labels: chore, @ic-message-routing-owners

#4202 chore: refactor to use test_strategy in Crypto Tree Hash proptests
  Cargo.lock
  rs/crypto/tree_hash/BUILD.bazel
  rs/crypto/tree_hash/Cargo.toml
  rs/crypto/tree_hash/test_utils/BUILD.bazel
  rs/crypto/tree_hash/test_utils/Cargo.toml
  rs/crypto/tree_hash/test_utils/tests/conversions.rs
  rs/crypto/tree_hash/tests/conversion.rs
  rs/crypto/tree_hash/tests/encoding.rs
  rs/crypto/tree_hash/tests/merge.rs
  rs/crypto/tree_hash/tests/mixed_hash_tree_proto.rs
  rs/crypto/tree_hash/tests/tree_hash.rs
Labels: chore, @crypto-team, @ic-message-routing-owners

#3969 feat(governance): Move Rewards Distribution into timer
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/nervous_system/timer_task/BUILD.bazel
  rs/nervous_system/timer_task/Cargo.toml
  rs/nervous_system/timer_task/src/lib.rs
  rs/nervous_system/timers/BUILD.bazel
  rs/nervous_system/timers/Cargo.toml
  rs/nervous_system/timers/src/lib.rs
  rs/nervous_system/timers/src/test.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/Cargo.toml
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/src/canister_state.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/governance/src/timer_tasks/reward_distribution.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/fixtures/environment_fixture.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/proposals.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @idx, @nns-team

#4196 test(nns): Fix tests that see less and less voting power.
  rs/nns/governance/init/src/lib.rs
  rs/nns/integration_tests/src/neuron_following.rs
Labels: test, @nns-team

#4211 chore: removes an entry that doesn't exist from CODEOWNERS
  .github/CODEOWNERS
Labels: chore, @ic-owners-owners

#4203 chore(IDX): drop sandbox_tmpfs_path
  bazel/conf/.bazelrc.build
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#4221 fix(IDX): export SSH_AUTH_SOCK in bazel-test-all
  .github/actions/bazel-test-all/action.yaml
Labels: fix, @idx

#4219 fix(IDX): set GH token
  .github/workflows/update-mainnet-revisions.yaml
Labels: fix, @idx

#4223 fix(IDX): switch var names
  .github/workflows/update-mainnet-revisions.yaml
Labels: fix, @idx

#4224 fix(IDX): create empty SHA256SUMS even if no build
  ci/bazel-scripts/main.sh
Labels: fix, @idx

#4168 test: add integration tests for the socks proxy path in the outcalls adapter
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  bazel/external_crates.bzl
  rs/https_outcalls/adapter/BUILD.bazel
  rs/https_outcalls/adapter/Cargo.toml
  rs/https_outcalls/adapter/src/rpc_server.rs
  rs/https_outcalls/adapter/tests/server_test.rs
Labels: test

#4208 chore: add proposal to install salt sharing canister
  rs/boundary_node/salt_sharing/proposals/install_03-03-2025_135629.md
Labels: chore, @boundary-node

#4217 chore(fuzzing): Add `fcntl` to the sandbox monitor whitelist
  rs/execution_environment/fuzz/src/lib.rs
Labels: chore, @execution

#4226 chore: increase state hash timeout in SM tests
  rs/state_machine_tests/src/lib.rs
Labels: chore

#4229 refactor: Convert more canister manager tests to use ExecutionTest framework
  rs/execution_environment/src/canister_manager/tests.rs
Labels: refactor

#3912 chore(cketh): Update EVM RPC canister
  MODULE.bazel
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#4214 perf(nns): Assert the instructions of certain periodic tasks are not too high
  rs/nns/governance/src/benches_util.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron_store/benches.rs
Labels: perf

#3429 feat(node): Add path to read mainnet json from bazel
  BUILD.bazel
  MODULE.bazel
  WORKSPACE.bazel
  bazel/jq.bzl
  bazel/json.bzl
  bazel/mainnet-versions.bzl
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup/BUILD.bazel
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/orchestrator/cup_compatibility_test.rs
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/consensus/upgrade/common.rs
  rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
  rs/tests/consensus/upgrade/upgrade_downgrade_nns_subnet_test.rs
  rs/tests/dre/BUILD.bazel
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
Labels: feat, @idx, @dre, @consensus, @nns-team, @ic-message-routing-owners

#4230 chore(IDX): show build command in main.sh
  ci/bazel-scripts/main.sh
Labels: chore, @idx

#4184 feat(nns): Limit the number of neurons to unstake maturity in a single message
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/benches.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#4212 chore: streamline BUILD.bazel file for State Manager
  Cargo.lock
  rs/state_manager/BUILD.bazel
  rs/state_manager/Cargo.toml
Labels: chore, @ic-message-routing-owners

#4137 chore(sns): Obsolete airdrop neurons from initial SNS configuration
  Cargo.lock
  rs/nervous_system/integration_tests/tests/constraints_dependencies.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/sns-wasm/canister/sns-wasm.did
  rs/nns/sns-wasm/tests/upgrade_sns_instance.rs
  rs/nns/sns-wasm/unreleased_changelog.md
  rs/sns/init/BUILD.bazel
  rs/sns/init/Cargo.toml
  rs/sns/init/proto/ic_sns_init/pb/v1/sns_init.proto
  rs/sns/init/src/create_service_nervous_system.rs
  rs/sns/init/src/distributions.rs
  rs/sns/init/src/gen/ic_sns_init.pb.v1.rs
  rs/sns/init/src/lib.rs
  rs/sns/swap/src/swap.rs
  testnet/tools/nns-tools/scenarios/generate_airdrop_entries.sh
  testnet/tools/nns-tools/scenarios/sns_lots_of_airdrops.yml
Labels: chore, @nns-team

#4213 feat(governance): Scalable Voting Rewards
  rs/nervous_system/timer_task/src/lib.rs
  rs/nervous_system/timer_task/tests/test_canisters/timer_task_canister.rs
  rs/nervous_system/timers/src/test.rs
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/benches.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/reward/calculation.rs
  rs/nns/governance/src/reward/distribution.rs
  rs/nns/governance/src/reward/mod.rs
  rs/nns/governance/src/storage.rs
  rs/nns/governance/src/timer_tasks/calculate_distributable_rewards.rs
  rs/nns/governance/src/timer_tasks/distribute_rewards.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/governance/src/voting.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/voting_rewards.rs
Labels: feat, @nns-team

#3808 refactor(nns): Migrate nns-common to ic-cdk
  Cargo.lock
  rs/nns/common/BUILD.bazel
  rs/nns/common/Cargo.toml
  rs/nns/common/src/access_control.rs
  rs/nns/common/src/registry.rs
  rs/nns/common/src/types.rs
  rs/nns/handlers/root/impl/BUILD.bazel
  rs/nns/handlers/root/impl/Cargo.toml
  rs/nns/test_utils/BUILD.bazel
  rs/nns/test_utils/Cargo.toml
Labels: refactor, @nns-team

#4216 feat(BOUN-1360): make `ic-gateway` a monorepo dependency
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/main.rs
  rs/replica/Cargo.toml
  rs/tests/boundary_nodes/integration_test_common/src/lib.rs
Labels: feat, @idx, @boundary-node, @pocket-ic

#4220 test(EXC-1982): Benchmark compilation cost
  rs/embedders/benches/compilation.rs
Labels: test, @execution

#4243 test(sns): Release qualification tests should take automatic target version advancement into account
  mainnet-canister-revisions.json
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs
  rs/nervous_system/integration_tests/tests/upgrade_everything_test.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
Labels: test, @idx, @nns-team

#4231 fix: Sanitize transport public key input bytes in execution
  rs/crypto/utils/canister_threshold_sig/src/lib.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
Labels: fix, @execution, @crypto-team

#4228 test(consensus): Update VetKD lifecycle test
  Cargo.lock
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/tests/consensus/vetkd/BUILD.bazel
  rs/tests/consensus/vetkd/Cargo.toml
  rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs
Labels: test, @consensus

#4131 refactor(CRP-2612): Renaming for ReshareChainKeys
  rs/consensus/src/idkg/payload_builder.rs
  rs/consensus/src/idkg/payload_builder/resharing.rs
  rs/consensus/src/idkg/payload_verifier.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/tests/threshold_signatures.rs
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/replicated_state/src/replicated_state.rs
Labels: refactor, @consensus, @execution, @ic-message-routing-owners, @ic-interface-owners, CI_OVERRIDE_BUF_BREAKING

#4234 chore(crypto): CRP-2717 Validate Schnorr aux field in management canister interface
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/tests/threshold_signatures.rs
Labels: chore, @execution

#4236 test(nns): Use a separate binary to prepare golden state to speed up experimentation
  Cargo.lock
  rs/nns/test_utils/golden_nns_state/BUILD.bazel
  rs/nns/test_utils/golden_nns_state/Cargo.toml
  rs/nns/test_utils/golden_nns_state/src/lib.rs
  rs/nns/test_utils/prepare_golden_state/BUILD.bazel
  rs/nns/test_utils/prepare_golden_state/Cargo.toml
  rs/nns/test_utils/prepare_golden_state/src/lib.rs
  rs/nns/test_utils/prepare_golden_state/src/watch_and_prepare.rs
Labels: test, @nns-team

#4249 refactor(tests): Reorganize build_*_wasm functions
  rs/nns/test_utils/src/common.rs
Labels: refactor, @nns-team

#4227 fix(IDX): don't run system tests with 'local' by default
  rs/tests/kubeconfig.bzl
  rs/tests/system_tests.bzl
Labels: fix, @idx

#4247 feat(node): Add path to read mainnet json from bazel
  BUILD.bazel
  MODULE.bazel
  WORKSPACE.bazel
  bazel/jq.bzl
  bazel/json.bzl
  bazel/mainnet-versions.bzl
  rs/tests/common.bzl
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup/BUILD.bazel
  rs/tests/consensus/backup/common.rs
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/orchestrator/cup_compatibility_test.rs
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/consensus/upgrade/common.rs
  rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
  rs/tests/consensus/upgrade/upgrade_downgrade_nns_subnet_test.rs
  rs/tests/dre/BUILD.bazel
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/message_routing/BUILD.bazel
  rs/tests/message_routing/queues_compatibility_test.rs
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/message_routing/xnet/xnet_compatibility.rs
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/ic_mainnet_nns_recovery/src/lib.rs
Labels: feat, @idx, @dre, @consensus, @nns-team, @ic-message-routing-owners, CI_ALL_BAZEL_TARGETS

#4254 chore(IDX): cleanup main.sh
  ci/bazel-scripts/main.sh
Labels: chore, @idx

#4257 chore(IDX): don't create buf bins in PWD
  pre-commit/check-incompatibilities.sh
Labels: chore

#4159 refactor(IDX): move rust-benchmarks to daily workflow
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-rust-bench.yml
Labels: refactor, @idx

#4260 chore(IDX): update codeowners
  .github/CODEOWNERS
Labels: chore, @ic-owners-owners

#4259 chore(IDX): remove references to old env vars
  .rclone.conf
Labels: chore, @idx

#4237 feat(nns): Increase the _pb method failure rate to 0.7 again
  rs/nns/governance/canister/canister.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#4250 feat(nns): Add Node Rewards Canister (without functionality)
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  publish/canisters/BUILD.bazel
  rs/nns/test_utils/src/common.rs
  rs/node_rewards/CHANGELOG.md
  rs/node_rewards/canister/BUILD.bazel
  rs/node_rewards/canister/Cargo.toml
  rs/node_rewards/canister/api/BUILD.bazel
  rs/node_rewards/canister/api/Cargo.toml
  rs/node_rewards/canister/api/src/lib.rs
  rs/node_rewards/canister/api/src/lifecycle_args.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/lib.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/tests/example_test.rs
Labels: feat, @idx, @nns-team, @ic-interface-owners, @ic-owners-owners

#4173 feat(sns): Add field `topic` to `ProposalData`
  Cargo.lock
  rs/sns/governance/api/src/ic_sns_governance.pb.v1.rs
  rs/sns/governance/canister/governance.did
  rs/sns/governance/canister/governance_test.did
  rs/sns/governance/proto/ic_sns_governance/pb/v1/governance.proto
  rs/sns/governance/src/gen/ic_sns_governance.pb.v1.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/src/pb/conversions.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#4268 test(nns): Improve rs/nns/integration_tests
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/src/copy_inactive_neurons_to_stable_memory.rs
  rs/nns/integration_tests/src/lib.rs
Labels: test, @nns-team

#4273 fix(nns): Avoid applying approve_genesis_kyc for more than 1000 neurons
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: fix, @nns-team

#4271 chore(node_rewards): Fix changelogs for node_rewards canister
  rs/node_rewards/canister/CHANGELOG.md
  rs/node_rewards/canister/unreleased_changelog.md
Labels: chore, @dre, @nns-team

#4266 fix: extracting of sampling period for power measurements
  ic-os/components/hostos-scripts/monitoring/monitor-power.sh
Labels: fix, @node

#4267 fix(fuzzing): Update `get_persisted_global` to match proper encoding
  rs/embedders/fuzz/src/ic_wasm.rs
Labels: fix, @execution

#4240 test(ckbtc): Add a test that replays mainnet events and dumps stable mem
  Cargo.lock
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/Cargo.toml
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/storage.rs
  rs/bitcoin/ckbtc/minter/tests/dump_stable_memory.rs
Labels: test, @cross-chain-team

#4270 fix(sns): Ensure all topics can be set while adding new custom proposals
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/proposal.rs
  rs/sns/governance/unreleased_changelog.md
Labels: fix, @nns-team

#4256 chore(BOUN-1348): upgrade axum to 0.8
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/boundary_node/certificate_issuance/certificate_issuer/src/main.rs
  rs/boundary_node/ic_boundary/Cargo.toml
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/src/call/call_v2.rs
  rs/http_endpoints/public/src/call/call_v3.rs
  rs/http_endpoints/public/src/common.rs
  rs/http_endpoints/public/src/query.rs
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/http_endpoints/public/src/read_state/subnet.rs
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/lib.rs
  rs/pocket_ic_server/src/main.rs
  rs/pocket_ic_server/src/state_api/canister_id.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
  rs/tests/httpbin-rs/src/main.rs
Labels: chore, @idx, @consensus, @boundary-node, @pocket-ic

#4276 feat(BOUN-1364): ic-boundary: make self-health-checking more smart
  rs/boundary_node/ic_boundary/src/check/test.rs
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
  rs/boundary_node/ic_boundary/src/snapshot/test.rs
  rs/boundary_node/ic_boundary/src/test_utils.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat, @boundary-node, @pocket-ic

#4255 feat: new system API to retrieve liquid cycle balance of a canister
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/embedders/src/wasmtime_embedder/system_api_complexity.rs
  rs/embedders/tests/wasmtime_embedder.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/tests/execution_test.rs
  rs/interfaces/src/execution_environment.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/test_utilities/embedders/src/lib.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
Labels: feat, @execution

#4277 fix(BOUN-1364): handle empty subnets and no subnets
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/routes/test.rs
Labels: fix

#4278 feat(sns_cli): Add Auto upgrades status to `sns health`
  rs/sns/cli/src/health.rs
Labels: feat, @nns-team

#4274 feat(nns): Re-enable neuron migration
  rs/nns/governance/canbench/canbench_results.yml
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/governance_migrations.rs
Labels: feat, @nns-team

#4280 chore(IDX): move cloud creds to action input
  .github/actions/bazel-test-all/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows-source/schedule-hourly.yml
  .github/workflows/ci-main.yml
  .github/workflows/schedule-hourly.yml
  .github/workflows/system-tests-k8s.yml
  ci/bazel-scripts/main.sh
Labels: chore, @idx, CI_ALL_BAZEL_TARGETS

#4093 chore: address guestOS/hostOS FW findings
  ic-os/components/ic/generate-ic-config/ic.json5.template
  ic-os/components/misc/chrony/chrony.conf
  ic-os/components/networking/nftables/hostos/nftables.template
  rs/orchestrator/testdata/nftables_assigned_replica.conf.golden
Labels: chore, @node

#4285 feat(nns): Enable timer task metrics
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/timer_tasks/mod.rs
  rs/nns/governance/src/timer_tasks/seeding.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat

#4180 feat(nns): Add `neuron_minimum_dissolve_delay_to_vote_seconds` to `VotingPowerEconomics`
  rs/nns/governance/api/src/ic_nns_governance.pb.v1.rs
  rs/nns/governance/api/src/pb.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/src/network_economics.rs
  rs/nns/governance/src/network_economics_tests.rs
  rs/nns/governance/src/neuron_store.rs
  rs/nns/governance/src/neuron_store/neuron_store_tests.rs
  rs/nns/governance/src/pb/conversions.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @nns-team, CI_ALL_BAZEL_TARGETS

#4293 revert: "refactor(IDX): move rust-benchmarks to daily workflow"
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
  .github/workflows/schedule-rust-bench.yml
Labels: revert, @idx

#4188 chore: Bump wasmtime version
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  MODULE.bazel
  bazel/cranelift-assembler-lib.patch
  bazel/cranelift-assembler-main.patch
  bazel/cranelift-codegen-meta-isle.patch
  bazel/cranelift-codegen-meta.patch
  bazel/cranelift-isle.patch
  bazel/external_crates.bzl
  rs/embedders/Cargo.toml
Labels: chore, @idx

#4246 chore: Bump wasm tools
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
Labels: chore

#4296 chore(ICP-Ledger): migrate non-pb query endpoints from dfn to cdk
  Cargo.lock
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/main.rs
Labels: chore, @finint

#4288 chore(nns/sns): Update changelog after release
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
Labels: chore

#4303 test(ICP-Ledger): adding test fot transfer_fee_pb
  rs/ledger_suite/icp/tests/tests.rs
Labels: test

#4304 fix: Move StandardOutput+StandardError to correct section
  ic-os/components/ic/generate-ic-config/generate-ic-config.service
Labels: fix

#4301 fix: retry fetching tip block
  rs/rosetta-api/icp/ledger_canister_blocks_synchronizer/src/ledger_blocks_sync.rs
Labels: fix

#4306 fix: Remove CPU microcode from GuestOS
  ic-os/components/early-boot/initramfs-tools/guestos/amd64-microcode
  ic-os/components/early-boot/initramfs-tools/guestos/intel-microcode
  ic-os/components/guestos.bzl
Labels: fix

#4299 chore(ICP-Ledger): migrating protobuf query endpoints from dfn to cdk
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/src/lib.rs
Labels: chore, @finint

#4235 test(ICRC_Ledger): FI-1652: Add tests for archiving large amounts of blocks
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
Labels: test, @finint

#4291 chore(EXC): Remove outdated TODO
  rs/execution_environment/src/hypervisor.rs
Labels: chore

#4300 chore(IDX): use correct .gz name for canisters
  bazel/canisters.bzl
  packages/pocket-ic/BUILD.bazel
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/ethereum/cketh/minter/BUILD.bazel
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/index-ng/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/nns/handlers/lifeline/impl/BUILD.bazel
  rs/rust_canisters/stable_memory_integrity/BUILD.bazel
Labels: chore, @idx, @execution, @pocket-ic, @nns-team, @cross-chain-team, @finint, CI_ALL_BAZEL_TARGETS

#4283 feat: [MR-662] Add CyclesUseCase::DroppedMessages variant
  rs/cycles_account_manager/src/lib.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_state/system_state.rs
  rs/replicated_state/src/metadata_state.rs
  rs/replicated_state/src/metadata_state/tests.rs
  rs/types/types/src/funds/cycles.rs
Labels: feat

#4313 fix(IDX): don't run //rs/bitcoin/ckbtc/minter:mainnet_events.mem.gz on MacOS x86_64
  rs/bitcoin/ckbtc/minter/BUILD.bazel
Labels: fix, @cross-chain-team, CI_MACOS_INTEL

#4312 fix(EXC-1990): Limit compilation cache entries
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/src/compilation_cache.rs
  rs/embedders/src/lib.rs
  rs/embedders/tests/compilation_cache.rs
  rs/execution_environment/src/hypervisor.rs
  rs/types/types/src/lib.rs
  rs/utils/lru_cache/src/lib.rs
Labels: fix

#4307 chore(dep-mgmt): Add `disallowed-types` for protobuf `CodedInputStream`
  clippy.toml
Labels: chore, @ic-interface-owners

#4275 feat(fuzzing): Add new Wasm module generator for system API
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/embedders/fuzz/BUILD.bazel
  rs/embedders/fuzz/src/ic_wasm.rs
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/fuzz/src/lib.rs
  rs/embedders/fuzz/src/special_int.rs
  rs/embedders/fuzz/src/wasm_executor.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/execution_environment/fuzz/BUILD.bazel
  rs/execution_environment/fuzz/fuzz_targets/execute_ic_wasm.rs
  rs/execution_environment/fuzz/fuzz_targets/execute_system_api.rs
  rs/execution_environment/fuzz/src/lib.rs
Labels: feat, @execution

#4193 fix: No warnings on XNet payload building
  rs/xnet/payload_builder/src/impl_tests.rs
  rs/xnet/payload_builder/src/lib.rs
Labels: fix

#4315 chore: update ic-gateway dep & release
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  ic-os/boundary-guestos/context/Dockerfile
Labels: chore

#4320 feat: [NODE-1574] Upgrade components to SEV-SNP compatible versions
  ic-os/hostos/context/Dockerfile.base
  ic-os/hostos/context/packages.common
Labels: feat

#4328 chore: [EXC-1833] Revert "chore: Ignore wasmtime validation errors (#3338)"
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/wasmtime_embedder_tests.rs
  rs/execution_environment/tests/execution_test.rs
Labels: chore, @execution

#4330 fix(IDX): adding missing step
  .github/workflows/system-tests-k8s.yml
Labels: fix, @idx

#4319 test(ICRC_Ledger): FI-1693: Adapt ICRC golden state tests to migration of blocks
  rs/ledger_suite/icrc1/tests/golden_state_upgrade_downgrade.rs
Labels: test, @finint

#4333 chore: Reduce the size of the random_instructions proptest
  rs/replicated_state/src/page_map/storage/tests.rs
Labels: chore

#4066 fix: EXC-1969: Fix in-round DTS for memory copy
  rs/canister_sandbox/src/dts.rs
  rs/embedders/src/wasm_executor.rs
  rs/execution_environment/tests/dts.rs
  rs/interfaces/src/execution_environment.rs
  rs/system_api/src/lib.rs
Labels: fix, @execution

#4334 test(sns): Upgrade SNS-W before deploying SNS (and bump the canister mainnet versions)
  mainnet-canister-revisions.json
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
Labels: test, @idx, @nns-team

#4339 chore: fix typos in http_outcalls metrics.rs file
  rs/https_outcalls/client/src/metrics.rs
Labels: chore

#4329 fix(utils): Add invariants check for `pop_lru`
  rs/utils/lru_cache/src/lib.rs
Labels: fix, @ic-interface-owners

#4345 chore: Check block proposal version before integrity
  rs/consensus/src/consensus/validator.rs
Labels: chore, @consensus

#4336 test(EXC-1983): Add a query benchmark to compilation benches
  rs/embedders/BUILD.bazel
  rs/embedders/benches/compilation.rs
Labels: test, @execution

#4350 chore: Remove unnecessary `certified_height` argument
  rs/consensus/src/consensus/block_maker.rs
  rs/consensus/src/consensus/malicious_consensus.rs
Labels: chore, @consensus

#4322 chore(IDX): load ledger suite orchestrator wasm directly
  rs/ethereum/ledger-suite-orchestrator/test_utils/src/lib.rs
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#4279 refactor(consensus): remote transcript delivery
  rs/consensus/src/consensus/batch_delivery.rs
  rs/consensus/src/consensus/finalizer.rs
Labels: refactor, @consensus

#4344 chore(icp-rosetta): add changelog for rosetta icp 2.1.3
  Cargo.lock
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/CHANGELOG.md
  rs/rosetta-api/icp/Cargo.toml
Labels: chore

#4355 test(ICP-Ledger): add test for send_dfx
  rs/ledger_suite/icp/tests/tests.rs
Labels: test, @finint

#4356 chore(IDX): deduplicate checksum upload
  .github/actions/bazel-upload-checksums/action.yaml
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/bazel-scripts/main.sh
Labels: chore, @idx

#4325 test(IDX): only enable `flaky = True` for tests that are >= 1% flaky
  bazel/README.md
  packages/pocket-ic/BUILD.bazel
  rs/boundary_node/rate_limits/integration_tests/BUILD.bazel
  rs/boundary_node/salt_sharing/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nns/integration_tests/BUILD.bazel
  rs/p2p/consensus_manager/BUILD.bazel
  rs/registry/admin/BUILD.bazel
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/sns/integration_tests/BUILD.bazel
  rs/tests/boundary_nodes/BUILD.bazel
  rs/tests/ckbtc/BUILD.bazel
  rs/tests/consensus/BUILD.bazel
  rs/tests/consensus/backup/BUILD.bazel
  rs/tests/consensus/orchestrator/BUILD.bazel
  rs/tests/consensus/subnet_recovery/BUILD.bazel
  rs/tests/consensus/tecdsa/BUILD.bazel
  rs/tests/consensus/upgrade/BUILD.bazel
  rs/tests/consensus/vetkd/BUILD.bazel
  rs/tests/crypto/BUILD.bazel
  rs/tests/execution/BUILD.bazel
  rs/tests/financial_integrations/BUILD.bazel
  rs/tests/financial_integrations/rosetta/BUILD.bazel
  rs/tests/idx/BUILD.bazel
  rs/tests/message_routing/xnet/BUILD.bazel
  rs/tests/nested/BUILD.bazel
  rs/tests/networking/BUILD.bazel
  rs/tests/nns/BUILD.bazel
  rs/tests/nns/sns/BUILD.bazel
  rs/tests/node/BUILD.bazel
  rs/tests/query_stats/BUILD.bazel
  rs/tests/research/BUILD.bazel
  rs/tests/sdk/BUILD.bazel
  rs/tests/testnets/BUILD.bazel
Labels: test, @idx, @consensus, @execution, @boundary-node, @pocket-ic, @nns-team, @crypto-team, @ic-message-routing-owners, @node, @cross-chain-team, @finint, @sdk, @research

#4357 chore(dep-mgmt): Add `oisy-wallet`, `chain-fusion-signer` to periodic dep scanning
  ci/src/dependencies/job/bazel_rust_ic_scanner_periodic_job.py
  ci/src/dependencies/job/npm_scanner_periodic_job.py
Labels: chore, @product-security

#4310 chore: add API BNs to release qualification tests
  Cargo.lock
  rs/tests/dre/guest_os_qualification.rs
  rs/tests/dre/utils/BUILD.bazel
  rs/tests/dre/utils/Cargo.toml
  rs/tests/dre/utils/lib.rs
  rs/tests/dre/utils/steps/update_subnet_type.rs
  rs/tests/dre/utils/steps/workload.rs
  rs/tests/driver/src/nns.rs
Labels: chore, @idx, @dre

#4337 test(EXC-1985): Add open chat user canister benchmark
  rs/embedders/benches/compilation.rs
  rs/embedders/benches/test-data/user.wasm.gz
  rs/embedders/benches/test-data/user_canister_impl.wasm
Labels: test

#4182 chore: EXC: Remove unused DTS workarounds
  rs/execution_environment/benches/lib/src/common.rs
  rs/execution_environment/tests/dts.rs
Labels: chore, @execution

#4352 test(EXC): Add pop to lru cache proptest
  rs/utils/lru_cache/src/lib.rs
Labels: test

#4362 chore(IDX): simplify run-build-ic.sh
  ci/scripts/run-build-ic.sh
Labels: chore, @idx

#4364 test(EXC-1984): QR code canister benchmark
  rs/embedders/benches/compilation.rs
  rs/embedders/benches/test-data/qrcode_backend.wasm.gz
Labels: test

#4369 revert: "feat: [NODE-1574] Upgrade components to SEV-SNP compatible versions"
  ic-os/hostos/context/Dockerfile.base
  ic-os/hostos/context/packages.common
Labels: revert

#4371 feat: Remove firmware from GuestOS
  ic-os/guestos/context/Dockerfile.base
  ic-os/guestos/context/packages.common
Labels: feat

#4354 feat(crypto): CRP-2709 improve vetKD API naming
  packages/ic-vetkd-utils/src/lib.rs
  rs/consensus/src/idkg/signer.rs
  rs/consensus/src/idkg/test_utils.rs
  rs/consensus/src/idkg/utils.rs
  rs/consensus/vetkd/src/lib.rs
  rs/consensus/vetkd/src/test_utils.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/benches/vetkd.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/vetkd/tests/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/api.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/vetkd/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/local_csp_vault/vetkd/tests.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/mod.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_client.rs
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
  rs/crypto/src/vetkd/mod.rs
  rs/crypto/test_utils/local_csp_vault/src/lib.rs
  rs/crypto/tests/vetkd.rs
  rs/crypto/utils/canister_threshold_sig/src/lib.rs
  rs/embedders/src/wasm_utils/validation.rs
  rs/embedders/src/wasmtime_embedder/system_api.rs
  rs/execution_environment/benches/system_api/execute_update.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/dts.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/protobuf/def/state/metadata/v1/metadata.proto
  rs/protobuf/src/gen/state/state.metadata.v1.rs
  rs/replicated_state/src/metadata_state/subnet_call_context_manager.rs
  rs/system_api/src/lib.rs
  rs/system_api/src/routing.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/system_api/tests/system_api.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_fails_without_cycles_test.rs
  rs/tests/consensus/tecdsa/tecdsa_signature_life_cycle_test.rs
  rs/tests/consensus/tecdsa/utils/src/lib.rs
  rs/tests/consensus/vetkd/vetkd_key_life_cycle_test.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/consensus/idkg/common.rs
  rs/types/types/src/crypto/vetkd.rs
  rs/types/types/src/crypto/vetkd/test.rs
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
  rs/universal_canister/impl/src/api.rs
  rs/universal_canister/impl/src/lib.rs
  rs/universal_canister/impl/src/main.rs
  rs/universal_canister/lib/src/lib.rs
Labels: feat, @consensus, @execution, @crypto-team, @ic-message-routing-owners, @ic-interface-owners

#4351 refactor(nervous-system): Move canister interfaces into canister crate
  Cargo.lock
  rs/nervous_system/canisters/BUILD.bazel
  rs/nervous_system/canisters/Cargo.toml
  rs/nervous_system/canisters/src/cmc.rs
  rs/nervous_system/canisters/src/ledger.rs
  rs/nervous_system/clients/BUILD.bazel
  rs/nervous_system/clients/Cargo.toml
  rs/nervous_system/clients/src/ledger_client.rs
  rs/nervous_system/common/src/cmc.rs
  rs/nervous_system/common/src/ledger.rs
  rs/nervous_system/common/src/lib.rs
  rs/nervous_system/common/test_utils/BUILD.bazel
  rs/nervous_system/common/test_utils/Cargo.toml
  rs/nervous_system/common/test_utils/src/lib.rs
  rs/nns/governance/BUILD.bazel
  rs/nns/governance/benches/scale.rs
  rs/nns/governance/canister/tla_ledger.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/ledger_helper.rs
  rs/nns/governance/src/test_utils.rs
  rs/nns/governance/tests/degraded_mode.rs
  rs/nns/governance/tests/fake.rs
  rs/nns/governance/tests/fixtures/mod.rs
  rs/nns/governance/tests/governance.rs
  rs/nns/governance/tests/interleaving/mod.rs
  rs/nns/governance/tests/interleaving_tests.rs
  rs/sns/governance/BUILD.bazel
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/advance_target_sns_version_tests.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/fail_stuck_upgrade_in_progress_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/tests/fixtures/mod.rs
  rs/sns/integration_tests/BUILD.bazel
  rs/sns/integration_tests/Cargo.toml
  rs/sns/integration_tests/src/neuron.rs
  rs/sns/swap/src/environment.rs
  rs/sns/swap/src/types.rs
  rs/sns/swap/tests/common/doubles.rs
Labels: refactor, @nns-team

#4284 chore: upgrade stable-structures
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u256.yml
  rs/ledger_suite/icrc1/ledger/canbench_results/canbench_u64.yml
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/nns/governance/canbench/canbench_results.yml
Labels: chore, @idx, @nns-team, @finint

#4373 fix(IDX): initialize ARGS var
  ci/scripts/run-build-ic.sh
Labels: fix

#4370 chore(nns/sns): Remove temporary SNS-W upgrade steps from SNS release qualification tests, edit changelog
  rs/nervous_system/integration_tests/tests/sns_release_qualification.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils.rs
  rs/nervous_system/integration_tests/tests/sns_upgrade_test_utils_legacy.rs
  rs/nervous_system/integration_tests/tests/upgrade_existing_sns_test.rs
  rs/nns/sns-wasm/CHANGELOG.md
  rs/nns/sns-wasm/unreleased_changelog.md
Labels: chore, @nns-team

#4375 fix: Remove flakiness from the bitcoin adapter integration test
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/tests/adapter_test.rs
Labels: fix, @consensus

#4363 test: Efficiently write `LocalStoreImpl` to disk
  Cargo.lock
  rs/messaging/BUILD.bazel
  rs/messaging/Cargo.toml
  rs/messaging/src/message_routing/tests.rs
  rs/p2p/test_utils/BUILD.bazel
  rs/p2p/test_utils/Cargo.toml
  rs/p2p/test_utils/src/lib.rs
  rs/registry/local_registry/BUILD.bazel
  rs/registry/local_registry/Cargo.toml
  rs/registry/local_registry/src/lib.rs
  rs/registry/local_store/src/lib.rs
  rs/sys/src/fs.rs
  rs/test_utilities/registry/BUILD.bazel
  rs/test_utilities/registry/Cargo.toml
  rs/test_utilities/registry/src/lib.rs
  rs/tests/idx/mainnet_test.rs
Labels: test, @ic-message-routing-owners, @ic-interface-owners

#4377 test(IDX): mark query_stats_above_threshold and query_stats_basic as long_tests
  rs/tests/query_stats/BUILD.bazel
Labels: test, @consensus, @execution

#4378 chore(IDX): remove dead upload code
  ci/src/artifacts/BUILD.bazel
  ci/src/artifacts/collect_core_dumps.sh
  ci/src/artifacts/find-build-id.sh
  ci/src/artifacts/newest_sha_with_disk_image.sh
  ci/src/artifacts/openssl-sign.sh
  ci/src/artifacts/openssl-verify.sh
  ci/src/artifacts/rclone_download.py
  ci/src/artifacts/rclone_upload.py
  ci/src/artifacts/trusted-builders-public.key
Labels: chore, @idx

#4332 feat: [EXC-1954] Add types and interfaces for snapshot import and export API (1/2)
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/dts.rs
  rs/replicated_state/src/canister_state/execution_state.rs
  rs/system_api/src/routing.rs
  rs/system_api/src/sandbox_safe_system_state.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: feat, @execution, @ic-message-routing-owners, @ic-interface-owners

#4366 chore(IDX): run system-tests up to 3 times on CI
  bazel/conf/.bazelrc.build
Labels: chore, @idx

#4381 test(IDX): have a 30s timeout for creating the Universal and Message Canisters
  rs/tests/driver/src/util.rs
Labels: test, @idx, CI_ALL_BAZEL_TARGETS

#4367 chore(crypto): Bump ic_bls12_381
  Cargo.Bazel.Fuzzing.json.lock
  Cargo.Bazel.Fuzzing.toml.lock
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  bazel/external_crates.bzl
Labels: chore, @idx

#4382 chore: Remove artifact_pool from whitelist of private mananagement types
  rs/types/management_canister_types/BUILD.bazel
Labels: chore

#4368 feat(sns): Define proposal criticality based on proposal topics
  Cargo.lock
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nervous_system/integration_tests/Cargo.toml
  rs/nervous_system/integration_tests/src/create_service_nervous_system_builder.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/nervous_system/integration_tests/tests/sns_topics.rs
  rs/sns/governance/proposal_criticality/src/lib.rs
  rs/sns/governance/src/governance.rs
  rs/sns/governance/src/governance/assorted_governance_tests.rs
  rs/sns/governance/src/governance/proposal_topics_tests.rs
  rs/sns/governance/src/neuron.rs
  rs/sns/governance/src/topics.rs
  rs/sns/governance/src/types.rs
  rs/sns/governance/src/types/tests.rs
  rs/sns/governance/unreleased_changelog.md
Labels: feat, @nns-team

#4384 refactor: Downgrade `panic` to `debug_assert` in `Payload::take_prefix`, part 2
  rs/xnet/payload_builder/src/certified_slice_pool.rs
Labels: refactor

#4029 chore(ckbtc): Add a canbench for event migration
  Cargo.lock
  bazel/canbench.bzl
  bazel/canbench.sh
  rs/bitcoin/ckbtc/minter/BUILD.bazel
  rs/bitcoin/ckbtc/minter/Cargo.toml
  rs/bitcoin/ckbtc/minter/canbench/canbench.yml
  rs/bitcoin/ckbtc/minter/canbench/results.yml
  rs/bitcoin/ckbtc/minter/src/storage.rs
Labels: chore, @idx, @cross-chain-team

#4324 chore(ICP-Ledger): migrate tests from dfn to cdk
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/tests.rs
Labels: chore

#4323 chore(ICP-Ledger): migrate metrics from dfn to cdk
  Cargo.lock
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/tests.rs
Labels: chore

#4316 chore(ICP-Ledger): migrate transfer and approve endpoints from dfn to cdk
  Cargo.lock
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/ledger_canisters.bzl
  rs/ledger_suite/icp/ledger/src/lib.rs
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/tests.rs
Labels: chore

#4393 chore(IDX): simplify S3 upload
  .rclone-anon.conf
  .rclone.conf
  bazel/conf/.bazelrc.internal
  ci/src/artifacts/upload.bzl
  ci/src/artifacts/upload.sh
  ci/tools/rclone
Labels: chore, @idx

#4390 chore: Update whitelists for management canister types
  rs/types/management_canister_types/BUILD.bazel
Labels: chore
