Repository dfinity/ic, pull requests merged in 2025-09, with the labels that each got.

#6487 feat: adding the data model and canister method for node swapping
  Cargo.lock
  rs/nervous_system/agent/src/nns/registry.rs
  rs/nervous_system/agent/src/nns/registry/requests.rs
  rs/nervous_system/integration_tests/src/pocket_ic_helpers.rs
  rs/registry/canister/BUILD.bazel
  rs/registry/canister/Cargo.toml
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/canister/registry.did
  rs/registry/canister/canister/registry_test.did
  rs/registry/canister/src/flags.rs
  rs/registry/canister/src/mutations/do_swap_node_in_subnet_directly.rs
  rs/registry/canister/src/mutations/mod.rs
  rs/registry/canister/tests/common/test_helpers.rs
  rs/registry/canister/tests/swap_node_in_subnet_directly.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, @governance-team

#6528 fix: filter for excluded tags in targets.py
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  ci/bazel-scripts/targets.py
Labels: fix, @idx

#6535 chore: remove drun from IC repo
  .github/CODEOWNERS
  .github/workflows/tag-release.yml
  Cargo.lock
  Cargo.toml
  hs/spec_compliance/BUILD.bazel
  hs/spec_compliance/src/IC/DRun/Parse.hs
  publish/binaries/BUILD.bazel
  rs/canister_sandbox/src/launcher.rs
  rs/canister_sandbox/src/lib.rs
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/drun/BUILD.bazel
  rs/drun/Cargo.toml
  rs/drun/README.adoc
  rs/drun/in.txt
  rs/drun/src/lib.rs
  rs/drun/src/main.rs
  rs/drun/src/message.rs
  rs/types/management_canister_types/BUILD.bazel
Labels: chore, @idx, @execution, @languages, @ic-owners-owners, @research

#6506 chore: tag //rs/tests/ckbtc:adapter_basics_test as long_test
  PULL_REQUEST_BAZEL_TARGETS
  rs/tests/ckbtc/BUILD.bazel
Labels: chore, @idx, @cross-chain-team

#6536 test: bump timeout of the //rs/tests/consensus/upgrade:upgrade_downgrade_app_subnet_test
  rs/tests/consensus/upgrade/upgrade_downgrade_app_subnet_test.rs
Labels: test, @consensus

#6541 chore: tag //rs/tests/nns:nns_dapp_test as long_test
  rs/tests/nns/BUILD.bazel
Labels: chore, @governance-team

#6492 chore(canister_migration): [CON-1487] Rename some structs/constants from *CALL_V3* to *SYNC_CALL*
  rs/http_endpoints/public/src/call/call_async.rs
  rs/http_endpoints/public/src/call/call_sync.rs
  rs/http_endpoints/public/src/metrics.rs
  rs/http_endpoints/public/tests/load_shed_test.rs
Labels: chore, @consensus

#6553 chore: schedule daily workflow an hour earlier so it doesn't overlap with Release Testing
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: chore, @idx

#6555 chore: print the bazel targets to test in bazel-test-all
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#6559 test: add test for uploading and loading a canister snapshot with invalid WASM
  rs/execution_environment/tests/canister_snapshots.rs
Labels: test

#6561 chore: rm systest bazel config
  bazel/conf/.bazelrc.build
  ic-os/dev-tools/hostos-upgrade-tests.sh
  ic-os/guestos/README.adoc
  rs/tests/README.md
  rs/tests/README_NEW.md
  rs/tests/ict/cmd/testCmd.go
  rs/tests/ict/cmd/testnetCreateCmd.go
Labels: chore, @idx, @node

#6562 chore: print bazel query in targets.py with proper quotes
  ci/bazel-scripts/targets.py
Labels: chore, @idx

#6563 feat(XC): enable Dogecoin for staging canisters
  rs/config/src/execution_environment.rs
Labels: feat, @execution

#6445 chore: EXC-2087: Use `HeapBytes` in caches
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  packages/ic-error-types/BUILD.bazel
  packages/ic-error-types/Cargo.toml
  packages/ic-error-types/src/lib.rs
  packages/ic-heap-bytes-derive/BUILD.bazel
  packages/ic-heap-bytes-derive/Cargo.toml
  packages/ic-heap-bytes-derive/src/lib.rs
  packages/ic-heap-bytes/BUILD.bazel
  packages/ic-heap-bytes/Cargo.toml
  packages/ic-heap-bytes/README.md
  packages/ic-heap-bytes/src/lib.rs
  packages/ic-heap-bytes/src/tests.rs
  rs/embedders/BUILD.bazel
  rs/embedders/Cargo.toml
  rs/embedders/src/compilation_cache.rs
  rs/embedders/src/serialized_module.rs
  rs/embedders/src/wasm_utils.rs
  rs/execution_environment/BUILD.bazel
  rs/execution_environment/Cargo.toml
  rs/execution_environment/src/hypervisor.rs
  rs/execution_environment/src/query_handler/query_cache.rs
  rs/execution_environment/src/query_handler/query_cache/tests.rs
  rs/interfaces/BUILD.bazel
  rs/interfaces/Cargo.toml
  rs/interfaces/src/execution_environment/errors.rs
  rs/phantom_newtype/BUILD.bazel
  rs/phantom_newtype/Cargo.toml
  rs/phantom_newtype/src/amountof.rs
  rs/phantom_newtype/src/id.rs
  rs/types/base_types/BUILD.bazel
  rs/types/base_types/Cargo.toml
  rs/types/base_types/src/canister_id.rs
  rs/types/base_types/src/principal_id.rs
  rs/types/types/BUILD.bazel
  rs/types/types/Cargo.toml
  rs/types/types/src/batch/execution_environment.rs
  rs/types/types/src/funds/cycles.rs
  rs/types/types/src/ingress.rs
  rs/types/types/src/lib.rs
  rs/types/types/src/messages/http.rs
  rs/types/types/src/methods.rs
  rs/types/types/src/time.rs
  rs/types/wasm_types/BUILD.bazel
  rs/types/wasm_types/Cargo.toml
  rs/types/wasm_types/src/errors.rs
  rs/types/wasm_types/src/lib.rs
  rs/utils/lru_cache/BUILD.bazel
  rs/utils/lru_cache/Cargo.toml
  rs/utils/lru_cache/src/lib.rs
Labels: chore, @idx, @consensus, @execution, @ic-interface-owners

#6219 fix(orchestrator): Introduce timeout with backoff when fetching CUPs
  Cargo.lock
  rs/orchestrator/BUILD.bazel
  rs/orchestrator/Cargo.toml
  rs/orchestrator/src/catch_up_package_provider.rs
  rs/orchestrator/src/utils.rs
Labels: fix, @consensus, CI_ALL_BAZEL_TARGETS

#6560 fix(PocketIC): do not enable auto progress twice and further fixes/hardening
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
Labels: fix, @pocket-ic

#6568 chore(fuzzing): Make sandbox binary identifiable via a custom section
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/canister_sandbox/BUILD.bazel
  rs/canister_sandbox/Cargo.toml
  rs/canister_sandbox/src/lib.rs
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/execution_environment/fuzz/src/lib.rs
Labels: chore, @idx, @execution

#6545 feat: [CON-1578] don't allow requesting `/canister_ranges` paths in `/api/{v2,v3}/canister/<canister_id>/read_state`
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/tests/networking/read_state_test.rs
Labels: feat, @consensus

#6554 fix(nns-recovery): choose DFINITY-owned node as one with highest certification share height
  rs/tests/nested/src/lib.rs
Labels: fix, @node, CI_ALL_BAZEL_TARGETS

#6480 feat: [MR-688] Reject requests coming from seemly wrong subnet
  rs/messaging/src/routing/stream_handler.rs
  rs/messaging/src/routing/stream_handler/tests.rs
Labels: feat

#6565 fix: Use correct registry version for `ChainKeyConfig` in IDKG data payload builder
  rs/consensus/idkg/src/payload_builder.rs
Labels: fix, @consensus

#6574 chore: CON-1583 Add a topology version metric and use it in some tests adding nodes
  rs/p2p/peer_manager/src/lib.rs
  rs/p2p/peer_manager/src/metrics.rs
  rs/tests/consensus/adding_nodes_to_subnet_test.rs
  rs/tests/consensus/tecdsa/tecdsa_add_nodes_test.rs
  rs/tests/consensus/utils/src/node.rs
Labels: chore, @consensus

#6596 feat(release-runscript): Add correct tags to forum posts
  rs/nervous_system/tools/release-runscript/src/main.rs
Labels: feat, @governance-team

#6474 chore: use PocketIcBuilder::with_icp_features in sns-testing
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  rs/canister_sandbox/src/replica_controller/process_exe_and_args.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/src/main.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/sns/testing/BUILD.bazel
  rs/sns/testing/Cargo.toml
  rs/sns/testing/README.md
  rs/sns/testing/src/bin/init.rs
  rs/sns/testing/src/bin/main.rs
  rs/sns/testing/src/lib.rs
  rs/sns/testing/src/nns_dapp.rs
  rs/sns/testing/src/sns.rs
  rs/sns/testing/src/utils.rs
  rs/sns/testing/tests/sns_testing_ci.rs
Labels: chore, @execution, @pocket-ic, @governance-team

#6575 chore(cmc): Remove unreachable functions (ledger removed notify flow)
  rs/nns/cmc/src/main.rs
  rs/nns/cmc/unreleased_changelog.md
Labels: chore, @governance-team

#6591 feat: release PocketIC v10.0.0
  Cargo.lock
  packages/ic-metrics-assert/Cargo.toml
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/lib.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/CHANGELOG.md
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/main.rs
Labels: feat

#6600 fix(NPR): Discard historical rewards storage and APIs
  rs/node_rewards/canister/api/src/provider_rewards_calculation.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/proto/rewards_calculator/pb/v1/types.proto
  rs/node_rewards/canister/protobuf/src/gen/rewards_calculator.pb.v1.rs
  rs/node_rewards/canister/protobuf/src/lib.rs
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/src/storage.rs
  rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
Labels: fix, @dre, @governance-team

#6571 feat(proposal-cli): create forum topic for canister upgrade proposals
  Cargo.lock
  rs/cross-chain/proposal-cli/BUILD.bazel
  rs/cross-chain/proposal-cli/Cargo.toml
  rs/cross-chain/proposal-cli/README.adoc
  rs/cross-chain/proposal-cli/src/canister/mod.rs
  rs/cross-chain/proposal-cli/src/canister/tests.rs
  rs/cross-chain/proposal-cli/src/dashboard/mod.rs
  rs/cross-chain/proposal-cli/src/dashboard/responses.rs
  rs/cross-chain/proposal-cli/src/dashboard/tests.rs
  rs/cross-chain/proposal-cli/src/forum/mod.rs
  rs/cross-chain/proposal-cli/src/forum/tests.rs
  rs/cross-chain/proposal-cli/src/main.rs
Labels: feat, @cross-chain-team

#6609 test(ICRC-Ledger): FI-1856: Add icrc3_get_tip_certificate endpoint to the icrc3 test ledger
  Cargo.lock
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/BUILD.bazel
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/Cargo.toml
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/icrc3_test_ledger.did
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/src/main.rs
  rs/ledger_suite/icrc1/test_utils/icrc3_test_ledger/tests/tests.rs
Labels: test, @finint

#6619 fix: use docker-compatible authentication file
  .github/workflows/rosetta-release.yml
Labels: fix, @idx, @finint

#6597 feat(dogecoin): make Header a parameter in adapter implementation
  Cargo.Bazel.json.lock
  Cargo.Bazel.toml.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/bin/adapter-stress-test.rs
  rs/bitcoin/adapter/bin/ic-btc-adapter/cli.rs
  rs/bitcoin/adapter/src/addressbook.rs
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/common.rs
  rs/bitcoin/adapter/src/config.rs
  rs/bitcoin/adapter/src/connection.rs
  rs/bitcoin/adapter/src/connectionmanager.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/lib.rs
  rs/bitcoin/adapter/src/router.rs
  rs/bitcoin/adapter/src/rpc_server.rs
  rs/bitcoin/adapter/src/stream.rs
  rs/bitcoin/adapter/src/transaction_store.rs
  rs/bitcoin/adapter/test_utils/src/bitcoind.rs
  rs/bitcoin/adapter/test_utils/src/rpc_client.rs
  rs/bitcoin/adapter/tests/integration.rs
  rs/bitcoin/validation/src/header.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: feat, @idx, @consensus, @execution, @pocket-ic, @cross-chain-team

#6599 chore(sns): Cleanup SNS migration code
  rs/sns/governance/canister/canister.rs
Labels: chore, @governance-team

#6582 feat(sns-wasm): Service discovery for SNS canisters
  rs/nns/sns-wasm/canister/canister.rs
  rs/nns/sns-wasm/src/sns_wasm.rs
  rs/nns/sns-wasm/unreleased_changelog.md
Labels: feat

#6613 fix(recovery): escape ic-recovery filepaths
  rs/recovery/src/file_sync_helper.rs
  rs/recovery/src/ssh_helper.rs
  rs/recovery/src/steps.rs
Labels: fix, @consensus

#6627 test(sns): change the module hash of kongswap-adaptor-canister to its release version
  MODULE.bazel
Labels: test

#6623 chore(nns): Clean up making_sns_proposal
  rs/nns/governance/api/src/types.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/heap_governance_data.rs
  rs/nns/governance/src/pb/conversions/mod.rs
Labels: chore, @governance-team

#6645 fix: bump timeout of bazel-test-all from 120 to 150 minutes
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: fix, @idx

#6651 test: more reserved cycles tests
  rs/execution_environment/tests/storage_reservation.rs
Labels: test

#6653 test(btc-adapter): handle wallet already loading error
  rs/bitcoin/adapter/test_utils/src/rpc_client.rs
Labels: test, @consensus, @cross-chain-team

#6656 docs: Add section about feature flags
  rs/execution_environment/Contributing.md
Labels: docs

#6617 refactor: refactor NNS recovery test to support more scenarios
  Cargo.lock
  Cargo.toml
  PULL_REQUEST_BAZEL_TARGETS
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/Cargo.toml
  rs/tests/nested/guestos_upgrade.rs
  rs/tests/nested/hostos_upgrade.rs
  rs/tests/nested/nns_recovery/BUILD.bazel
  rs/tests/nested/nns_recovery/Cargo.toml
  rs/tests/nested/nns_recovery/common.rs
  rs/tests/nested/nns_recovery/nr_remote.rs
  rs/tests/nested/registration.rs
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
Labels: refactor, @idx, @node

#6636 chore(PocketIC): clean up server API
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/icp_features.rs
  packages/pocket-ic/tests/tests.rs
Labels: chore

#6529 feat: CON-1533 Introduce a Consensus flag for storing pre-signatures in state
  rs/config/src/subnet_config.rs
  rs/consensus/idkg/src/payload_builder.rs
  rs/consensus/idkg/src/payload_builder/signatures.rs
  rs/consensus/idkg/src/payload_verifier.rs
  rs/types/types/src/consensus/idkg.rs
Labels: feat, @consensus, @execution

#6639 feat: Support an unset unassigned version
  Cargo.lock
  rs/prep/src/internet_computer.rs
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/ic.rs
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/Cargo.toml
  rs/tests/nested/src/util.rs
Labels: feat, @idx, @node, @utopia

#6680 chore(nervous-system): Update changelog for release 2025-09-09
  rs/nns/cmc/CHANGELOG.md
  rs/nns/cmc/unreleased_changelog.md
  rs/nns/governance/CHANGELOG.md
  rs/nns/governance/unreleased_changelog.md
  rs/nns/sns-wasm/CHANGELOG.md
  rs/nns/sns-wasm/unreleased_changelog.md
  rs/registry/canister/CHANGELOG.md
  rs/registry/canister/unreleased_changelog.md
  rs/sns/governance/CHANGELOG.md
  rs/sns/governance/unreleased_changelog.md
  rs/sns/swap/CHANGELOG.md
  rs/sns/swap/unreleased_changelog.md
Labels: chore

#6662 feat(nns): Implement a proposal type DeregisterKnownNeuron behind feature flag
  rs/nns/governance/api/src/proposal_submission_helpers.rs
  rs/nns/governance/api/src/types.rs
  rs/nns/governance/canister/governance.did
  rs/nns/governance/canister/governance_test.did
  rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
  rs/nns/governance/src/gen/ic_nns_governance.pb.v1.rs
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/neuron/types.rs
  rs/nns/governance/src/pb/conversions/mod.rs
  rs/nns/governance/src/pb/proposal_conversions.rs
  rs/nns/governance/src/proposals/deregister_known_neuron.rs
  rs/nns/governance/src/proposals/deregister_known_neuron_tests.rs
  rs/nns/governance/src/proposals/mod.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/known_neurons.rs
  rs/nns/test_utils/src/state_test_helpers.rs
Labels: feat, @governance-team

#6385 chore: EXC-1740: Create canister tests improvements
  rs/execution_environment/src/canister_manager/tests.rs
Labels: chore, @execution

#6683 fix: //rs/tests/nns:nns_dapp_test
  Cargo.lock
  rs/tests/nns/nns_dapp/BUILD.bazel
  rs/tests/nns/nns_dapp/Cargo.toml
  rs/tests/nns/nns_dapp/nns_dapp.rs
Labels: fix, CI_ALL_BAZEL_TARGETS

#6658 chore(node): extend manageboot logging and minor fixes
  ic-os/components/upgrade/manageboot/manageboot.sh
Labels: chore, @node

#6684 fix(PocketIC): requests to /api paths always return a response
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/src/state_api/state.rs
Labels: fix, @pocket-ic

#6691 chore: Remove pocket ic team completely
  .github/CODEOWNERS
Labels: chore

#6668 feat(governance): Enable FulfillSubnetRentalRequest proposals.
  rs/nns/governance/src/lib.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @governance-team

#6699 feat: EXC-2032: Add memory tracker Wasm page metrics
  rs/canister_sandbox/src/replica_controller/sandboxed_execution_controller.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/src/wasmtime_embedder/tests.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/interfaces/src/execution_environment.rs
  rs/memory_tracker/src/lib.rs
Labels: feat, @execution

#6752 fix: use lld linker on aarch64-linux to work around linker bug
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  WORKSPACE.bazel
Labels: fix

#6730 feat(NRC): Refactor NRC to compute daily rewards
  Cargo.lock
  rs/node_rewards/canister/api/src/provider_rewards_calculation.rs
  rs/node_rewards/canister/api/src/providers_rewards.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/api_conversion.rs
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs
  rs/node_rewards/canister/src/lib.rs
  rs/node_rewards/canister/src/main.rs
  rs/node_rewards/canister/src/metrics.rs
  rs/node_rewards/canister/src/metrics/tests.rs
  rs/node_rewards/canister/src/registry_querier.rs
  rs/node_rewards/canister/src/registry_querier/tests.rs
  rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
  rs/node_rewards/rewards_calculation/BUILD.bazel
  rs/node_rewards/rewards_calculation/Cargo.toml
  rs/node_rewards/rewards_calculation/src/lib.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/mod.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/results.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/test_utils.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/v1.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/mod.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/test_utils.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator/tests.rs
  rs/node_rewards/rewards_calculation/src/rewards_calculator_results.rs
  rs/node_rewards/rewards_calculation/src/types.rs
Labels: feat, @dre, @governance-team

#6705 feat(btc-adapter): persist headers
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
  Cargo.lock
  Cargo.toml
  WORKSPACE.bazel
  rs/artifact_pool/Cargo.toml
  rs/bitcoin/adapter/BUILD.bazel
  rs/bitcoin/adapter/Cargo.toml
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/common.rs
  rs/bitcoin/adapter/src/config.rs
  rs/bitcoin/adapter/src/connectionmanager.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/header_cache.rs
  rs/bitcoin/adapter/src/lib.rs
  rs/bitcoin/adapter/src/transaction_store.rs
Labels: feat, @idx, @consensus, @cross-chain-team

#6747 fix(PocketIC): use Vampire/setup-wsl
  .github/workflows/pocket-ic-tests-windows.yml
Labels: fix, @idx

#6727 chore(PocketIC): speed up tests of system canister deployment
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/tests/common.rs
  packages/pocket-ic/tests/icp_features.rs
  packages/pocket-ic/tests/tests.rs
Labels: chore, @execution

#6746 chore(PocketIC): doc comments for IcpFeatures
  packages/pocket-ic/src/common/rest.rs
Labels: chore, @execution

#6452 feat(crypto): CRP-2810 implement public key derivation for threshold schemes
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  packages/ic-pub-key/BUILD.bazel
  packages/ic-pub-key/CHANGELOG.md
  packages/ic-pub-key/Cargo.toml
  packages/ic-pub-key/LICENSE
  packages/ic-pub-key/README.md
  packages/ic-pub-key/src/lib.rs
  packages/ic-pub-key/tests/tests.rs
Labels: feat, @ic-owners-owners

#6749 chore(p2p): Add metrics for the number of concurrent incoming/outgoing QUIC streams
  rs/p2p/quic_transport/src/connection_handle.rs
  rs/p2p/quic_transport/src/lib.rs
  rs/p2p/quic_transport/src/metrics.rs
  rs/p2p/quic_transport/src/request_handler.rs
Labels: chore, @consensus

#6756 perf(crypto): In NIDKG benchmarks avoid unnecessary setup
  rs/crypto/benches/ni_dkg.rs
Labels: perf

#6753 perf(crypto): In IDKG benchmarks avoid needlessly creating test env
  rs/crypto/benches/idkg.rs
Labels: perf

#6733 refactor(Ledgers): FI-1814: Extract some consts into ic-ledger-suite-state-machine-tests-constants crate
  Cargo.lock
  Cargo.toml
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/test_utils/src/pocket_ic_helpers/ledger.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
  rs/ledger_suite/icrc1/BUILD.bazel
  rs/ledger_suite/icrc1/Cargo.toml
  rs/ledger_suite/icrc1/ledger/BUILD.bazel
  rs/ledger_suite/icrc1/ledger/Cargo.toml
  rs/ledger_suite/icrc1/ledger/src/tests.rs
  rs/ledger_suite/icrc1/ledger/tests/tests.rs
  rs/ledger_suite/icrc1/tests/upgrade_downgrade.rs
  rs/ledger_suite/tests/sm-tests/BUILD.bazel
  rs/ledger_suite/tests/sm-tests/Cargo.toml
  rs/ledger_suite/tests/sm-tests/constants/BUILD.bazel
  rs/ledger_suite/tests/sm-tests/constants/Cargo.toml
  rs/ledger_suite/tests/sm-tests/constants/src/lib.rs
  rs/ledger_suite/tests/sm-tests/src/lib.rs
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/Cargo.toml
  rs/rosetta-api/icp/client/BUILD.bazel
  rs/rosetta-api/icp/client/Cargo.toml
  rs/rosetta-api/icp/client/tests/tests.rs
  rs/rosetta-api/icp/runner/BUILD.bazel
  rs/rosetta-api/icp/runner/Cargo.toml
  rs/rosetta-api/icp/runner/tests/tests.rs
  rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel
  rs/rosetta-api/icp/tests/integration_tests/Cargo.toml
  rs/rosetta-api/icp/tests/integration_tests/tests/tests.rs
  rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/icrc1/BUILD.bazel
  rs/rosetta-api/icrc1/Cargo.toml
  rs/rosetta-api/icrc1/tests/common/local_replica.rs
Labels: refactor, @finint

#6775 chore: update CODEOWNERS for NNS recovery tests
  .github/CODEOWNERS
Labels: chore, @consensus, @node, @ic-owners-owners

#6641 chore(nns): Release notes
  rs/node_rewards/canister/CHANGELOG.md
Labels: chore, @dre

#6677 chore: [NODE-1708] Update matching version assert
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/ic.rs
  rs/tests/driver/src/driver/ic_images.rs
  rs/tests/driver/src/driver/nested.rs
  rs/tests/driver/src/driver/vector_vm.rs
  rs/tests/nested/nns_recovery/common.rs
  rs/tests/nested/recovery_upgrader_test.rs
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
  rs/tests/testnets/nns_recovery.rs
Labels: chore, @idx, @consensus, @node

#6754 perf(crypto): Generate unmasked key transcript directly in test utils and benchmarks
  rs/crypto/benches/idkg.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/crypto/tests/canister_threshold_idkg.rs
Labels: perf, @crypto-team

#6743 feat: generating invocation uuids and displaying them as job summary
  .github/actions/generate-invocation-ids/action.yml
  .github/actions/generate-invocation-ids/generate-ids.py
  .github/workflows-source/ci-main.yml
  .github/workflows-source/ci-pr-only.yml
  .github/workflows-source/schedule-daily.yml
  .github/workflows/ci-main.yml
  .github/workflows/ci-pr-only.yml
  .github/workflows/schedule-daily.yml
  ci/container/build-ic.sh
Labels: feat, @idx

#6788 refactor: FI-1862: Fix xrc_mock_canister path
  rs/tests/nns/BUILD.bazel
Labels: refactor, @governance-team

#6787 chore: do not label mainnet revision PRs with CI_ALL_BAZEL_TARGETS
  ci/src/mainnet_revisions/mainnet_revisions.py
Labels: chore

#6644 feat(bitcoin): add dogecoin header validation to adapter
  Cargo.lock
  MODULE.bazel
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/common.rs
  rs/bitcoin/adapter/src/header_cache.rs
  rs/bitcoin/adapter/src/lib.rs
  rs/bitcoin/adapter/src/router.rs
  rs/bitcoin/validation/BUILD.bazel
  rs/bitcoin/validation/Cargo.toml
  rs/bitcoin/validation/src/constants.rs
  rs/bitcoin/validation/src/doge.rs
  rs/bitcoin/validation/src/header.rs
  rs/bitcoin/validation/src/lib.rs
  rs/bitcoin/validation/src/tests.rs
  rs/bitcoin/validation/src/tests/doge.rs
  rs/bitcoin/validation/src/tests/doge/auxpow.rs
  rs/bitcoin/validation/src/tests/doge/utils.rs
  rs/bitcoin/validation/src/tests/utils.rs
Labels: feat, @idx, @consensus, @execution, @cross-chain-team

#6772 chore: Remove mut from initialize_state_on_disk
  rs/state_manager/src/state_sync/chunkable.rs
Labels: chore, @ic-message-routing-owners

#6731 chore: convert further Haskell tests to Rust
  hs/spec_compliance/src/IC/Test/Spec.hs
  rs/execution_environment/src/canister_manager/tests.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/tests/hypervisor.rs
  rs/universal_canister/lib/src/lib.rs
Labels: chore, @execution, @research

#6764 fix(ICP-Index): remove incorrect account id data type comment, add separate type
  rs/ledger_suite/icp/index/src/main.rs
Labels: fix

#6714 tests: More migration canister tests
  Cargo.lock
  rs/migration_canister/BUILD.bazel
  rs/migration_canister/Cargo.toml
  rs/migration_canister/src/external_interfaces/management.rs
  rs/migration_canister/src/lib.rs
  rs/migration_canister/src/processing.rs
  rs/migration_canister/tests/tests.rs
Labels: @execution

#6690 chore(canister_migration): deprecate old canister ranges paths in the new endpoints
  Cargo.lock
  rs/http_endpoints/public/BUILD.bazel
  rs/http_endpoints/public/Cargo.toml
  rs/http_endpoints/public/src/lib.rs
  rs/http_endpoints/public/src/read_state.rs
  rs/http_endpoints/public/src/read_state/canister.rs
  rs/http_endpoints/public/src/read_state/subnet.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/test_utilities/consensus/src/fake.rs
  rs/tests/networking/read_state_test.rs
Labels: chore, @consensus, @execution

#6766 refactor(node): hostos_grub.cfg to contain only a single linux command
  ic-os/bootloader/hostos_grub.cfg
Labels: refactor, @node

#6798 chore(crypto): CRP-2928 Fix some formatting errors introduced in Rust 2024 Edition conversion
  rs/crypto/internal/crypto_service_provider/src/vault/remote_csp_vault/tarpc_csp_vault_server.rs
  rs/crypto/internal/crypto_service_provider/src/vault/test_utils/ni_dkg/fixtures.rs
  rs/crypto/node_key_validation/src/tests.rs
  rs/crypto/src/sign/threshold_sig/ni_dkg/transcript/tests.rs
  rs/types/types/src/crypto/threshold_sig/ni_dkg/transcripts_to_retain.rs
Labels: chore

#6760 fix(btc-adapter): improve btc-adapter responsiveness
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/bin/ic-btc-adapter/main.rs
  rs/bitcoin/adapter/src/addressbook.rs
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/connectionmanager.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/lib.rs
  rs/bitcoin/adapter/src/router.rs
  rs/bitcoin/adapter/src/rpc_server.rs
  rs/bitcoin/adapter/tests/integration.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: fix, @consensus, @execution, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6790 chore: small refactor of targets.py to avoid repeated code
  ci/bazel-scripts/targets.py
Labels: chore

#6761 chore(XC): remove deprecation from `ic-cdk` in `ic-ckbtc-minter`
  rs/bitcoin/ckbtc/minter/ckbtc_minter.did
  rs/bitcoin/ckbtc/minter/src/dashboard.rs
  rs/bitcoin/ckbtc/minter/src/lib.rs
  rs/bitcoin/ckbtc/minter/src/main.rs
  rs/bitcoin/ckbtc/minter/src/management.rs
  rs/bitcoin/ckbtc/minter/src/metrics.rs
  rs/bitcoin/ckbtc/minter/src/state.rs
  rs/bitcoin/ckbtc/minter/src/test_fixtures.rs
  rs/bitcoin/ckbtc/minter/src/updates/get_btc_address.rs
  rs/bitcoin/ckbtc/minter/src/updates/get_withdrawal_account.rs
  rs/bitcoin/ckbtc/minter/src/updates/retrieve_btc.rs
  rs/bitcoin/ckbtc/minter/src/updates/tests.rs
  rs/bitcoin/ckbtc/minter/tests/replay_events.rs
  rs/bitcoin/ckbtc/minter/tests/tests.rs
Labels: chore, @cross-chain-team, CI_ALL_BAZEL_TARGETS

#6785 fix(PocketIC): miscellaneous
  Cargo.lock
  packages/pocket-ic/BUILD.bazel
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/Cargo.toml
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/tests/icp_features.rs
  packages/pocket-ic/tests/tests.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/external_canister_types.rs
  rs/pocket_ic_server/src/pocket_ic.rs
  rs/pocket_ic_server/src/state_api/routes.rs
  rs/pocket_ic_server/tests/external_types_tests.rs
  rs/sns/testing/src/bin/init.rs
  rs/sns/testing/tests/sns_testing_ci.rs
Labels: fix, @execution, @governance-team

#6811 chore: inline dependencies in ic-admin
  rs/registry/admin/BUILD.bazel
  rs/registry/admin/Cargo.toml
  rs/registry/admin/bin/create_subnet.rs
  rs/registry/admin/bin/helpers.rs
  rs/registry/admin/bin/main.rs
  rs/registry/admin/bin/main_tests.rs
  rs/registry/admin/bin/recover_subnet.rs
  rs/registry/admin/bin/types.rs
  rs/registry/admin/bin/update_subnet.rs
Labels: chore, @governance-team

#6816 fix: add _MB in setup-lvs to enforce size limit
  ic-os/components/guestos/init/setup-lvs/setup-lvs.sh
Labels: fix

#6819 refactor: Replace `setupos-create-config` binary with `create_setupos_config` library function
  Cargo.lock
  rs/ic_os/dev_test_tools/setupos-image-config/BUILD.bazel
  rs/ic_os/dev_test_tools/setupos-image-config/Cargo.toml
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/create.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/inject.rs
  rs/ic_os/dev_test_tools/setupos-image-config/src/lib.rs
  rs/tests/driver/BUILD.bazel
  rs/tests/driver/Cargo.toml
  rs/tests/driver/src/driver/bootstrap.rs
  rs/tests/driver/src/driver/test_env_api.rs
  rs/tests/system_tests.bzl
Labels: refactor, @node

#6838 chore(node): convert version-hash to a full hash
  ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.sh
  rs/tests/nested/nns_recovery/common.rs
  rs/tests/nested/src/lib.rs
Labels: chore, @consensus, @node

#6786 feat: Whitelist migration canister to call registry endpoint
  rs/nns/constants/src/lib.rs
  rs/registry/canister/canister/canister.rs
  rs/registry/canister/unreleased_changelog.md
Labels: feat, CI_ALL_BAZEL_TARGETS, @governance-team

#6797 feat(btc-adapter): implement a hybrid header cache
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/src/blockchainmanager.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/header_cache.rs
  rs/bitcoin/adapter/src/lib.rs
Labels: feat, @consensus, @cross-chain-team

#6820 feat(PocketIC): make TTL configurable via StartServerParams
  packages/pocket-ic/CHANGELOG.md
  packages/pocket-ic/src/lib.rs
  packages/pocket-ic/src/nonblocking.rs
  packages/pocket-ic/tests/tests.rs
Labels: feat

#6665 perf: CON-1473 Make `IDkgTranscript`s cheaper to clone
  rs/consensus/idkg/src/test_utils.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/complaint/tests.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/retain_active_keys/tests.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/transcript.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/transcript/tests.rs
  rs/crypto/src/sign/canister_threshold_sig/idkg/utils/tests.rs
  rs/crypto/src/sign/canister_threshold_sig/tests.rs
  rs/crypto/test_utils/canister_threshold_sigs/src/lib.rs
  rs/crypto/tests/canister_threshold_idkg.rs
  rs/registry/canister/tests/recover_subnet.rs
  rs/test_utilities/consensus/src/idkg.rs
  rs/test_utilities/src/crypto.rs
  rs/types/types/src/crypto/canister_threshold_sig/idkg.rs
  rs/types/types/src/crypto/canister_threshold_sig/idkg/proto_conversions.rs
  rs/types/types/src/crypto/canister_threshold_sig/idkg/tests/index.rs
  rs/types/types/src/crypto/canister_threshold_sig/idkg/tests/test_utils.rs
  rs/types/types/src/crypto/canister_threshold_sig/idkg/tests/verify_transcript_params.rs
  rs/types/types/src/crypto/canister_threshold_sig/tests.rs
Labels: perf, @consensus, @crypto-team, @governance-team

#6840 chore: do not check memory allocation bounds when loading checkpoint
  rs/state_layout/src/state_layout/proto.rs
  rs/types/types/src/lib.rs
Labels: chore, @ic-message-routing-owners, @ic-interface-owners

#6659 perf(crypto): CRP-2921 Use a batch inversion for BLS12-381 Lagrange coefficients
  rs/crypto/internal/crypto_lib/bls12_381/type/benches/ops.rs
  rs/crypto/internal/crypto_lib/bls12_381/type/src/interpolation.rs
  rs/crypto/internal/crypto_lib/bls12_381/type/src/lib.rs
  rs/crypto/internal/crypto_lib/bls12_381/type/tests/tests.rs
Labels: perf, @crypto-team

#6696 chore(nns): Clean up StopOrStartCanister as an NNS Function
  rs/nns/governance/src/governance.rs
  rs/nns/governance/unreleased_changelog.md
  rs/nns/integration_tests/src/stop_or_start_canister.rs
Labels: chore, @governance-team

#6844 chore: EXC: Remove unused `StorageData` field
  rs/embedders/fuzz/src/imports.rs
  rs/embedders/src/wasmtime_embedder.rs
  rs/embedders/src/wasmtime_embedder/tests.rs
Labels: chore, @execution

#6835 feat: Add node reward type to `ic-admin` topology output
  rs/registry/admin/bin/main.rs
  rs/registry/admin/bin/types.rs
Labels: feat, @governance-team

#6894 fix: Temporary fix for NNS nightly test
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
Labels: CI_ALL_BAZEL_TARGETS, @governance-team

#6903 chore: bump timeout of bazel-test-macos-intel to 3 hours
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: chore, @idx

#6909 fix(adapter): benchmark hanging due to server blocking thread
  rs/bitcoin/adapter/benches/e2e.rs
Labels: fix, @consensus, @cross-chain-team

#6905 refactor: Move HttpQueryHandler declaration closer to its implementation
  rs/execution_environment/src/query_handler.rs
Labels: refactor

#6912 fix(PocketIC): zombie process after panic
  rs/pocket_ic_server/src/main.rs
  rs/pocket_ic_server/src/state_api/routes.rs
Labels: fix

#6906 feat: Migration Canister continued
  rs/migration_canister/BUILD.bazel
  rs/migration_canister/src/canister_state.rs
  rs/migration_canister/src/external_interfaces/management.rs
  rs/migration_canister/src/external_interfaces/registry.rs
  rs/migration_canister/src/lib.rs
  rs/migration_canister/src/migration_canister.rs
  rs/migration_canister/src/processing.rs
  rs/migration_canister/src/tests.rs
  rs/migration_canister/tests/tests.rs
Labels: feat

#6918 chore(sns): named arguments for all fields of RegisterExtensionArgs
  rs/sns/cli/src/register_extension.rs
Labels: chore

#6701 feat: [MR-494] Use hardlink to copy files in state sync
  rs/state_layout/src/utils.rs
  rs/state_manager/src/lib.rs
  rs/state_manager/src/state_sync/chunkable.rs
  rs/state_manager/tests/state_manager.rs
  rs/tests/message_routing/rejoin_test_lib/rejoin_test_lib.rs
Labels: feat, @ic-message-routing-owners

#6670 feat(BOUN-1474): ic-boundary: add new routes
  rs/boundary_node/ic_boundary/src/cli.rs
  rs/boundary_node/ic_boundary/src/core.rs
  rs/boundary_node/ic_boundary/src/http/middleware/cache.rs
  rs/boundary_node/ic_boundary/src/http/middleware/process.rs
  rs/boundary_node/ic_boundary/src/http/middleware/retry.rs
  rs/boundary_node/ic_boundary/src/http/middleware/validate.rs
  rs/boundary_node/ic_boundary/src/http/mod.rs
  rs/boundary_node/ic_boundary/src/metrics.rs
  rs/boundary_node/ic_boundary/src/rate_limiting/generic.rs
  rs/boundary_node/ic_boundary/src/routes.rs
  rs/boundary_node/ic_boundary/src/snapshot.rs
  rs/boundary_node/rate_limits/api/src/schema_versions/v1.rs
  rs/tests/networking/http_endpoints_public_spec_test.rs
Labels: feat, @consensus, @boundary-node

#6843 chore: include commit date and revision in ic-admin --version
  bazel/BUILD.bazel
  bazel/workspace_status.sh
  rs/registry/admin/BUILD.bazel
  rs/registry/admin/bin/main.rs
  rs/registry/admin/build.rs
Labels: chore, @idx, @governance-team

#6907 refactor(IDX): use anchors for schedule-daily
  .github/workflows-source/schedule-daily.yml
  .github/workflows/schedule-daily.yml
Labels: refactor, @idx

#6930 fix(ic-recovery): ignore `ic_adapter` when downloading state
  rs/recovery/src/lib.rs
Labels: fix, @consensus

#6871 test: Add migration canister to system test framework
  Cargo.lock
  rs/nns/canister_ids.json
  rs/nns/constants/src/lib.rs
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/integration_tests/src/upgrade_canisters_with_golden_nns_state.rs
  rs/nns/test_utils/src/itest_helpers.rs
  rs/sns/integration_tests/BUILD.bazel
  rs/test_utilities/BUILD.bazel
  rs/tests/common.bzl
  rs/tests/execution/BUILD.bazel
  rs/tests/execution/Cargo.toml
  rs/tests/execution/canister_migration_test.rs
  rs/tests/system_tests.bzl
Labels: test, @idx, @execution, @ic-interface-owners, @governance-team

#6576 feat: Implement SEV disk encryption key exchange
  Cargo.Bazel.json.lock
  Cargo.lock
  Cargo.toml
  bazel/external_crates.bzl
  rs/ic_os/attestation/src/e2e_tests.rs
  rs/ic_os/attestation/src/verification.rs
  rs/ic_os/guest_upgrade/client/BUILD.bazel
  rs/ic_os/guest_upgrade/client/Cargo.toml
  rs/ic_os/guest_upgrade/client/src/lib.rs
  rs/ic_os/guest_upgrade/client/src/main.rs
  rs/ic_os/guest_upgrade/client/src/tls.rs
  rs/ic_os/guest_upgrade/server/BUILD.bazel
  rs/ic_os/guest_upgrade/server/Cargo.toml
  rs/ic_os/guest_upgrade/server/src/lib.rs
  rs/ic_os/guest_upgrade/server/src/server.rs
  rs/ic_os/guest_upgrade/server/src/service.rs
  rs/ic_os/guest_upgrade/server/src/tls.rs
  rs/ic_os/guest_upgrade/shared/BUILD.bazel
  rs/ic_os/guest_upgrade/shared/Cargo.toml
  rs/ic_os/guest_upgrade/shared/build.rs
  rs/ic_os/guest_upgrade/shared/proto/api.proto
  rs/ic_os/guest_upgrade/shared/src/api.rs
  rs/ic_os/guest_upgrade/shared/src/attestation.rs
  rs/ic_os/guest_upgrade/shared/src/lib.rs
  rs/ic_os/guest_upgrade/tests/BUILD.bazel
  rs/ic_os/guest_upgrade/tests/Cargo.toml
  rs/ic_os/guest_upgrade/tests/src/lib.rs
  rs/ic_os/os_tools/guest_disk/BUILD.bazel
  rs/ic_os/os_tools/guest_disk/Cargo.toml
  rs/ic_os/os_tools/guest_disk/src/lib.rs
  rs/ic_os/os_tools/guest_disk/src/main.rs
  rs/ic_os/os_tools/guest_disk/src/sev.rs
  rs/registry/nns_data_provider_wrappers/BUILD.bazel
Labels: feat

#6889 feat: [MR-719] Introduce `Refund` and `StreamMessage`
  rs/protobuf/def/state/queues/v1/queues.proto
  rs/protobuf/src/gen/state/state.queues.v1.rs
  rs/protobuf/src/gen/types/state.queues.v1.rs
  rs/types/types/src/messages.rs
  rs/types/types/src/messages/inter_canister.rs
  rs/types/types/src/messages/inter_canister/tests.rs
Labels: feat, @ic-interface-owners

#6935 refactor(IDX): use anchors for main-ci
  .github/workflows-source/ci-main.yml
  .github/workflows/ci-main.yml
Labels: refactor, @idx

#6944 chore(crypto): include underlying error in DecryptError::InvalidChunk
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/api/ni_dkg_errors.rs
  rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/src/ni_dkg/groth20_bls12_381/encryption.rs
Labels: chore, @crypto-team

#6833 chore(ckbtc): upgrade ledger suite
  rs/bitcoin/ckbtc/mainnet/ckbtc_archive_upgrade_2025_09_19.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_index_upgrade_2025_09_19.md
  rs/bitcoin/ckbtc/mainnet/ckbtc_ledger_upgrade_2025_09_19.md
Labels: chore, @cross-chain-team

#6757 perf(crypto): CRP-2930 Reduce "warm up time" during crypto benchmarks
  rs/crypto/benches/basic_sig.rs
  rs/crypto/benches/canister_sig.rs
  rs/crypto/benches/hash.rs
  rs/crypto/benches/idkg.rs
  rs/crypto/benches/multi_sig.rs
  rs/crypto/benches/ni_dkg.rs
  rs/crypto/benches/tecdsa.rs
  rs/crypto/benches/threshold_sig.rs
  rs/crypto/benches/tschnorr.rs
  rs/crypto/benches/vetkd.rs
Labels: perf, @crypto-team

#6853 fix(node-rewards-canister): Consolidate DayUtc type
  Cargo.lock
  rs/node_rewards/canister/api/BUILD.bazel
  rs/node_rewards/canister/api/Cargo.toml
  rs/node_rewards/canister/api/src/lib.rs
  rs/node_rewards/canister/api/src/provider_rewards_calculation.rs
  rs/node_rewards/canister/api/src/providers_rewards.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/api_conversion.rs
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs
  rs/node_rewards/canister/src/metrics.rs
  rs/node_rewards/canister/src/metrics/tests.rs
  rs/node_rewards/canister/src/registry_querier.rs
  rs/node_rewards/canister/src/registry_querier/tests.rs
  rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
  rs/node_rewards/rewards_calculation/BUILD.bazel
  rs/node_rewards/rewards_calculation/Cargo.toml
  rs/node_rewards/rewards_calculation/src/types.rs
Labels: fix, @dre, @crypto-team, @governance-team

#6836 chore(cketh/ckerc20): upgrade ledger suite
  rs/ethereum/cketh/mainnet/orchestrator_upgrade_2025_09_19.md
Labels: chore, @cross-chain-team

#6941 chore(dogecoin): add dogecoin canister IDs to prometheus VM
  rs/tests/driver/src/driver/prometheus_vm.rs
Labels: chore

#6841 chore(node): recovery artifact verification
  ic-os/components/misc/guestos-recovery/guestos-recovery-upgrader/guestos-recovery-upgrader.sh
Labels: chore, @node

#6946 refactor(node): Move nested tests into separate files
  Cargo.lock
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/Cargo.toml
  rs/tests/nested/guestos_upgrade.rs
  rs/tests/nested/hostos_upgrade.rs
  rs/tests/nested/recovery_upgrader_test.rs
  rs/tests/nested/src/lib.rs
  rs/tests/nested/src/util.rs
Labels: refactor, @node

#6923 chore(node): Add template engine for ic.json.template
  Cargo.lock
  ic-os/components/networking/nftables/hostos/setup-nftables.sh
  rs/ic_os/config/BUILD.bazel
  rs/ic_os/config/Cargo.toml
  rs/ic_os/config/build.rs
  rs/ic_os/config/src/guestos/generate_ic_config.rs
  rs/ic_os/config/src/lib.rs
  rs/ic_os/config/src/main.rs
  rs/ic_os/config/templates/ic.json5.template
Labels: chore, @node

#6740 perf(dogecoin): benchmark adapter for adding Dogecoin block headers
  MODULE.bazel
  rs/bitcoin/adapter/BUILD.bazel
  rs/bitcoin/adapter/benches/e2e.rs
  rs/bitcoin/adapter/src/blockchainstate.rs
  rs/bitcoin/adapter/src/get_successors_handler.rs
  rs/bitcoin/adapter/src/header_cache.rs
  rs/bitcoin/adapter/src/lib.rs
  rs/bitcoin/validation/src/header.rs
Labels: perf, @idx, @consensus, @execution, @cross-chain-team

#6592 feat: Allow loading a snapshot onto another canister
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests/canister_snapshots.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/tests/canister_snapshots.rs
  rs/protobuf/def/state/canister_state_bits/v1/canister_state_bits.proto
  rs/protobuf/src/gen/state/state.canister_state_bits.v1.rs
  rs/replicated_state/src/canister_snapshots.rs
  rs/replicated_state/src/page_map.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/ic.did
Labels: feat, @execution, @ic-message-routing-owners

#6717 chore(ICP_Ledger): FI-1845: Remove ICP ledger notify-method feature
  publish/canisters/BUILD.bazel
  rs/cross-chain/proposal-cli/src/canister/mod.rs
  rs/ledger_suite/icp/BUILD.bazel
  rs/ledger_suite/icp/index/BUILD.bazel
  rs/ledger_suite/icp/ledger/BUILD.bazel
  rs/ledger_suite/icp/ledger/Cargo.toml
  rs/ledger_suite/icp/ledger/src/main.rs
  rs/ledger_suite/icp/ledger/tests/tests.rs
  rs/ledger_suite/icp/tests/golden_nns_state.rs
  rs/ledger_suite/icp/tests/tests.rs
  rs/ledger_suite/icp/tests/upgrade_downgrade.rs
  rs/nervous_system/integration_tests/BUILD.bazel
  rs/nns/constants/src/lib.rs
  rs/nns/handlers/root/impl/BUILD.bazel
  rs/nns/integration_tests/BUILD.bazel
  rs/nns/sns-wasm/BUILD.bazel
  rs/nns/test_utils/src/common.rs
  rs/nns/test_utils/src/itest_helpers.rs
  rs/node_rewards/canister/BUILD.bazel
  rs/pocket_ic_server/BUILD.bazel
  rs/registry/admin/BUILD.bazel
  rs/rosetta-api/icp/BUILD.bazel
  rs/rosetta-api/icp/client/BUILD.bazel
  rs/rosetta-api/icp/client/tests/tests.rs
  rs/rosetta-api/icp/runner/BUILD.bazel
  rs/rosetta-api/icp/runner/tests/tests.rs
  rs/rosetta-api/icp/tests/integration_tests/BUILD.bazel
  rs/rosetta-api/icp/tests/integration_tests/tests/tests.rs
  rs/rosetta-api/icp/tests/system_tests/common/system_test_environment.rs
  rs/rosetta-api/icp/tests/system_tests/test_cases/block_synchronization.rs
  rs/rosetta-api/scripts/download_latest_icp_ledger.sh
  rs/sns/integration_tests/BUILD.bazel
  rs/tests/common.bzl
  rs/tests/financial_integrations/rosetta/rosetta_test_lib/setup.rs
  testnet/tools/nns-tools/lib/canister_wasms.sh
Labels: chore, @idx, @dre, @execution, @cross-chain-team, @finint, @governance-team

#6963 revert: "feat: [NODE-1679] Track mainnet measurements in repo (#6900)"
  WORKSPACE.bazel
  bazel/mainnet-icos-images.bzl
  ci/src/mainnet_revisions/mainnet_revisions.py
  ic-os/guestos/envs/dev/BUILD.bazel
  ic-os/setupos/defs.bzl
  mainnet-icos-revisions.json
  rs/tests/common.bzl
  rs/tests/driver/src/driver/ic_images.rs
  rs/tests/nested/BUILD.bazel
  rs/tests/system_tests.bzl
Labels: revert, @idx, @node

#6966 Bitcoin checker readme
  rs/bitcoin/checker/README.md
  rs/bitcoin/checker/btc_checker_overview.png
Labels: @cross-chain-team

#6795 fix(nns): remove unsafe math from network_economics
  rs/nns/governance/src/network_economics.rs
Labels: fix, @governance-team

#6958 chore(PocketIC): top up anonymous account on cycles ledger
  Cargo.lock
  packages/pocket-ic/src/common/rest.rs
  packages/pocket-ic/tests/icp_features.rs
  rs/pocket_ic_server/BUILD.bazel
  rs/pocket_ic_server/Cargo.toml
  rs/pocket_ic_server/src/external_canister_types.rs
  rs/pocket_ic_server/src/pocket_ic.rs
Labels: chore

#6908 refactor: Encapsulate CyclesAccountManager as an execution service
  rs/determinism_test/src/setup.rs
  rs/execution_environment/src/lib.rs
  rs/replay/src/player.rs
  rs/replica/src/setup_ic_stack.rs
  rs/state_machine_tests/src/lib.rs
Labels: refactor, @consensus, @execution, @ic-message-routing-owners

#6978 chore: trigger upgrade tests on mainnet-icos-revisions.json changes
  PULL_REQUEST_BAZEL_TARGETS
Labels: chore, @idx

#6924 feat: New remote attestation endpoint
  Cargo.lock
  Cargo.toml
  ic-os/components/guestos.bzl
  ic-os/components/guestos/generate-ic-config/ic.json5.template
  ic-os/components/guestos/remote-attestation-server.service
  ic-os/guestos/defs.bzl
  rs/ic_os/attestation/src/custom_data.rs
  rs/ic_os/attestation/src/e2e_tests.rs
  rs/ic_os/guest_upgrade/client/src/lib.rs
  rs/ic_os/guest_upgrade/server/src/service.rs
  rs/ic_os/guest_upgrade/shared/src/attestation.rs
  rs/ic_os/remote_attestation/server/BUILD.bazel
  rs/ic_os/remote_attestation/server/Cargo.toml
  rs/ic_os/remote_attestation/server/src/main.rs
  rs/ic_os/remote_attestation/shared/BUILD.bazel
  rs/ic_os/remote_attestation/shared/Cargo.toml
  rs/ic_os/remote_attestation/shared/build.rs
  rs/ic_os/remote_attestation/shared/proto/remote_attestation.proto
  rs/ic_os/remote_attestation/shared/src/lib.rs
  rs/orchestrator/testdata/nftables_assigned_replica.conf.golden
Labels: feat, @consensus, @node

#6984 chore: Pass host hostname to a dev container
  ci/container/container-run.sh
Labels: chore, @idx

#6985 chore: Add prefix to named temp files in production
  rs/ic_os/dev_test_tools/setupos-image-config/src/bin/inject.rs
  rs/ic_os/device/src/device_mapping.rs
  rs/ic_os/os_tools/guest_vm_runner/src/guest_direct_boot.rs
  rs/ic_os/os_tools/guest_vm_runner/src/main.rs
  rs/ic_os/sev/src/host/mod.rs
  rs/ic_os/vsock/vsock_lib/src/host/hsm.rs
Labels: chore, @node

#6993 feat(IDX): move weekly secrets to env
  .github/workflows/schedule-weekly.yml
Labels: feat, @idx

#6980 chore(crypto): Add release date for ic-pub-key
  packages/ic-pub-key/CHANGELOG.md
Labels: chore

#6949 chore: [NODE-1679] Publish dev measurements
  ic-os/guestos/envs/dev/BUILD.bazel
Labels: chore

#7005 test(node): remove recovery_upgrader_test
  PULL_REQUEST_BAZEL_TARGETS
  rs/tests/nested/BUILD.bazel
  rs/tests/nested/recovery_upgrader_test.rs
Labels: test, @idx, @node

#6942 feat(governance): Created neuron-subaccount tool.
  Cargo.lock
  Cargo.toml
  rs/nervous_system/tools/neuron-subaccount/BUILD.bazel
  rs/nervous_system/tools/neuron-subaccount/Cargo.toml
  rs/nervous_system/tools/neuron-subaccount/src/main.rs
Labels: feat, @governance-team

#6974 fix: deploy.py wait_func path and guestos_ipv6_address optionality
  ic-os/dev-tools/bare_metal_deployment/deploy.py
Labels: fix, @node

#6989 fix(http-outcalls): Make invalid_ip correctness test less flaky.
  rs/tests/networking/canister_http_correctness_test.rs
Labels: fix, @consensus

#6893 fix(ic-recovery): `ic-recovery` fixes and improvements
  rs/recovery/src/app_subnet_recovery.rs
  rs/recovery/src/args_merger.rs
  rs/recovery/src/cmd.rs
  rs/recovery/src/lib.rs
  rs/recovery/src/main.rs
  rs/recovery/src/nns_recovery_failover_nodes.rs
  rs/recovery/src/nns_recovery_same_nodes.rs
  rs/recovery/src/recovery_state.rs
  rs/recovery/src/steps.rs
  rs/recovery/subnet_splitting/src/main.rs
  rs/recovery/subnet_splitting/src/subnet_splitting.rs
  rs/tests/consensus/subnet_recovery/common.rs
  rs/tests/consensus/subnet_recovery/sr_nns_failover_nodes_test.rs
  rs/tests/consensus/subnet_splitting_test.rs
  rs/tests/nested/nns_recovery/common.rs
  rs/tests/nested/nns_recovery/nr_broken_dfinity_node.rs
  rs/tests/nested/nns_recovery/nr_local.rs
  rs/tests/nested/nns_recovery/nr_remote.rs
Labels: fix, @consensus, @node

#7007 fix(networking): Fix state sync performance test
  rs/tests/networking/BUILD.bazel
  rs/tests/networking/state_sync_performance.rs
Labels: fix, @consensus

#6707 feat(canister_logging): add filtering support for fetching logs
  rs/config/src/execution_environment.rs
  rs/execution_environment/src/canister_logs.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/query_handler.rs
  rs/execution_environment/tests/canister_logging.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/ic.did
Labels: feat, @execution

#6692 chore(governance): Delete the FulfillSubnetRentalRequest flag.
  rs/nns/governance/src/lib.rs
  rs/nns/governance/src/proposals/fulfill_subnet_rental_request.rs
  rs/nns/governance/src/proposals/fulfill_subnet_rental_request/tests.rs
Labels: chore

#6981 fix(node-rewards-canister): Discard DayUtc type in favor of NaiveDate
  Cargo.lock
  rs/node_rewards/canister/BUILD.bazel
  rs/node_rewards/canister/Cargo.toml
  rs/node_rewards/canister/api/BUILD.bazel
  rs/node_rewards/canister/api/Cargo.toml
  rs/node_rewards/canister/api/src/lib.rs
  rs/node_rewards/canister/api/src/provider_rewards_calculation.rs
  rs/node_rewards/canister/api/src/providers_rewards.rs
  rs/node_rewards/canister/node-rewards-canister.did
  rs/node_rewards/canister/src/canister/mod.rs
  rs/node_rewards/canister/src/canister/test/get_node_providers_rewards.rs
  rs/node_rewards/canister/src/chrono_utils.rs
  rs/node_rewards/canister/src/lib.rs
  rs/node_rewards/canister/src/metrics.rs
  rs/node_rewards/canister/src/metrics/tests.rs
  rs/node_rewards/canister/src/registry_querier.rs
  rs/node_rewards/canister/src/registry_querier/tests.rs
  rs/node_rewards/canister/tests/get_node_providers_monthly_xdr_rewards.rs
  rs/node_rewards/rewards_calculation/Cargo.toml
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/mod.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/results.rs
  rs/node_rewards/rewards_calculation/src/performance_based_algorithm/v1.rs
  rs/node_rewards/rewards_calculation/src/types.rs
Labels: fix, @dre, @governance-team

#6725 feat: Add a canister_metadata management canister method
  rs/embedders/src/wasmtime_embedder/system_api/routing.rs
  rs/embedders/src/wasmtime_embedder/system_api/sandbox_safe_system_state.rs
  rs/execution_environment/src/canister_manager.rs
  rs/execution_environment/src/canister_manager/types.rs
  rs/execution_environment/src/execution_environment.rs
  rs/execution_environment/src/execution_environment/tests.rs
  rs/execution_environment/src/execution_environment_metrics.rs
  rs/execution_environment/src/ic00_permissions.rs
  rs/execution_environment/src/scheduler.rs
  rs/execution_environment/tests/dts.rs
  rs/execution_environment/tests/execution_test.rs
  rs/test_utilities/execution_environment/src/lib.rs
  rs/types/management_canister_types/src/lib.rs
  rs/types/management_canister_types/tests/candid_equality.rs
  rs/types/management_canister_types/tests/ic.did
  rs/types/types/src/messages/ingress_messages.rs
  rs/types/types/src/messages/inter_canister.rs
Labels: feat, @execution, @ic-interface-owners

#6848 feat(nns): Record known neuron votes before clearing ballots
  rs/nns/governance/src/governance.rs
  rs/nns/governance/src/governance/tests/mod.rs
  rs/nns/governance/unreleased_changelog.md
Labels: feat, @governance-team
